### PR TITLE
[4.10] Always workaround null transaction

### PR DESCRIPTION
**Pull request by cgwalters**
I did another look at 2101379 and I think Jerry was right, the original workaround in the MCO didn't cover this case.  We again have an inbound fix for RHEL 8.4, but this will be quicker to ship.

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Sorry, didn't get to this, do we think this is still needed? It will probably need to be attached to a bug or jira to get the bot to accept it as a backport. Or have we waited long enough that we can wait for the RHEL fix instead?

**Comment by cgwalters** [comment]
We shipped the fix in RHEL 8.6 and 8.4, so I think we don't need this.

**Comment by cgwalters** [comment]
See https://access.redhat.com/errata/RHBA-2023:0505

**Comment by sinnykumari** [comment]
I don't understand how fix going into latest RHEL z streams will help when we are performing rebase on node that doesn't yet have upgraded to OCP version containing the fix in ostree. Shouldn't we still need this PR to handle upgrade for clusters that aren't on OCP version containing the ostree with fix?

**Comment by sinnykumari** [comment]
I am bad at mapping what version of ostree went into OCP 4.11 and 4.12 GA. @cgwalters  Do we need this patch in 4.11 and 4.12 as well or 4.11 and 4.12 GA went with ostree fix included?

This bug is unpredictable and can can happen on multiple nodes in the cluster. Recently we also observed this in  https://issues.redhat.com/browse/OCPBUGS-7248 and https://issues.redhat.com/browse/OCPBUGS-6668.
For better upgrade experience I will lean towards adding this workaround in older releases.
@yuqi-zhang @rioliu-rh what do you think?

**Comment by yuqi-zhang** [comment]
Hmm, I don't have a strong feeling either way, I think this is safe to add.

The main issue (I think) with having the fix in rpm-ostree is, during the upgrade from 4.10.x->4.10.52+, the old rpm-ostree is used so until the reboot, you have a chance of hitting this still, whereas with the workaround technically you'll be safer if you upgrade from 4.9 since the MCD comes in first.

So regardless this will still have some impact, so if we feel that is worth it, we can add this additional fix for more vulnerable version upgrades

**Comment by cgwalters** [comment]
One problem is that the fix on the rpm-ostree side made the upgrade not *wedge* forever, but it still is buggy until we pull in https://github.com/coreos/rpm-ostree/pull/4224

**Pull request closed without merging**
