### PR TITLE
Bug 2104503: Updating ose-machine-config-operator images to be consistent with ART

### PR DESCRIPTION
**Pull request by sinnykumari**
Motivated from 4.11 PR https://github.com/openshift/machine-config-operator/pull/2937/
It includes:
- Using latest build image
- Update golangci-lint to 1.46.2 as needed with switch to golang-1.18 based build image
- Fix error reported by golangci-lint while running `make verify`

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
While we're at it, should we add in https://github.com/openshift/machine-config-operator/pull/3225 as well?

**Comment by sinnykumari** [comment]
> While we're at it, should we add in #3225 as well?

good catch. Updated image for Dockerfile.proxy as well

**Comment by sinnykumari** [comment]
> do you know of any differences building on the 4.10/4.11/4.12 base images?

Not really.  4.11/4.12 base image have golang-1.18 compared to 4.10 which has golang 1.17
Main difference we saw is golnagci-linter pointed out some cosmetic issues like use of deprecated function (toml decoder), old coding practices (using octal format for file mode), etc.

**Comment by yuqi-zhang** [comment]
/lgtm

Thanks!

**Pull request merged**
