### PR TITLE
daemon: Add some logging for state

### PR DESCRIPTION
**Pull request by cgwalters**
I'm debugging https://bugzilla.redhat.com/show_bug.cgi?id=2075126
and I find our handling of the `state` variable a bit suspicious.

Unfortunately...we don't log this in the default daemon logs
and it would have been *very* useful to have that because it is
input to a key bit of control flow today - if the state is not `done`
then we try to perform an update between config A and config A which
smells like a bug to me.

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

One theory is that the sync did not properly sync cache yet, so the annotation was updated on the previous sync, but the cached state says we are not yet done. That's similar to the uncordoned-but-actually-not issue we see sometimes. One other fix option is to have the setdone annotation be at the same time as the currentconfig annotation update, so either both go through or neither.

I think for important things maybe we can force the cache to resync or use a `get` method directly off API? Just a thought.

**Comment by cgwalters** [comment]
> I think for important things maybe we can force the cache to resync or use a get method directly off API? Just a thought.

I don't actually understand why we have this nodeWriter thing to do asynchronous writes.  I think we should instead block in a synchronous retry loop to update our state.

OK, some quick git annotate leads to https://github.com/openshift/machine-config-operator/commit/90de9570a268108f5ec7283a051ff2bc119ac045 and luckily we can ask - @rphillips why did you change node annotation writes to be asynchronous?

**Comment by cgwalters** [comment]
I looked through the logs of the [e2e-gcp-op run](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/3102/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1516892451980185600/artifacts/e2e-gcp-op/gather-extra/artifacts/pods/) and all looks good to me.

The (previously existing) race condition here around the async writes of `state` seem clearly visible, e.g.:

```
I0420 21:49:24.408341    8906 update.go:1971] Update completed for config rendered-master-91778d49bbc278edbbe966436f6c9071 and node has been successfully uncordoned
I0420 21:49:24.423595    8906 daemon.go:1597] In desired config rendered-master-91778d49bbc278edbbe966436f6c9071
I0420 21:49:24.438440    8906 config_drift_monitor.go:246] Config Drift Monitor started
I0420 21:50:05.955092    8906 daemon.go:526] Transitioned from state: Degraded -> Done
```

Only about 40 seconds after the daemon thinks it's done does the round-trip to the apiserver come back and update our cached copy.

So...I think it's actually quite possible that if the node changes between then, we may try to update again.  But, I'll circle back and try to prove that in further work.

**Comment by cgwalters** [comment]
This can't break upgrades, we're just adding log messages.  Failures are existing known flakes.
/override ci/prow/e2e-agnostic-upgrade

**Pull request merged**
