### PR TITLE
MCO-396: daemon: FCOS workaround, plus SELinux workaround

### PR DESCRIPTION
**Pull request by cgwalters**
daemon: Temporarily copy auth file with more open perms on FCOS

This works around an rpm-ostree regression
https://issues.redhat.com/browse/OKD-63

---

daemon: Temporarily `setenforce 0` for inplace update from container

In practice, we should ship a SELinux policy tweak that allows a transition
from `spc_t` -> `install_t` but for now I want to see if this works.

---

### CODE REVIEW

**Comment by vrutkovs** [comment]
OKD install now passes in okd-e2e-aws, thanks!

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

**Comment by yuqi-zhang** [comment]
CI is currently blocked on https://issues.redhat.com/browse/TRT-589

**Comment by cgwalters** [comment]
OK from the controlplane journal on OKD:

```
Oct 04 11:53:29 ip-10-0-159-199 audit[3599]: AVC avc:  denied  { mac_admin } for  pid=3599 comm="pool-rpm-ostree" capability=33  scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=capability2 permissive=0
```

Argh.  This is likely to bite us in RHEL too.  We're going to need to override the container security context.  This issue is one of the reasons why running ostree in a container is a bit tricky.

**Comment by cgwalters** [comment]
https://issues.redhat.com/browse/MCO-396

**Comment by cgwalters** [comment]
OK I rolled a workaround for https://issues.redhat.com/browse/MCO-396 into this, because the OKD path is hitting this today.

**Comment by cgwalters** [comment]
> ci/prow/okd-e2e-aws — Job succeeded.   

:tada:

**Comment by cgwalters** [comment]
This undermines my confidence in the old-bootimage path, we'll want to verify that better after this lands.

**Comment by vrutkovs** [comment]
/skip

SKipping optional tests as it unblocks OKD nightlies

**Pull request merged**
