### PR TITLE
Bug 1803986:Revert 1473 and skip etcd-member.yaml validation

### PR DESCRIPTION
**Pull request by runcom**
Closes #1480 

Enable CEO testing - return early when validating the file CEO cares about

@deads2k @kikisdeliveryservice

### CODE REVIEW

**Comment by deads2k** [comment]
Related to other bugzillas for etcd.

**Comment by kikisdeliveryservice** [comment]
```
 2020/02/18 01:14:06 warning: failed to update lease "3cd6cd76-82a1-4c0e-bfde-0be89131cc67": status 503 Service Unavailable, status code 503 updating 3cd6cd76-82a1-4c0e-bfde-0be89131cc67
2020/02/18 01:14:36 warning: failed to update lease "3cd6cd76-82a1-4c0e-bfde-0be89131cc67": status 503 Service Unavailable, status code 503 updating 3cd6cd76-82a1-4c0e-bfde-0be89131cc67
```

/retest

**Pull request merged**
