### PR TITLE
OpenStack: pull improvements and IPv6 fixes from BM

### PR DESCRIPTION
**Pull request by mandre**
This pulls all the recent changes from BM to OpenStack platform.

https://github.com/openshift/machine-config-operator/pull/1388: Bug 1790823: [IPI][BAREMETAL] Verify that mdns-publisher starts after hostname is set
https://github.com/openshift/machine-config-operator/pull/1219: [Baremetal] - update haproxy statistics url
https://github.com/openshift/machine-config-operator/pull/1256: [Baremetal] Haproxy add support for IPv6 frontend
https://github.com/openshift/machine-config-operator/pull/1396: baremetal: ipv6, switch to NM dispatcher for DNS VIP prepending
https://github.com/openshift/machine-config-operator/pull/1395: Bug 1798637: baremetal: IPv6 add dhcp-duid to NetworkManager config
https://github.com/openshift/machine-config-operator/pull/1419: Bug 1796148: baremetal: Remove .template from path in dhcp-dhclient-conf.yaml
https://github.com/openshift/machine-config-operator/pull/1436: Bug 1798146: [baremetal] Ipv6 non virtual ip fix
https://github.com/openshift/machine-config-operator/pull/1444: Bug 1798788: Set Kubelet node IP to non-vip
https://github.com/openshift/machine-config-operator/pull/1456: Bug 1801662: baremetal: all resolvconf editing to NM dispatcher
https://github.com/openshift/machine-config-operator/pull/1455:  Bug 1790823: [baremetal] Verify that MDNS doesn't advertise localhost

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
(scaleup test is broken..)

/skip

**Comment by vrutkovs** [comment]
Please don't create more python scripts, these won't work on OKD. Can it be wrapped in a container?

**Comment by mandre** [comment]
> Please don't create more python scripts, these won't work on OKD. Can it be wrapped in a container?

The `nodeip-finder` script should indeed be moved to `baremetal-runtimecfg` image, the same you did for `non-virtual-ip` in https://github.com/openshift/baremetal-runtimecfg/pull/46

**Comment by pierreprinetti** [comment]
/lgtm
/hold

IPv4 deployment successful, feel free to `/hold cancel` when ready

**Comment by mandre** [comment]
/hold cancel

Moving `nodeip-finder` to `baremetal-runtimecfg` should be done in a separate PR.

**Pull request merged**
