### PR TITLE
WIP: Tests for #540

### PR DESCRIPTION
**Pull request by mtrmac**
This attempts to test #540 by hard-coding a permission-required pause image, per #537.

First iteration reverts _both_ of the fixes, so that I can see what the failure looks like; then I’ll drop the revert to test the code from #540.

### CODE REVIEW

**Comment by mtrmac** [comment]
Well, that was underwhelming… `artifacts/e2e-aws-op/bootstrap/crio.service` is empty.

Anyway, the closest to an error report is
```
level=fatal msg="waiting for Kubernetes API: context deadline exceeded"
2019/03/13 13:44:10 Container setup in pod e2e-aws-op failed, exit code 1, reason Error
```

let’s see if actually including the fix improves things.

**Comment by cgwalters** [comment]
OK, so at least that last e2e-aws-op run failed with a symptom that could very well be caused by the fact this patch didn't work.

https://github.com/openshift/machine-config-operator/issues/530
would help us debug this.

At the moment whenever I have to debug something like this I end up using libvirt since you can ssh to the bootstrap node easily, get the console logs from the masters, etc.

**Comment by mtrmac** [comment]
(Tests succeeded, both in #540 and here, after rebasing; while I am waiting for a machine to investigate possible failures in detail, let’s try the “revert both fixes” experiment again.)

**Comment by mtrmac** [comment]
(Failures with both fixes reverted are the same as last time:
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/542/pull-ci-openshift-machine-config-operator-master-e2e-aws/2635
- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/542/pull-ci-openshift-machine-config-operator-master-e2e-aws-op/1179

)

**Comment by mtrmac** [comment]
/test e2e-aws

(https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/542/pull-ci-openshift-machine-config-operator-master-e2e-aws/2637 seems to be AWS `RequestLimitExceeded`.)

**Comment by mtrmac** [comment]
@cgwalters Tests did pass twice ( https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/542/pull-ci-openshift-machine-config-operator-master-e2e-aws/2628/ after this week’s rebase.

AFAICS most of the failures in https://openshift-gce-devel.appspot.com/pr/openshift_machine-config-operator/542 are caused by either AWS `RequestLimitExceeded` errors, or by e2e tests failing — but those tests running at all means that the `pause` container is usable, doesn’t it?

(Warning: I still have _very little_ idea what I’m doing.)

**Comment by mtrmac** [comment]
> Tests did pass twice ( https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/542/pull-ci-openshift-machine-config-operator-master-e2e-aws/2628/

… and https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/542/pull-ci-openshift-machine-config-operator-master-e2e-aws/2680/ )

**Comment by kikisdeliveryservice** [comment]
#540 has been approved so closing this PR since it's not needed anymore. Thanks!

**Pull request closed without merging**
