### PR TITLE
Move some deduped templates back to where they belong

### PR DESCRIPTION
**Pull request by bcrochet**
An on-prem template wasn't moved correctly, and an OpenStack template was moved when it shouldn't have been.

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
This is kni/openstack, I'd like to see owners from both lgtm before approving

/hold

**Comment by cybertron** [comment]
/lgtm

So that's why afterburn started showing up in my failed units lately. :-)

**Comment by kikisdeliveryservice** [comment]
(waiting for openstack lgtm)

**Comment by bcrochet** [comment]
e2e-gcp-op is failing across the board. I think e2e-metal-ipi-ovn-dualstack is broken for other reasons. The other platform test failures do not seem to be related, AFAICT.

**Comment by bcrochet** [comment]
@kikisdeliveryservice I think all platforms have given a lgtm. Thanks.

**Review by kikisdeliveryservice — APPROVED** [review]

**Comment by bcrochet** [comment]
@yuqi-zhang On this one, it is safe to skip e2e-metal-ipi-ovn-dualstack. It was added as a test for an unrelated issue. vsphere-upi should pass once 2207 is merged.

**Comment by runcom** [comment]
follow up from https://github.com/openshift/machine-config-operator/pull/2209#issuecomment-729272506

/override ci/prow/e2e-gcp-op
/override ci/prow/e2e-metal-ipi-ovn-dualstack

**Pull request merged**
