### PR TITLE
Bug 1801662: baremetal: all resolvconf editing to NM dispatcher

### PR DESCRIPTION
**Pull request by celebdor**
Before this patch, the search domain modification was dependant on
dhclient. Unfortunately, the interaction of both components sometimes
fails. This patch makes sure that we preserve what comes from the dhcp
client (whichever may be) but we set what we need in VIP managing
environments.

### CODE REVIEW

**Comment by jparrill** [comment]
BZ Related: https://bugzilla.redhat.com/show_bug.cgi?id=1801638

**Comment by kikisdeliveryservice** [comment]
this needs a BZ to merge (ie Bz in title etc...)

**Pull request merged**
