### PR TITLE
[release-4.10] Bug 2070492: configure-ovs: move dhcp config from br-ex to ovs-if-br-ex

### PR DESCRIPTION
**Pull request by jcaamano**
Cherry-pick of #3024 [e43a9f2](https://github.com/openshift/machine-config-operator/pull/3024/commits/e43a9f216937df5b0fc9c744be78687ac38c21f2)

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by jcaamano** [comment]
Both e2e-azure-ovn-upgrade and e2e-metal-ipi-ovn-ipv6 but checked the logs and got past this changes working as expected so their issues should be unrelated to these changes.
In regards to backport risk assessment, this bug moves some properties that were being set in the incorrect interface and are copied from the original network configuration of the node. They relate to obtaining assignments through DHCP but that might not be relevant on all platforms. If the default network works, there is no reason for br-ex network that we create not to work.

**Pull request merged**
