### PR TITLE
OCPBUGS-2079: Add ephemeral storage to kubelet system reserved args

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

Fixes: https://issues.redhat.com/browse/OCPBUGS-2079

**- What I did**
Add missing ephemeral storage value to system reserved arg of the kubelet

**- How to verify it**
Log into the node, and verify that kubelet process has started with the system reserved arg that has ephemeral storage

**- Description for the changelog**

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
lgtm. I believe the function is used for both bootstrap and in-cluster, so we should be covered there, but out of curiosity, did you test bootstrapping with this kubeletconfig?

**Comment by harche** [comment]
> lgtm. I believe the function is used for both bootstrap and in-cluster, so we should be covered there, but out of curiosity, did you test bootstrapping with this kubeletconfig?

I launched a cluster using cluster-bot with this PR, and the functionality worked out of box in that case.

**Comment by yuqi-zhang** [comment]
> I launched a cluster using cluster-bot with this PR, and the functionality worked out of box in that case.

Right, I meant launch a PR with a user-provided kubeletconfig as part of the bootstrap manifests that sets ephemeral storage, which I didn't know you could do via cluster-bot, but I could just be completely out of date

**Comment by harche** [comment]
> > I launched a cluster using cluster-bot with this PR, and the functionality worked out of box in that case.
> 
> Right, I meant launch a PR with a user-provided kubeletconfig as part of the bootstrap manifests that sets ephemeral storage, which I didn't know you could do via cluster-bot, but I could just be completely out of date

Oh ok, got you now. Let me test it that way. Thanks.

**Comment by yuqi-zhang** [comment]
Strange, I approved the PR but the approved label never applied. Let me know how that goes, and I'll try again tomorrow

**Comment by harche** [comment]
> Strange, I approved the PR but the approved label never applied. Let me know how that goes, and I'll try again tomorrow

@yuqi-zhang I tested in the bootstrap mode but it seems all values of system reserved (i.e. cpu, memory, ephemeral storage) are dropped. We will have to re-test the changes from https://github.com/openshift/machine-config-operator/pull/2547/

I used following KubeletConfig to drop in manifest folder,
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: system-reserved-config2
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
  kubeletConfig:
    systemReserved:
      cpu: 500m
      memory: 500Mi
      ephemeral-storage: 15Gi
```
The kubelet came up with all default values for memory,cpu, ephemeral storage,
```
--system-reserved=cpu=500m,memory=1Gi,ephemeral-storage=1Gi
```
The expected values were (without the change in this PR the value for ephemeral storage won't change anyway), 
```
 --system-reserved=cpu=500m,memory=500Mi,ephemeral-storage=1Gi
```

I have created a separate bug to track this issue with bootstrap mode and system reserved, https://issues.redhat.com/browse/OCPBUGS-2634 

cc @QiWang19 @rphillips

**Comment by harche** [comment]
By mistake I used the wrong cluster for testing. I re-ran the tests using the proper cluster and it seems to be working fine. Sorry for the noise.  The value of the ephemeral storage in system reserved was correctly applied in kubelet args (in bootstrap mode),

```
--system-reserved=cpu=500m,memory=500Mi,ephemeral-storage=15Gi 
```

cc @yuqi-zhang

**Comment by yuqi-zhang** [comment]
ack, thanks for the additional testing!

/approve

**Pull request merged**
