### PR TITLE
two small MCD patches

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by runcom** [comment]
`daemon: Don't check our own state flag for update check` I thought I changed that somewhere else so it makes total sense 👍 

/approve

**Comment by runcom** [comment]
I'm starting to think the op error is a valid error? 🤔

**Comment by cgwalters** [comment]
Yeah, we may need to always do "if current == desired, set state to done".

**Comment by cgwalters** [comment]
> Yeah, we may need to always do "if current == desired, set state to done".

Dropped that patch for now, this one is just two trivial patches now.

**Comment by kikisdeliveryservice** [comment]
i think it's gonna be one of those wacky ci afternoons...

/retest

**Pull request merged**
