### PR TITLE
OCPBUGS-25821,OCPBUGS-31381: certificate_writer: clean up disk-write logic

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Presently it seems that the daemon sometimes doesn't react to the configmap changes, possibly due to the lexicographical comparison (which probably should have been a size?)

Change the logic a bit such that it:
1. checks for all the cert changes (adds/updates)
2. always write in from the configmap
3. still defer kubelet restarts/MCD restarts for some cases
4. do not write back to the configmap as that shouldn't be necessary

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-metal-ipi-upgrade-ovn-ipv6

To see if this helps

**Comment by yuqi-zhang** [comment]
/payload 4.16 nightly blocking

For general payload, in case this triggers something odd

**Comment by yuqi-zhang** [comment]
Did some manual testing, the rotation mechanism works but it does restart kubelet the first time around (which I think we are trying to avoid) since there are some minor diffs, so this might cause issues in upgrades.

Will see what's changing here and what we can do about it

**Comment by yuqi-zhang** [comment]
As far as I can tell this isn't breaking anything in payloads. The failures seem unrelated and an upgrade test passed.

cc @sergiordlr would you want to test this pre-merge?

**Comment by djoshy** [comment]
Gave it a final look, looks good to me! Will hold for pre merge qe review

/lgtm
/hold

**Comment by sergiordlr** [comment]
Certificate rotation verification

1. Patch the loadbalancer-serving-signer secret to trigger a cert rotation

`oc patch secret/loadbalancer-serving-signer -n openshift-kube-apiserver-operator -p='{"metadata": {"annotations": {"auth.openshift.io/certificate-not-after": null}}}'
`

2. Check that the certificate in kube-apiserver-server-ca has been updated
3. Check that the /etc/kubernetes/kubeconfig file use the certificates defined in  `cm/kube-apiserver-server-ca -n openshift-config-managed`
`  oc debug -q  node/$(oc get nodes -l node-role.kubernetes.io/worker -ojsonpath="{.items[0].metadata.name}") -- chroot /host cat /etc/kubernetes/kubeconfig | yq  '.clusters[0].cluster."certificate-authority-data"' -r | base64 -d > kubernetes.kubeconfig.certificates`
4. Check that the /var/lib/kubelet/kubeconfig uses the same certificates used by /etc/kubernetes/kubeconfig
`   oc debug -q  node/$(oc get nodes -l node-role.kubernetes.io/worker -ojsonpath="{.items[0].metadata.name}") -- chroot /host cat /var/lib/kubelet/kubeconfig | yq  '.clusters[0].cluster."certificate-authority-data"' -r | base64 -d > kubelet.kubeconfig.certificates`
5. Check that no ClusterOperators is degraded and all of them become stable after a while (kube-apiserver applies new modifications).

Make sure that we are not breaking https://issues.redhat.com/browse/OCPBUGS-31067

1. Upgrade from 4.13 to this CI image

```
    - lastTransitionTime: "2024-05-10T12:29:03Z"
      message: |-
        Multiple cluster operators should not be upgraded between minor versions:
        * Cluster operator control-plane-machine-set should not be upgraded between minor versions: AsExpected: cluster operator is not upgradable
        * Cluster operator network should not be upgraded between minor versions: OpenShiftSDNConfigured: Cluster is configured with OpenShiftSDN, which is not supported in the next version. Please follow the documented steps to migrate from OpenShiftSDN to OVN-Kubernetes in order to be able to upgrade. https://docs.openshift.com/container-platform/4.16/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html
        * Cluster operator machine-config should not be upgraded between minor versions: DegradedPool: One or more machine config pools are degraded, please see `oc get mcp` for further details and resolve before upgrading
      reason: ClusterOperatorsNotUpgradeable
      status: "False"
      type: Upgradeable
    desired:
      image: registry.build03.ci.openshift.org/ci-ln-7gl9xzb/release:latest
      version: 4.16.0-0.ci.test-2024-05-09-155445-ci-ln-7gl9xzb-latest
    history:
    - acceptedRisks: |-
        Target release version="" image="registry.build03.ci.openshift.org/ci-ln-7gl9xzb/release:latest" cannot be verified, but continuing anyway because the update was forced: release images that are not accessed via digest cannot be verified
        Precondition "ClusterVersionRecommendedUpdate" failed because of "UnknownUpdate": RetrievedUpdates=False (VersionNotFound), so the recommended status of updating from 4.15.13 to 4.16.0-0.ci.test-2024-05-09-155445-ci-ln-7gl9xzb-latest is unknown.
      completionTime: "2024-05-10T13:25:30Z"
      image: registry.build03.ci.openshift.org/ci-ln-7gl9xzb/release:latest
      startedTime: "2024-05-10T12:26:32Z"
      state: Completed
      verified: false
      version: 4.16.0-0.ci.test-2024-05-09-155445-ci-ln-7gl9xzb-latest
    - acceptedRisks: |-
        Target release version="" image="quay.io/openshift-release-dev/ocp-release:4.15.13-x86_64" cannot be verified, but continuing anyway because the update was forced: release images that are not accessed via digest cannot be verified
        Forced through blocking failures: Multiple precondition checks failed:
        * Precondition "ClusterVersionUpgradeable" failed because of "ResourceDeletesInProgress": Cluster minor level upgrades are not allowed while resource deletions are in progress; resources=clusterrolebinding "default-account-openshift-machine-config-operator"
        * Precondition "EtcdRecentBackup" failed because of "ControllerStarted": RecentBackup: The etcd backup controller is starting, and will decide if recent backups are available or if a backup is required
        * Precondition "ClusterVersionRecommendedUpdate" failed because of "UnknownUpdate": RetrievedUpdates=False (VersionNotFound), so the recommended status of updating from 4.14.25 to 4.15.13 is unknown.
      completionTime: "2024-05-10T11:43:46Z"
      image: quay.io/openshift-release-dev/ocp-release:4.15.13-x86_64
      startedTime: "2024-05-10T10:45:43Z"
      state: Completed
      verified: false
      version: 4.15.13
    - acceptedRisks: |-
        Target release version="" image="quay.io/openshift-release-dev/ocp-release:4.14.25-x86_64" cannot be verified, but continuing anyway because the update was forced: release images that are not accessed via digest cannot be verified
        Forced through blocking failures: Multiple precondition checks failed:
        * Precondition "ClusterVersionUpgradeable" failed because of "AdminAckRequired": Kubernetes 1.27 and therefore OpenShift 4.14 remove several APIs which require admin consideration. Please see the knowledge article https://access.redhat.com/articles/6958395 for details and instructions.
        * Precondition "EtcdRecentBackup" failed because of "ControllerStarted": RecentBackup: The etcd backup controller is starting, and will decide if recent backups are available or if a backup is required
        * Precondition "ClusterVersionRecommendedUpdate" failed because of "UnknownUpdate": RetrievedUpdates=True (), so the update from 4.13.41 to 4.14.25 is probably neither recommended nor supported.
      completionTime: "2024-05-10T10:44:09Z"
      image: quay.io/openshift-release-dev/ocp-release:4.14.25-x86_64
      startedTime: "2024-05-10T09:40:56Z"
      state: Completed
      verified: false
      version: 4.14.25
    - completionTime: "2024-05-10T09:35:28Z"
      image: quay.io/openshift-release-dev/ocp-release@sha256:dbb8aa0cf53dc5ac663514e259ad2768d8c82fd1fe7181a4cfb484e3ffdbd3ba
      startedTime: "2024-05-10T09:08:51Z"
      state: Completed
      verified: false
      version: 4.13.41
```

2. Scale up a  machineset

```
$ oc scale machineset -n openshift-machine-api sregidor-upg13-n8r7h-worker-us-east-2a --replicas 2
machineset.machine.openshift.io/sregidor-upg13-n8r7h-worker-us-east-2a scaled

$ oc get nodes
NAME                                         STATUS   ROLES                  AGE     VERSION
ip-10-0-133-118.us-east-2.compute.internal   Ready    control-plane,master   4h27m   v1.29.4+6c10b2d
ip-10-0-133-139.us-east-2.compute.internal   Ready    worker                 4h22m   v1.29.4+6c10b2d
ip-10-0-147-69.us-east-2.compute.internal    Ready    worker                 5m15s   v1.29.4+6c10b2d
ip-10-0-178-100.us-east-2.compute.internal   Ready    worker                 4h22m   v1.29.4+6c10b2d
ip-10-0-185-143.us-east-2.compute.internal   Ready    control-plane,master   4h27m   v1.29.4+6c10b2d
ip-10-0-201-203.us-east-2.compute.internal   Ready    control-plane,master   4h28m   v1.29.4+6c10b2d
ip-10-0-219-143.us-east-2.compute.internal   Ready    worker                 4h19m   v1.29.4+6c10b2d
```

3. Check pending CSRs
```
$ oc get csr
NAME        AGE     SIGNERNAME                                    REQUESTOR                                                                   REQUESTEDDURATION   CONDITION
csr-587hk   3h23m   kubernetes.io/kube-apiserver-client           system:node:ip-10-0-133-139.us-east-2.compute.internal                      24h                 Approved,Issued
csr-nh27s   5m44s   kubernetes.io/kube-apiserver-client           system:node:ip-10-0-147-69.us-east-2.compute.internal                       24h                 Approved,Issued
csr-qsmdq   6m11s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   <none>              Approved,Issued
csr-wht9b   6m      kubernetes.io/kubelet-serving                 system:node:ip-10-0-147-69.us-east-2.compute.internal                       <none>              Approved,Issued
```


We can add the qe-approved label

/label qe-approved

**Comment by yuqi-zhang** [comment]
Thanks for testing @sergiordlr !

/hold cancel

**Pull request merged**
