### PR TITLE
Bug 1828622: bumps kubelet log level to 4

### PR DESCRIPTION
**Pull request by rphillips**
**- What I did**
Bumping the kubelet log level to 4 to aid in debugging an issue.

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rphillips** [comment]
DO NOT MERGE 
/hold

**Comment by tedyu** [comment]
Makes sense.
This should give us more information for debugging.

**Comment by rphillips** [comment]
/hold cancel

merging this PR to bump the log level to 4 will give us more insight into CI issues

**Pull request merged**
