### PR TITLE
Bug 1980844: install/0000_90_machine-config-operator_01_prometheus-rules: Doc 95% for SystemMemoryExceedsReserved

### PR DESCRIPTION
**Pull request by wking**
Catching the message up with the logic change from 5148f16bd6 (#2716).

### CODE REVIEW

**Review by sinnykumari — APPROVED** [review]
good catch!

**Comment by kikisdeliveryservice** [comment]
im just adding a hold for now since the e2e-upgrade is broken
/hold

**Comment by sinnykumari** [comment]
To see if upgrade job is only broken on azure platform (currently being used by e2e-agnostic-upgrade)
/test e2e-gcp-upgrade

**Comment by sinnykumari** [comment]
e2e-agnostic-upgrade has succeeded, removing hold to get it merged.
/hold cancel

**Pull request merged**
