### PR TITLE
Tighten scheduler permissions in mco clusterrole

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**- What I did**
Reduce the permissions of mco to `watch`,`list` and `get` scheduler config

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
Looks sane since we're not updating the object ourselves

/approve
/lgtm

**Comment by ravisantoshgudimetla** [comment]
`"openshift-machine-api/cluster-autoscaler-operator\" (144 of 431): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-machine-api/machine-api-operator\"`

**Pull request merged**
