### PR TITLE
Bug 1805908: Add template for recycler pod

### PR DESCRIPTION
**Pull request by bertinatto**
**- What I did**

Added template for recycler pod.

**- How to verify it**

This should create a new file in `/etc/kubernetes/manifests/recycler-pod.yaml`.

CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
until I manually test this.

**Comment by bertinatto** [comment]
/hold cancel
I confirmed that the template was created correctly.

**Comment by gnufied** [comment]
@bertinatto we need a PR in https://github.com/openshift/cluster-kube-controller-manager-operator/ for updating arguments to controller-manger as well?

**Comment by bertinatto** [comment]
> @bertinatto we need a PR in https://github.com/openshift/cluster-kube-controller-manager-operator/ for updating arguments to controller-manger as well?

Yes, there's a link up above for that PR

**Comment by runcom** [comment]
I'll leave to storage or whoever is in charge of this to lgtm, approving meanwhile as it seems right

/approve

**Pull request merged**
