### PR TITLE
pkg/operator: update LastTransitionTime when flipping conditions

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

Update `LastTransitionTime` when flipping progressing
xref: https://github.com/openshift/cluster-version-operator/pull/154

as done in https://github.com/openshift/cluster-version-operator/pull/153

**- How to verify it**

There's gonna be a test in origin covering this

**- Description for the changelog**

### CODE REVIEW

**Comment by cgwalters** [comment]
/approve

Looks like a null deref in the unit tests though:

```
--- FAIL: TestInClusterBringUpStayOnErr (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf65d76]
```

I think you need:

```
if existingCondition != nil && existingCondition.Status != coStatus.Status {
```

**Comment by runcom** [comment]
> if existingCondition != nil && existingCondition.Status != coStatus.Status {

nope, the test isn't initializing the conditions, when we have a cluster that's guaranted to not be nil, I'm updating the code

**Comment by runcom** [comment]
Fixed now, and verify job running :)

**Comment by abhinavdahiya** [comment]
Do you mind explaining why using the last transition time from new condition is not correct. The user must have set the time correctly already right?

**Comment by runcom** [comment]
> The user must have set the time correctly already right?

@abhinavdahiya what does this mean? how is the user able to change that in the clusteroperator object? (also, I was basically following what's in here https://github.com/openshift/cluster-version-operator/pull/153)

**Comment by abhinavdahiya** [comment]
> > The user must have set the time correctly already right?
> 
> @abhinavdahiya what does this mean? how is the user able to change that in the clusteroperator object? (also, I was basically following what's in here [openshift/cluster-version-operator#153](https://github.com/openshift/cluster-version-operator/pull/153))

Oops wrong PR. I wanted to ask that question on https://github.com/openshift/cluster-version-operator/pull/153

**Comment by runcom** [comment]
aws

/retest

**Comment by runcom** [comment]
wat

/retest

**Comment by wking** [comment]
@runcom: what's with all the `/retest`?  Do you expect this to go through (your odds are not good ;)?

**Comment by runcom** [comment]
> @runcom: what's with all the `/retest`? Do you expect this to go through (your odds are not good ;)?

@abhinavdahiya reported on slack that is known to happen (I stopped retesting and following the BZ now)

**Comment by wking** [comment]
> I stopped retesting and following the BZ now...

Cross-linking https://bugzilla.redhat.com/show_bug.cgi?id=1695507 for `error: build error: no such image`.  I think you can recover by removing the project (and forcing CI to create a new one for you).  In your case, the project is `ci-op-z3zbtw4v` (from [here][1]).  So maybe try:

```console
$ oc delete project
```

and *then* kick it again?

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/599/pull-ci-openshift-machine-config-operator-master-e2e-aws/2935

**Comment by runcom** [comment]
> Cross-linking https://bugzilla.redhat.com/show_bug.cgi?id=1695507 for `error: build error: no such image`. I think you can recover by removing the project (and forcing CI to create a new one for you). In your case, the project is `ci-op-z3zbtw4v` (from [here](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/599/pull-ci-openshift-machine-config-operator-master-e2e-aws/2935)). So maybe try:
> 
> ```
> $ oc delete project ci-op-z3zbtw4v
> ```
> 
> and _then_ kick it again?

looking at this today, I cannot see that project anymore, I'll kick a retest and see

/retest

**Comment by runcom** [comment]
seems to have worked now and tests are running fine

**Comment by runcom** [comment]
```
level=fatal msg="failed to initialize the cluster: Cluster operator authentication is still updating: timed out waiting for the condition"
```

/retest

**Comment by runcom** [comment]
this is finally green :tada:

**Pull request merged**
