### PR TITLE
OCPBUGS-16622: daemon: Copy matching binary to host, re-exec with it

### PR DESCRIPTION
**Pull request by sinnykumari**
Manual backport of PR https://github.com/openshift/machine-config-operator/pull/3799
Also, fixed cosmetic issue noted in https://github.com/openshift/machine-config-operator/pull/3799#issuecomment-1642431904 about log formatting.
Due to various differences, it took me some time to carefully cherry-pick each commits from PR#3799. Hopefully, I didn't miss anything.

### CODE REVIEW

**Comment by cgwalters** [comment]
/lgtm
This looks correct to me...can you add some comments with parts of the code that conflicted we should look at?

**Comment by cgwalters** [comment]
```
 pkg/daemon/osrelease/osrelease.go:21:2: `rhel` is unused (deadcode)
	rhel   string = "rhel" 
```

Ah yes right...a minor style bug.

**Comment by sinnykumari** [comment]
> This looks correct to me...can you add some comments with parts of the code that conflicted we should look at?

Mainly conflicts were in:
- Dockerfile, Dockerfile.rhel7: due to base image being hel-9-golang-1.19-openshift-4.13 instead of rhel-9-golang-1.20-openshift-4.14 . Also, it was creating some additional changes in https://github.com/openshift/machine-config-operator/pull/3812/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R22 logic due to additional changes in 4.14
-  Around https://github.com/openshift/machine-config-operator/pull/3812/files#diff-bbc610f8a15808cb99f67b8e5c82310523a220d901009acbe5347e66797b9cfaR28 , because we use maybe-persist-nics in 4.13 while persist-nics in 4.14
- Similarly for https://github.com/openshift/machine-config-operator/pull/3812/files#diff-3380ef05804fcff21705fcca487ee27355893c239fb1f0df5077f9dc90cb6719R19 , making it persist-nics
- There were also for cmd/machine-config-daemon/start.go 

manual editing for cherry-pick were needed for all first 4 commits from https://github.com/openshift/machine-config-operator/pull/3799/commits

**Comment by sinnykumari** [comment]
Tests are failing due to not able to find nmstatectl at expected location:
```
E0721 06:57:32.234836   11172 writer.go:200] Marking Degraded due to: failed to run nmstatectl: fork/exec /run/machine-config-daemon-bin/nmstatectl: no such file or directory
I0721 06:58:32.251231   11172 daemon.go:1691] Running: /run/machine-config-daemon-bin/nmstatectl persist-nic-names --root / --inspect
```

**Comment by sinnykumari** [comment]
@cgwalters any clue what is missing here. 
We are correctly mounting /usr/bin/ content at https://github.com/openshift/machine-config-operator/blob/e2b1bd7c25dc2a7ea05b7ca41047a37f0080c2b4/pkg/daemon/daemon.go#L419 into /run/machine-config-daemon-bin/

We didn't see this problem in 4.14 because we run nmstatectl binary only when host is RHEL8 https://github.com/openshift/machine-config-operator/blob/master/pkg/daemon/daemon.go

**Comment by sinnykumari** [comment]
Tests are passing again!
@cgwalters Addition change https://github.com/openshift/machine-config-operator/pull/3812/commits/2324a73bae3cb33bec9a8c7784b2e04f8d774e0b to fix test, need lgtm again. To prevent any undesired behavior, I am thinking of including this commit in 4.14 as well even though we are not running nmstatectl binary in day2.

**Comment by sinnykumari** [comment]
@mrunalp we will also need to get valid-bug label applied

**Pull request merged**
