### PR TITLE
Fix a typo in the readme

### PR DESCRIPTION
**Pull request by QiWang19**
Fix a typo in the readme.

Signed-off-by: Qi Wang <qiwan@redhat.com>

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
I could in theory add the `bugzilla/valid-bug` manually which otherwise would prevent this from merging, but not sure if that's best practice

**Comment by kikisdeliveryservice** [comment]
We don't really need to retest this/run anymore e2e on this and since it's just a minor typo it can wait

/hold

**Comment by QiWang19** [comment]
@kikisdeliveryservice PTAL.

**Pull request closed without merging**
