### PR TITLE
Bug 2078945: Ensure only one apiserver-watcher process is active on a node. 

### PR DESCRIPTION
**Pull request by sanchezl**
**- What I did**

An alternative of https://github.com/openshift/machine-config-operator/pull/2674, using `flock`.

**- Description for the changelog**

wrap `apiserver-watcher` call with `flock`.

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
ill add a hold to both PRs and yall can let me know which one you want to go with.

/hold
/assign @deads2k @squeed @aojea

**Comment by squeed** [comment]
@sanchezl cute :). Can you file a WIP "backport" pr on 4.10? Would you expect it to work?

**Comment by aojea** [comment]
lgtm

defer to @squeed the final decision, but this seems simpler and easier to backport

**Comment by squeed** [comment]
Let's do this one. Feel free to un-hold. Thanks!

**Comment by sanchezl** [comment]
/hold 
while I get things straight in BZ

**Pull request merged**
