### PR TITLE
[release-4.9] OCPBUGS-4051: Add ephemeral storage to kubelet system reserved args

### PR DESCRIPTION
**Pull request by harche**
This is a manual pick of https://github.com/openshift/machine-config-operator/pull/3408

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
Seems fine from a sanity perspective. How far do you anticipate needing to backport this, and do we need to do any additional testing?

**Comment by harche** [comment]
> Seems fine from a sanity perspective. How far do you anticipate needing to backport this, and do we need to do any additional testing?

Thanks @yuqi-zhang for the approval. We introduced the auto node sizing in 4.8, so these backports will have to go all the way till 4.8. 

Apart from the testing QA is doing to verify the PRs, we don't need anything more than that.

**Comment by yuqi-zhang** [comment]
sorry wrong label

/label backport-risk-assessed

**Comment by harche** [comment]
@wking https://issues.redhat.com/browse/OCPBUGS-4101 is now in `verified` state. Should we remove the hold from this PR?

**Comment by yuqi-zhang** [comment]
looking at the other chain, it is awaiting backport to 4.11: https://github.com/openshift/machine-config-operator/pull/3459

how are these interweaved again? Do we need to wait for that to get into previous versions? Or is that not directly related

**Comment by harche** [comment]
@yuqi-zhang When we set the system reserved values for the kubelet, we should have been setting memory, cpu and ephemeral storage values. But for some reason we were only setting memory and cpu. This PR fixes that issue and sets the missing ephemeral storage value for the kubelet. 

On the other hand, https://github.com/openshift/machine-config-operator/pull/3459/ makese the system reserved values more reselient against a blank (and hence invalid) input. 

These two PRs are linked. (This) one introduces missing parameter and other one makes those parameters more resilient against bad input.

**Comment by yuqi-zhang** [comment]
Ok, so not directly conflicting in any way, I think both are now awaiting QE approval, but can otherwise be merged as needed

**Comment by yuqi-zhang** [comment]
Based on the conversation in slack, we will wait for https://github.com/openshift/machine-config-operator/pull/3487 to merge, then backport both via this PR together, does that sound correct?

**Comment by harche** [comment]
> Based on the conversation in slack, we will wait for #3487 to merge, then backport both via this PR together, does that sound correct?

Yes, that's correct.

**Comment by yuqi-zhang** [comment]
We have all the necessary labels, ad the other dependent bug https://issues.redhat.com//browse/OCPBUGS-5831 has been verified for 4.10

/hold cancel

**Comment by yuqi-zhang** [comment]
Is there anyone asking for this to go to 4.8? I think 4.8 is old enough such that this shouldn't really be necessary

**Comment by harche** [comment]
> Is there anyone asking for this to go to 4.8? I think 4.8 is old enough such that this shouldn't really be necessary

Yeah, you are right. I won't pursue this unless someone asks for it.

**Pull request merged**
