### PR TITLE
DNM: OKD e2e testing

### PR DESCRIPTION
**Pull request by LorbusChris**
Do not merge

### CODE REVIEW

**Comment by LorbusChris** [comment]
@haircommander can we get a cri-o 1.23 build for Fedora? RHCOS already has it, and it's the only thing left blocking OKD from using mainline MCO.

**Comment by haircommander** [comment]
> @haircommander can we get a cri-o 1.23 build for Fedora? RHCOS already has it, and it's the only thing left blocking OKD from using mainline MCO.

I am waiting until we cut 1.23.0. I could build an rc if you were eager, but I hope to have 1.23.0 cut soon after kubernetes 1.23.0 is cut

**Comment by LorbusChris** [comment]
That's fine. We have to wrangle some CI configs once it's available, but a few more days more or less don't really matter

**Comment by LorbusChris** [comment]
@vrutkovs e2e passes with MCO from mainline master. I think we can now drop the fork for 4.10?

**Pull request closed without merging**
