### PR TITLE
Revert "split stopping kubelet and reboot into two commands for debugging"

### PR DESCRIPTION
**Pull request by rphillips**
Reverts openshift/machine-config-operator#1176

The shutting down of the kubelet needs to be atomic with the reboot. Shutting down the kubelet will cause the MCD to be killed.

### CODE REVIEW

**Comment by cgwalters** [comment]
Ah, right.  yes.
/approve

**Comment by ashcrow** [comment]
Flake getting an image:
```
received unexpected HTTP status: 500 Internal Server Error
```

**Comment by ashcrow** [comment]
More of
```
received unexpected HTTP status: 500 Internal Server Error
```

holding off to retest

**Comment by rphillips** [comment]
fixed yet?
/test images

**Comment by ashcrow** [comment]
> fixed yet?

My understanding is it should be. We will see :crossed_fingers:.

**Comment by kikisdeliveryservice** [comment]
> > fixed yet?
> 
> My understanding is it should be. We will see crossed_fingers.

i think you jinxed it

**Comment by rphillips** [comment]
I mentioned in slack... After this PR we need to migrate from `reboot` to `systemctl reboot` due to:

```
sh-4.4# reboot ; echo $?
Failed to connect to bus: No data available
0
```

**Comment by kikisdeliveryservice** [comment]
even tho this might trigger ci flooding my inbox :laughing: 
/lgtm

**Comment by cgwalters** [comment]
> I mentioned in slack... After this PR we need to migrate from reboot to systemctl reboot due to:

That doesn't make sense to me since `reboot` *is* `systemctl`:

```
$ ls -al /usr/sbin/reboot
lrwxrwxrwx. 1 root root 16 Sep  3 13:01 /usr/sbin/reboot -> ../bin/systemctl*
```

"Failed to connect to bus" sounds like something that might happen if the system was in the middle of rebooting and `dbus.service` had already gone down.

**Comment by rphillips** [comment]
@cgwalters ```podman run --privileged -ti -v /:/rootfs fedora /bin/bash -c 'chroot /rootfs'```
and try `reboot`

**Comment by rphillips** [comment]
@ashcrow mentioned in slack that systemctl.c does have a number of `multiple paths for reboot depending on environment and call`.

Likely a bug with the way $0 is handled in systemd.

**Pull request merged**
