### PR TITLE
templates/container-storage: Add a "this is generated" note

### PR DESCRIPTION
**Pull request by cgwalters**
It's identical between master/worker, so move it into the
common pool.

Just a cleanup while looking at
https://github.com/openshift/machine-config-operator/issues/1319

---

templates/container-storage: Add a "this is generated" note

This is a best practice, and particularly in this case
when we're intending to modify a config file, it can't be identical
to the shipped version.

This avoids having libostree replace it with a newer version.

Closes: #1319

### CODE REVIEW

**Comment by cgwalters** [comment]
If [my theory](https://github.com/openshift/machine-config-operator/issues/1319#issuecomment-564206602) is correct, then in this PR what I'll do is add a second commit which adds a dummy comment like `# Generated from the Machine Config Operator's containerruntimeconfig` - that will mark the file as modified and libostree won't replace it with a new default.

**Comment by cgwalters** [comment]
Now with a new :new:  commit which should fix the bug.
And hopefully CI is fixed now (some errors were unrelated).

**Comment by cgwalters** [comment]
Just logged into the cluster spun up by that e2e-aws and things are looking good there so far!

```
walters@toolbox ~/s/g/o/ostree> oc get machineconfigpool
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-5497b82f2b60d6a6e17bd16345e22dc1   True      False      False      3              3                   3                     0                      9m53s
worker   rendered-worker-4fe1fc25bc80ac51a692798946497e92   True      False      False      3              3                   3                     0                      9m53s
```

**Comment by cgwalters** [comment]
I just want to say it's pretty awesome that we're fixing a critical bug by adding a comment.

Funny enough, this bug is effectively the inverse of https://src.fedoraproject.org/rpms/selinux-policy/pull-request/2

**Comment by vrutkovs** [comment]
Clean install works, but gcp-upgrade still fails - not sure why though, I expected this to resolve upgrades as well

**Comment by cgwalters** [comment]
I think if the current release payload is broken, then upgrades can't pass.  Let's retry once, but if it still fails I think we should pull out the `/override` :hammer: .
/test e2e-gcp-upgrade

**Comment by cgwalters** [comment]
One mystery here is how we got into a situation where the promoted payload cause this issue.

**Comment by kikisdeliveryservice** [comment]
Looking here it seems as tho it's failing bc of the storage.conf thing:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1320/pull-ci-openshift-machine-config-operator-master-e2e-gcp-upgrade/605/artifacts/e2e-gcp-upgrade/pods/openshift-machine-config-operator_machine-config-daemon-4wfbw_machine-config-daemon.log

If that's that case we can either hold this until that is resolved (since this isn't emergency) or merge it bc it helps solve that (which doesn't seemlike that case?)

**Comment by vrutkovs** [comment]
IIUC the broken machine-os-content never got promoted to nightlies (https://openshift-release.svc.ci.openshift.org/ 4.3.0.0 broken for ~5 days), but CI tests compose latest release from latest tags, so it attempts to update from a broken payload to a "fixed" payload. I assumed this would fix it too, not quite sure why it doesn't.

Perhaps its MCD on the host not being updated (this requires a new MCD RPM with this PR)?

**Comment by cgwalters** [comment]
> If that's that case we can either hold this until that is resolved (since this isn't emergency)

The storage.conf conflict is exactly what this PR is addressing.  Note this one passed e2e-aws, but other PRs on master aren't.

>  but CI tests compose latest release from latest tags, so it attempts to update from a broken payload to a "fixed" payload. 

Hmm.  Oh, wait, so CI runs are also pulling in the latest `machine-os-content` that's tagged, but before promotion?  That seems like a bug if so.

Anyways, I want to more fully outline how this bug occurred.  First, [libostree](https://github.com/ostreedev/ostree/) has a semantic for config files shared with dpkg/rpm and other OS update systems in general, which is "keep modified config files, replace with latest version otherwise".  

We previously tried to replace the file with its default version, and that worked OK because the *new* version was the same thing.

But the MCD will validate that it's in its expected state, and as soon as we do the upgrade, we fail that validation.

Here we're just adding a comment to flag the file as modified and ensure that our version always wins, regardless of what changes in the package.

(Now we should also stop overwriting the package version and merge our changes, but that's a separate bug)

We need to backport this probably as far back as 4.2 or maybe even 4.1 - otherwise it's a time bomb waiting to bite whenever podman is updated in those streams.

**Comment by cgwalters** [comment]
I think the upgrade is failing because we need this PR backported to older branches too.

So, someone mind validating what I'm saying here and then dropping the `/override e2e-gcp-upgrade` ?

**Comment by kikisdeliveryservice** [comment]
So I'm pretty sure this is failing in bootstrap (as always) bc the bootstrap version wouldn't have the changes the PR has it would be upgrading _to_ this version. (ie a cluster comes up without images from this PR and then upgrades to this PR image). It will always fail until the fix is merged and future prs would be upgrading from the version with the fix. Right?

**Comment by kikisdeliveryservice** [comment]
Ok double checked my e2e understanding and yes: cluster comes up -> upgrades to image with PR's changes -> runs e2e.  This PR is still getting stuck in the initial bootstrap (exactly how/where all the other e2e runs were failing before this PR) bc it doesn't have the fix.  So talked to Colin and will override.

/lgtm

**Comment by cgwalters** [comment]
Oh nice thanks vrutkovs!

**Comment by vrutkovs** [comment]
/retitle Bug 1781708: templates/container-storage: Add a "this is generated" note

**Pull request merged**
