### PR TITLE
*: Remove files used for etcd-quorum-guard, as it is being migrated to...

### PR DESCRIPTION
**Pull request by retroflexer**
… cluster-etcd-operator.

**- What I did**
Removed files used in the past for deploying etcd-quorum-guard and defining PDB for it.

**- How to verify it**
etcd-quorum-guard pods are no longer in the machine-config-operator namespace.

**- Description for the changelog**

Migrate etcd-quorum-guard from machine-config-operator to cluster-etcd-operator.

### CODE REVIEW

**Comment by retroflexer** [comment]
Hold deleting these files until the corresponding files in cluster-etcd-operator are merged. 
(https://github.com/openshift/cluster-etcd-operator/pull/394)
/hold

**Comment by hexfusion** [comment]
I was communicated that the failing tests are not related to this change. In general, the change is where we need to go.

/hold cancel

**Comment by retroflexer** [comment]
Verified the PR to be working well with y-upgrades using cluster-bot on aws and gcp (tested with CEO's 394 along with this PR).

aws:
job test upgrade 4.5 4.6,openshift/machine-config-operator#1928,#394 aws succeeded
(https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1286728540858880000)

gcp:
job test upgrade 4.5 4.6,openshift/machine-config-operator#1928,#394 gcp succeeded
(https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1286844014271664128)

**Comment by runcom** [comment]
@kikisdeliveryservice ptal

/retest
/approve

**Comment by wking** [comment]
f0a4088fc3a looks fine to me, and I don't see a problem with this landing slightly ahead of openshift/cluster-etcd-operator#394 if it ends up winning the `/retest`-vs.-CI-flake race.

**Comment by kikisdeliveryservice** [comment]
metal-ipi is failing we can skip
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-metal-ipi

/skip

**Pull request merged**
