### PR TITLE
Bug 1843010: Remove dns vip

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
This PR follow [1][2][3]  in removing DNS VIP.
This PR solves the issue with the removal of dhclient on rchos for ocp 4.6 and is a first step from removing DNSVIP.

Taken from [2]:
"Now that etcd does not need DNS for clustering, we no longer need to
have a VIP to allow the masters to use the bootstrap coredns until
their own coredns instances start. Instead, we can just point them
at the local coredns directly and skip the extra complexity."

[1] https://github.com/openshift/machine-config-operator/pull/1569
[2] https://github.com/openshift/machine-config-operator/pull/1666
[3] https://github.com/openshift/machine-config-operator/pull/1773

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
actually adding hold to prevent accidental merging without a clear signal on the ovirt job for now :)

/hold

**Comment by dougsland** [comment]
> This PR follow [1][2][3] in removing DNS VIP.
> This PR solves the issue with the removal of dhclient on rchos for ocp 4.6 and is a first step from removing DNSVIP.
> 
> Taken from [2]:
> "Now that etcd does not need DNS for clustering, we no longer need to
> have a VIP to allow the masters to use the bootstrap coredns until
> their own coredns instances start. Instead, we can just point them
> at the local coredns directly and skip the extra complexity."
> 
> [1] #1569
> [2] #1666
> [3] #1773

Just for tracking.  Could you please also mention: 
https://github.com/openshift/installer/pull/3692/commits/b7425aa015ec6db424027e6a51a8bdb04f3b48a9 ?

**Comment by kikisdeliveryservice** [comment]
ovirt job passed

/hold cance

**Comment by kikisdeliveryservice** [comment]
@Gal-Zaidman you can do a cherry pick on this to get 4.5 backport it will also create a BZ for you.

**Pull request merged**
