### PR TITLE
OCPBUGS-21721: install/0000_90_machine-config-operator_90_deletion: Drop this file

### PR DESCRIPTION
**Pull request by wking**
ace637f50b (#3740, [OCPBUGS-10924](https://issues.redhat.com/browse/OCPBUGS-10924)) moved the 4.14 machine-config operator to a non-default ServiceAccount and ClusterRoleBinding.  But 4.13 and earlier remain on the default ServiceAccount.

1cdb75f6ce (#3923, [OCPBUGS-19400](https://issues.redhat.com/browse/OCPBUGS-19400)) brought `Recreate` logic back to [4.13.14][1] and later (good), but also brought back a `delete` manifest for the default ClusterRoleBinding, which leads to the 4.13 cluster-version operator fighting with itself over whether that ClusterRoleBinding should exist (it should exist on 4.13, [OCPBUGS-21721](https://issues.redhat.com/browse/OCPBUGS-21721)).  For example, [this CI run][2] updates from 4.12.36 to 4.13.14, and has:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/1707415968109563904/artifacts/e2e-aws-upgrade/clusterversion.json | jq -r '.items[].status.conditions[] | select(.type == "Upgradeable") | .lastTransitionTime + " " + .type + "=" + .status + " " + .reason + ": " + .message'
2023-09-28T17:09:41Z Upgradeable=False ResourceDeletesInProgress: Cluster minor level upgrades are not allowed while resource deletions are in progress; resources=clusterrolebinding "default-account-openshift-machine-config-operator"
```

**- What I did**

By dropping the deletion manifest from 4.13, we avoid contention between two manifests, and leave the default ClusterRoleBinding alone until a later update to 4.14 will remove it.

**- How to verify it**

Update from 4.12 to 4.13.  Confirm that the default ClusterRoleBinding exists and that ClusterVersion's `Upgradeable` is not complaining about `resource deletions are in progress`.

**- Description for the changelog**

Are we doing an MCO change-log?  I'd expect this to get handled via Jira fields.

[1]:  https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.13.14
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/1707415968109563904

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Ignore the bootstrap-unit failure, I caused that via a previous PR and haven't had a chance to fix it. Regardless, not a blocking job

**Comment by rioliu-rh** [comment]
pre-merge testing, build ci image with this PR 
upgrade cluster from 4.12.38 to 4.13.0-0.ci.test-2023-10-17-020658-ci-ln-ztgfry2-latest.
upgrade is completed successfully
check status conditions of clusterversion/version, no condition `ResourceDeletesInProgress` found. 
```console
$ cv version -o yaml | yq -y '.status.conditions'
- lastTransitionTime: '2023-10-17T02:24:27Z'
  message: 'Unable to retrieve available updates: currently reconciling cluster version
    4.13.0-0.ci.test-2023-10-17-020658-ci-ln-ztgfry2-latest not found in the "stable-4.12"
    channel'
  reason: VersionNotFound
  status: 'False'
  type: RetrievedUpdates
- lastTransitionTime: '2023-10-17T02:50:37Z'
  message: Capabilities match configured spec
  reason: AsExpected
  status: 'False'
  type: ImplicitlyEnabledCapabilities
- lastTransitionTime: '2023-10-17T02:24:27Z'
  message: Payload loaded version="4.13.0-0.ci.test-2023-10-17-020658-ci-ln-ztgfry2-latest"
    image="registry.build05.ci.openshift.org/ci-ln-ztgfry2/release:latest" architecture="amd64"
  reason: PayloadLoaded
  status: 'True'
  type: ReleaseAccepted
- lastTransitionTime: '2023-10-17T02:43:14Z'
  message: Done applying 4.13.0-0.ci.test-2023-10-17-020658-ci-ln-ztgfry2-latest
  status: 'True'
  type: Available
- lastTransitionTime: '2023-10-17T03:56:12Z'
  status: 'False'
  type: Failing
- lastTransitionTime: '2023-10-17T03:58:27Z'
  message: Cluster version is 4.13.0-0.ci.test-2023-10-17-020658-ci-ln-ztgfry2-latest
  status: 'False'
  type: Progressing
```

**Comment by sinnykumari** [comment]
this makes sense. Thanks Trevor
/lgtm
/label backport-risk-assessed

**Comment by rioliu-rh** [comment]
/retitle OCPBUGS-19400,OCPBUGS-21721: install/0000_90_machine-config-operator_90_deletion: Drop this file

**Pull request merged**
