### PR TITLE
Make our resourcemerge fork update a container's Resources.Requests, un-revert #2802 

### PR DESCRIPTION
**Pull request by jkyros**
A payload was rejected due to upgrade test failures for the machine-config-controller, and PR #2802 was reverted.  

```
{  fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: Mar 17 07:40:40.823: Pods in platform namespaces are not following resource request/limit rules or do not have an exception granted:
  apps/v1/Deployment/openshift-machine-config-operator/machine-config-controller/container/oauth-proxy does not have a cpu request (rule: "apps/v1/Deployment/openshift-machine-config-operator/machine-config-controller/container/oauth-proxy/request[cpu]")
  apps/v1/Deployment/openshift-machine-config-operator/machine-config-controller/container/oauth-proxy does not have a memory request (rule: "apps/v1/Deployment/openshift-machine-config-operator/machine-config-controller/container/oauth-proxy/request[memory]")}
```
This PR "un-reverts" the reversion from https://github.com/openshift/machine-config-operator/pull/3027 and fixes the underlying issue that was causing the failures. 

#### How the original problem happened: 

- We added the oauth-proxy to machine-config-controller as part of #2802. 
- The machine-config-controller manifest which contained it existed in earlier versions, but the oauth-proxy "sidecar" was new. 
- On upgrade we don't reapply the machine-config-controller manifest, we merge the old and the new container settings and update the object
- The oauth-proxy fields got merged into the new object, but the oauth-proxy container's requested resources got scraped off because our fork of the resourcemerge library didn't know how to merge Resources.Requests
- Payload tests failed because those fields were missing after an update. (  even though they were present in the manifest, they were not present on the object ) 

#### How this fixes it: 
- This makes sure we update the container's Resources.Requests structure when we merge the container object so required fields are no longer missing when we upgrade

### CODE REVIEW

**Comment by mkenigs** [comment]
Grr wish we could have gotten https://github.com/openshift/machine-config-operator/pull/2882 in and avoided this

**Comment by jkyros** [comment]
I think our deal was in order to re-merge we needed a clean payload test (after we passed CI). e2e-agnostic-upgrade will probably flake at least once, but even so I'm going to hold this so it doesn't try to auto-merge. I'll trigger the payload test after we get a green CI run. 
/hold

**Comment by jkyros** [comment]
I'm not just blindly mashing on it, I promise. That last run was sandbox creation failures because it couldn't reach the container registry. 
/retest

**Comment by jkyros** [comment]
@deads2k it looks like that passed everything in the payload test except for those failures in [e2e-aws-serial  ](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-machine-config-operator-3028-ci-4.11-e2e-aws-serial/1504807446261010432) and that looks like etcd problems (and I am not seeing a way this code could be affecting that). 

There were a couple lines under `"Multi-stage test e2e-aws-serial - e2e-aws-servial-openshift-e2e-test container test` that briefly gave me pause, since we did change those ClusterRoles as part of this PR but it didn't look like it was saying that's what caused the failure, just that those roles changed ( I also might be interpreting that wrong ) : 

```
{  0.000 I ns/openshift-machine-config-operator deployment/machine-config-operator reason/ClusterRoleUpdated Updated ClusterRole.rbac.authorization.k8s.io/machine-config-controller -n openshift-machine-config-operator because it changed
Mar 18 15:10:50.000 I ns/openshift-machine-config-operator deployment/machine-config-operator reason/ClusterRoleUpdated Updated ClusterRole.rbac.authorization.k8s.io/machine-config-controller-events -n openshift-machine-config-operator because it changed
Mar 18 15:10:50.709 E e2e-test/"[sig-instrumentation][Late] OpenShift alerting rules should have a runbook_url annotation if the alert is critical [Skipped:Disconnected] [Suite:openshift/conformance/parallel]" finishedStatus/Flaked

Failing invariants:

[bz-etcd][invariant] alert/etcdHighNumberOfLeaderChanges should not be at or above info
```

With that `e2e-aws-serial`  failure, is that "back to the drawing board" for this, or does this still have a shot at getting in? 

(I didn't want to just try retesting again without because these tests are expensive)

**Pull request merged**
