### PR TITLE
OCPBUGS-19958: [release-4.13] Backport logspam PRs

### PR DESCRIPTION
**Pull request by yuqi-zhang**
A combined backport of John's work in https://github.com/openshift/machine-config-operator/pull/3662, https://github.com/openshift/machine-config-operator/pull/3682, https://github.com/openshift/machine-config-operator/pull/3713

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
uh maybe it's 

/jira cherrypick OCPBUGS-4877

**Comment by jkyros** [comment]
yep, that looks like all of em
/lgtm

**Comment by sinnykumari** [comment]
@yuqi-zhang Looks like bootstrap-unit  is not required in 4.13 and PR got merged with test failing. Can you take a look at this failing test and see if we need to do any fixes in a follow-up PR.

**Pull request merged**
