### PR TITLE
Migrate kubeletconfig to kubernetes@1.12.5

### PR DESCRIPTION
**Pull request by abhinavdahiya**
/cc @rphillips @sjenning

### CODE REVIEW

**Comment by rphillips** [comment]
I'll take a look at the failure.

**Comment by rphillips** [comment]
Looks like the CVO needs a bump, and the MCO code updated to use the newer CVO client:

```
        master: Could not introduce github.com/openshift/cluster-version-operator@master, as its subpackage github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned is missing. (Package is required by (root).)
```

**Comment by abhinavdahiya** [comment]
> Looks like the CVO needs a bump, and the MCO code updated to use the newer CVO client:
> 
> ```
>         master: Could not introduce github.com/openshift/cluster-version-operator@master, as its subpackage github.com/openshift/cluster-version-operator/pkg/generated/clientset/versioned is missing. (Package is required by (root).)
> ```

we should drop any code that imports CVO, we are not using anything from cluster version operator. The OperatorStatus moved to `openshift/api/ config`

**Comment by rphillips** [comment]
/lgtm

nice job!

**Pull request merged**
