### PR TITLE
TEST: update bindata.go

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
seeing `test verify` fail on a docfix: https://github.com/openshift/machine-config-operator/pull/953

which seems..wrong

### CODE REVIEW

**Comment by runcom** [comment]
Nope, we've updated Bindata to use the official github.com/go-bindata/go-bindata https://github.com/openshift/machine-config-operator/pull/929

You need to use that and this can be closed

**Comment by kikisdeliveryservice** [comment]
why is #953 failing test verify?? it's a docfix

**Comment by kikisdeliveryservice** [comment]
i updated my setup and did `go get -u github.com/go-bindata/go-bindata` and running `make update` on master updates bindata.go

**Comment by cgwalters** [comment]
Hm yeah I'm not sure what's going wrong here to be honest.  Offhand thought, maybe the CI has a cached image with an older build of `go-bindata`?

**Comment by kikisdeliveryservice** [comment]
#957 is the bindata fix. will open an issue summarzing what happened and we can decide how to proceed

**Pull request closed without merging**
