### PR TITLE
[release-4.14] OCPBUGS-19344: Ignore invoking nbctl calls if its SDN

### PR DESCRIPTION
**Pull request by tssurya**
**- What I did**
Clean cherry-pick of https://github.com/openshift/machine-config-operator/pull/3926

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by tssurya** [comment]
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-sdn 10

**Comment by tssurya** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade 10

**Comment by asood-rh** [comment]
/label qe-approved

Azure cluster created with PR came up stable.
 systemctl status openshift-azure-routes.service shows nbctl call not invoked.

Sep 21 15:39:33 ci-ln-76gvi7t-1d09d-5kzh5-master-0 openshift-azure-routes[23977]: Plugin is SDN, nothing to do.. exiting

**Review by trozet — APPROVED** [review]
/lgtm

**Review by sinnykumari — APPROVED** [review]

**Pull request merged**
