### PR TITLE
[release-4.6] Bug 1933206: Revert "pkg/daemon: Add IgnitionVersion to Daemon"

### PR DESCRIPTION
**Pull request by bgilbert**
This is a non-automated cherry-pick of #2431.

### CODE REVIEW

**Review by ashcrow — APPROVED** [review]

**Comment by mfojtik** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.


* Score: *0.20*
* Reason: *maximum total for this z-stream is 10*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Pull request merged**
