### PR TITLE
Bug 1703234: pkg/operator: ignore CM changes that we don't care about

### PR DESCRIPTION
**Pull request by runcom**
Triggering a sync on the following CMs chnages causes a wasteful sync (every 14s):
```
NAME                             DATA   AGE
machine-config                   0      27m
machine-config-controller        0      27m
```
Those cms seem to be bound to operator and controller leases. Since we
don't need to listen on them for our sync, just ignore them.

I'm following up with someone who understands more than me on this but it shouldn't be an issue to just ignore those.

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
/hold

this is quite spammy actually - holding till I at least figure stuff in my test cluster - we can drop this to glog v2 maybe.

**Comment by runcom** [comment]
ok, somehow we have a ConfigMap resyncinc every 14s for no good reason - trying to understand why now.

**Comment by runcom** [comment]
```

**Comment by runcom** [comment]
/hold

We need to wholly ignore Config maps based on the leader annotation (got word from Clayton). I'll change this later today.

**Comment by runcom** [comment]
/hold cancel

fully good to go now!

**Comment by runcom** [comment]
leaning towards skipping that test..........

**Comment by kikisdeliveryservice** [comment]
> leaning towards skipping that test..........

the etcd quorum loss one?  looking at the runs it hasn't had a successful one on this pr at all and only 2 successful runs since Monday... yikes

**Comment by runcom** [comment]
> the etcd quorum loss one? looking at the runs it hasn't had a successful one on this pr at all and only 2 successful runs since Monday... yikes

yeah, it's known to be highly flake :(

**Pull request merged**
