### PR TITLE
Bug 1755558: Ensure ETCD_INITIAL_CLUSTER is preserved during restore

### PR DESCRIPTION
**Pull request by smarterclayton**
`/run/etcd/environment` can contain ETCD_INITIAL_CLUSTER which would
override the value the user provided as an argument. This flow is
used during disaster recovery when only a single master remains and
the INITIAL_CLUSTER value needs to come from the user (the other
members are dead / gone).

Backport #1135

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@smarterclayton  Unfortunately 4.1 uses a different gobindata than the rest... for this one you have to use https://github.com/jteeuwen/go-bindata then do the makeverify.

See: https://github.com/openshift/machine-config-operator/pull/1132/files

**Comment by hexfusion** [comment]
@smarterclayton 4.1 we need to regen test files.

I think it is `go test ./pkg/controller/template/... -u`

/cc @kikisdeliveryservice

**Comment by runcom** [comment]
to fix unit tests:

```bash
$ go test ./pkg/controller/template/... -u
```

**Comment by kikisdeliveryservice** [comment]
```
level=error msg="\t* module.vpc.aws_lb.api_internal: 1 error occurred:"
level=error msg="\t* aws_lb.api_internal: timeout while waiting for state to become 'active' (last state: 'provisioning', timeout: 20m0s)
```

aws errors now

**Comment by eparis** [comment]
/retest
does this get lgtm/approval from the team now?

**Comment by runcom** [comment]
re-echoing the lgtm and leaving to patch manager

/lgtm

**Comment by ashcrow** [comment]
```
Backport #1135
```
That's this one :smile: 

Backport https://github.com/openshift/machine-config-operator/pull/1133

BZ is verified

**Pull request merged**
