### PR TITLE
FAQ: add entry about RHEL worker nodes

### PR DESCRIPTION
**Pull request by miabbott**
A question came up in Slack about using the MCO with RHEL worker
nodes, so this tries to answer the question.

### CODE REVIEW

**Comment by runcom** [comment]
For reference, https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2145/pull-ci-openshift-machine-config-operator-master-e2e-aws-workers-rhel7/1319673392265170944/artifacts/e2e-aws-workers-rhel7/gather-extra/pods/openshift-machine-config-operator_machine-config-daemon-2z4cl_machine-config-daemon.log <- rhel workers have an instance of the MCD running 

:+1: 

/approve

**Comment by sinnykumari** [comment]
Since this is a doc update, ci shouldn't be affected by the change.
/skip

**Pull request merged**
