### PR TITLE
templates: bump etcd to v3.3.10

### PR DESCRIPTION
**Pull request by hexfusion**
Currently OpenShift 4.0 installs are using an old version of etcd v3.2.14. This PR bumps that to 3.3.10 which will be the release version. I am going to leave the previous comments in here as a reminder as we will be using a different image.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@hexfusion can you run `go test ./pkg/controller/template/... -u` to update the golden files for unit tests.

**Comment by hexfusion** [comment]
> @hexfusion can you run `go test ./pkg/controller/template/... -u` to update the golden files for unit tests.

@abhinavdahiya thank you for the help, updated.

**Comment by hexfusion** [comment]
I need to review the logs on the images I am seeing a fair bit of I/O related issues with etcd but this will require a deeper look.

**Comment by hexfusion** [comment]
@abhinavdahiya reran tests and all are green, do you have any further concerns?

**Comment by abhinavdahiya** [comment]
@hexfusion needs a rebase.. :innocent:

**Comment by ashcrow** [comment]
This makes sense to me but I'll let @abhinavdahiya do the honors :smile:

**Pull request merged**
