### PR TITLE
Add openAPIV3Schema to CRDs

### PR DESCRIPTION
**Pull request by sanchezl**

### CODE REVIEW

**Comment by sanchezl** [comment]
Needs https://github.com/coreos/ignition/issues/917 resolved.

**Comment by yuqi-zhang** [comment]
I think we can close this in favour of https://github.com/openshift/machine-config-operator/pull/1485, and we can work on the generation later after https://github.com/idubinskiy/schematyper/pull/18 and https://github.com/openshift/machine-config-operator/pull/996 in https://github.com/openshift/machine-config-operator/pull/1486

**Comment by LorbusChris** [comment]
Once #996 has merged we could immediately move the api definitions over to the api repo. Therefore my question is, should try to solve this locally in this repo, or over in api?

**Comment by yuqi-zhang** [comment]
> should try to solve this locally

by this do you mean the definitions themselves or the auto generation? The definitions themselves have been merged. The generation of manifests don't have to live in the MCO repo.

**Comment by LorbusChris** [comment]
ok awesome. Then the question should've really been: Do we move the api over immediately after unblocking that, or is there a reason to wait with that?

**Comment by kikisdeliveryservice** [comment]
> I think we can close this in favour of #1485, and we can work on the generation later after [idubinskiy/schematyper#18](https://github.com/idubinskiy/schematyper/pull/18) and #996 in #1486

closing as per the above message. if this is in error, please reopen.

**Pull request closed without merging**
