### PR TITLE
Prep patches for bumping openshift/client-go

### PR DESCRIPTION
**Pull request by cgwalters**
go.mod: Unpin k8s.io bits

Prep for bumping openshift/library-go.

---

go.mod: Remove pinned googleapis/gnostic

Prep for bumping openshift/client-go.

---

### CODE REVIEW

**Comment by cgwalters** [comment]
We're seeing everything just be slightly slower here...
/retest

**Comment by jkyros** [comment]
I did glance through those test runs. Am I correct in interpreting the above as 

- "the tests were probably slow because of unrelated issues and everything is probably fine" 

rather than

- "The library bump seems to have made the MCO noticably slower? "

:smile:

**Comment by cgwalters** [comment]
I'm not sure honestly.  Offhand, I think our e2e-gcp-op may have actually been suffering from https://github.com/openshift/os/pull/898 which got fixed.

**Review by yuqi-zhang — APPROVED** [review]
Ok so the slowdown seems to have gone away with the aforementioned fixes in https://github.com/openshift/os/pull/898. Now cleanup or not the delay is generally very small:

No cleanup: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/3251/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1549833049129095168/artifacts/e2e-gcp-op/gather-extra/artifacts/pods/openshift-machine-config-operator_machine-config-daemon-4tkk5_machine-config-daemon.log

and 

Cleanup: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/3251/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1549833049129095168/artifacts/e2e-gcp-op/gather-extra/artifacts/pods/openshift-machine-config-operator_machine-config-daemon-fv4vz_machine-config-daemon.log

Otherwise, this looks like a clean bump, all CI is happy, let's get this in!

/lgtm

**Pull request merged**
