### PR TITLE
Bug 1775643: [release-4.3] Revert "*: add support for cluster-etcd-operator"

### PR DESCRIPTION
**Pull request by hexfusion**
`cluster-etcd-operator` did not make it into 4.3 some of the changes made before feature freeze lead to regression in DR. I feel strongly that these changes should be reverted and a new approach taken in 4.4. Specifically moving `setup-etcd-environment` out if MCO into `cluster-etcd-operator`. As these changes will not be used in 4.3 and adds unnecessary complexity to the etcd-member spec revert feels appropriate.

This reverts commits

- cmd/setup-etcd-environment: reduce cyclomatic complexity:
  e3163a5165bc4833d42488e6e74cbf1c7a12f0bc

- *: resolve verify failures
  5741f892b8e2db31612e662fccd45da3df5f5ce7

- cmd/setup-etcd-environment: remove etcd-bootstrap hard coded value
  d96a1cca54b03c19b36421542bc8bea8b1a97efd

- cmd/setup-etcd-env: set ENDPOINTS after it is populated
  a56735d1ede127255a774a0caa79310146be0c15

- *: use kubecsr mount, add readiness probe to etcd pod
  b67b2d40e3131c39fe0a57bb7ed895e6414080ba

- setup-etcd-environment: add logic to mount certs
  f43ecedb17ed377f47e50fd9eec7358924e2f6f7

- setup-etcd-environment: add base scaleup logic
  f68859ea2217e804fd95aee70e27fa6ea60d4e83

- *: Add cluster etcd operator image in MCO
   492fac6a218c7d305709af5a144436a418db90a6

### CODE REVIEW

**Comment by hexfusion** [comment]
@kikisdeliveryservice thanks all set.

**Comment by kikisdeliveryservice** [comment]
Is there a PR reverting this in master? That would need to merge first.

**Comment by hexfusion** [comment]
No this is only for 4.3 4.4/master will stay.

**Comment by kikisdeliveryservice** [comment]
Ahh so we are saying that we are reverting 4.3 bc it is incomplete and thus more stable to just wait until it's all in the next go round?

**Comment by hexfusion** [comment]
This code being reverted introduced a regression in 4.3 DR. So cleaning this all up and improving stability is my major concern. As the code is not used by 4.3 in anyway reverting feels the cleanest way forward.

**Comment by hexfusion** [comment]
cc @smarterclayton although https://github.com/openshift/machine-config-operator/pull/1287 will resolve the DR regression. It would be a lot cleaner to just revert all cluster-etcd-operator related changes we made in MCO for 4.3. If this is a problem I can rework.

**Comment by hexfusion** [comment]
cc @derekwaynecarr

**Pull request merged**
