### PR TITLE
Bug 2024826: Allow resolv prepender without default search domain

### PR DESCRIPTION
**Pull request by mandre**
Commit e1fbf07 introduced a regression where the local nameserver was
only prepended to the list of nameservers when the NM generated
`resolv.conf` had a default search domain.

This commit fix the regex to look for nameservers rather than search
domain, and makes the script a little more robust by using start of
line anchor in regexes.

### CODE REVIEW

**Comment by mandre** [comment]
Hi @cybertron, can you PTAL at this bug fix for your recent change #2835. We're unable to deploy OCP on clouds that don't provide a default search domain via DHCP.
/assign @cybertron

**Comment by cybertron** [comment]
/lgtm

I tested this locally and it still does what we need for baremetal, so should be good to go. Thanks for the fix!

**Comment by mandre** [comment]
This needs an approval.
/assign sinnykumari

**Review by sinnykumari — APPROVED** [review]

**Comment by mdbooth** [comment]
This is blocking me.

**Pull request merged**
