### PR TITLE
Bug 1919272: [release-4.6] NM resolve prepender: support appending a nameserver for systemd-resolved

### PR DESCRIPTION
**Pull request by vrutkovs**
FCOS 33 doesn't use NM to manage resolv.conf. Instead it uses systemd-resolved.
The script should not replace /etc/resolv.conf in this case, but instead create a dropin for systemd-resolved.

Cherry-pick of https://github.com/openshift/machine-config-operator/pull/2359 on release-4.6

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

Testing it now

**Comment by sinnykumari** [comment]
lol, gave lgtm on wrong PR. It was intended for https://github.com/openshift/release/pull/15145
/lgtm cancel

**Comment by vrutkovs** [comment]
OKD vSphere setup reaches test phase, fails on unit tests

**Comment by vrutkovs** [comment]
/hold cancel

Seems to work on CI

**Comment by vrutkovs** [comment]
/test okd-e2e-vsphere

Failed to checkout src

**Comment by vrutkovs** [comment]
OKD vSphere test keeps picking up older installer (boostrap fixed in https://github.com/openshift/installer/pull/4584), not sure why

**Comment by vrutkovs** [comment]
/test okd-e2e-vsphere

Failed to obtain the lease

**Comment by jcpowermac** [comment]
vSphere CI failures were caused by docker rate limiting, looks like OKD installed correctly.

/lgtm

**Review by kikisdeliveryservice — APPROVED** [review]

**Review by Fedosin — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
/test e2e-ovirt
/skip

Skipping OKD tests - these fail on known flakes

**Pull request merged**
