### PR TITLE
[release-4.15] OCPBUGS-30761: add static pods for rbacproxy

### PR DESCRIPTION
**Pull request by rphillips**
Cherry pick of https://github.com/openshift/machine-config-operator/pull/4175

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
/label backport-risk-assessed

Should be safe to merge since nothing should be using these, but since this is technically a backport (not sure why the bot allows it via a story card) will hold off lgtm until we can verify (or open a bug)

**Review by harche — COMMENTED** [review]
/lgtm

**Pull request merged**
