### PR TITLE
[WIP] Bug 1850057: update etcd followers first, use bfq on control plane

### PR DESCRIPTION
**Pull request by cgwalters**
This PR rolls up a few others, including notably:

- https://github.com/openshift/machine-config-operator/pull/1957
- https://github.com/openshift/machine-config-operator/pull/1962

Then adds: WIP: Update etcd followers first 

The way we're talking to etcd is a bit hacky, I ended up cargo
culting some code.  This would be much cleaner if the etcd operator
did it.

But it's critical that we update the etcd followers first, because
leader elections are disruptive events and we can easily minimize
that.

Closes: https://github.com/openshift/machine-config-operator/issues/1897

---

### Updated release images for testing (v2)

I think the previous results were misleading/broken due to using the same release image as base, new images:

`test upgrade registry.svc.ci.openshift.org/coreos/walters-mco-upgrade-release@sha256:25deaaf3074cf984f352ab92fca5f61c4663c9b506ce05c50db8f723a5b386b7 registry.svc.ci.openshift.org/coreos/walters-mco-upgrade-release-target@sha256:1ad5e2fb2df0e4af4abd3c1e59461a7977924201eb0eada524ce7af34d7ac1c4`

- 🔴 https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1291715700414484480 
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1291842967132180480
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-azure/1291842988791566336
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1291842941274296320

### CODE REVIEW

**Comment by cgwalters** [comment]
OK a while ago I'd invested some time in tweaking the node controller to have useful logs around what it's doing; my first "point of contact" when looking at upgrades was its logs.  But...we lose most those on upgrade since the pod gets killed, so trying to determine success for this PR was annoying.

Ended up reworking things here so the node controller emits events - currently the MCD emits useful events which can be queried afterwards (in our CI runs we dump `events.json`).  I added a single event emitted when the node controller changes a node target config, but also added special events just for the control plane.  Going forward I think we should (strategically) do more of this "special case the control plane" at least for extra logging and care.

**Comment by kikisdeliveryservice** [comment]
Wondering how this squares with @ericavonb comment:
https://github.com/openshift/machine-config-operator/pull/1947#issuecomment-665971962

```
Catching up on all the issues behind this PR. I don't like adding new etcd-specific logic to the MCO. It feels like this moves us backwards from separating out etcd concerns into its own operator. Can we do this in a more component-agnostic way?

Something like, a node label or annotation that specifies upgrade priority classes maybe?
```

Since there have been huge efforts to decouple MCO/etcd in 4.5 and move to the etcd operator?

**Comment by ericavonb** [comment]
> Since there have been huge efforts to decouple MCO/etcd in 4.5 and move to the etcd operator?
Right. Like looking at this PR, could the etcd-specific stuff in the daemon be done in the etcd-operator? Why are putting it in the MCO?

**Comment by cgwalters** [comment]
OK yeah I think the events are useful, e.g. with this PR I can do
` jq '.items[] | select(.source.component == "machineconfigcontroller-nodecontroller") | .firstTimestamp + " " + .message' < events.json |less` and see:
```
"2020-07-30T04:28:07Z Deferring update of etcd leader ci-op-5tr7l488-28de9-769ls-master-2"
"2020-07-30T04:28:07Z Targeted node ci-op-5tr7l488-28de9-769ls-master-0 to config rendered-master-a22c80e6e6f0f775632695e7b355590f"
"2020-07-30T04:28:07Z Node ci-op-5tr7l488-28de9-769ls-master-0 now has machineconfiguration.openshift.io/desiredConfig=rendered-master-a22c80e6e6f0f775632695e7b355590f"
"2020-07-30T04:28:08Z Node ci-op-5tr7l488-28de9-769ls-master-0 now has machineconfiguration.openshift.io/state=Working"
"2020-07-30T04:30:22Z Deferring update of etcd leader ci-op-5tr7l488-28de9-769ls-master-2"
"2020-07-30T04:30:22Z Targeted node ci-op-5tr7l488-28de9-769ls-master-1 to config rendered-master-a22c80e6e6f0f775632695e7b355590f"
"2020-07-30T04:30:22Z Node ci-op-5tr7l488-28de9-769ls-master-1 now has machineconfiguration.openshift.io/desiredConfig=rendered-master-a22c80e6e6f0f775632695e7b355590f"
"2020-07-30T04:30:23Z Node ci-op-5tr7l488-28de9-769ls-master-1 now has machineconfiguration.openshift.io/state=Working"
"2020-07-30T04:32:53Z Targeted node ci-op-5tr7l488-28de9-769ls-master-2 to config rendered-master-a22c80e6e6f0f775632695e7b355590f"
"2020-07-30T04:32:53Z Node ci-op-5tr7l488-28de9-769ls-master-2 now has machineconfiguration.openshift.io/desiredConfig=rendered-master-a22c80e6e6f0f775632695e7b355590f"
"2020-07-30T04:32:54Z Node ci-op-5tr7l488-28de9-769ls-master-2 now has machineconfiguration.openshift.io/state=Working"
"2020-07-30T04:33:34Z Node ci-op-5tr7l488-28de9-769ls-master-0 now has machineconfiguration.openshift.io/uds=1"
"2020-07-30T04:34:58Z Node ci-op-5tr7l488-28de9-769ls-master-2 now has machineconfiguration.openshift.io/uds=0"
"2020-07-30T04:28:07Z Targeted node ci-op-5tr7l488-28de9-769ls-worker-b-95ssc to config rendered-worker-49464673d8d72c9fe228d47ddc99d968"
"2020-07-30T04:32:53Z Targeted node ci-op-5tr7l488-28de9-769ls-worker-c-7fp2l to config rendered-worker-49464673d8d72c9fe228d47ddc99d968"
"2020-07-30T04:35:09Z Targeted node ci-op-5tr7l488-28de9-769ls-worker-d-gtzb4 to config rendered-worker-49464673d8d72c9fe228d47ddc99d968"
```

**Comment by cgwalters** [comment]
> Since there have been huge efforts to decouple MCO/etcd in 4.5 and move to the etcd operator?
> Right. Like looking at this PR, could the etcd-specific stuff in the daemon be done in the etcd-operator? Why are putting it in the MCO?

It sounds like you're suggesting a different *tactic*, not a different strategy, correct?  In other words, the strategy is ensuring the MCO upgrades etcd followers first, the tactic is how that's implemented.

I totally agree that the way we're talking to etcd directly here is hacky, but the debate for that is over here:
https://github.com/openshift/api/pull/694

**Comment by cgwalters** [comment]
Split out from this:

 - https://github.com/openshift/machine-config-operator/pull/1962
 - https://github.com/openshift/machine-config-operator/pull/1957

**Comment by cgwalters** [comment]
Using [Promecieus](https://promecieus.svc.ci.openshift.org/) and looking at `etcd_server_leader_changes_seen_total` from this PR's [upgrade job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1946/pull-ci-openshift-machine-config-operator-master-e2e-gcp-upgrade/1288675184663859200) I see just one leader change, which looks good.

**Comment by cgwalters** [comment]
This is for https://bugzilla.redhat.com/show_bug.cgi?id=1850057

**Comment by cgwalters** [comment]
OK the effect here is clearly noticeable - the no-op change takes ~10s here, but looking at the timings in https://github.com/openshift/machine-config-operator/pull/1977 the no-op change is 1s.

I'm going to do some more testing with [nontrivial updates](https://github.com/coreos/coreos-assembler/pull/1635).

**Comment by cgwalters** [comment]
Oddly a job with this PR failed upgrade disruption, but one with just the node annotations succeeded:

job test upgrade registry.svc.ci.openshift.org/coreos/walters-mco-upgrade-release@sha256:590160f6354921b38309cedb5191797d65566aa241839e5d45398582b45c7f6a registry.svc.ci.openshift.org/coreos/walters-mco-upgrade-release-target@sha256:4e6c02cf433ad9a45d8639725b7c665557f3143a6a3855fbdbf48aa30b1203a3 failed

job test upgrade nightly registry.svc.ci.openshift.org/coreos/walters-mco-upgrade-release-target@sha256:4e6c02cf433ad9a45d8639725b7c665557f3143a6a3855fbdbf48aa30b1203a3 succeeded

**Comment by cgwalters** [comment]
I just noticed that one of the [azure runs above](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-azure/1291464050709893120) claimed success, but actually didn't upgrade the OS - it seems the MCO was reporting success but clearly the MCC and MCD were still working.

It's *possible* this bug is somehow introduced by this PR...going to go look at some existing e2e-upgrade jobs.

**Comment by cgwalters** [comment]
Ugh and wait a second, [this failed GCP run](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1291464088030810112) seems to have rebooted the masters *twice* - from [this MCD log](https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1291464088030810112/artifacts/launch/pods/openshift-machine-config-operator_machine-config-daemon-8fv4g_machine-config-daemon.log):
`I0806 20:59:03.361444    2297 update.go:1455] Starting update from rendered-worker-a3629c84fa68ef33ff7fa7b5c501041f to rendered-worker-b88d93e7e9a96f5d961386e6e811875a: &{osUpdate:false kargs:false fips:false passwd:false files:false units:true kernelType:false extensions:false}`
Are we potentially racing in the MCC...something like container runtime controller generating a MC after we've already resync'd the core configs?  
/me goes to diff the MCs

**Comment by cgwalters** [comment]
> Are we potentially racing in the MCC...something like container runtime controller generating a MC after we've already resync'd the core configs?

The problem there appears to be quite simple:

- New CVO started and installed updated `configmap/machine-config-osimageurl` 
- The old MCO rendered a new MC with that update, started a rollout to masters/workers
- Then the new MCO took over, rolled out another config update with template changes encapsulated inside it
- So we then upgraded *again*

I thought we had addressed this...but if so, it is lost in the dim spaces between neuron firings for me.

**Comment by cgwalters** [comment]
Updated some commentary in https://github.com/openshift/machine-config-operator/pull/1957

The argument for merging this one (etcd leader awareness) is basically: A useful baseline metric for disruption is etcd leader election count, and if OS upgrades might randomly force that anywhere between 1-3 times, success becomes harder to measure.

But it probably does make sense to do https://github.com/openshift/machine-config-operator/pull/1957 first, (also get https://github.com/openshift/cluster-etcd-operator/pull/418 in), measure a bit, then experiment with this on top.

**Comment by ironcladlou** [comment]
Re: testing, I commented on the issue (https://github.com/openshift/machine-config-operator/issues/1897#issuecomment-673524556) but maybe should have commented here. Cross-referencing...

**Comment by cgwalters** [comment]
Per https://github.com/openshift/machine-config-operator/issues/1897#issuecomment-673524556 we will focus on etcd latency metrics and not leader elections - so it's not worth carrying the code today to have "etcd leader awareness" for node upgrades.

**Comment by cgwalters** [comment]
This PR is now replaced by https://github.com/openshift/machine-config-operator/pull/1957

**Pull request closed without merging**
