### PR TITLE
Migrate to Go Modules

### PR DESCRIPTION
**Pull request by runcom**
Carry #1136 from @LorbusChris - add other commits, and rebased, could be good to go 👍 

Close #1136

### CODE REVIEW

**Comment by rphillips** [comment]
lgtm (but will defer to others)... Is the name phase to bump the openshift deps to 1.16?

**Comment by runcom** [comment]
> lgtm (but will defer to others)... Is the next phase to bump the openshift deps to 1.16?

https://github.com/openshift/machine-config-operator/pull/1146

**Comment by sinnykumari** [comment]
lgtm

works locally as expected, requires gpgme-devel and libassuan-devel packages on host as mentioned in https://github.com/openshift/machine-config-operator/pull/1136#issuecomment-535574990

**Comment by runcom** [comment]
The kube bump PR seems to be working fine - let's get this in @kikisdeliveryservice @ericavonb @sinnykumari @yuqi-zhang

**Pull request merged**
