### PR TITLE
OCPBUGS-32922: [release-4.15] add cluster fleet evaluation support to mco

### PR DESCRIPTION
**Pull request by rphillips**
Backports https://github.com/openshift/machine-config-operator/pull/4316 to 4.15.

### CODE REVIEW

**Review by QiWang19 — COMMENTED** [review]
/lgtm

**Review by yuqi-zhang — APPROVED** [review]
Sane backport

**Comment by lyman9966** [comment]
/label qe-approved 
1)oc get clusteroperators.config.openshift.io machine-config -o yaml | grep EvaluationConditionsDetected -B 3
  - lastTransitionTime: "2024-04-12T13:03:04Z"
    reason: AsExpected
    status: "False"
    type: EvaluationConditionsDetected
2)Applying:
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-worker-kube-config
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
  kubeletConfig:
    failSwapOn: false
3) oc get clusteroperators.config.openshift.io machine-config -o yaml | grep EvaluationConditionsDetected -B 3
  - lastTransitionTime: "2024-04-30T05:01:00Z"
    reason: 'failswapon: KubeletConfig setting is currently unsupported by OpenShift'
    status: "True"
    type: EvaluationConditionsDetected
4) Applying: 
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
 name: set-runtime
spec:
 machineConfigPoolSelector:
   matchLabels:
     pools.operator.machineconfiguration.openshift.io/worker: ""
 containerRuntimeConfig:
   defaultRuntime: "runc"
5)% oc get clusteroperators.config.openshift.io machine-config -o yaml | grep EvaluationConditionsDetected -B 3
    reason: 'failswapon: KubeletConfig setting is currently unsupported by OpenShift::runc:
      transition to default crun'
    status: "True"
    type: EvaluationConditionsDetected
6)Applying:
apiVersion: config.openshift.io/v1
kind: Node
metadata:
  name: cluster
spec:
  cgroupMode: v1
7)% oc get clusteroperators.config.openshift.io machine-config -o yaml | grep EvaluationConditionsDetected -B 5     
  - lastTransitionTime: "2024-04-30T05:01:00Z"
    reason: 'cgroupsv1: support has been deprecated in favor of cgroupsv2::failswapon:
      KubeletConfig setting is currently unsupported by OpenShift::runc: transition
      to default crun'
    status: "True"
    type: EvaluationConditionsDetected

**Pull request merged**
