### PR TITLE
Extend container runtime request timeout from 2m to 4m.

### PR DESCRIPTION
**Pull request by dgoodwin**
This is an attempt at understanding problems on Azure related to bug
https://bugzilla.redhat.com/show_bug.cgi?id=2025967

We are unsure if this will be a permanent change or not, but it will
help point us in the right direction.

### CODE REVIEW

**Comment by sinnykumari** [comment]
PTAL
/assign @rphillips

**Comment by rphillips** [comment]
If we want to do this we should set it in the kubelet config ([Worker](https://github.com/openshift/machine-config-operator/blob/master/templates/worker/01-worker-kubelet/_base/files/kubelet.yaml) [Master](https://github.com/openshift/machine-config-operator/blob/master/templates/master/01-master-kubelet/_base/files/kubelet.yaml)), and remove the [restriction](https://github.com/openshift/machine-config-operator/blob/7615a61b2b440986fa0410adab7efdfa8aa44ae1/pkg/controller/kubelet-config/helpers.go#L262) to set the option.

Do we have signal from CI that this change helps?

**Comment by dgoodwin** [comment]
> If we want to do this we should set it in the kubelet config ([Worker](https://github.com/openshift/machine-config-operator/blob/master/templates/worker/01-worker-kubelet/_base/files/kubelet.yaml), [Master](https://github.com/openshift/machine-config-operator/blob/master/templates/master/01-master-kubelet/_base/files/kubelet.yaml)), and remove the [restriction](https://github.com/openshift/machine-config-operator/blob/7615a61b2b440986fa0410adab7efdfa8aa44ae1/pkg/controller/kubelet-config/helpers.go#L262) to set the option.
> 
> Do we have signal from CI that this change helps?

Ok I can rework that in those three places.

We do not have any signal this will help, we'll need to see it run like this for a few days and frankly I have my doubts, but we need to try anything at this point.

**Comment by rphillips** [comment]
migrating this PR to https://github.com/openshift/machine-config-operator/pull/2883

**Pull request closed without merging**
