### PR TITLE
process extensions before file updates

### PR DESCRIPTION
**Pull request by yuvalk**
so that files/ systemd units can rely on extensions in the same MC

Closes: OCPBUGS-17826

**- What I did**
I changed the order by which update is applied, so that extensions are processed before files (systemd, file content, etc)

**- How to verify it**
try with the following mc spec:
```
  config:
    ignition:
      version: 3.2.0
  extensions:
    - ipsec
  systemd:
    units:
    - name: ipsec.service
      enabled: true
```

**- Description for the changelog**
change update apply order so that extensions can be specified with systemd units that relate to extension content

### CODE REVIEW

**Comment by sinnykumari** [comment]
Unfortunately this is not going to help for this usecase. Extensions and OSUpdates are applied using rpm-ostree and this results into a new deployment. They don't get reflected to current OS deployment to which it has been booted. While, any writing file/ systemd service and any processing to it happen to booted deployment on RHCOS node.

**Comment by yuvalk** [comment]
> Unfortunately this is not going to help for this usecase. Extensions and OSUpdates are applied using rpm-ostree and this results into a new deployment. They don't get reflected to current OS deployment to which it has been booted. While, any writing file/ systemd service and any processing to it happen to booted deployment on RHCOS node.

right, that would be too easy ;-)

**Comment by cgwalters** [comment]
This relates to https://github.com/openshift/machine-config-operator/issues/1190 which is going to be fixed by the in-cluster build and layering because we consistently and transactionally update the OS and configuration as one unit in this approach.

**Pull request closed without merging**
