### PR TITLE
Bug 1825991: Remove vsphere-non-virtual-ip.yaml from worker templates

### PR DESCRIPTION
**Pull request by mtnbikenc**
The file conflicts with the common template file of the same name (vsphere-non-virtual-ip.yaml) causing the nodeip-configuration service to fail on workers.

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by mtnbikenc** [comment]
/test e2e-aws-scaleup-rhel7

```
Worker config rollout failed
```

**Comment by kikisdeliveryservice** [comment]
@jcpowermac PTAL

**Pull request merged**
