### PR TITLE
OCPBUGS-28974, OCPBUGS-21628: daemon: Handle correctly OS Version for 4.1 and 4.2 bootimages

### PR DESCRIPTION
**Pull request by sinnykumari**
Fixes:
- https://issues.redhat.com/browse/OCPBUGS-28974
- https://issues.redhat.com/browse/OCPBUGS-21628

### CODE REVIEW

**Comment by sinnykumari** [comment]
We may have to do post merge verification since it hits image pull related issue when scale-up gets tested with older bootimage:
```
Jun 25 14:19:47 ip-10-0-64-54 sh[1474]: Trying to pull registry.build03.ci.openshift.org/ci-ln-7fgcnct/stable@sha256:d2a5c5414fbffb6212a4fdb0a471787a3bdfb77e784bbb555265288158dd41fb...time="2024-06-25T14:19:47Z" level=error msg="Error pulling image ref //registry.build03.ci.openshift.org/ci-ln-7fgcnct/stable@sha256:d2a5c5414fbffb6212a4fdb0a471787a3bdfb77e784bbb555265288158dd41fb: Digest of source image's manifest would not match destination reference"
Jun 25 14:19:47 ip-10-0-64-54 sh[1474]: Failed
Jun 25 14:19:47 ip-10-0-64-54 sh[1474]: Error: error pulling image "registry.build03.ci.openshift.org/ci-ln-7fgcnct/stable@sha256:d2a5c5414fbffb6212a4fdb0a471787a3bdfb77e784bbb555265288158dd41fb": unable to pull registry.build03.ci.openshift.org/ci-ln-7fgcnct/stable@sha256:d2a5c5414fbffb6212a4fdb0a471787a3bdfb77e784bbb555265288158dd41fb: unable to pull image: Digest of source image's manifest would not match destination reference
```
I think @sergiordlr  saw this issue in past as well https://redhat-internal.slack.com/archives/C02CZNQHGN8/p1712169045599479?thread_ts=1712153017.929469&cid=C02CZNQHGN8

**Review by yuqi-zhang — APPROVED** [review]
/lgtm
/hold

Holding for qe pre-merge approval, if needed

**Comment by sergiordlr** [comment]
@sinnykumari is right, we can't pre-merge verify it.

Please, merge this PR without the qe-approved label and we will verify it post merge.


Thanks!

**Comment by sinnykumari** [comment]
Thanks Sergio!
Removing hold so that verification can happen post merge
/hold cancel

**Comment by sinnykumari** [comment]
We need this to be backported until 4.13 
/cherry-pick release 4.16

**Pull request merged**
