### PR TITLE
pkg/controller: Add MachineConfigController's  template sub controller

### PR DESCRIPTION
**Pull request by abhinavdahiya**
* adds the template sub ctrl
* templates used to generate Machineconfigs for aws, libvirt
* some tests for template ctrl

- The templates are based on [tectonic-node-controller](https://github.com/coreos-inc/tectonic-operators/tree/master/controller/node/templates)
- The controller code semantics are based on [upstream controllers eg.](https://github.com/kubernetes/kubernetes/blob/74bcefc8b2bf88a2f5816336999b524cc48cf6c0/pkg/controller/deployment/deployment_controller.go)

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@vikramsk

**Comment by sdemos** [comment]
Are these the template files that are used to generate the ignition that gets sent to machines and used by the MCD to do the machine state reconciliation? If so, I thought I remembered @crawford saying that they were all going to be ignition files, but these are all CLCs.

**Comment by sdemos** [comment]
For posterity, I received the answer to my question OOB. My understanding is 1. the template files aren't actually CLCs, but instead a similar DSL for describing the information we need and 2. the template files aren't actually going to end up in the cluster directly, and instead will be synthesized into ignition configs. They are the way they are simply to ease the maintenance burden for people who have to modify the basic templates. 

Please correct me if I got any of that explanation wrong.

**Comment by abhinavdahiya** [comment]
@sdemos that's correct.

**Pull request merged**
