### PR TITLE
Bug 1847705: Stop forcing dhclient in baremetal and friends

### PR DESCRIPTION
**Pull request by cybertron**
In 4.6 the RHCOS image no longer has dhclient. In order to maintain
the same behavior for DHCPv6 it is also necessary to set the
ipv6.dhcp-iaid option to mac (which is what dhclient always uses).

Note that I applied the same config for ovirt even though it was
only setting dhcp=dhclient before. I think making all of these
configs consistent is the right thing to do, even if a platform
doesn't care about IPv6.

Also, there was previously a dhclient.conf file that overrode the
search domain. Since we moved the resolv prepender to a dispatcher
script I don't think we need that setting anymore. The prepender
script already overrides the search domain. It looks like dhclient.conf
was also being used to prepend the DNS VIP on at least one platform.
I've still removed that file because I believe it has no effect on
the 4.6 images so if that breaks anything it will need to be fixed
separately anyway.

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by cybertron** [comment]
Note that my baremetal deployments are still failing for other reasons, but this seems to have gotten DHCP working correctly.

/cc @mandre @rgolangh @patrickdillon

I doubt this will cause any new breakage since dhclient is not on the 4.6 images anyway, but please verify that this won't mess up your platforms.

**Comment by cgwalters** [comment]
Hmm.  But there's something tricky going on here because the Ignition here can only affect the *real root*.  So what's happening in the initramfs isn't being configured here.

If this somehow fixes things then we have a drift between the initramfs and the real root.

BTW this is tangentially related to https://github.com/coreos/fedora-coreos-tracker/issues/513 I think.

**Comment by cgwalters** [comment]
Did you test this with the current scenario of pivoting from 4.5, or with https://github.com/openshift/installer/pull/3763 ?

**Comment by cybertron** [comment]
Yeah, this still gets the wrong address initially, but at least it gets the right one in the end so the deployment works. I'm not entirely sure that's a change in behavior since previously we'd have had the same issue with the duid. I'll have to look at a 4.5 deployment to see how that behaved.

So far I've only tested with the installer patch to use the 4.6 image. I can try it without, although we might be able to tell how it worked from the ci job. It won't pass, but it might get far enough to see how DHCP worked.

**Comment by hardys** [comment]
Tested locally and I can confirm this resolves the DHCP issue we were seeing with dev-scripts and ipv6

/lgtm

**Comment by hardys** [comment]
> Did you test this with the current scenario of pivoting from 4.5, or with [openshift/installer#3763](https://github.com/openshift/installer/pull/3763) ?

I just tested both with and without https://github.com/openshift/installer/pull/3763 - in both cases the masters now get their expected DHCPv6 reservations so I think this part of the fix is working OK.

**Comment by hardys** [comment]
Also looking at the e2e-metal-ipi CI output (libvirt serial console output for each master VM we see:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1840/pull-ci-openshift-machine-config-operator-master-e2e-metal-ipi/1273351120147714048/artifacts/e2e-metal-ipi/baremetalds-devscripts-gather/

$ cat ostest_master_0-serial0.log  | grep ^enp2s0 | uniq
enp2s0:  fd2e:6f44:5dd8:c956::14
enp2s0:  fd2e:6f44:5dd8:c956::4
$ cat ostest_master_1-serial0.log  | grep ^enp2s0 | uniq
enp2s0:  fd2e:6f44:5dd8:c956::15
$ cat ostest_master_2-serial0.log  | grep ^enp2s0 | uniq
enp2s0:  fd2e:6f44:5dd8:c956::16

This again shows the expected IPs, although I'm a little surprised to see the ingressVIP show up on master-0 - this is a deployment with 2 workers so the ingress VIP should only ever point to workers I think? /cc @yboaron @celebdor - that's unrelated to this fix though, it may be a separate issue we need to address.

**Comment by stbenjam** [comment]
> This again shows the expected IPs, although I'm a little surprised to see the ingressVIP show up on master-0 - this is a deployment with 2 workers so the ingress VIP should only ever point to workers I think? /cc @yboaron @celebdor - that's unrelated to this fix though, it may be a separate issue we need to address.

Did the build you're using have https://github.com/openshift/machine-config-operator/pull/1817? For a long time baremetal masters have been scheduable regardless of # of workers due to the old kubelet hack still being there.

**Comment by hardys** [comment]
> > This again shows the expected IPs, although I'm a little surprised to see the ingressVIP show up on master-0 - this is a deployment with 2 workers so the ingress VIP should only ever point to workers I think? /cc @yboaron @celebdor - that's unrelated to this fix though, it may be a separate issue we need to address.
> 
> Did the build you're using have #1817? For a long time baremetal masters have been scheduable regardless of # of workers due to the old kubelet hack still being there.

Yes I just fetched this PR branch which includes that commit, so I guess there must still be something that causes the ingressVIP to end up on a master - not yet looked into it in detail

**Comment by celebdor** [comment]
> > > This again shows the expected IPs, although I'm a little surprised to see the ingressVIP show up on master-0 - this is a deployment with 2 workers so the ingress VIP should only ever point to workers I think? /cc @yboaron @celebdor - that's unrelated to this fix though, it may be a separate issue we need to address.
> > 
> > 
> > Did the build you're using have #1817? For a long time baremetal masters have been scheduable regardless of # of workers due to the old kubelet hack still being there.
> 
> Yes I just fetched this PR branch which includes that commit, so I guess there must still be something that causes the ingressVIP to end up on a master - not yet looked into it in detail
> 
> Edit actually the results were from the CI run - there it's NUM_WORKERS=2 also AFAICS

Was ingress responsive?

**Comment by cybertron** [comment]
Just rebased. Hopefully this will pass metal ci now.

**Comment by stbenjam** [comment]
Is metal-ipi expected to pass? I thought we still had OVN issues

**Comment by cybertron** [comment]
https://github.com/openshift/machine-config-operator/pull/1830 was the fix for the OVN issue. The rebase was to pull that in so it should pass now.

**Comment by hardys** [comment]
The ovirt/vsphere jobs seem to be failing early before cluster deployment, I'm not sure how stable those are - I think we can probably go ahead and merge this to unblock the e2e-baremetal-ipi job since that and the e2e-openstack job passed?

**Comment by yuqi-zhang** [comment]
I think this is fine, could someone take a look for vsphere to make sure this is good there? @jcpowermac maybe

**Comment by jcpowermac** [comment]
e2e-vsphere needs to pass the basic installation. The previous test failed do to ipam issues.
/test e2e-vsphere

**Comment by cybertron** [comment]
I've opened https://github.com/openshift/machine-config-operator/pull/1851 as a minimal fix to unblock baremetal while we sort out the other platforms. It would be nice to get a fix in since this has been blocking baremetal for a week already.

**Comment by mandre** [comment]
/test e2e-openstack

Re-testing openstack after https://github.com/openshift/installer/pull/3763 merged.

**Comment by mandre** [comment]
For openstack at least, we'll need https://github.com/openshift/installer/pull/3789 as well in order to have the e2e-openstack job green.

**Comment by kikisdeliveryservice** [comment]
"baremetal and friends" <--- :laughing: ?I love it.

Looks like we also need #1865 to unblock?

**Comment by cybertron** [comment]
> "baremetal and friends" <--- laughing ?I love it.

Easier than listing all of the baremetal-like platforms. :-)

> Looks like we also need #1865 to unblock?

We shouldn't. That is just a subset of this PR so the fix is already included here. It's the same thing I did to unblock baremetal with #1851.

**Comment by kikisdeliveryservice** [comment]
```error: unable to connect to image repository registry.svc.ci.openshift.org/ci-op-fcqjydkk/stable@sha256:9a1cac05fe7f2570b14f0b98543a524200fa25f417aaaf37c7c7c466f427f850: endpoint "https://registry.svc.ci.openshift.org" does not support v2 API```

seeing that in failed jobs, reported in 4-dev bc it's weird.

**Comment by cgwalters** [comment]
> "baremetal and friends" <--- laughing ?I love it.

BRB writing a script for a Netflix drama series

**Comment by mandre** [comment]
:+1: for OpenStack

**Pull request merged**
