### PR TITLE
OCPBUGS-12456: fix duplicate RotateKubeletServerCertificate setting

### PR DESCRIPTION
**Pull request by rphillips**
Fixed a duplicate featuregate key causing errors on the new 1.27 rebase.

### CODE REVIEW

**Comment by rphillips** [comment]
@yuqi-zhang I'm not seeing anything in the MCO e2e-gcp-op logs? Is this ok to merge?

**Comment by yuqi-zhang** [comment]
@rphillips yeah I think our master gcp-op is running into some slowdowns causing the test to time out. I see the bug currently has undefined priority. Do you think this is urgent enough to warrant an override? I think it should be safe.

Also the MCO QE is prioritizing pre-merge testing more now. Do you think this should skip pre-merge validation? Preferrably we would like to pre-merge test all bug fixes

**Pull request merged**
