### PR TITLE
[release-4.1] templates/master/00-master: add DR tools

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

backport of #757 

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by hexfusion** [comment]
@derekwaynecarr @smarterclayton could either of you bless this into 4.1, please? We plan on moving these tools to a container for 4.2 and depreciating in MCO.

**Comment by vrutkovs** [comment]
/hold

Lets pull in https://github.com/openshift/machine-config-operator/pull/775 and https://github.com/openshift/machine-config-operator/pull/776 (+ additional fixes) once these are merged

**Comment by hexfusion** [comment]
We have everything we need here.

/hold cancel

**Pull request merged**
