### PR TITLE
Bug 1834194: vsphere: check if .Infra.Status and .Infra.Status.PlatformStatus is nil

### PR DESCRIPTION
**Pull request by jcpowermac**
Cherry-pick: #1728

### CODE REVIEW

**Comment by sinnykumari** [comment]
/test e2e-vsphere
/test e2e-vsphere-upi
cc: @patrickdillon @mtnbikenc

**Comment by kikisdeliveryservice** [comment]
@jcpowermac do we actually expect the 4.4 vsphere job to pass?

https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-release-4.4-e2e-vsphere

**Comment by kikisdeliveryservice** [comment]
@jcpowermac is it expected to fail vsphere?

**Comment by jcpowermac** [comment]
> @jcpowermac is it expected to fail vsphere?

@kikisdeliveryservice The tests that are failing have a BZ associated with them.  Haven't seen an update to it lately.  From my perspective it looks ok.

**Comment by kikisdeliveryservice** [comment]
as per @jcpowermac comment above:

/skip

**Comment by sdodson** [comment]
/retitle Bug 1834194: vsphere: check if .Infra.Status and .Infra.Status.PlatformStatus is nil

**Comment by sdodson** [comment]
/override ci/prow/e2e-gcp-op
/override ci/prow/e2e-gcp-upgrade
Not relevant to this platform.

**Pull request merged**
