### PR TITLE
Bug 1897361: ctrcfg_test: Wait for our prior target config

### PR DESCRIPTION
**Pull request by cgwalters**
Waiting for the previous MC isn't right here; we're deleting
a config and so what we want to wait for is the previous pool
target.

Drop the racy `sleep()`.

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
Yesterday I was also confused about why they didn't just waitForPoolComplete like we do in MCD tests so this makes sense to me. Obvi would like test run to confirm it but yep. :+1: !

**Comment by rphillips** [comment]
ci/prow/e2e-agnostic-upgrade -- gcp IAM error, unrelated

**Comment by haircommander** [comment]
haha it would help to write tests for components you understand... LGTM, good find @cgwalters :smile:

**Comment by kikisdeliveryservice** [comment]
testing another pr without second commit.

/hold

**Comment by kikisdeliveryservice** [comment]
Closing in favor of https://github.com/openshift/machine-config-operator/pull/2229 which is the first commit by Colin and the minimal commit necessary to fix the ctrcfg test:

https://github.com/openshift/machine-config-operator/pull/2229

**Pull request closed without merging**
