### PR TITLE
OCPBUGS-6213: Update MCO images to be consistent with ART

### PR DESCRIPTION
**Pull request by sinnykumari**
io/ioutil package has been deprecated since go-1.16. With switch to using go-1.19 image in MCO, these deprecated functions can no longer be used. Updated MCO to use equivalent functionalities provided by os and io package.
    - ioutil.WriteFile() -> os.WriteFile()
    - ioutil.ReadFile() -> os.ReadFile()
    - ioutil.ReadDir() -> os.ReadDir() and adds a helper function to convert fs.DirEntry to []fs.FileInfo to preserve MCO behavior
    - ioutil.TempDir() -> os.MkdirTemp()
    - ioutil.TempFile() -> os.CreateTemp()
    - ioutil.ReadAll() -> io.ReadAll()

Also closes PR https://github.com/openshift/machine-config-operator/pull/3450

### CODE REVIEW

**Comment by sinnykumari** [comment]
putting hold for getting qe-approved label for pre-merge testing
/hold

**Comment by sergiordlr** [comment]
QE verification

1. Make sure that the PR does not contain any reference to ioutil

```
$ grep -R ioutil * | grep -v vendor
pkg/controller/common/helpers.go:// ioutil.ReadDir has been deprecated with os.ReadDir.
pkg/controller/common/helpers.go:// ioutil.ReadDir() used to return []fs.FileInfo but os.ReadDir() returns []fs.DirEntry.
pkg/controller/common/helpers.go:// Implementation to fetch fileInfo is taken from https://pkg.go.dev/io/ioutil#ReadDir
```

2. Sanity check running test cases:

"[sig-mco] MCO Author:mhanss-Longduration-NonPreRelease-Critical-42438-add journald systemd config [Disruptive] [Serial]"


No errors found.

We add the qe-approved label

/label qe-approved

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

**Comment by sinnykumari** [comment]
removing hold as we have qe-approved label
/hold cancel
/retest

**Comment by sinnykumari** [comment]
skipping optional tests
/skip

**Comment by sinnykumari** [comment]
aws-ovn-upgrade test failed due to aws resource limitation, retesting
/test e2e-aws-ovn-upgrade

**Comment by yuqi-zhang** [comment]
This is also happening for 4.12 still annoyingly at https://github.com/openshift/machine-config-operator/pull/3359. I'm going to try to do a manual backport

Hmm, what's the command again? Is it

/jira cherry-pick

**Comment by yuqi-zhang** [comment]
oh uh that didn't do what I expected it to... whoops

**Pull request merged**
