### PR TITLE
daemon: Automatically sync master taint

### PR DESCRIPTION
**Pull request by cgwalters**
If a user or code adds the `worker` role to the masters, automatically
remove our `NoSchedule` taint.

Alternative to https://github.com/openshift/machine-config-operator/pull/845

Closes: https://github.com/openshift/machine-config-operator/issues/763

### CODE REVIEW

**Comment by cgwalters** [comment]
Not tested yet

**Comment by cgwalters** [comment]
This PR is silent on how the `worker` label ends up on the masters; so it isn't a complete solution (I should remove the `Closes` probably).  However, since we need to make both changes (router selects for worker explicitly at least), it simplifies things to reduce the problem down to "label worker or not", instead of both labels and taints.

This was inspired by [this bit of code](https://github.com/openshift/machine-config-operator/issues/763#issuecomment-501383523) in the GCP provider.

(It's a bit surprising this isn't an upstream kube default actually but I guess it gets into policy vs mechanism)

**Comment by cgwalters** [comment]
Cleaned up a bit, added some comments.  Lifting WIP, I tested this and it works as advertised.  I can add an e2e if people want.

**Comment by cgwalters** [comment]
I still feel this is true:

>  However, since we need to make both changes (router selects for worker explicitly at least), it simplifies things to reduce the problem down to "label worker or not", instead of both labels and taints.

So I'd like to propose landing this, even if we don't have a consensus on how the worker label should be added.

**Comment by kikisdeliveryservice** [comment]
hey our new linter works?!

**Comment by cgwalters** [comment]
...and then, Colin hesitated briefly over the `git push` button to fix some whitespace, knowing that 3 clusters would be launched as a result of this action.  But, YOLO (and so do the clusters from a PR).

**Comment by cgwalters** [comment]
Closing per https://github.com/openshift/machine-config-operator/issues/763#issuecomment-502205542

**Pull request closed without merging**
