### PR TITLE
Bug 1764116: templates: rename our dropins to include the mco string

### PR DESCRIPTION
**Pull request by runcom**
Mainly to avoid ppl to ship something which could override the MCO files.

The situation can still happen, in which case, the bad MC must be deleted and in order to rollback the maxUnavailable for the pool must be increased by at least 1

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
@cgwalters wondering why this wasn't the case till the beginning :/

**Comment by runcom** [comment]
> @cgwalters wondering why this wasn't the case till the beginning :/

the actual issue here is that the rendered machineconfigs can contain duplicate entries for e.g. a service or unit. If that's the case, the validate routine can validate and fail only the first entry but what we have written on disk is the second one - should we change the validate routine to always check the last entry if there's a duplicate?  This PR just makes sure we can rollback but maybe the fix to validation is needed as well.

**Comment by runcom** [comment]
(This PR isn't working as intended also, so keep holding)

**Comment by runcom** [comment]
maybe we should completely avoid having users override what we ship?

**Comment by cgwalters** [comment]
> @ajeddeloh since a rendered mc can contain duplicates entries, should we validate only against the last one? right now, we're validating and bailing at the first entry, but the MCD applies the last when writing to disk.

I believe it's a hard error to have duplicate files in Ignition spec 3.  We should also indeed disallow this in the MCO I'd say.

But the clear shorter term fix is to change our validation to check the last one for consistency with what we actually write.

**Comment by runcom** [comment]
> I believe it's a hard error to have duplicate files in Ignition spec 3. We should also indeed disallow this in the MCO I'd say.

uhm, so then the MCC has to learn to generate rendered MCs by always using the last entry in alphabetical order? 🤔

**Comment by cgwalters** [comment]
I think we should error out.

**Comment by ajeddeloh** [comment]
> > @ajeddeloh since a rendered mc can contain duplicates entries, should we validate only against the last one? right now, we're validating and bailing at the first entry, but the MCD applies the last when writing to disk.

> I believe it's a hard error to have duplicate files in Ignition spec 3. We should also indeed disallow this in the MCO I'd say.

Correct that duplicates are disallowed in spec 3.0.0+. Spec 2.x is more complicated. The last one listed "wins" but only if overwrite is true. Also they're created in the order: directories, then files, then links. This means a file can never "win" against a link. This is also fixed with spec 3.

**Comment by runcom** [comment]
> The last one listed "wins" but only if overwrite is true

here the scenario is "we write a file at a dropin location" then "a dropin writes on that location again" ouch - does spec v3 disallow this?

**Comment by kikisdeliveryservice** [comment]
> I think we should error out.

Erroring out seems to be the cleanest choice, imo - it's predictable and clear to a user what they need to do going forward.

**Comment by ajeddeloh** [comment]
> here the scenario is "we write a file at a dropin location" then "a dropin writes on that location again" ouch - does spec v3 disallow this?

Can you clarify? Do you mean a systemd drop in or an appended config?

**Comment by runcom** [comment]
> Can you clarify? Do you mean a systemd drop in or an appended config?

yep, a systemd dropin.

**Comment by ajeddeloh** [comment]
Hmm yeah I think we ought to check for that in Ignition as well actually. Failing seems like the right thing to do since the user is asking for the impossible.

**Comment by runcom** [comment]
> But the clear shorter term fix is to change our validation to check the last one for consistency with what we actually write.

I don't believe this is the right thing to do now as a short term hack - the reason here writing a file at a location and writing a dropin config which later writes there. Allowing the validation to pass means that any configuration already shipped (for things like crio and kubelet) can be firstly overridden and secondly skipped from validation.
I believe this a broader issue also, how does someone ship a crio dropin? should we allow that since crio is controlled by the CRC crd? hence it makes sense to just error out when someone provides a configuration that would overwrite anything specified _before_.

What do you all think?

**Comment by cgwalters** [comment]
> I believe this a broader issue also, how does someone ship a crio dropin? 

I think the problem here is that the user chose *the same name* for the dropin `10-default-env.conf` as we did.  Perhaps it'd be clearer if we named our drop-ins like `10-mco-default-env.conf` and hopefully users would not include `-mco` in their names.

**Comment by runcom** [comment]
> and hopefully users would not include `-mco` in their names.

so if they do instead, I think we need to avoid rendering and communicate that, how does that sound?

**Comment by runcom** [comment]
I'm updating this PR to move to `-mco-` for our dropins meanwhile - still doesn't solve the issue tho :(

**Comment by runcom** [comment]
About this PR and Bug tho, the issue was mainly the inability to roll back and I think that's the case because the pools are hitting their maxUnavailable so bumping that to 2 will reconcile the cluster, I'm verifying that, we can then get the rename in and postpone any later discussion about validation when spec 3 will be in MCO maybe (?)

**Comment by runcom** [comment]
Closed by https://github.com/openshift/machine-config-operator/pull/1715

**Pull request closed without merging**
