### PR TITLE
[release-4.13]OCPBUGS-27816: use *resource.Quantity to not automatically set 0

### PR DESCRIPTION
**Pull request by QiWang19**
**- What I did**
Backport API fix https://github.com/openshift/api/pull/1656 to 4.13
**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by QiWang19** [comment]
@yuqi-zhang could you tag this?

**Review by yuqi-zhang — APPROVED** [review]
Seems safe to do

**Comment by lyman9966** [comment]
/label qe-approved 
test passed: 
$ oc get containerruntimeconfig  pidlimit -o json | jq '.spec.containerRuntimeConfig'
{
  "logLevel": "debug",
  "pidsLimit": 4096
}

**Pull request merged**
