### PR TITLE
OCPBUGS-5888: Don't switch to the "live" certificate bundle until after first ControllerConfig is generated

### PR DESCRIPTION
**Pull request by jkyros**
In #3458 we switched to using the proper "live" certificate bundle, but it contains additional certificates, so the machineConfig generated from it is different than it used to be.

 You can see that new clusters come up with two `rendered-config`s per pool instead of one: 
```
[jkyros@jkyros-t590 tmp]$ oc get mc
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
00-worker                                          60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
01-master-container-runtime                        60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
01-master-kubelet                                  60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
01-worker-container-runtime                        60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
01-worker-kubelet                                  60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
99-master-generated-registries                     60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
99-master-ssh                                                                                 3.2.0             80m
99-worker-generated-registries                     60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
99-worker-ssh                                                                                 3.2.0             80m
rendered-master-6b2321ecc4284430d06c2f15c8395daf   60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
rendered-master-f045b089604973c06b3812cf00abe82a   60bb76579811a2487e67ba337a99e13282257b92   3.2.0             68m
rendered-worker-05f8911eb4fc4525b8b83398ea200868   60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
rendered-worker-74f0aa81d273e31a7e999d68b50f9626   60bb76579811a2487e67ba337a99e13282257b92   3.2.0             68m

```
(one of them has the "bootstrap" certificates, the other one rendered a couple minutes later has the "live" certificates) 

The switch to using the new "live" bundle is gated on whether or not the `kube-system/bootstrap` configmap is present. 

It seems that if `kube-system/bootstrap` appears before we've rendered our first MachineConfig, the first "live" MachineConfig will contain the certificates from the "live" bundle (rather than the "bootstrap" one), which results in the `machine-config-daemon` being unable to find a rendered-config matching what it bootstrapped with (and degrading). 

**- What I did**
This PR just makes sure we don't switch to using the "live" bundle until we've actually rendered that first "matching" config to keep the daemons happy. 

**- How to verify it**
The original issue was hard to reproduce (as it was due to timing) and we still don't know what causes the timings to be different sometimes to where the first controllerConfig doesn't happen until after `kube-system/bootstrap` exists. 

**- Description for the changelog**
MCO will wait for first ControllerConfig before switching from "bootstrap" to "live" certificate bundle. 

Fixes:[OCPBUGS-5888]( https://issues.redhat.com/browse/OCPBUGS-5888)

### CODE REVIEW

**Comment by jkyros** [comment]
argh
/jira refresh

**Comment by jkyros** [comment]
Failed to apply terraform, unrelated
/test e2e-aws-ovn-upgrade

**Comment by yuqi-zhang** [comment]
I think one way to verify this could be, if we built a custom payload to delay the first MCO sync for ~10 minutes via adding a sleep to like https://github.com/jkyros/machine-config-operator/blob/89b4d2ea257558810592092db4e2dcfa9d6e905a/pkg/operator/sync.go#L213 function. Then we can see a difference in behaviour with and without this PR

Do you think that will work @jkyros ?

**Comment by jkyros** [comment]
I tested it with a custom payload by dragging out the controllerConfig sync until after the boostrap configmap shows up. 

https://github.com/openshift/machine-config-operator/compare/master...jkyros:ocpbugs-5888-verification 
quay.io/jkyros/ocp-release:ocpbugs-5888-failure

That breaks it like we're seeing, but if I add the `optr.InClusterBringup` check back in it doesn't break. 

https://github.com/openshift/machine-config-operator/compare/master...jkyros:ocpbugs-5888-success 
quay.io/jkyros/ocp-release:ocpbugs-5888-success

I can also try it with sleeps but I figured I'd just be gambling on timings. So yes, we can verify it with a custom payload..if trying it with a custom payload is sufficient for verification. :smile:

**Review by yuqi-zhang — APPROVED** [review]
/lgtm
/hold

for QE testing.

We probably need a longer term solution for this, but I think this lgtm as a fix for the most pressing issue. Thanks John!

**Comment by yuqi-zhang** [comment]
@sergiordlr @rioliu-rh would we be able to pre-merge verify via the steps in https://github.com/openshift/machine-config-operator/pull/3513#issuecomment-1407295725 ? (Assuming John's payloads still are around).

**Comment by sergiordlr** [comment]
Since the error depends on a rare race condition we have no consitent way to reproduce this issue.

In order to verify it we will use hacked payloads that will always force the race condition to trigger the error. One payload with the fix and another payload without the fix.


1. Installation of the hacked payload without the fix. (We hack the payload in order to force the first controllerConfig to happen after the bootstrap)

branch: https://github.com/openshift/machine-config-operator/compare/master...jkyros:ocpbugs-5888-verification

The result is that the same error reported in the jira issue happens:
```
ERROR Cluster operator machine-config Degraded is True with RequiredPoolsFailed: Unable to apply 4.13.0-0.nightly-2023-01-27-165107: error during syncRequiredMachineConfigPools: [timed out waiting for the condition, error pool master is not ready, retrying. Status: (pool degraded: true total: 3, ready 0, updated: 0, unavailable: 3)] 
```

We can see that the error reported by the MCD is this one:

```
I0202 17:44:09.109053    6117 daemon.go:1257] In bootstrap mode
E0202 17:44:09.109102    6117 writer.go:200] Marking Degraded due to: machineconfig.machineconfiguration.openshift.io "rendered-master-a200fca22f425e7fa71ddec0e7e77541" not found
```

This is the expected error.


2. Installation of the hacked payload with the fix (We hack the payload in order to force the first controllerConfig to happen after the bootstrap, plus the fix has been added):

branch: https://github.com/openshift/machine-config-operator/compare/master...jkyros:ocpbugs-5888-success

We can see that 2 MCs were rendered for each pool:

```
$ oc get mc
.....
rendered-master-065128f111fbf7a584e9d83ab82aad9d   4124f2276938909245d7ef2fad76c952769d189f   3.2.0             20m
rendered-master-a7d4d7aaa3ac33969ea5f5831cd0ebef   4124f2276938909245d7ef2fad76c952769d189f   3.2.0             23m
rendered-worker-aa36076375c160c279c14307f473e850   4124f2276938909245d7ef2fad76c952769d189f   3.2.0             23m
rendered-worker-ecc4e57b38863deea544176fcc0922cb   4124f2276938909245d7ef2fad76c952769d189f   3.2.0             20m

```
And that the pools could be configured without problems using the latest MC:

```
$ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-065128f111fbf7a584e9d83ab82aad9d   True      False      False      3              3                   3                     0                      31m
worker   rendered-worker-ecc4e57b38863deea544176fcc0922cb   True      False      False      3              3                   3                     0                      31m


```

We add the qe-approve label

/label qe-approved

**Comment by yuqi-zhang** [comment]
/hold cancel

thanks everyone! Let's get this fix in

**Pull request merged**
