### PR TITLE
etcd: add fallback to logs on error

### PR DESCRIPTION
**Pull request by mfojtik**
**- What I did**

Set the `terminationMessagePolicy` so when the etcd container crash, it will record the last N lines of the container log into pod status. That means we can see the reason it crashed instead of just observe the crashloop.

This will help debugging etcd crashes.

**- How to verify it**

Wait for etcd to crash, then oc get pods/etcd-member -o yaml should show the last few lines from the etcd container.

**- Description for the changelog**

### CODE REVIEW

**Comment by smarterclayton** [comment]
/lgtm cancel

You need to update the unit tests.

**Comment by mfojtik** [comment]
@smarterclayton updated...

**Comment by cgwalters** [comment]
(For future reference I personally would prefer that we squash commits like that)

**Pull request merged**
