### PR TITLE
Bug 1889912: vendor in drain fix for using high cpu

### PR DESCRIPTION
**Pull request by rphillips**
**- What I did**
Drains can use high CPU. This PR vendors in the backport of the drain fix from upstream.

ref: https://github.com/kubernetes/kubernetes/pull/95260

**- How to verify it**

**- Description for the changelog**
```
Fix drains from using high cpu
```

### CODE REVIEW

**Comment by rphillips** [comment]
go mod tidy on the force push

**Review by cgwalters — APPROVED** [review]
Looks sane to me, this is clearly worth a quick backport.

**Review by ashcrow — APPROVED** [review]

**Pull request merged**
