### PR TITLE
[WIP] Use keepalived version 2.0.10 

### PR DESCRIPTION
**Pull request by yboaron**
I used https://github.com/openshift/images/pull/88 to create the customized Keepalived image

### CODE REVIEW

**Comment by yboaron** [comment]
metal-ipi CI fails to pull quay.io/yboaron/origin-keepalived-ipfailover:latest   on bootstrap ,
when I edited /etc/kubernetes/manifests/keepalived.yaml  on one of the masters to use quay.io/yboaron/origin-keepalived-ipfailover  it was OK

Any idea what's wrong ?


This is the error on Kubelet
May 06 12:30:33 localhost kubelet.sh[3039]: E0506 12:30:33.451244    3096 remote_image.go:114] "PullImage from image service failed" err="rpc error: code = Unknown desc = error pinging docker registry quay.io: Get \"https://quay.io/v2/\": dial tcp 54.156.10.58:443: connect: network is unreachable" image="quay.io/yboaron/origin-keepalived-ipfailover:latest"
May 06 12:30:33 localhost kubelet.sh[3039]: E0506 12:30:33.451511    3096 kuberuntime_image.go:51] "Failed to pull image" err="rpc error: code = Unknown desc = error pinging docker registry quay.io: Get \"https://quay.io/v2/\": dial tcp 54.156.10.58:443: connect: network is unreachable" image="quay.io/yboaron/origin-keepalived-ipfailover:latest"
May 06 12:30:33 localhost kubelet.sh[3039]: E0506 12:30:33.451678    3096 kuberuntime_manager.go:864] container &Container{Name:keepalived,Image:quay.io/yboaron/origin-keepalived-ipfailover:latest,Command:[/bin/bash -c #/bin/bash
(edited)





Reply…

**Comment by stbenjam** [comment]
2 successful installs...


/test e2e-metal-ipi-ovn-dualstack

**Comment by yboaron** [comment]
The double VIP issue in the bootstrap stage was solved by https://github.com/openshift/baremetal-runtimecfg/pull/137 
/close

**Pull request closed without merging**
