### PR TITLE
OCPBUGS-32028: Decrease logs of haproxy

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
@mkowalski sounds like below logs still print after changing to 

```
# oc rsh -n openshift-kni-infra haproxy-master-0
Defaulted container "haproxy" out of: haproxy, haproxy-monitor, verify-api-int-resolvable (init)
sh-4.4$ cat /etc/haproxy/haproxy.cfg | grep log
  log     /var/run/haproxy/haproxy-log.sock local0 notice alert
  log-format "%ci:%cp -> %fi:%fp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq"
  option  dontlognull
  option dontlognull
   option  log-health-checks



<134>Mar 12 01:41:01 haproxy[46]: ::ffff:192.168.111.1:53422 -> ::ffff:192.168.111.20:9445 [12/Mar/2024:01:40:28.063] main masters/master-1 1/0/33700 15180 -- 97/97/96/36/0 0/0
<134>Mar 12 01:41:03 haproxy[46]: ::ffff:192.168.111.25:49302 -> ::ffff:192.168.111.20:9445 [12/Mar/2024:01:41:03.173] main masters/master-0 1/0/4 2850 -- 98/98/97/53/0 0/0
<134>Mar 12 01:41:03 haproxy[46]: ::ffff:192.168.111.25:49304 -> ::ffff:192.168.111.20:9445 [12/Mar/2024:01:41:03.173] main masters/master-1 1/0/6 2858 -- 97/97/96/36/0 0/0
<134>Mar 12 01:41:05 haproxy[46]: ::ffff:192.168.111.1:47856 -> ::ffff:192.168.111.20:9445 [12/Mar/2024:01:41:04.228] main masters/master-2 1/0/1258 16319 -- 98/98/97/7/0 0/0
```

**Comment by mkowalski** [comment]
I just modified to remove `log-health-checks` option. Maybe this is what was logged

**Comment by zhaozhanqi** [comment]
Yes, the logs do not show up after removing `log-health-checks`

**Comment by mkowalski** [comment]
/cc @cybertron 

In my opinion access logs for haproxy are not really useful, I do not recall us ever looking into them

**Review by sinnykumari — APPROVED** [review]

**Pull request merged**
