### PR TITLE
Add MCONamespace constant

### PR DESCRIPTION
**Pull request by mkenigs**
@cgwalters factoring this out per https://github.com/jkyros/machine-config-operator/pull/1#discussion_r819105807

Is it worth replacing everywhere this is used with the constant?

### CODE REVIEW

**Comment by cgwalters** [comment]
> Is it worth replacing everywhere this is used with the constant?

I don't have a strong opinion on this.  There's a middle ground: not necessarily everywhere, but at least the places we plan to change soon.

Though mechanically speaking what I'd do here is two things:

- Start out PRs like this as draft, because we don't need to run all the CI for them to start until it's agreed to merge
- I tend to generate "prep" PRs which can contain multiple smaller cleanups, but still factored out into separate commits.  An example is https://github.com/openshift/machine-config-operator/pull/2980 - so on this topic I'd assume there's other preparatory cleanups we could factor out that could be rolled in here too.

**Comment by mkenigs** [comment]
> * I tend to generate "prep" PRs which can contain multiple smaller cleanups, but still factored out into separate commits.  An example is [Preparatory patches for bumping fcct -> butane #2980](https://github.com/openshift/machine-config-operator/pull/2980) - so on this topic I'd assume there's other preparatory cleanups we could factor out that could be rolled in here too.

Would that include something like this commit https://github.com/jkyros/machine-config-operator/pull/1/commits/930b9c6242b29f680ee970a71fcd83a813e6339b? Or should that one only be against `layering`?

**Comment by cgwalters** [comment]
> Would that include something like this commit https://github.com/jkyros/machine-config-operator/commit/930b9c6242b29f680ee970a71fcd83a813e6339b? Or should that one only be against layering?

That one seems reasonable to merge into main/master to me!  But my PoV here is we should operate on "rough consensus and working code".  If e.g. you and at least one other person think it's good for main/master, it probably is!  

That said...I think it's worth looking at this from the other angle - what should *only* go on the layering branch?  After considering this for approximately 37.2 seconds, one strawman proposal I have here is that (if it helps us, and I think it will) on the layering branch we disable all upgrade testing and assume we're doing a new install from a new bootimage that has the new rpm-ostree (which reminds me, we need to do an installer bootimage bump, I am not aware of anythig blocking that, will get someone to look).

**Comment by mkenigs** [comment]
Closing since this is too small of a PR and will roll this change into https://github.com/openshift/machine-config-operator/pull/2987

**Pull request closed without merging**
