### PR TITLE
[FCOS] gcp templates: update gcp-routes

### PR DESCRIPTION
**Pull request by vrutkovs**
**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by vrutkovs** [comment]
Flakes

/retest

**Comment by vrutkovs** [comment]
This version of `gcp-routes.sh` is exactly the same as RHCOS uses. The issue is that it doesn't pass shellcheck on installer.

/hold

**Comment by LorbusChris** [comment]
I think this is the wrong version of the script, should we close?

**Comment by LorbusChris** [comment]
feel free to reopen if that's not the case :)
/close

**Pull request closed without merging**
