### PR TITLE
OCPBUGS-39222: Do not enable on-prem-resolv-prepender.path for UPI

### PR DESCRIPTION
**Pull request by mkowalski**
Closes: OCPBUGS-39222

### CODE REVIEW

**Review by cybertron — COMMENTED** [review]
/lgtm

**Comment by zhaozhanqi** [comment]
@mkowalski 
sounds like I did not see this service `on-prem-resolv-prepender.path` on one 4.16 cluster with UPI, is that exist on UPI?
```
zzhao@localhost:~$ oc get infrastructures.config.openshift.io -o yaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Infrastructure
  metadata:
    creationTimestamp: "2024-08-30T00:24:25Z"
    generation: 1
    name: cluster
    resourceVersion: "507"
    uid: 79756bb0-b86f-44a3-9d03-3d067175579a
  spec:
    cloudConfig:
      name: ""
    platformSpec:
      type: None
  status:
    apiServerInternalURI: https://api-int.newugd-57536.qe.devcluster.openshift.com:6443
    apiServerURL: https://api.newugd-57536.qe.devcluster.openshift.com:6443
    controlPlaneTopology: HighlyAvailable
    cpuPartitioning: None
    etcdDiscoveryDomain: ""
    infrastructureName: newugd-57536-hvwkt
    infrastructureTopology: HighlyAvailable
    platform: None
    platformStatus:
      type: None
kind: List
metadata:
  resourceVersion: ""
zzhao@localhost:~$ oc debug node/master-00.newugd-57536.qe.devcluster.openshift.com
Starting pod/master-00newugd-57536qedevclusteropenshiftcom-debug-5hl57 ...
To use host binaries, run `chroot /host`
Pod IP: 145.40.88.217
If you don't see a command prompt, try pressing enter.
sh-5.1# chroot /host
sh-5.1# systemctl cat on-prem-resolv-prepender.path
No files found for on-prem-resolv-prepender.path.
sh-5.1# 
```

**Comment by zhaozhanqi** [comment]
> @mkowalski sounds like I did not see this service `on-prem-resolv-prepender.path` on one 4.16 cluster with UPI, is that exist on UPI?
> 
> ```
> zzhao@localhost:~$ oc get infrastructures.config.openshift.io -o yaml
> apiVersion: v1
> items:
> - apiVersion: config.openshift.io/v1
>   kind: Infrastructure
>   metadata:
>     creationTimestamp: "2024-08-30T00:24:25Z"
>     generation: 1
>     name: cluster
>     resourceVersion: "507"
>     uid: 79756bb0-b86f-44a3-9d03-3d067175579a
>   spec:
>     cloudConfig:
>       name: ""
>     platformSpec:
>       type: None
>   status:
>     apiServerInternalURI: https://api-int.newugd-57536.qe.devcluster.openshift.com:6443
>     apiServerURL: https://api.newugd-57536.qe.devcluster.openshift.com:6443
>     controlPlaneTopology: HighlyAvailable
>     cpuPartitioning: None
>     etcdDiscoveryDomain: ""
>     infrastructureName: newugd-57536-hvwkt
>     infrastructureTopology: HighlyAvailable
>     platform: None
>     platformStatus:
>       type: None
> kind: List
> metadata:
>   resourceVersion: ""
> zzhao@localhost:~$ oc debug node/master-00.newugd-57536.qe.devcluster.openshift.com
> Starting pod/master-00newugd-57536qedevclusteropenshiftcom-debug-5hl57 ...
> To use host binaries, run `chroot /host`
> Pod IP: 145.40.88.217
> If you don't see a command prompt, try pressing enter.
> sh-5.1# chroot /host
> sh-5.1# systemctl cat on-prem-resolv-prepender.path
> No files found for on-prem-resolv-prepender.path.
> sh-5.1# 
> ```

oh.  I see, this only happen on UPI vsphere.  

```
zzhao@localhost:~$ oc debug node/zzhaovspher46-qhvbl-control-plane-0
Starting pod/zzhaovspher46-qhvbl-control-plane-0-debug-ng55v ...
To use host binaries, run `chroot /host`
Pod IP: 192.168.221.72
If you don't see a command prompt, try pressing enter.
sh-5.1# chroot /host
sh-5.1# systemctl status on-prem-resolv-prepender.service
● on-prem-resolv-prepender.service - Populates resolv.conf according to on-prem IPI needs
     Loaded: loaded (/etc/systemd/system/on-prem-resolv-prepender.service; static)
     Active: activating (auto-restart) (Result: resources) since Fri 2024-08-30 07:33:22 UTC; 5s ago
TriggeredBy: ● on-prem-resolv-prepender.path
        CPU: 0

Aug 30 07:33:22 zzhaovspher46-qhvbl-control-plane-0 systemd[1]: on-prem-resolv-prepender.service: Failed to load environment files: No such file or directory
Aug 30 07:33:22 zzhaovspher46-qhvbl-control-plane-0 systemd[1]: on-prem-resolv-prepender.service: Failed to run 'start' task: No such file or directory
Aug 30 07:33:22 zzhaovspher46-qhvbl-control-plane-0 systemd[1]: on-prem-resolv-prepender.service: Failed with result 'resources'.
Aug 30 07:33:22 zzhaovspher46-qhvbl-control-plane-0 systemd[1]: Failed to start Populates resolv.conf according to on-prem IPI needs.
sh-5.1# systemctl cat on-prem-resolv-prepender.path
# /etc/systemd/system/on-prem-resolv-prepender.path
[Unit]
Description=Watches for changes in /var/run/NetworkManager/resolv.conf according to on-prem IPI needs
[Path]
PathModified=/var/run/NetworkManager/resolv.conf
Unit=on-prem-resolv-prepender.service
[Install]
WantedBy=multi-user.target
sh-5.1# exit
exit

```

**Comment by mkowalski** [comment]
Exactly. Customer in https://issues.redhat.com/browse/OCPBUGS-39162 reported to us that they use 4.16.8 on vSphere UPI and they see this unit activating.

Please note this is ONLY cosmetic thing. The resolv-prepender will never run and do its job there, it's just that it spams the journal log.

**Comment by zhaozhanqi** [comment]
with this build I tested on UPI vsphere cluster. now the service status is inactive

```
sh-5.1# systemctl status on-prem-resolv-prepender.service
○ on-prem-resolv-prepender.service - Populates resolv.conf according to on-prem IPI needs
     Loaded: loaded (/etc/systemd/system/on-prem-resolv-prepender.service; static)
     Active: inactive (dead)
```
/label qe-approved

**Comment by cybertron** [comment]
/retest-required

This isn't deployed on either aws or gcp so it can't have broken those jobs.

**Review by yuqi-zhang — APPROVED** [review]

**Pull request merged**
