### PR TITLE
bug 1834925: vsphere: check if .Infra.Status and .Infra.Status.PlatformStatus is nil

### PR DESCRIPTION
**Pull request by jcpowermac**
Update the vsphere templates to check if `.Infra.Status` and `.Infra.Status.PlatformStatus` is nil.

### CODE REVIEW

**Comment by jcpowermac** [comment]
cc: @patrickdillon @mtnbikenc

**Comment by patrickdillon** [comment]
fun with pointers
/lgtm

**Comment by kikisdeliveryservice** [comment]
@jcpowermac can you PTAL at the e2e-vsphere errors? we are already aware of an issue existing in gcp-op jobs, but vsphere jobs looks very red? https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-vsphere

**Comment by jcpowermac** [comment]
> @jcpowermac can you PTAL at the e2e-vsphere errors? we are already aware of an issue existing in gcp-op jobs, but vsphere jobs looks very red? https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-vsphere

Its test failures that I would think that are unrelated to this PR.
I have seen the similar failures with UPI as well. Yesterday I started to investigate them individually but it will take time to workthrough.

**Comment by yuqi-zhang** [comment]
I can override `e2e-gcp-op` if you're confident this fixes the issue for vsphere (this wouldn't affect e2e-gcp-op anyways)

**Comment by jcpowermac** [comment]
> I can override `e2e-gcp-op` if you're confident this fixes the issue for vsphere (this wouldn't affect e2e-gcp-op anyways)

looks like e2e-gcp-op has failed quite a bit with the same issue unrelated to this PR.

https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op

**Comment by yuqi-zhang** [comment]
Right its https://bugzilla.redhat.com/show_bug.cgi?id=1834895 the gcp-op failure. Its consistently broken. If you don't mind waiting we will fix that

**Pull request merged**
