### PR TITLE
WIP: Symlink authfile with private pause

### PR DESCRIPTION
**Pull request by cgwalters**
Additional hack to test https://github.com/openshift/machine-config-operator/pull/535

### CODE REVIEW

**Comment by cgwalters** [comment]
Hum.  This seems to be failing for a reason I don't understand:

```
Mar 08 20:51:33 osiris-s7ks9-master-0 hyperkube[3680]: E0308 20:51:33.465332    3680 pod_workers.go:186] Error syncing pod 041392a926382976036e2d579c30316e ("etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)"), skipping: failed to "CreatePodSandbox" for "etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)" with CreatePodSandboxError: "CreatePodSandbox for pod \"etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)\" failed: rpc error: code = Unknown desc = error creating pod sandbox with name \"k8s_etcd-member-osiris-s7ks9-master-0_kube-system_041392a926382976036e2d579c30316e_0\": empty trailing digest or ID in \"@\": invalid reference"
Mar 08 20:51:33 osiris-s7ks9-master-0 hyperkube[3680]: E0308 20:51:33.465242    3680 kuberuntime_sandbox.go:65] CreatePodSandbox for pod "etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)" failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-member-osiris-s7ks9-master-0_kube-system_041392a926382976036e2d579c30316e_0": empty trailing digest or ID in "@": invalid reference
```

```
[root@osiris-s7ks9-master-0 ~]# grep -i pause /etc/crio/crio.conf 
# pause_image is the image which we use to instantiate infra containers.
pause_image = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:810ded5c25b9ec252dba6a2497d1eff9ad13a19cc3ac290ef8943b7d658803f"
# pause_command is the command to run in a pause_image to have a container just
pause_command = "/usr/bin/pod"
```

**Comment by cgwalters** [comment]
More logs with crio debug:

```
Mar 08 21:11:20 osiris-s7ks9-master-0 hyperkube[3680]: E0308 21:11:20.422284    3680 pod_workers.go:186] Error syncing pod 041392a926382976036e2d579c30316e ("etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)"), skipping: failed to "CreatePodSandbox" for "etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)" with CreatePodSandboxError: "CreatePodSandbox for pod \"etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)\" failed: rpc error: code = Unknown desc = error creating pod sandbox with name \"k8s_etcd-member-osiris-s7ks9-master-0_kube-system_041392a926382976036e2d579c30316e_0\": empty trailing digest or ID in \"@\": invalid reference"
Mar 08 21:11:20 osiris-s7ks9-master-0 hyperkube[3680]: E0308 21:11:20.422190    3680 kuberuntime_manager.go:660] createPodSandbox for pod "etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)" failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-member-osiris-s7ks9-master-0_kube-system_041392a926382976036e2d579c30316e_0": empty trailing digest or ID in "@": invalid reference
Mar 08 21:11:20 osiris-s7ks9-master-0 hyperkube[3680]: E0308 21:11:20.422154    3680 kuberuntime_sandbox.go:65] CreatePodSandbox for pod "etcd-member-osiris-s7ks9-master-0_kube-system(041392a926382976036e2d579c30316e)" failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-member-osiris-s7ks9-master-0_kube-system_041392a926382976036e2d579c30316e_0": empty trailing digest or ID in "@": invalid reference
Mar 08 21:11:20 osiris-s7ks9-master-0 hyperkube[3680]: E0308 21:11:20.422080    3680 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_etcd-member-osiris-s7ks9-master-0_kube-system_041392a926382976036e2d579c30316e_0": empty trailing digest or ID in "@": invalid reference
Mar 08 21:11:20 osiris-s7ks9-master-0 crio[4372]: time="2019-03-08 21:11:20.421480183Z" level=info msg="Attempting to run pod sandbox with infra container: kube-system/etcd-member-osiris-s7ks9-master-0/POD"
Mar 08 21:11:20 osiris-s7ks9-master-0 crio[4372]: time="2019-03-08 21:11:20.421395323Z" level=debug msg="RunPodSandboxRequest &RunPodSandboxRequest{Config:&PodSandboxConfig{Metadata:&PodSandboxMetadata{Name:etcd-member-osiris-s7ks9-master-0,Uid:041392a926382976036e2d579c30316e,Namespace:kube-system,Attempt:0,},Hostname:,LogDirectory:/var/log/pods/041392a926382976036e2d579c30316e,DnsConfig:&DNSConfig{Servers:[192.168.126.1],Searches:[osiris.verbum.local],Options:[],},PortMappings:[&PortMapping{Protocol:TCP,ContainerPort:2380,HostPort:2380,HostIp:,} &PortMapping{Protocol:TCP,ContainerPort:2379,HostPort:2379,HostIp:,}],Labels:map[string]string{io.kubernetes.pod.name: etcd-member-osiris-s7ks9-master-0,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: 041392a926382976036e2d579c30316e,k8s-app: etcd,},Annotations:map[string]string{kubernetes.io/config.hash: 041392a926382976036e2d579c30316e,kubernetes.io/config.seen: 2019-03-08T20:51:32.397228524Z,kubernetes.io/config.source: file,},Linux:&LinuxPodSandboxConfig{CgroupParent:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod041392a926382976036e2d579c30316e.slice,SecurityContext:&LinuxSandboxSecurityContext{NamespaceOptions:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,},SelinuxOptions:nil,RunAsUser:nil,ReadonlyRootfs:false,SupplementalGroups:[],Privileged:false,SeccompProfilePath:,RunAsGroup:nil,},Sysctls:map[string]string{},},},RuntimeHandler:,}"
```

**Comment by cgwalters** [comment]
Miloslove spotted that the checksum was truncated here; copy-paste error when I extracted it from the release image.  Let's take another swing at this!

**Comment by cgwalters** [comment]
Cluster formed:

```
$ oc -c setup logs e2e-aws-op 
level=warning msg="Found override for ReleaseImage. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating cluster..."
level=info msg="Waiting up to 30m0s for the Kubernetes API..."
level=info msg="API v1.12.4+8284053 up"
level=info msg="Waiting up to 30m0s for the bootstrap-complete event..."
level=info msg="Destroying the bootstrap resources..."
level=info msg="Waiting up to 30m0s for the cluster to initialize..."
```

**Comment by cgwalters** [comment]
```
$ oc debug node/ip-10-0-134-235.ec2.internal                                                                                                                                                                      
Starting pod/ip-10-0-134-235ec2internal-debug ...                                                                                                                                                                  
To directly access the host PATH, try `chroot /host /bin/bash`                                                                                                                                                    
If you don't see a command prompt, try pressing enter.                                                                                                                                                             
sh-4.2# chroot /host                                                                                                                                                                                                                                                                                                                                                                                            
sh-4.2# ls -al /root/.docker/                                                                                                                                                                                     
total 0                                                                                                                                                                                                           
drwxr-xr-x. 2 root root  25 Mar  8 21:33 .                                                                                                                                                                        
drwx------. 3 root root 123 Mar  8 21:33 ..                                                                                                                                                                       
lrwxrwxrwx. 1 root root  28 Mar  8 21:33 config.json -> /var/lib/kubelet/config.json      
sh-4.2# podman images| grep quay
quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256        810ded5c25b9ec252dba6a2497d1eff9ad13a19cc3ac290ef8943b7d658803f2   68487363bd9a   4 days ago          236 MB                                         
quay.io/coreos/kube-client-agent                             36c62ccd7b16b522450c61e96fc556b217ee24f5                           b02de22ff740   4 months ago        33.8 MB   
```

This looks good to me!

**Comment by runcom** [comment]
Awesome! Still WIP?

**Comment by cgwalters** [comment]
> Awesome! Still WIP?

This is just a testing PR for https://github.com/openshift/machine-config-operator/pull/535

Closing this one, let's get the other one merged!

**Pull request closed without merging**
