### PR TITLE
Add etcd-quota-guard e2e and remove debugging code

### PR DESCRIPTION
**Pull request by RobertKrawitz**
**- What I did**
Add e2e for etcd-quota-guard, and remove debugging startup code from the pod

Followon to #671.

**- How to verify it**
Run e2e

**- Description for the changelog**
Add e2e for etcd-quota-guard, and remove debugging startup code from the pod

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
will probably have to raise the e2e timeout for this?  let's see, but we're pretty close to the 50 mins already.

**Comment by RobertKrawitz** [comment]
@kikisdeliveryservice this test is fairly quick, but where is that limit so I can make the change if I need to?

**Comment by kikisdeliveryservice** [comment]
@RobertKrawitz i believe it's set in the Makefile

**Comment by RobertKrawitz** [comment]
Yep.  I'll see what happens; if it times out, I'll raise it to 55m.

**Comment by RobertKrawitz** [comment]
/hold
I want to see why the test failed the first time.  It shouldn't have failed in that way.

**Comment by runcom** [comment]
looks like e2e went fine no?

**Comment by hexfusion** [comment]
Was this the concern?

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/673/pull-ci-openshift-machine-config-operator-master-e2e-aws-op/1767/

**Comment by RobertKrawitz** [comment]
@hexfusion yes.  I don't like that it failed once in that way and then passed.

**Comment by RobertKrawitz** [comment]
/hold cancel

Unable to reproduce this after about 5 tries.  I've bumped the timeout in question to 5 minutes in case that was the issue.

**Comment by RobertKrawitz** [comment]
Also bumped the e2e timeout to 55 minutes per @kikisdeliveryservice recommendation.

**Comment by RobertKrawitz** [comment]
/retest
infra failure

**Comment by RobertKrawitz** [comment]
@runcom see comments above; I believe this is ready to merge.

**Pull request merged**
