### PR TITLE
Bug 2039541: Fix duplicate prepender entries in resolv.conf

### PR DESCRIPTION
**Pull request by cybertron**
In #2835, we changed how the prepender finds the location to insert
the prepended nameserver. Unfortunately, this caused it to prepend
the nameserver before each existing nameserver line, which results
in duplicate entries for the local nameserver. For example:

search ostest.test.metalkube.org
nameserver 192.168.111.23
nameserver 8.8.8.8
nameserver 192.168.111.23
# nameserver 192.168.111.1

This is mildly problematic since it pushes the second nameserver out
of the list of 3 that are allowed. In general this probably won't
cause problems because only the local nameserver is actually used,
but it looks weird and will almost certainly result in a bug report
from customers at some point.

The replacement sed line is stolen from [0] and is specific to GNU
sed, but that shouldn't be a problem for us since we only use that
version of sed.

0: https://stackoverflow.com/questions/9970124/sed-to-insert-on-first-match-only

**- What I did**

**- How to verify it**

**- Description for the changelog**
Fix resolv-prepender logic to avoid duplicate entries.

### CODE REVIEW

**Comment by cybertron** [comment]
The formatting of the description is a bit weird. The last nameserver that shows up as a title is actually commented out.

**Review by mandre — COMMENTED** [review]
Tried it locally, does what it's supposed to do :)
/lgtm

**Comment by mandre** [comment]
@cybertron do you have a BZ you can reference?

**Review by cgwalters — APPROVED** [review]

**Comment by cybertron** [comment]
> @cybertron do you have a BZ you can reference?

Oops, thanks for the reminder. I opened one but forgot to add it here.

**Pull request merged**
