### PR TITLE
pkg/daemon: don't flip Degraded/Working and add an Unreconcilable state

### PR DESCRIPTION
**Pull request by runcom**
pkg/daemon: keep degraded state after failure

Now that the Degraded state is just a state with the only scope of being
informative, keep it instead of just flipping between Working->Degraded
when we fail. When an MC degrades the machine, it still keeps retrying
to reconcile but at least administrators know that something is wrong
instantly.

Signed-off-by: Antonio Murdaca <runcom@linux.com>

pkg/daemon: add an Unreconcilable state

This new state is, like Degraded, the way we communicate to
administrators that something went specifically wrong with their
MachineConfigs. A natural follow up to this would be going ahead and
expose the real error on the object itself. With this state admins can also
just delete the bad MC and roll back.

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
This should help with https://github.com/openshift/machine-config-operator/issues/254 but that issue talks about a label (not an annotation state like this PR does). Also related to https://github.com/openshift/machine-config-operator/issues/234 which could be a follow up to this...

**Comment by cgwalters** [comment]
Don't we also need to remove `Degraded` on success?

**Comment by runcom** [comment]
> Don't we also need to remove `Degraded` on success?

uhm, if the update goes through, we reboot and set `Done` directly

**Comment by cgwalters** [comment]
> uhm, if the update goes through, we reboot and set Done directly

Right, duh!

/lgtm

**Pull request merged**
