### PR TITLE
Bug 1954554: add e2e for auto node sizing

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

Closes: https://issues.redhat.com/browse/OCPNODE-547

**- What I did**
Add e2e for auto node sizing

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by harche** [comment]
Verified in local run,

```bash
$ go test -failfast -timeout 90m -v${WHAT:+ -run="$WHAT"} --run TestKubeletConfigMaxPods ./test/e2e/
=== RUN   TestKubeletConfigMaxPods
ip-10-0-163-116.us-east-2.compute.internal
    utils.go:64: Pool node-max-pods has rendered config mc-max-pods with rendered-node-max-pods-08de4f9f70cd8ebde3e3bb76f6c41dcc (waited 6.757179099s)
    utils.go:86: Pool node-max-pods has completed rendered-node-max-pods-08de4f9f70cd8ebde3e3bb76f6c41dcc (waited 8.245979051s)
    utils.go:64: Pool node-max-pods has rendered config 99-node-max-pods-generated-kubelet with rendered-node-max-pods-d1c68de7851772d0dabcfb1c1834cb4f (waited 4.496078055s)
    utils.go:86: Pool node-max-pods has completed rendered-node-max-pods-d1c68de7851772d0dabcfb1c1834cb4f (waited 3m10.308007951s)
ip-10-0-163-116.us-east-2.compute.internal
    utils.go:64: Pool node-max-pods has rendered config 99-node-max-pods-generated-kubelet-1 with rendered-node-max-pods-627eb1f5a7f1601ead8ac1a921b16111 (waited 4.572049128s)
    utils.go:86: Pool node-max-pods has completed rendered-node-max-pods-627eb1f5a7f1601ead8ac1a921b16111 (waited 1m42.405661613s)
    kubeletcfg_test.go:147: Deleted KubeletConfig kubelet-test-200
    utils.go:86: Pool node-max-pods has completed rendered-node-max-pods-d1c68de7851772d0dabcfb1c1834cb4f (waited 1m46.249892494s)
    kubeletcfg_test.go:157: Deleted KubeletConfig kubelet-test-100
    utils.go:86: Pool node-max-pods has completed rendered-node-max-pods-08de4f9f70cd8ebde3e3bb76f6c41dcc (waited 1m44.332148343s)
    utils.go:86: Pool worker has completed rendered-worker-08de4f9f70cd8ebde3e3bb76f6c41dcc (waited 6.245881813s)
--- PASS: TestKubeletConfigMaxPods (566.50s)
PASS
ok      github.com/openshift/machine-config-operator/test/e2e   566.512s
```

**Review by sinnykumari — APPROVED** [review]

**Comment by sinnykumari** [comment]
You will also need to create a bug for this.

**Comment by harche** [comment]
> You will also need to create a bug for this.

Sure, thanks. 

/hold

**Pull request merged**
