### PR TITLE
OCPBUGS-6018: controller: don't render new MC until base MCs update

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Add an additional check to the controller logic to not create a
new rendered-MC until all the base MachineConfigs have updated to
the newest version.

With just regular MCs, since we have the controllerconfig version
check right above it, it basically gates the template-controller
managed MCs to be updated before the render-controller creates a
new rendered config. However, containerruntimeconfigcontroller
and kubeletconfigcontroller have no such guarantee, making it such that
if you have both change during an update, it can happen before
template-controller changes if and only if something like this ordering
occurs:

1. the CRCC creates a new containerruntimeconfig due to the update
2. the template controller finishes re-creating the base configs
3. the kubeletconfig errors long enough and doesn't finish until after 2

This will cause the render controller to create a new rendered MC that
uses the OLD kubeletconfig-MC, which at best is a double reboot for 1
node, and at worst block the update and break maxUnavailable nodes per
pool as shown in the bug.

This bug is quite nebulous and has an exact trigger condition, which is
why we haven't seen it until now.

We also technically have something that should error here:
https://github.com/openshift/machine-config-operator/blob/fc27a2bdaa8517adf61d855195453d2b48f6b802/pkg/operator/status.go#L592-L606

But that:
1. runs as part of syncRequiredMachineConfigPools which is after
   controller gets recreated
2. is not a hard error, and only gets reported after the 10min timeout
3. seems to be mostly reporting for rendered MCs to indicate that the
   pool isn't updated to the latest configuration
4. is master pool only

So that doesn't actually help with this scenario

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Ah, I'll create a public issue with the bug. I've tested this on 4.11 and it works, so this should be ready to review, but I will do some testing on master just in case

**Comment by sinnykumari** [comment]
lgtm, nice debugging Jerry.

Looks like added tests may require some adjustment

**Comment by yuqi-zhang** [comment]
Fixed the tests, tested to work on 4.12->4.13 upgrades as well, will add testing steps into the bug

**Comment by sinnykumari** [comment]
/lgtm
Also skipping these optional tests as failure shouldn't be related to this PR
/skip

**Comment by sergiordlr** [comment]
To verify this PR we followed the instructions in this jira ticket https://issues.redhat.com//browse/OCPBUGS-6018


Since the error depends on the order of the events, it cannot be reproduced consistently, hence we will create two 4.13 ocp release images with custom hacked machine-config-operators in order to force the failures:
1) an image that will always report a failure in kubeletconfig and does NOT contain the fix for this issue. https://github.com/yuqi-zhang/machine-config-operator/tree/fix-old-kubeletconfig-test-always-fail-kcc-without-fix 
2) an image that will always report a failure in kubeletconfig and contains the fix for this issue. https://github.com/yuqi-zhang/machine-config-operator/tree/fix-old-kubeletconfig-test-always-fail-kcc

The base release image used to create those hacked images will be _registry.ci.openshift.org/ocp/release:4.13.0-0.nightly-2023-01-17-152326_. Using this command:

```
$ oc adm release new --from-release registry.ci.openshift.org/ocp/release:4.13.0-0.nightly-2023-01-17-152326 \
      --to-image quay.io/hacked/image:tag machine-config-operator=quay.io/hacked/machine-config-operator:tag
```



And we will execute 3 upgrades.

1. From 4.12 -> image1 (kubeleterror+nofix)
2. From 4.12 -> image2 (kubeleterror+fix)
3. From 4.12 -> normal no hacked image that contains this PR


Before executing every upgrade we will create a kubeletconfig resource and a containerruntimeconfig resource


**Upgrade from 4.12 -> image1 (kubeleterror+nofix)**

The kubeletconfig resource is not updated with the new controller's hash, but the worker MC has the new HASH

```
$ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-bf53ef56cff15c81c9db9ac731dbbef0   True      False      False      3              3                   3                     0                      3h42m
worker   rendered-worker-ff18389e63a56096ee389ff770065203   True      False      False      3              3                   3                     0                      3h42m
```


```
$ oc get mc -o yaml 99-worker-generated-containerruntime 99-worker-generated-kubelet rendered-worker-ff18389e63a56096ee389ff770065203 | grep controller-version
      machineconfiguration.openshift.io/generated-by-controller-version: c2a5a46dc2c49ac86da64f8b434e635077dd709c
      machineconfiguration.openshift.io/generated-by-controller-version: 60fb64fa861f1231f779226aa5dcd5c4ef604dcb   <-- kubeletconfig's MC was not updated
      machineconfiguration.openshift.io/generated-by-controller-version: c2a5a46dc2c49ac86da64f8b434e635077dd709c   <-- but the rendered MC was
```




**Upgrade from 4.12 -> image2 (kubeleterror+fix)**

The kukebeletconfig's MC resource is not updated with the new controller's hash, hence the MCC reports a failure and refuses to update the rendered MC with the new hash until the kubeletconfig's MC hash is updated before

```
$ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-b68ea2a57196be97352555270ff8a941   True      False      False      3              3                   3                     0                      158m
worker   rendered-worker-d023ec8ab02da9fa03471d388a6eb9ac   True      False      True       3              3                   3                     0                      158m
```


```
$ oc get mc 99-worker-generated-containerruntime 99-worker-generated-kubelet rendered-worker-d023ec8ab02da9fa03471d388a6eb9ac -o yaml |grep controller-version
      machineconfiguration.openshift.io/generated-by-controller-version: ff4e61b35f236b6aac3979e31ff346d2a62a5dc2
      machineconfiguration.openshift.io/generated-by-controller-version: 60fb64fa861f1231f779226aa5dcd5c4ef604dcb  <----- KubeletConfig's MC is not updated
      machineconfiguration.openshift.io/generated-by-controller-version: 60fb64fa861f1231f779226aa5dcd5c4ef604dcb   <----- and the rendered MC is not updated either, it is waiting.
```

We can clearly see the log error messages reporting the issue:
```
$ oc logs -n openshift-machine-config-operator machine-config-controller-59dbb959d4-xhkgh |grep Ignoring 
......
I0120 13:30:27.457048       1 render_controller.go:377] Error syncing machineconfigpool worker: Ignoring MC 99-worker-generated-kubelet generated by older version 60fb64fa861f1231f779226aa5dcd5c4ef604dcb (my version: ff4e61b35f236b6aac3979e31ff346d2a62a5dc2)
E0120 13:31:49.388543       1 render_controller.go:382] Ignoring MC 99-worker-generated-kubelet generated by older version 60fb64fa861f1231f779226aa5dcd5c4ef604dcb (my version: ff4e61b35f236b6aac3979e31ff346d2a62a5dc2)
I0120 13:31:49.388559       1 render_controller.go:383] Dropping machineconfigpool "worker" out of the queue: Ignoring MC 99-worker-generated-kubelet generated by older version 60fb64fa861f1231f779226aa5dcd5c4ef604dcb (my version: ff4e61b35f236b6aac3979e31ff346d2a62a5dc2)
```

Manually editing the controller-version in the kubeletconfig's MC, fixed the problem and the controller was able to render a new MC.


**Upgrade from 4.12 -> normal not-hacked 4.13 release that contains this PR**

We can't reproduce the error at will, but we can make sure that this PR is not breaking normal upgrades.

No kubelet error occurred in this execution, so the issue was not reproduced. After executing the upgrade, though, the pools were OK and the MCs were updated with the right hash

```
$ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-7ad434075274ac63bdd0c9b464419663   True      False      False      3              3                   3                     0                      140m
worker   rendered-worker-e299b94340bd8a65f634a2a91f24ca64   True      False      False      3              3                   3                     0                      140m

```
```
$ oc get mc 99-worker-generated-containerruntime 99-worker-generated-kubelet rendered-worker-e299b94340bd8a65f634a2a91f24ca64 -o yaml |grep controller-version
      machineconfiguration.openshift.io/generated-by-controller-version: d37a5efc4dac4efaf64d47ff3d45114e73c3f2cc
      machineconfiguration.openshift.io/generated-by-controller-version: d37a5efc4dac4efaf64d47ff3d45114e73c3f2cc
      machineconfiguration.openshift.io/generated-by-controller-version: d37a5efc4dac4efaf64d47ff3d45114e73c3f2cc
```


We add the qe-approved label

/label qe-approved

**Pull request merged**
