### PR TITLE
bug 1804418: remove the etcd-member pod because we no longer need it

### PR DESCRIPTION
**Pull request by deads2k**
When combined with https://github.com/openshift/cluster-etcd-operator/pull/112, we can get a working install and a working upgrade.

/hold

### CODE REVIEW

**Comment by deads2k** [comment]
this worked when combined into a payload with https://github.com/openshift/cluster-etcd-operator/pull/142

**Comment by hexfusion** [comment]
this has been manually tested with success.

> this worked when combined into a payload with [openshift/cluster-etcd-operator#142](https://github.com/openshift/cluster-etcd-operator/pull/142)

confirming manual testing by @retroflexer and @sanchezl 

/lgtm

**Comment by sinnykumari** [comment]
/hold
Needs a valid bug in order to get merged in master (4.4)
/retest

**Pull request merged**
