### PR TITLE
Bug 2024511: [release-4.8] [on-prem] Manual backporting of keepalived arp retries

### PR DESCRIPTION
**Pull request by yboaron**
Manual backporting of:
  https://github.com/openshift/machine-config-operator/pull/2794
  https://github.com/openshift/machine-config-operator/pull/2578

### CODE REVIEW

**Comment by cybertron** [comment]
/cc @jcpowermac 

I think backporting this to 4.7 should address the ARP bug we've been discussing.

@yboaron This is going to need a clone of the original bug attached in order to merge.

**Review by kikisdeliveryservice — APPROVED** [review]
Adding approval but also a hold, remove hold once BZ is added.

/hold

**Comment by yboaron** [comment]
/retitle Bug: 2024511  [release-4.8] [on-prem] Manual backporting of keepalived arp retries

**Comment by yboaron** [comment]
/retitle Bug 2024511: [release-4.8] [on-prem] Manual backporting of keepalived arp retries

**Comment by yboaron** [comment]
All the relevant gates are green, 
@kikisdeliveryservice, Can we merge this backport PR?

**Comment by sinnykumari** [comment]
> All the relevant gates are green, @kikisdeliveryservice, Can we merge this backport PR?

As mentioned in the https://github.com/openshift/machine-config-operator/pull/2831#pullrequestreview-808937753 , since it has valid bug now, it should be ok to merge. Please make sure to ask your dev and QE team members listed in https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/machine-config-operator/_pluginconfig.yaml to get backport-risk-assesed and cherry-pick-approval level

**Comment by cybertron** [comment]
/backport-risk-assessed

I've never done this before and I'm guessing at the command. :-)

**Comment by cybertron** [comment]
/label backport-risk-assessed

Let's try this instead.

**Comment by sinnykumari** [comment]
@vvoronkov you username has been fixed in https://github.com/openshift/release/pull/23944 , please retry to add the cherry=pick-approved label, should work now.

**Comment by cybertron** [comment]
/hold cancel

This should be good to go now.

**Pull request merged**
