### PR TITLE
 render: Add `core` user explicitly to groups

### PR DESCRIPTION
**Pull request by cgwalters**
This is prep for increasing alignment with FCOS where we'd
like to not have the user hardcoded.

See also: openshift/installer#1445

This way the privileged user is only created if a SSH key is
provided.

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
We explicitly don't support groups -we don't support Pass:Users:SSH, so I don't see how we can present MCs to the user where core has a group?  They will expect to be able to change this and we do not allow it.

**Comment by cgwalters** [comment]
> so I don't see how we can present MCs to the user where core has a group?

The user can't edit it.  But actually you're right in that may  cause a problem for the MCD, even though it will be correctly handled by the Ignition run at provisioning time.

Although actually I think it should work, because we do:

```
	if !reflect.DeepEqual(oldIgn.Passwd, newIgn.Passwd) {
		if !reflect.DeepEqual(oldIgn.Passwd.Groups, newIgn.Passwd.Groups) {
			return errors.New("ignition Passwd Groups section contains changes")
		}
```

And unless the user tries to change the groups, the old/new will be the same (previously empty, now with those hardcoded values).

**Comment by kikisdeliveryservice** [comment]
I think it's really confusing to have something in the MC that they cannot edit and will try to edit as opposed to just not showing it to them in the first place.   For better or for worse, we are using MCs as a UI, and I think this is bound to cause confusion.

**Comment by kikisdeliveryservice** [comment]
Would this mean that they user has to copy the user:groups that they dont even know exist into a new MC if they are just trying to update their keys via a new MC?

For ex: i run installer and give it some keys. Later I want to update the keys so I create a new MC with user: core and keys:... if I dont copy over some groups that I dont even know about, my MC will fail?

What if I want to keep my keys and remove the groups? I can't change the groups without getting rid of the user and keys?

**Comment by kikisdeliveryservice** [comment]
Spoke to @cgwalters and he's trying a different approach, for now will mark this as hold.

/hold

**Comment by kikisdeliveryservice** [comment]
In an effort to clean up the MCO repo, closing old open PRs with no recent activity.  

Feel free to reopen.

**Pull request closed without merging**
