### PR TITLE
[release-4.8] Bug 2000500: bump SystemMemoryExceedsReservation alert threshold to 95%

### PR DESCRIPTION
**Pull request by harche**
This is a backport of https://github.com/openshift/machine-config-operator/pull/2716

Signed-off-by: Harshal Patil <harpatil@redhat.com>

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by sinnykumari — APPROVED** [review]

**Comment by hardys** [comment]
[patch-manager] Approving for cherry-pic with a score of 0.70

**Pull request merged**
