### PR TITLE
Use hostNetwork: true for operator and controller

### PR DESCRIPTION
**Pull request by cgwalters**
We want to support switching cluster network types "day 2".
This may involve a MachineConfig rollout, so using the
host network will avoid potential deadlocks.

### CODE REVIEW

**Comment by cgwalters** [comment]
It's not 100% clear to me that we don't *also* need to change the MCO with this.  I *think* the only potential consequence if the MCO is temporarily unable to network is that the clusteroperator status won't update; otherwise...once a control plane rollout is done and the node hosting the MCO is drained, if the MCO lands on an updated node then status should start working again.

But maybe it would just overall be easier to understand if we made *all* containers in the MCO `hostNetwork: true` and hence fully severed any dependency on the SDN.

**Comment by sinnykumari** [comment]
> But maybe it would just overall be easier to understand if we made _all_ containers in the MCO `hostNetwork: true` and hence fully severed any dependency on the SDN.

+1

I am curious to know why MCO pods didn't opt for host networking in the beginning?

**Comment by pliurh** [comment]
> But maybe it would just overall be easier to understand if we made all containers in the MCO hostNetwork: true and hence fully severed any dependency on the SDN.

+1

**Comment by cgwalters** [comment]
Updated to make the operator use `hostNetwork: true` too.

**Comment by pliurh** [comment]
@cgwalters If we want to decouple the MCO with the clusterNetwork, using hostNetwork may not be sufficient. Currently, MCO uses the in-cluster kube client configuration which talks to the apiserver VIP of `172.30.0.1`. The route to this VIP is also handled by the clusterNetwork providers on hostnetwork. So if we want MCO has no dependency on the clusterNetwork, we shall also use the URI of `api-int.<cluster-domain>` to communicate with the apiserver.

**Comment by crawford** [comment]
Is this part of a larger epic or enhancement?

**Comment by darkmuggle** [comment]
/retest

The SDN Team is asking that we include this in 4.8. AFAIK, this looks fine.  
@skinny or  @kikisdeliveryservice  give the +1, would one of you feel comfortable with an LGTM?

**Comment by sinnykumari** [comment]
With my limited cluster networking knowledge can't think of any issue, this PR looks good to me as it is.
Do we have CI coverage somewhere to look at where we perform Day2 networking switch?

**Comment by kikisdeliveryservice** [comment]
> Is this part of a larger epic or enhancement?

@pliurh could you answer the above?

**Comment by pliurh** [comment]
Here is the story of 4.8 https://issues.redhat.com/browse/SDN-1546

Currently, we don't have CI for the SDN migration. Because during the migration, a manual reboot step is required, which I haven't figure out how it can be done in openshift-ci. We used to have a baremetal CI environment for that, but it was put to other uses. :(

My two cents: Put the SDN migration requirement aside, considering MCO's position, I think it still makes sense to decouple the MCO from the cluster network.

**Comment by cgwalters** [comment]
> Because during the migration, a manual reboot step is required, which I haven't figure out how it can be done in openshift-ci. 

Just cordon/drain the node and then use e.g. `oc debug node/$node chroot /host reboot`.

**Comment by danwinship** [comment]
> I am curious to know why MCO pods didn't opt for host networking in the beginning?

> +1 As someone who be confused later... I think this is the way to go unless there are good reasons not to?

For pods that don't expose any services, the argument against being hostNetwork is mostly just that it's more privilege (eg, now you can't restrict the pods with NetworkPolicy, etc). Especially, pods that are both `privileged` and `hostNetwork` can do a lot of damage if they are compromised. (But neither MCO nor MCC is privileged.)

(If either pod exposes any ports [for metrics?] you will need to update https://github.com/openshift/enhancements/blob/master/enhancements/network/host-port-registry.md)

> So if we want MCO has no dependency on the clusterNetwork, we shall also use the URI of `api-int.<cluster-domain>` to communicate with the apiserver.

cf #2232

**Pull request closed without merging**
