### PR TITLE
CORS-3713: Extend in-cluster DNS support to AWS Platform

### PR DESCRIPTION
**Pull request by sadasu**
In-cluster DNS support was previously added for the GCP platform. Only the platform specific portions of that solution have been updated to include the AWS platform.

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by sadasu** [comment]
@yuqi-zhang Could you PTAL?

**Review by yuqi-zhang — APPROVED** [review]
logically seems fine, although I don't know how to test this. Is this covered by any existing CI? Alternatively, maybe this should be QE pre-verified?

**Comment by sadasu** [comment]
> logically seems fine, although I don't know how to test this. Is this covered by any existing CI? Alternatively, maybe this should be QE pre-verified?

Will be tested by both QE and CI. This [tech preview CI job](https://github.com/openshift/release/pull/57437) is being added to test this feature.

**Comment by mkowalski** [comment]
/lgtm

As discussed via Slack, looks good because it's basically copy-pasta of the code handling GCP extending the logic for AWS. But if after the feature freeze it turns out we need additional implementation in baremetal-runtimecfg, then we should be reverting this one here.

I hope the current code in runtimecfg handles cloud platforms "all-at-once", but we (on-prem networking) never really tested the use of baremetal-runtimecfg in non-metal platforms so there may be gaps.

**Comment by sadasu** [comment]
> As discussed via Slack, looks good because it's basically copy-pasta of the code handling GCP extending the logic for AWS. But if after the feature freeze it turns out we need additional implementation in baremetal-runtimecfg, then we should be reverting this one here.
> 
> I hope the current code in runtimecfg handles cloud platforms "all-at-once", but we (on-prem networking) never really tested the use of baremetal-runtimecfg in non-metal platforms so there may be gaps.

Yes, code added to baremetal-runtimecfg is generic for cloud platforms and does not need any additional changes to add support for AWS (and later Azure).

**Pull request merged**
