### PR TITLE
Bug 1851344: Pass proxy settings nodeip-configuration service for baremetal, vsphere, openstack

### PR DESCRIPTION
**Pull request by mandre**
The nodeip-configuration service used in on-premise platforms needs to
follow proxy settings otherwise it may not be able to download
container image.

### CODE REVIEW

**Comment by mandre** [comment]
For some reason, github didn't pick my last commit so I had to rebase and force push the branch...

/test e2e-openstack
/test e2e-ovirt
/test e2e-vshpere

**Comment by kikisdeliveryservice** [comment]
upgrade job seems broke-ish ill check in 4-dev

**Comment by cybertron** [comment]
Seems fine to me, assuming it passes ci.

**Comment by mandre** [comment]
/retest

We expect to see at least BM and OpenStack working.
ovirt is currently failing because of https://bugzilla.redhat.com/show_bug.cgi?id=1853889 and vsphere has its own issues.

**Comment by mandre** [comment]
/hold cancel
This should be good to merge.

**Pull request merged**
