### PR TITLE
OWNERS: drop @runcom with gratitude

### PR DESCRIPTION
**Pull request by darkmuggle**
With gratitude and best wishes for @runcom's new grand adventure, this removes Antonio from the owner's file. 

(Per his request)

### CODE REVIEW

**Comment by hexfusion** [comment]
thanks for everything @runcom !

**Comment by ashcrow** [comment]
I see both Colin and I are still listed in the `OWNERS` file. Should we be removed as well so it's direct team folks in the list?

**Comment by sinnykumari** [comment]
> I see both Colin and I are still listed in the `OWNERS` file. Should we be removed as well so it's direct team folks in the list?

I am personally more than happy with having both of you being part of reviewers if you are interested. Always good to have more eyes reviewing/approving the PR, The More the Merrier :)

**Comment by kikisdeliveryservice** [comment]
> I see both Colin and I are still listed in the `OWNERS` file. Should we be removed as well so it's direct team folks in the list?

I think to clean up PR assignees it makes sense, I know that Steve and I both go through and have to reassign frequently.

**Comment by kikisdeliveryservice** [comment]
> I see both Colin and I are still listed in the `OWNERS` file. Should we be removed as well so it's direct team folks in the list?

I think to cleaning up the file makes sense, I know that Steve and I both go through and have to manually reassign frequently. I am, of course, happy for your reviews :smile_cat: even if the file gets cleanedup! :smiley: but also think that an active team member should have to approve prs that merge.

**Comment by darkmuggle** [comment]
> I see both Colin and I are still listed in the `OWNERS` file. Should we be removed as well so it's direct team folks in the list?

It goes without saying that both @ashcrow and @cgwalters are trusted reviewers and have contributed much to the MCO. I'm happy to go either way, and I'll defer the final decision both @ashcrow and @cgwalters -- what saw ye?

**Comment by ashcrow** [comment]
Go ahead and remove me. I I will still help as needed but I don't require merge powers.

**Comment by cgwalters** [comment]
Feel free to drop me too if it helps clean up the bot assignments etc.  I'll still be around for sure :smile:

**Comment by sinnykumari** [comment]
with 4.7 branching in place, master should be now pointing to 4.8 :thinking:

**Review by ashcrow — APPROVED** [review]

**Pull request merged**
