### PR TITLE
OCPBUGS-1616 Fix CI Job failure

### PR DESCRIPTION
**Pull request by sairameshv**
Signed-off-by: Sai Ramesh Vanka svanka@redhat.com

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
in order to call the techpreview job you probably need to update openshift/release in someway like this: https://github.com/openshift/release/commit/b69c4e720954d307e00beebc60ca9df876d4cd9e

cc: @sinnykumari

**Comment by sairameshv** [comment]
/close
I will open up a new PR that consists of the cgroupv2 support along with this fix combined.

**Pull request closed without merging**
