### PR TITLE
Bug 1803232: Fixed hardcoded ingress VIP password

### LINKED ISSUE #1379: keepalived's ingress VIP barmetal password hardcoded
https://github.com/openshift/machine-config-operator/blob/master/templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml#L70

https://github.com/openshift/machine-config-operator/blob/1e15e3f76c5a050123f38896655c5ca23dafe2ed/templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml#L22

While others have been templated as `{{`{{ .Cluster.Name }}`}}_something` the ingress VIP is hardcoded

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes #1379

**- What I did**
The current keepalived ingress VIP password is hardcoded so I've changed to follow the other VIP passwords.

**- How to verify it**
Deploy a cluster and observe the `/etc/keepalived/keepalived.conf` file

**- Description for the changelog**
Fixed hardcoded ingress VIP password

### CODE REVIEW

**Comment by cgwalters** [comment]
I'm not very familiar with keepalived; only skimmed some of [the docs](https://www.keepalived.org/doc/software_design.html#failover-vrrp-framework).  But we're just changing from a truly hardcoded password to one that is easily guessable.   Is it expected that in practice vrrpd is on a trusted network or something?

**Comment by e-minguez** [comment]
cc @celebdor @yboaron @bcrochet

**Comment by kikisdeliveryservice** [comment]
we need a BZ for this

/hold

**Comment by celebdor** [comment]
/retitle Bug 1803232: Fixed hardcoded ingress VIP password

**Comment by kikisdeliveryservice** [comment]
ty @celebdor !

/approve

**Comment by sinnykumari** [comment]
removing hold, we have valid bz attached
/hold cancel
/test e2e-gcp-op

**Comment by sinnykumari** [comment]
/hold
Target of BZ#1803232 is set to 4.4 while this PR is against master branch

**Comment by sinnykumari** [comment]
Removing hold as bz# 1803232 targets to 4.5 now
/hold cancel
/retest

**Comment by runcom** [comment]
> /cherrypick release-4.4

4.4 BZ for the cherry-pick: https://bugzilla.redhat.com/show_bug.cgi?id=1810996

**Comment by e-minguez** [comment]
Is there any way to skip unrelated tests?

**Comment by sinnykumari** [comment]
e2e-gcp-op failure could be related to https://github.com/openshift/machine-config-operator/pull/1545#issuecomment-596446878

**Pull request merged**
