### PR TITLE
Bump(openshift/api): to get CSI changes

### PR DESCRIPTION
**Pull request by bertinatto**
In upstream, CSI migration is GA for Azure Disk and OpenStack Cinder.
As a result, we need to stop force-disabling the feature gates because
that doesn't have any effect anymore.

CC @openshift/storage

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Could you add some context to the commit message? For example, why some featuregates are being removed

**Comment by bertinatto** [comment]
> Could you add some context to the commit message? For example, why some featuregates are being removed

I amended the commit message to add context for the CSI changes, however, I don't know all the details for all the other changes in openshift/api.

**Comment by kikisdeliveryservice** [comment]
weird, i thought this ran:
/test e2e-openstack

**Comment by kikisdeliveryservice** [comment]
@bertinatto can you assign some non-mco reviewers for this who have some background to review his change?

**Comment by jsafrane** [comment]
/lgtm
from storage team POV

**Comment by kikisdeliveryservice** [comment]
Since the commit references openstack as well, @mandre @pierreprinetti would be mind just taking a quick look on this?

**Review by mandre — COMMENTED** [review]
> Since the commit references openstack as well, @mandre @pierreprinetti would be mind just taking a quick look on this?

LGTM, as far as OpenStack platform is concerned.

**Comment by kikisdeliveryservice** [comment]
@rphillips re: non-CSI featuregate changes, do these look ok?

**Pull request merged**
