### PR TITLE
Use go "embed" module to store manifests

### PR DESCRIPTION
**Pull request by Fedosin**
This PR starts using "embed" go module to store manifests in the binary. It is easier and more natural than doing so with go-bindata.

### CODE REVIEW

**Comment by cgwalters** [comment]
Dup of https://github.com/openshift/machine-config-operator/pull/2739 ?

**Comment by Fedosin** [comment]
Oh, sorry, didn't notice that patch. As I see it's closed now, so we can continue here.

**Comment by sinnykumari** [comment]
LGTM
@LorbusChris Since you also invested time in this with PR https://github.com/openshift/machine-config-operator/pull/2739 , can you take a look in case I missed something.

**Review by LorbusChris — APPROVED** [review]
LGTM

**Review by sinnykumari — APPROVED** [review]

**Pull request merged**
