### PR TITLE
OCPBUGS-27190: Fix mirrorSourcePolicy error prompt imagecontentsourcepolicies

### PR DESCRIPTION
**Pull request by QiWang19**
**- What I did**
Fix conflicting mirrorSourcePolicy error prompt to include imagecontentsourcepolicies
**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by QiWang19** [comment]
@lyman9966 PTAL

**Review by mtrmac — COMMENTED** [review]
/lgtm

**Comment by QiWang19** [comment]
@yuqi-zhang could you approve?

**Review by yuqi-zhang — APPROVED** [review]

**Pull request merged**
