### PR TITLE
OCPBUGS-23484: kubevirt, Activate nodeip-configuration.service

### PR DESCRIPTION
**Pull request by qinqon**
**- What I did**
Activate nodeip-configuration for KubeVirt

**- How to verify it**
When creating the node-hint file KubeVirt node select the proper IP for kubelet

**- Description for the changelog**
kubevirt: Activate nodeip-configuration.service

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Comment by qinqon** [comment]
/assign @sinnykumari 

Can you approve the PR ? it's all good from the hypershift kubevirt team.

**Review by sinnykumari — APPROVED** [review]
Change is kubervit specific

**Pull request merged**
