### PR TITLE
[release-4.12] OCPBUGS-14071: Imageinspect takes type of error into account, drop podman inspect fallback

### PR DESCRIPTION
**Pull request by jkyros**
Manual 4.12 cherry-pick of https://github.com/openshift/machine-config-operator/pull/3413

~~had to bump `go-health` because it had dependency issues~~

### CODE REVIEW

**Comment by jkyros** [comment]
Well this is going to be unpleasant since verify is picker than it was previously :smile:

**Comment by sergiordlr** [comment]
Using IPI on AWS. 

All e2e critical test cases passed.
All Layering test cases passed.

/label cherry-pick-approved

**Comment by sinnykumari** [comment]
seeing if verify is still an issue
/test verify

**Comment by jkyros** [comment]
That looks like general hypershift failure, but we'll see
 /test e2e-hypershift

**Comment by jkyros** [comment]
one more time. Hypershift seems to be failing the chaos tests with timeouts but this shouldn't affect any of that. 
/test e2e-hypershift

**Comment by jkyros** [comment]
Yep, hypershift chaos tests are broken regardless of the changes in this PR. I tested that over here:  https://github.com/openshift/machine-config-operator/pull/4118, so this PR here  should be ready. 

@sergiordlr I don't know if you need to re-verify this but I think it's ready

**Review by yuqi-zhang — APPROVED** [review]
/lgtm
/label  backport-risk-assessed

Should be safe, is there any harm to not backporting this @jkyros ? It looks like it's been a long while since the PR merged to 4.13

**Comment by jkyros** [comment]
There's no actual harm to not backporting this other than "it's probably going to annoy people on 4.12 if we don't fix it" -- without this the mcd just won't "come up for air" for a long while if you feed it an image it can never retrieve. It just keeps trying and trying while reporting "working" (so nobody knows anything is wrong until waaaaaay later).

**Comment by jkyros** [comment]
I have had really interesting luck with the bots the last couple weeks
/label backport-risk-assessed

**Pull request merged**
