### PR TITLE
WIP: Bug 1885365: update.go: use systemd presets to enable/disable units

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Change unit enable/disable to write a mco systemd preset file, so
that we can properly handle units not targetting multi-user.target.wants.
The code is essentially copied from Ignition/units and emulates
Ignition behaviour for this.

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
I think I should perhaps just shell out directly to `systemctl enable/disable`, Benjamin noted that presets are really just used for defaults on firstboot.

**Comment by bgilbert** [comment]
The officially recommended approach for programmatic enable/disable operations at runtime is to use the [systemd D-Bus API](https://www.freedesktop.org/wiki/Software/systemd/dbus/), but I don't know if that's feasible here.

**Comment by cgwalters** [comment]
> I think I should perhaps just shell out directly to systemctl enable/disable, Benjamin noted that presets are really just used for defaults on firstboot.

Yeah, I think so.  It'd be a lot simpler of a patch too.

**Comment by yuqi-zhang** [comment]
closing in favour of https://github.com/openshift/machine-config-operator/pull/2145

**Pull request closed without merging**
