### PR TITLE
Revert "Start openvswitch and ovsdb-server when network is ovn/ovs"

### PR DESCRIPTION
**Pull request by runcom**
This reverts commit be883a8c6752cbc34bf606b0b3fcab1134b864d2.

This is related to https://github.com/openshift/machine-config-operator/pull/1636

Holding pending @squeed and @mccv1r0 tests

/hold

### CODE REVIEW

**Comment by squeed** [comment]
Filed a quick PR to adopt host openvswitch - https://github.com/openshift/cluster-network-operator/pull/672 - if that merges, we won't need this.

**Comment by vishnoianil** [comment]
@squeed if #672 is gonna take time, we should merge this PR, because most of the gcp-ovn ci jobs seems to be failing because of the original PR of this revert.

**Comment by squeed** [comment]
672 should be good to go; just needs review. It passed enough CI to give me confidence that it's fine.

**Comment by squeed** [comment]
Nevermind, upgrades are failing. Let's revert
/lgtm
:-(

**Comment by dcbw** [comment]
@runcom @eparis I think we just need to green-button this one to unblock our 4.6 CI.

**Comment by ashcrow** [comment]
I am OK with this revert but I do not have green button access.

**Comment by squeed** [comment]
any owner can "/override ci/prow-e2e-gcp-upgrade"

**Comment by ashcrow** [comment]
This may be stuck. According to the tide details link everything is in order ...

**Comment by ashcrow** [comment]
Scratch that: `In Pool - In Batch & Test Pending`

**Comment by ashcrow** [comment]
Since this is causing issues in CI I'm going to override the retests to get CI working again.

**Comment by aravindhp** [comment]
Would it help if the repo had e2e tests run against an OVN cluster too? That way such issues can be caught in the PR itself. The SDN team has also made it easy by adding step registry flows ( [ipi-aws-ovn-hybrid](https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/workflow/ipi-aws-ovn-hybrid), [openshift-e2e-aws-ovn](https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/workflow/openshift-e2e-aws-ovn)) for bringing up an OVN cluster.

**Comment by dcbw** [comment]
Yes, it certainly would help to have a gating test for e2e-aws-ovn at least.

**Comment by vishnoianil** [comment]
> Yes, it certainly would help to have a gating test for e2e-aws-ovn at least.

+1

**Comment by dcbw** [comment]
https://github.com/openshift/release/pull/9767

**Pull request merged**
