### PR TITLE
Bug 2092003: Fixup of URL for AWS unit/file to compute instance provider-id

### PR DESCRIPTION
**Pull request by andreaskaris**
Signed-off-by: Andreas Karis <ak.karis@gmail.com>

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
/approve

Out of curiosity, e2e-aws should have been required for the previous PR, which passed. Does this breakage not affect that? How can this be verified?

Out e2e-gcp-op is also broken but I can go ahead and override that since this is AWS only and is a breaking regression.

**Comment by yuqi-zhang** [comment]
https://prow.ci.openshift.org/pr-history/?org=openshift&repo=machine-config-operator&pr=3162

It did run the mandatory suite of set of tests when the PR first opened (and then commits were updated). Interestingly I don't think it retested before the merge though

**Comment by yuqi-zhang** [comment]
aws-serial is not mandatory in the MCO, no. Only gcp-op (mco internal), e2e-aws (normal e2e) and agnostic-upgrade (upgrade test on azure) are mandatory.

If serial + e2e aws passes here, I am +1 to merging this.

**Comment by yuqi-zhang** [comment]
Let's rebase this on https://github.com/openshift/machine-config-operator/pull/3175 and we can re-run the tests to be sure

**Comment by yuqi-zhang** [comment]
Serial did pass, as did all the required jobs. Is there anything else of concern? Should we run a payload check just to be safe?

**Comment by andreaskaris** [comment]
Sorry to be so ignorant (I'm relatively new), how would we do that?

**Comment by yuqi-zhang** [comment]
Ah sorry! This is something we don't do very often since it's pretty resource intensive. Given that this blocked previous payload promotion, I think this warrants running it to be safe.

/payload 4.11 ci blocking

**Comment by JoelSpeed** [comment]
Been looking at the results of the payload ci jobs, and as far as I can tell this isn't causing a massive issue. They all failed, but none of the jobs seem to have any indication that there's a catastrophic failure such as Nodes not being able to join the cluster. Looks to me like we should merge this

**Review by yuqi-zhang — APPROVED** [review]
Given the 2 payload serial runs appear to have failed on other flaky tests, I think we are good. Deferring to someone else to give the final lgtm when they are ready

**Comment by andreaskaris** [comment]
@JoelSpeed You want to give that lgtm?

**Pull request merged**
