### PR TITLE
MCO-395: daemon: Remove workaround for rpm-ostree bug

### PR DESCRIPTION
**Pull request by cgwalters**
We could have dropped this in 4.13, but it's definitely long since fixed in RHEL9 era rpm-ostree.  Definitely safe to drop in 4.14.

Motivated by simply seeing this in a recent log message.

### CODE REVIEW

**Comment by cgwalters** [comment]
I was reading through some conversation re https://issues.redhat.com/browse/OCPBUGS-11411 and the systemd developers mentioned they thought us invoking `systemctl daemon-reload` during bootup was a bad idea.

So there's extra motivation to drop this code.

**Comment by cgwalters** [comment]
Rebased :surfer: ...I guess this can wait for 4.15 even but, dunno...

**Comment by cgwalters** [comment]
This hypershift error doesn't seem related...but it is passing on some other PRs.  Not sure.
/retest

**Comment by cgwalters** [comment]
Linking this to MCO-395 which is just about tech debt reduction, and this is purely deleting code.
/test e2e-hypershift

**Comment by jkyros** [comment]
Well I was clearly not paying attention this, sorry :( 

I assume there is no new information that would prevent us from putting this in now? 
/remove-lifecycle stale

**Pull request closed without merging**
