### PR TITLE
templates: only add proxy to crio, kubelet and machine-config-daemon-host

### PR DESCRIPTION
**Pull request by runcom**
**- What I did**

Following discussion with @mrunalp we want to enable proxy only for kubelet, crio and machine-config-daemon-host (which manages pivot)

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
/hold

actually, pivot needs to be using this as well and we have a service we can inject envs to

**Comment by runcom** [comment]
> actually, pivot needs to be using this as well and we have a service we can inject envs to. I think all the services we ship in MCD need this override?

added envs for `machine-config-daemon-host` as well

/hold cancel

**Comment by mrunalp** [comment]
:+1:

**Comment by cgwalters** [comment]
I guess it's easier to be conservative to start, though I wonder if at some point we should gain a knob that's just "our whitelisted service" vs "everything".
/lgtm

**Pull request merged**
