### PR TITLE
Tighten the permissions on kubelet.conf

### PR DESCRIPTION
**Pull request by kenneth-dsouza**
According to CIS benchmark guidance 4.1.9, kubelet.conf should only be read/writeable to the owner (600).

**- What I did**
Changed permission of /etc/kubernetes/kubelet.conf to 0600.

**- How to verify it**
`# ls -l /etc/kubernetes/kubelet.conf 
-rw-------. 1 root root 2001 Feb 28 04:54 /etc/kubernetes/kubelet.conf`

**- Description for the changelog**
Tighten the permissions on kubelet.conf. 
According to CIS benchmark guidance 4.1.9, kubelet.conf should only be read/writeable to the owner (600).

### CODE REVIEW

**Review by yuqi-zhang — COMMENTED** [review]
/ok-to-test

There is also a template for the kubelet on master nodes which references 0644 still, that should probably also be updated

cc @rphillips , is this a security concern?

**Comment by kenneth-dsouza** [comment]
> /ok-to-test
> 
> There is also a template for the kubelet on master nodes which references 0644 still, that should probably also be updated
> 
> cc @rphillips , is this a security concern?

Ohh, let me update the PR to change value for master nodes.

**Comment by sinnykumari** [comment]
Can you also create a bug under OCPBUGS project under node/kubelet component and link it to this PR? Any fix usually require a bug/jira card. We will need review from that team on this PR.

**Comment by rphillips** [comment]
I'm not a fan of this.

* CU's might be using this file, rare, but possible
* All born clusters prior to the permission change would never get the permission change
* There is no gain by setting 600 permissions on the file, when the standard had been 644

**Comment by rphillips** [comment]
/close

This is a breaking change. CIS used to have 0644 permissions.

**Pull request closed without merging**
