### PR TITLE
add docker.io registry

### PR DESCRIPTION
**Pull request by rphillips**
Enables docker.io registries

### CODE REVIEW

**Comment by cgwalters** [comment]
I'll just continue my quest against this by commenting here:

https://bugzilla.redhat.com/show_bug.cgi?id=1434897#c7
https://url.corp.redhat.com/walters-registry-equality

**Comment by cgwalters** [comment]
(Why are we overriding the config files shipped in the RPMs anyways?)

**Comment by cgwalters** [comment]
Oh...this is probably because cri-o doesn't search `docker.io` by default right?

If that's breaking *our* code, and we are actually intending to pull containers from docker.io, I think we should *explicitly spell that out* in the configs.

**Comment by rphillips** [comment]
@cgwalters end users of containers usually expect docker pull busybox to pull the docker hub busybox.

**Comment by cgwalters** [comment]
(The question of it affecting *users* is IMO distinct...probably we should have a high level config knob in the installer to affect the registry search order)

> @cgwalters end users of containers usually expect docker pull busybox to pull the docker hub busybox.

Right, but we're not shipping `/usr/bin/docker`.

**Comment by sjenning** [comment]
>  Oh...this is probably because cri-o doesn't search docker.io by default right?
If that's breaking our code, and we are actually intending to pull containers from docker.io, I think we should explicitly spell that out in the configs.

Completely agree and we are working to find all those places.  We know the router, registry, and webconsole currently do not fully qualify there image paths.

Ideally we get to a world where the search list is empty and everyone fully qualifies their image paths.

**Comment by sjenning** [comment]
Backing my claim up https://github.com/coreos-inc/tectonic-operators/pull/463

**Pull request merged**
