### PR TITLE
Bug 1814008: templates/master/00-master/_base/files: remove deprecated etcd assets

### PR DESCRIPTION
**Pull request by hexfusion**
In 4.4+ we moved DR scripts out of MCO. This PR removes those files from MCO managed files that are no longer used and or deprecated.

4.4 Bug 1814010

### CODE REVIEW

**Comment by hexfusion** [comment]
> level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"

Terraform flake

/retest

**Comment by hexfusion** [comment]
/hold cancel

@kikisdeliveryservice @runcom PTAL

**Comment by kikisdeliveryservice** [comment]
@hexfusion is this related to https://github.com/openshift/machine-config-operator/pull/1490

**Comment by hexfusion** [comment]
> @hexfusion is this related to #1490

Well we are now removing #1490 along with the PR. It was thought that we would not be able to get the scripts removed in time for 4.4 but we did and now we need to cleanup our mess.

**Comment by kikisdeliveryservice** [comment]
> > @hexfusion is this related to #1490
> 
> Well we are now removing #1490 along with the PR. It was thought that we would not be able to get the scripts removed in time for 4.4 but we did and now we need to cleanup our mess.

gotcha!  

/approve

**Pull request merged**
