### PR TITLE
etcd-member: exec the etcd binaries

### PR DESCRIPTION
**Pull request by squeed**
Save on the shell, and we want to be sure that termination signals are passed to the etcd process correctly.

Discovered this while looking through etcd connectivity issues. Probably won't fix the problem, but it's good practice regardless.

### CODE REVIEW

**Comment by squeed** [comment]
cc @wking

**Comment by hexfusion** [comment]
/lgtm

thanks, @squeed @wking @mfojtik

**Comment by cgwalters** [comment]
Oh yes.  Missing `exec` calls are a pet peeve of mine.
/approve

**Pull request merged**
