### PR TITLE
Bug 1877071: vSphere - Limit the number of nameservers to 3

### PR DESCRIPTION
**Pull request by cptmorgan-rh**
This prevents the pods from complaining about the nameserver limits being exceeded on vSphere installations.

`Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.1.11.173 10.11.5.19 10.10.160.2`

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
would like vsphere team to take a loot

/hold

**Comment by yuqi-zhang** [comment]
Hi,

Given that the 4.6 deadline is coming up we are going to push this to 4.7 given this is not blocking release. If you believe this blocks a critical functionality, please feel free to move the BZ back to 4.6.

**Comment by sinnykumari** [comment]
lgtm.
This is similar to what we already did for OpenStack and baremetal platform in https://github.com/openshift/machine-config-operator/pull/1674 . Will let vSphere team to do final approval.

**Comment by jcpowermac** [comment]
/hold cancel

Just got a report of this happening in 4.5

**Pull request merged**
