### PR TITLE
Bug 1937594: Respect status.Migration in network.config when exsits

### PR DESCRIPTION
**Pull request by pliurh**
When status.Migration is set in network.config. MCO shall render
the node according to the target networkType.

### CODE REVIEW

**Comment by pliurh** [comment]
This PR need to rebase after MCO adopt the latest openshift/api.

**Comment by kikisdeliveryservice** [comment]
adding a hold until https://github.com/openshift/machine-config-operator/pull/2521 merges

/hold

**Comment by sinnykumari** [comment]
https://github.com/openshift/machine-config-operator/pull/2521 has been merged and this PR needs rebase.

**Comment by danwinship** [comment]
/lgtm
(and the api bump was handled by #2521)

**Comment by pliurh** [comment]
@kikisdeliveryservice Could you unhold this PR?

**Review by sinnykumari — APPROVED** [review]
LGTM
have removed hold since dependent PR has been merged and PR has been rebased

**Pull request merged**
