### PR TITLE
machineconfig: Capitalize FIPS fully

### PR DESCRIPTION
**Pull request by cgwalters**
It's an acronym, so make it follow golang style:
https://github.com/golang/go/wiki/CodeReviewComments#initialisms

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
as requested by @crawford LGTM but will let him give the final approval.

/assign @crawford

**Comment by kikisdeliveryservice** [comment]
@cgwalters can you change the docs here too: https://github.com/openshift/machine-config-operator/blob/ef7308babc5090338b21a63dd7a58e01d6e78c8b/docs/MachineConfiguration.md#machineconfig-definition

**Comment by crawford** [comment]
Looks good, but we are past feature freeze. Let's hold this until we cut the 4.2 branch.

**Comment by cgwalters** [comment]
/hold cancel
since 4.3/master is open now.  Rebased :surfing_man: too.

**Pull request merged**
