### PR TITLE
[release 4.4] Bug 1822268: Add new crio.conf field to the template

### PR DESCRIPTION
**Pull request by umohnani8**
Fixes #1822268 (https://bugzilla.redhat.com/show_bug.cgi?id=1822268)

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

**- What I did**
Add the default_env field to the crio.conf template
that is laid down by the MCO

**- How to verify it**

**- Description for the changelog**

Add default_env filed to the crio.conf template

### CODE REVIEW

**Comment by umohnani8** [comment]
@mrunalp @rphillips @runcom PTAL

**Comment by rphillips** [comment]
/retitle [release 4.4] Bug 1822268: Add new crio.conf field to the template

**Comment by kikisdeliveryservice** [comment]
@umohnani8 has the 4.5 fix merged yet?

**Comment by kikisdeliveryservice** [comment]
is this a backport?

**Comment by kikisdeliveryservice** [comment]
this is backport of https://github.com/openshift/machine-config-operator/pull/1664

**Comment by rphillips** [comment]
@mtrmac https://github.com/cri-o/cri-o/pull/3611 You are correct on the BZ. Dentries are growing with curl liveness calls. The cri-o patch and this patch will prevent the dentries from leaking. Technically, this is a kernel bug, but it is easier to work around with the env fix.

**Comment by mtrmac** [comment]
My primary concern was that the primary bug linked reported something quite different, and at a first glance only seem\ed tangentially related.

If someone returns to this 3 years later, , it should be reasonably possible _and very unambiguous_ what the thinking was.

**Comment by rphillips** [comment]
@mtrmac I updated the bz with a comment, which includes the various crio fixes going in with deferred error handling as well.

https://bugzilla.redhat.com/show_bug.cgi?id=1820507#c9

**Pull request merged**
