### PR TITLE
Add IBM Cloud managed annotations to CVO manifests

### PR DESCRIPTION
**Pull request by csrwng**
This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.

### CODE REVIEW

**Comment by cgwalters** [comment]
https://github.com/csrwng/enhancements/blob/2f2b304ef796adc13726917846ec0a9698a9f1c0/enhancements/update/ibm-public-cloud-support.md
says:

> The CVO needs to skip manifests that instantiate control plane operators, machine API related operators, and others that do not apply to this topology. These include:

...
    machine-config-operator

Yet this annotation seems like it's saying to include the MCO?  Or are we now working on a next phase that adds the MCO?

**Comment by csrwng** [comment]
@cgwalters we're currently not excluding all MCO manifests. The purpose of this PR is to keep parity with what we currently have with the exclude annotation (as in https://github.com/openshift/machine-config-operator/blob/aa54de35827a0971dced06b8de28b24892341917/install/0000_80_machine-config-operator_04_deployment.yaml#L9). None of the manifests that currently have the exclude annotation are getting the new include annotation, if that makes sense.

**Comment by cgwalters** [comment]
> None of the manifests that currently have the exclude annotation are getting the new include annotation, if that makes sense.

Kind of :smile: 
Willing to trust you here, I honestly have trouble wrapping my head around this totally different way to run OpenShift.  Are there any e2es or periodics that cover this?  Is there an easy/documented way to test behavior with this?

/approve
on general principle based on the above.  Will leave a lgtm to someone else.

**Comment by kikisdeliveryservice** [comment]
This will need a rebase.

**Comment by csrwng** [comment]
Thanks @kikisdeliveryservice, rebased

**Comment by kikisdeliveryservice** [comment]
This was fully approved on time but needed a rebase due to another PR merging. Readding lgtm.

/lgtm

**Pull request merged**
