### PR TITLE
Update github.com/containers/image

### PR DESCRIPTION
**Pull request by mtrmac**
**- What I did**

Update github.com/containers/image to remove a lot of the c/storage dependencies added in https://github.com/openshift/machine-config-operator/pull/2689 .

<s>This is vendoring an unreleased version of c/image; a release should happen soon, filing this now so that I don't forget.</s>

**- How to verify it**

Existing CI

**- Description for the changelog**
Removed some dependencies to decrease size of the built binary and compilation time.

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM
Thanks @mtrmac!

**Comment by sinnykumari** [comment]
Thanks for the PR, love that this reduces deps.
Shall we put hold on this PR until c/image gets released with the desired version we want?

**Comment by kikisdeliveryservice** [comment]
> Thanks for the PR, love that this reduces deps.
> Shall we put hold on this PR until c/image gets released with the desired version we want?

Same question as @sinnykumari 

But as a note: this is my favorite type of PR  :heart:

**Comment by mtrmac** [comment]
> > Thanks for the PR, love that this reduces deps.
> > Shall we put hold on this PR until c/image gets released with the desired version we want?
> 
> Same question as @sinnykumari

That’s up to the maintainers of this project :) FWIW a release should happen within a week.

**Comment by sinnykumari** [comment]
Putting hold until we update deps to released c/image
/hold

**Comment by mtrmac** [comment]
/hold cancel

Updated to use released containers/image v5.15.0 now.

**Review by sinnykumari — APPROVED** [review]
sweet :tada:

**Comment by kikisdeliveryservice** [comment]
Do we think there's an issue with this PR wrt to e2e-agnostic-upgrade, bc it seems to be consistnelty failing on the last push to this PR:
https://prow.ci.openshift.org/pr-history/?org=openshift&repo=machine-config-operator&pr=2695

OTOH the test also seems red for the last few days but not enough runs to tell

**Comment by mtrmac** [comment]
> Do we think there's an issue with this PR wrt to e2e-agnostic-upgrade, bc it seems to be consistnelty failing on the last push to this PR:
> https://prow.ci.openshift.org/pr-history/?org=openshift&repo=machine-config-operator&pr=2695

I’m honestly not sure. It is admittedly somewhat suggestive that each of the 5 recently-failing tests seems to be failing somewhat consistently over time, but each differently from the others.

At least the e2e-agnostic-upgrade failures about
```
event happened … times, something is wrong: ns/openshift-machine-api machine/… - reason/Updated Updated machine "…"
```
are likely https://github.com/openshift/cluster-api-provider-azure/pull/227 .

I’ll try to look into the root causes of the other consistent failures tomorrow.

**Comment by mtrmac** [comment]
The e2e-aws-disruptive
```
pods/openshift-insights_insights-operator-59d9d555c7-9k9sg_insights-operator.log.gz:E0730 13:30:37.574968       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
seems to be https://github.com/openshift/insights-operator/pull/484 , though why the API is not available is a different matter.

**Comment by mtrmac** [comment]
pull-ci-openshift-machine-config-operator-master-e2e-aws-techpreview-featuregate
```
fail [github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:113]: Aug  2 20:20:55.119: Some cluster operators are not ready: kube-apiserver (Upgradeable=False FeatureGates_RestrictedFeatureGates_TechPreviewNoUpgrade: FeatureGatesUpgradeable: "TechPreviewNoUpgrade" does not allow updates)
```
is https://github.com/openshift/release/pull/20554 , or whatever happened to it.

**Comment by cgwalters** [comment]
The failures are all known flakes.
/override ci/prow/e2e-agnostic-upgrade

**Pull request merged**
