### PR TITLE
add dynamic kubelet config option and directory

### PR DESCRIPTION
**Pull request by rphillips**
The kubelet manages the directory when it retrieves and sees changes within the dynamic kubelet configmap. [upstream docs](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/)

### CODE REVIEW

**Comment by sjenning** [comment]
i guess this is safe because in the absence of a dynamic config, it just falls back to the normal config right?

**Comment by rphillips** [comment]
correct

**Comment by abhinavdahiya** [comment]
Can you description as to who is going to setup the directory and why are we creating it if we need the contents to start the kubelet itself, and docs to how dynamic-config-dir behaves?

**Comment by rphillips** [comment]
The kubelet manages the directory when it retrieves and sees changes within the dynamic kubelet configmap. [upstream docs](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/)

**Comment by rphillips** [comment]
I could also see it living in /var/lib someplace.

**Comment by abhinavdahiya** [comment]
> I could also see it living in /var/lib someplace.

kubelet already stores its pki assets in `/var/lib/kubelet/pki`, Yeah `/var/lib/kubelet/configs` seems better.

**Comment by rphillips** [comment]
tweaked the dynamic kubelet paths to be /var/lib/kubelet/configs

**Comment by rphillips** [comment]
@abhinavdahiya friendly ping

**Comment by abhinavdahiya** [comment]
cc @aaronlevy

**Comment by aaronlevy** [comment]
Not intending to block, but do have a few concerns:

- While this is effectively a no-op, when the config is distributed via api object - the flags are still used (and override what's in the api-driven config). And if our goal is to get rid of rest of kubelet flags - I'd probably prefer we hold off until we can do both at once (rather than harder to debug merged config from two sources).

- Do we have plans around how we will retain safety when decoupling kubelet version from kubelet configuration? For example, we currently have "api-driven" kubelet configuration via the MCO - which also will couple OS updates (and therefor kubelet version) to new kubelet configuration. With this change, an OS update could cause kubelet to now have incompatible configuration. This may be less of a concern now, but it has definitely bitten us in the (tectonic) past.

**Comment by sjenning** [comment]
@aaronlevy I assume you put "api-driven" in quotes because the `kubelet.service` files for master and workers are really baked into the MCO at build time.  So... not *really* api-driven.

There will need to be some period of overlap.

In my mind the steps are

- set dyn kubelet config dir (this PR)
- get config controller integrated into the installer with a config map that matches the kubelets flag the MCO is serving up
- remove the redundant flags from the MCO `kubelet.service`

That sound reasonable?

**Comment by aaronlevy** [comment]
That's fine.

I mean api-driven (in quotes) because we technically control kubelet configuration via the API. If we deploy a new MCO with new kubelet configuration, it will roll that configuration out to nodes. Dynamic kubelet configuration is more or less a different way of doing the same thing.

Still have the same concern about decoupled kubelet config from kubelet version, however. Either we're confident that kubelet configuration never breaks between versions (at minimum we have deprecated flags), and/or we have some plans for how we enforce some kind of tight coupling between config operator and OS updates.

**Comment by rphillips** [comment]
Closing in favor of the MCO handling kubelet configuration.

**Pull request closed without merging**
