### PR TITLE
templates: Don't hardcode /usr/local/bin for etcd

### PR DESCRIPTION
**Pull request by cgwalters**
The image we're trying to switch to has it in `/usr/bin`, let's
just search `$PATH`.

Ref: https://github.com/openshift/installer/pull/1194

### CODE REVIEW

**Comment by ashcrow** [comment]
:boom::robot::boom:
:cloud::fire::cloud:

**Comment by runcom** [comment]
just wondering and brainstorming, we can take this on Slack if you want, but how do we make sure we don't regress on similar drifts (https://github.com/openshift/installer/pull/1194)? is this on the installer or on mco? how's the installer testing changes in the MCO (or does it use the latest published images)? do we need to start having a job which runs the latest available installer with the very latest mco code to make sure we don't drift? and viceversa? (spending my morning figuring this out also)

**Comment by cgwalters** [comment]
(Can people add approve and lgtm here?  Prow missed it earlier)

> do we need to start having a job which runs the latest available installer with the very latest mco code

That's what e2e-aws does; it runs master installer against the code from the PR.

What we need to do is start gating on degraded: https://github.com/openshift/machine-config-operator/issues/383

The original PR here sailed right through because we didn't have that.

**Pull request merged**
