### PR TITLE
[release-4.15] CORS-3169: Add support for in-cluster DNS on Cloud Platforms when cloud DNS cannot be used

### PR DESCRIPTION
**Pull request by sadasu**
* Bringing in the latest updates from openshift/api 
* Manual backport of https://github.com/openshift/machine-config-operator/pull/4018
* This feature behind the `TechPreviewNoUpgrade` feature gate in 4.15.

### CODE REVIEW

**Comment by sadasu** [comment]
@cybertron , @mkowalski Could you pls take a look?

**Comment by mkowalski** [comment]
LGTM from the On-Prem team fot the code itself.

Approval has to come from someone higher in the rank as this is a backport that touches CRDs and AFAIK something that should not happen but if API and/or Staff Engineering agrees, go ahead.

Implementation looks okay but decision to merge or not is outside of my grade

cc @JoelSpeed

**Comment by JoelSpeed** [comment]
API wise we've already had the discussion about backport, but this should still have a staff eng approval given it does change the API and adds a new feature

**Comment by cybertron** [comment]
/lgtm
/label backport-risk-assessed

According to the discussions I've had around this it's been agreed to backport this.

**Comment by sdodson** [comment]
/label approved
I'm approving this backport while the feature is still behind TechPreviewNoUpgrade featuregate. We will require QE to finish their validation and CI testing to confirm that this new feature meets or exceeds 90% pass rate before moving it to on by default. This is not an assertion that this feature will be on by default in 4.15 GA or any time thereafter, that remains to be decided.

**Pull request merged**
