### PR TITLE
[fcos] Add vrutkovs to OWNERS

### PR DESCRIPTION
**Pull request by vrutkovs**
Adding myself to OWNERS list in `fcos` branch only to speed up development

### CODE REVIEW

**Comment by vrutkovs** [comment]
@runcom e2e tests don't pass yet, could you override the test results?

**Comment by runcom** [comment]
I doubt I can, but trying

/override

**Comment by vrutkovs** [comment]
```
/override ci/prow/build-rpms-from-tar
/override ci/prow/e2e-aws
```

**Pull request merged**
