### PR TITLE
Cleanup BM owner aliases

### PR DESCRIPTION
**Pull request by creydr**
**- What I did**
* Removed @yboaron and myself (@creydr) from the bare metal approvers & reviewers list
* Added @dougsland as a bare metal reviewer & approver

**- How to verify it**
Check OWNERS_ALIASES file

/hold
until I fully disengaged from the BM networking team

### CODE REVIEW

**Review by dougsland — APPROVED** [review]

**Comment by cybertron** [comment]
/lgtm

We should probably trim the reviewer list a bit more too. I'm pretty sure Toni and Steve are not going to be regularly reviewing patches anymore. We can leave them on the approver list, but they shouldn't be auto-assigned as reviewers.

**Comment by sinnykumari** [comment]
LGM since this change has been reviewed by baremetal team
Thanks @creydr for all the contribution to the MCO repo!
/approve

**Pull request merged**
