### PR TITLE
OCPNODE-1501: add protectKernelDefaults to kubelet config

### PR DESCRIPTION
**Pull request by rphillips**
**- What I did**
Enables protectKernelDefaults by default.

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by sairameshv — APPROVED** [review]
LGTM

**Comment by vrutkovs** [comment]
This breaks OKD:
```
Feb 22 00:55:29 ip-10-0-130-89 kubenswrapper[10917]: I0222 00:55:29.556090   10917 state_mem.go:35] "Initializing new in-memory state store"
Feb 22 00:55:29 ip-10-0-130-89 kubenswrapper[10917]: E0222 00:55:29.557737   10917 kubelet.go:1479] "Failed to start ContainerManager" err="[invalid kernel flag: kernel/panic, expected value: 10, actual value: 0, invalid kernel flag: kernel/panic_on_oops, expected value: 1, actual value: 0, invalid kernel flag: vm/overcommit_memory, expected value: 1, actual value: 0]"
Feb 22 00:55:29 ip-10-0-130-89 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 00:55:29 ip-10-0-130-89 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

Do we need to set some kernel args?

**Comment by rphillips** [comment]
@vrutkovs https://github.com/openshift/kubernetes/pull/1475 merged to add the default sysctls to the rpm.

**Comment by vrutkovs** [comment]
Thanks! https://github.com/openshift/okd-machine-os/pull/533 should fix OKD's machine-os-content

**Pull request merged**
