### PR TITLE
Bug 1741608: logs are flooded with "failed to get pod stats: failed to get imageFs info: non-existent label "crio-images"" messages

### PR DESCRIPTION
**Pull request by RobertKrawitz**
Fixes: 1741608

Cherrypick of #772

### CODE REVIEW

**Comment by runcom** [comment]
ok figured
you need to use go-bindata from the old(pre-fork) repo
cause that's what we're sticking with in 4.1
```
$ go get -u github.com/jteeuwen/go-bindata/...  
$ make update
```
the diff should be empty actually, so you might as well just remove the make update step from commit

**Comment by jwforres** [comment]
this is missing the approved and lgtm labels, please try to get this PR fixed up so it can go into the next merge window

/test verify

**Pull request merged**
