### PR TITLE
MCO-790: Set up leader election in machine-os-builder

### PR DESCRIPTION
**Pull request by inesqyx**
- What I did

Mimicking the way that leader election is setup in machine config controller and machine config operator, we set up leader election in MOB as well. Doing so will ensure that only one single Machine OS Builder pod would be running at any given time.

- How to verify it

1. Deploy an OpenShift cluster.
2. Opt into on-cluster builds.
3. Retrieve the logs for the Machine OS Builder pod and verify that it pauses for leader election and eventually starts.
4. Delete the pod and wait for the Deployment to start a replacement pod.
5. Retrieve the replacement pod logs and verify that it pauses for leader election and eventually starts.

### CODE REVIEW

**Comment by sergiordlr** [comment]
When we configure a new imageBuilderType the machine-os-builder pod is restarted, but it does not release the lease, so when the new machine-os-builder pod starts it cannot get the lease and reports a failure with this message

```
$ oc logs machine-os-builder-fb856c6f4-nvrvf 
I0415 15:59:33.756112       1 start.go:89] Options parsed: {kubeconfig:}
I0415 15:59:33.756133       1 start.go:92] Version: machine-config-daemon-4.6.0-202006240615.p0-2682-g200c5f24-dirty (200c5f24043dee744f5b1680eb09cffcaa7d7a8f)
I0415 15:59:33.756143       1 builder.go:93] Using in-cluster kube client config
I0415 15:59:33.756369       1 leaderelection.go:122] The leader election gives 4 retries and allows for 30s of clock skew. The kube-apiserver downtime tolerance is 78s. Worst non-graceful lease acquisition is 2m43s. Worst graceful lease acquisition is {26s}.
I0415 15:59:33.770262       1 leaderelection.go:250] attempting to acquire leader lease openshift-machine-config-operator/machine-os-builder...
I0415 15:59:33.775174       1 leaderelection.go:354] lock is held by machine-os-builder-fb856c6f4-nvrvf_42ca8477-a939-4883-89f4-643b5dcfa7b0 and has not yet expired
I0415 15:59:33.775195       1 leaderelection.go:255] failed to acquire lease openshift-machine-config-operator/machine-os-builder

```

It fails for 2 minutes and a half and then takes the lease ungracefully. 

To reproduce it just enable the on-cluster-build functionality and reconfigure the imageBuildertType with this command, for example:


`$  oc patch cm/on-cluster-build-config -n openshift-machine-config-operator -p '{"data":{"imageBuilderType": "custom-pod-builder"}}`

Since imageBuilderType configuration is a controlled situation, the lease should be released and acquired gracefully, shouldn't it?

**Comment by sergiordlr** [comment]
With the new MachineOsCOnfig resource there is only one image builder type, hence the ticket that we opened regarding this PR no longer applies. 

We add the qe-approved label.

/label qe-approved

**Comment by inesqyx** [comment]
Close the PR, merged in https://github.com/openshift/machine-config-operator/pull/4327

**Pull request closed without merging**
