### PR TITLE
[Baremetal] Haproxy add support for IPv6 frontend

### PR DESCRIPTION
**Pull request by yboaron**
**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
/hold

since freeze

**Comment by kikisdeliveryservice** [comment]
this can now merge into master.

/hold cancel

**Comment by kikisdeliveryservice** [comment]
actually i see an issue here
/hold

**Comment by yboaron** [comment]
@kikisdeliveryservice,  Ooops, sorry about that.  I updated the commit's author.

**Comment by sinnykumari** [comment]
/lgtm

Commit author seems to have been fixed. Will let Kirsten do final check and lift hold.

**Pull request merged**
