### PR TITLE
Bug 1990012: Update controller config openapi schema

### PR DESCRIPTION
**Pull request by JoelSpeed**
**- What I did**

I used controller-gen to regenerate the openAPIV3Schema section of this CRD.
This means that it is now up to date and includes all of the latest fields from the objects that are embedded within it.

**- How to verify it**
Find a field such as `.spec.infra.status.platformStatus.azure.cloudName` which is not currently present in the CRD schema. Observe how this exists in the `infrastructure` resource, but does not exist in the embedded infra in the `controllerconfig` in clusters today. Try to add this field into the `controllerconfig`, it will be silently dropped by the API server.
Upgrade to this patch, observe how the field now exists and is copied from the main `infrastructure` resource.

**- Description for the changelog**

Update OpenAPI schema for `controllerconfig` CRD

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Sinny has been looking at moving our API to openshift/api, so looping her in to take a look.

Could you also provide some steps you used to generate this? I tried some time ago to use the generator and wasn't fully successful, and I think recently Sinny also had to do some manual steps to update this.

**Comment by JoelSpeed** [comment]
Sure, we have a script that runs this for us in MAO, so I originally started by copying that and trying to make it work for your project as I noticed you don't have a script for doing it.

The problem I reached was that your machineconfig has a raw extension, currently you have a schema defined within this even though it's not needed, so there's a large diff on the CR, everything else is pretty much ok and as normal

You can see the progress I made here https://github.com/JoelSpeed/machine-config-operator/commit/8769284800b01e8bdd508b48289ca5821413a967

Theres a few changes I had to make in `pkg/apis` that you may want to take note of, in particular the `groupName` comment is required to get controller-gen to do anything at all :)

**Comment by patrickdillon** [comment]
/test e2e-azure

@lobziik built a release image built with this patch. It resolves issues for joining worker nodes in Azure Stack UPI.

**Comment by JoelSpeed** [comment]
/test e2e-agnostic-upgrade

Is there anything more we need to do for this?

**Review by yuqi-zhang — APPROVED** [review]
Upgrade test failures seem unrelated to this PR. Generally lgtm, will give others a chance to take a last look if any concerns.

**Comment by sinnykumari** [comment]
Thanks Joel for catching this issue and opening up PR! 
As Jerry said, so far we have been updating our CRDs manually and we missed these changes as it wasn't directly MCO needed so far.

> You can see the progress I made here [JoelSpeed@8769284](https://github.com/JoelSpeed/machine-config-operator/commit/8769284800b01e8bdd508b48289ca5821413a967)
 
> Theres a few changes I had to make in `pkg/apis` that you may want to take note of, in particular the `groupName` comment is required to get controller-gen to do anything at all :)

+1, hopefully we will not have these issues once we finish our work to move MCO API to openshift/api

/lgtm

**Pull request merged**
