### PR TITLE
Update library-go to set OpenStack provider to external

### PR DESCRIPTION
**Pull request by JoelSpeed**
This PR bumps the openshift library go dependency to include https://github.com/openshift/library-go/pull/1383.

This will mean that OpenStack is always set to external and will force the migration from in-tree to out-of-tree for OpenStack.

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
/retest

generally looks fine, seems to be some container failures in the test suite, presumably not related?

**Comment by yuqi-zhang** [comment]
er, no

```
Building github.com/openshift/machine-config-operator/cmd/machine-config-daemon (machine-config-daemon-4.6.0-202006240615.p0-1565-gaa2411be-dirty, aa2411be8b779c280e7cf2e27956b7a7b43fbdb1) for linux/amd64
# k8s.io/client-go/applyconfigurations/meta/v1
vendor/k8s.io/client-go/applyconfigurations/meta/v1/unstructured.go:64:38: cannot use doc (variable of type *"github.com/googleapis/gnostic/openapiv2".Document) as type *"github.com/google/gnostic/openapiv2".Document in argument to proto.NewOpenAPIData
make: *** [Makefile:39: _build-machine-config-daemon] Error 2
error: build error: error building at STEP "RUN make install DESTDIR=./instroot && tar -C instroot -cf instroot.tar .": error while running runtime: exit status 2
```

**Comment by JoelSpeed** [comment]
> er, no
> 
> ```
> Building github.com/openshift/machine-config-operator/cmd/machine-config-daemon (machine-config-daemon-4.6.0-202006240615.p0-1565-gaa2411be-dirty, aa2411be8b779c280e7cf2e27956b7a7b43fbdb1) for linux/amd64
> # k8s.io/client-go/applyconfigurations/meta/v1
> vendor/k8s.io/client-go/applyconfigurations/meta/v1/unstructured.go:64:38: cannot use doc (variable of type *"github.com/googleapis/gnostic/openapiv2".Document) as type *"github.com/google/gnostic/openapiv2".Document in argument to proto.NewOpenAPIData
> make: *** [Makefile:39: _build-machine-config-daemon] Error 2
> error: build error: error building at STEP "RUN make install DESTDIR=./instroot && tar -C instroot -cf instroot.tar .": error while running runtime: exit status 2
> ```

Oops, I'll take a look at this now

**Comment by JoelSpeed** [comment]
> This overlaps with #3252 which has some prep work already split out in #3251

Thanks for pointing that out, I've just spent a few minutes getting things to build. I think we are getting a similar result looking at the resulting go mods.

I've had to migrate the resource lock that you are using to a `ConfigMapsLeases` resource lock which migrates users from configmaps over to leases as part of a deprecation cycle. Kept that as a separate commit for review.

I'll review your changes and double check what's left to do

**Comment by yuqi-zhang** [comment]
Latest failure shows
```
hack/../pkg is out of date. Please run make update
```
+ some test failures


Are we good to merge https://github.com/openshift/machine-config-operator/pull/3251 first? It should be a subset now (on a slightly older version for some packages)

**Comment by JoelSpeed** [comment]
Yep, something came up so I didn't get to finish this today. If you merge the other PR first I can rebase and fix the rest in the morning

**Comment by yuqi-zhang** [comment]
Ok thanks, let me review the other PR and try to get it in

**Comment by MaysaMacedo** [comment]
@JoelSpeed It seems it's just missing a `make update` now?

**Comment by JoelSpeed** [comment]
All the tests seem to be good now, lets see how the E2E goes

**Comment by MaysaMacedo** [comment]
I see the following in the machine config controller logs:

```
2022-07-28T18:21:57.275897107Z E0728 18:21:57.275869       1 leaderelection.go:334] error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-controller" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "openshift-machine-config-operator"
2022-07-28T18:22:33.666472558Z E0728 18:22:33.666145       1 leaderelection.go:330] error retrieving resource lock openshift-machine-config-operator/machine-config-controller: leases.coordination.k8s.io "machine-config-controller" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-controller" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "openshift-machine-config-operator"
```

Seems some permissions are missing?

**Comment by JoelSpeed** [comment]
> Seems some permissions are missing?

Yep, I think I've got that sorted in the latest commit

**Review by sinnykumari — APPROVED** [review]
Overall LGTM

**Comment by MaysaMacedo** [comment]
It LGTM. [The installation and e2e test](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-openstack/1554416303089913856), finalized fine.

**Comment by sinnykumari** [comment]
Thanks Maysa for testing!
/lgtm

**Pull request merged**
