### PR TITLE
[release-4.10] Bug 2087021: Fix file path having spaces for basename command

### PR DESCRIPTION
**Pull request by pperiyasamy**
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>

### CODE REVIEW

**Review by flavio-fernandes — COMMENTED** [review]
/lgtm

**Comment by yuqi-zhang** [comment]
The bugzilla bot system is designed such that you need to first fix in the latest version and then backport.

I see that in 4.11 https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/files/configure-ovs-network.yaml#L22 has already fixed this, so you have two options:

1. create a dummy 4.11 bug, move to fixed immediately and explain that it was fixed via a previous patch, and then link the 4.10 bug
2. try to override the bot (I'm not sure who has the perms to do this)

**Comment by yuqi-zhang** [comment]
Does this get superceded by https://github.com/openshift/machine-config-operator/pull/3159?

**Comment by yuqi-zhang** [comment]
Does this get superceded by https://github.com/openshift/machine-config-operator/pull/3159?

**Comment by pperiyasamy** [comment]
> Does this get superceded by #3159?

yes, #3159 would fix this problem too, closing without merging it.

**Pull request closed without merging**
