### PR TITLE
OCPBUGS-27799: Restrict using CoreDNS from outside of the node

### PR DESCRIPTION
**Pull request by kevydotvinu**
**- What I did**
- Use allow plugin

Fixes: OCPBUGS-27799

**- How to verify it**

```
nslookup <URL> <node-ip>
```

**- Description for the changelog**

- Add allow plugin

### CODE REVIEW

**Comment by cybertron** [comment]
Why is this necessary? Some of these records are deliberately provided to external clients in the interest of allowing deployments without any modification to external DNS servers. We need a pretty good reason to break that.

**Comment by mkowalski** [comment]
/hold

This is just wrong. It must never be merged. Please talk with on-prem net team for details

**Comment by cybertron** [comment]
Sorry for not responding earlier. I seem to have lost track of this.

> Hello @cybertron, thank you for your update. In that case is it a good idea to open the `forward` for the cluster domain at least and block the other hosts? Otherwise, any host can resolve any URL using the cluster nodes.

Any host has to be able to resolve any URL. The way it works is that the deployer points their deployment node (which may be their laptop) at one of the nodes as its first DNS server. Until the cluster comes up, it will fall back to the secondary servers in resolv.conf, but once the node is available it must be able to resolve all names normally because it will use the node DNS as _the_ DNS server. If we restricted it then all public DNS queries from the deployment machine would fail.

**Pull request closed without merging**
