### PR TITLE
OCPBUGS-630: controller: default overwrite to true for files

### PR DESCRIPTION
**Pull request by yuqi-zhang**
When rendering the final rendered-MC, add a default overwrite: true if
not provided by the user.

The MCO always overwrites files on disk, but Ignition does not. This can
cause a user-supplied MC with no default to fail spinning up new nodes,
since MCO would overwrite anything on the host for existing nodes, but
new nodes would not allow the overwrite if the file was already on the
base filesystem.

To verify this, you can provide any user-created MC with a files entry with no default ovewrite. With this change, it will render into a overwrite:true. Without this, we have no overwrite specified (which for ignition, defaults to false)

### CODE REVIEW

**Comment by sinnykumari** [comment]
make sense. Thanks Jerry!
Do we also need to update doc somewhere?
/lgtm
/approve
Putting hold for qe-approved label
/hold

**Comment by yuqi-zhang** [comment]
> Do we also need to update doc somewhere?

I don't think so. This is already implicitly the behaviour in the MCO, and I don't think most users were hitting it anyways since we didn't get that many bug reports for this. I can add a doc note on the BZ during release time.

We could add an additional note to have users set `overwrite: true` if they wish to create a MC, but at that point, we may as well force it in the MCO (always overwrite: true and reject any overwrite: false user MCs)

But, I don't think we need to be that aggressive since I have not yet seen any use case where overwrite: false is actually used.

**Comment by sinnykumari** [comment]
thanks Jerry, makes sense.

**Comment by sergiordlr** [comment]
Verified using IPI on AWS.

Steps:

1. Extract the current sshd_config file content in the worker nodes
```
$oc debug/NODE -- chroot /host cat /etc/ssh/sshd_config

```
2. Create a MC in order to deploy this same content, but adding a comment (for example "# MODIFIED FOR TESTING PURPOSES"). No "overWrite" attribute should be present in the MC.

```
 apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: new-sshd
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,IyMj.......
        filesystem: root
        mode: 420
        path: /etc/ssh/sshd_config
```



3. Make sure that the rendered machine config specifies that overWrite=true attribute

```
$ oc get mc -o yaml rendered-worker-bfe71eb2121e2fe16fe581426b1102d4 |grep sshd  -A2 -B2
        mode: 420
        overwrite: true            <<----- this attribute was added
        path: /etc/ssh/sshd_config
    systemd:
      units:

```
4. Check that the MC was deployed without errors:
```
$ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-752cd1b661753710b9eb27145fdd23f8   True      False      False      3              3                   3                     0                      32m
worker   rendered-worker-bfe71eb2121e2fe16fe581426b1102d4   True      False      False      2              2                   2                     0                      32m

$ oc debug node/ip-10-0-173-118.ec2.internal -- chroot /host cat /etc/ssh/sshd_config |grep -i test
Starting pod/ip-10-0-173-118ec2internal-debug ...
To use host binaries, run `chroot /host`
# MODIFIED FOR TESTING PURPOSES  <<<---- we can see the modification

Removing debug pod ...


```


4. Scale up the worker nodes creating one extra instance

```
$ oc get machineset -n openshift-machine-api
NAME                                          DESIRED   CURRENT   READY   AVAILABLE   AGE
ci-ln-ql9gwqb-76ef8-vbfdr-worker-us-east-1a   1         1         1       1           41m
ci-ln-ql9gwqb-76ef8-vbfdr-worker-us-east-1f   1         1         1       1           41m


$ oc -n openshift-machine-api scale machineset ci-ln-ql9gwqb-76ef8-vbfdr-worker-us-east-1f --replicas 2
```

5. Verify that the new node was created and added withtout problems

```
$ oc get machineset
NAME                                          DESIRED   CURRENT   READY   AVAILABLE   AGE
ci-ln-ql9gwqb-76ef8-vbfdr-worker-us-east-1a   1         1         1       1           54m
ci-ln-ql9gwqb-76ef8-vbfdr-worker-us-east-1f   2         2         2       2           54m

```

We add the qe-approved label

/label qe-approved


NOTE: Notice that if we specify "overWrite: false" in our MC instead of just omitting it, the rendered MC will use "overWrite: false" too and an error will happen in new nodes because sshd_config file already exists.

**Comment by yuqi-zhang** [comment]
/hold cancel

Thanks everyone!

**Comment by yuqi-zhang** [comment]
/test e2e-aws-ovn-upgrade

looks like a flake since there was a previous passing test, going to try again

**Comment by yuqi-zhang** [comment]
/test e2e-gcp-op

install flake

**Comment by yuqi-zhang** [comment]
will aim to backport 1 release for now

/cherry-pick release-4.12

**Pull request merged**
