### PR TITLE
[OCPNODE-709] add control-plane label

### PR DESCRIPTION
**Pull request by rphillips**
Add control plane label to master nodes.

[OCPNODE-709](https://issues.redhat.com/browse/OCPNODE-709)

### CODE REVIEW

**Comment by cgwalters** [comment]
> Add control plane label to master and worker nodes.

I think you mean "Add control plane label where we have master label"?

**Comment by rphillips** [comment]
/hold

this PR needs the kubelet PR https://github.com/openshift/kubernetes/pull/957

**Comment by rphillips** [comment]
/hold

rhcos is not building for 4.10 yet.

**Comment by rphillips** [comment]
/hold cancel

4.10 cluster installed correctly.

**Comment by cgwalters** [comment]
(I don't follow upstream kube much, I should but...) a question I didn't see answered here in the PR or the ticket: is this happening in upstream kube at all?  Or are we leading by example?  The latter is fine by me but if there's not an effort there I would hope we start one.

**Comment by rphillips** [comment]
We are not necessarily leading the change here. Upstream has already implemented this in kubeadm [[PR](https://github.com/kubernetes/kubernetes/pull/95382)]. It is my understanding that upstream controllers will eventually migrate to the control-plane label.

**Comment by yuqi-zhang** [comment]
Just a quick question: I remember there being a canonical list of accepted role labels that the kubelet can bootstrap with in OCP, and that was (at least in part) preventing booting into custom pools.

Do you know if that list still exists and whether the above still holds?

**Pull request closed without merging**
