### PR TITLE
OCPBUGS-16888: daemon: Make binary writing idempotent

### PR DESCRIPTION
**Pull request by sinnykumari**
Also. revert of PR https://github.com/openshift/machine-config-operator/pull/3824

### CODE REVIEW

**Comment by sinnykumari** [comment]
Since, https://github.com/openshift/machine-config-operator/pull/3824 is most likely going to break node scale-up. If we have appetite to merge this, we can merge in favor of fixing things and let qe perform testing. cc @cgwalters @yuqi-zhang @jupierce 

@sergiordlr mentioned that we can't verify PR for RHEL worker node, it can happen with nightly build.

**Comment by sinnykumari** [comment]
> Since, #3824 is most likely going to break node scale-up. 
nvm, it shouldn't break anything today.

**Comment by sinnykumari** [comment]
e2e-gcp-op test failure looks unrelated to PR change.
/test e2e-gcp-op

**Comment by sinnykumari** [comment]
Launched a cluster built with this PR via clusterbot, node scale-up works fine with 4.2 bootimage. MCD log looks good. Don't see any regression as a result of this PR. So, should be safe to go in.

**Comment by jupierce** [comment]
CI seems slow to react here. Merging by hand.

**Pull request merged**
