### PR TITLE
pkg/daemon: allow skip reboot in onceFrom MCD

### PR DESCRIPTION
**Pull request by runcom**
This patch introduces a new --skip-reboot flag (defaulting to false) and
only honored in onceFrom mode (e.g. dn.onceFrom != ""). This is a
requirement for BYOH team and the Ansible integration.

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
> /lgtm

putting an hold just til BYOH team reports back that this does work (I'll lift the hold and lgtm should still apply)

/hold

**Comment by runcom** [comment]
> New changes are detected. LGTM label has been removed.

repushed for BYOH team tests

**Comment by mtnbikenc** [comment]
BYOH scaleup tested successfully.  Nice task output and Ansible was able to control the reboot.
Tested with https://github.com/openshift/openshift-ansible/pull/11493
```
    I0415 14:19:16.300487       1 start.go:56] Version: 4.0.0-alpha.0-194-g1d6c0e6b-dirty
    I0415 14:19:16.300988       1 start.go:89] Starting node writer
    I0415 14:19:16.301020       1 start.go:96] Cannot initialize ClientBuilder, likely in onceFrom mode with Ignition
    I0415 14:19:16.301073       1 start.go:178] Calling chroot("/rootfs")
    I0415 14:19:16.301085       1 start.go:188] Starting MachineConfigDaemon
    I0415 14:19:16.301098       1 daemon.go:479] Enabling Kubelet Healthz Monitor
    I0415 14:19:16.398879       1 update.go:601] Writing file "/etc/tmpfiles.d/cleanup-cni.conf"
    I0415 14:19:16.401559       1 update.go:601] Writing file "/etc/systemd/system.conf.d/kubelet-cgroups.conf"
    I0415 14:19:16.403296       1 update.go:601] Writing file "/var/lib/kubelet/config.json"
    I0415 14:19:16.405363       1 update.go:601] Writing file "/etc/kubernetes/ca.crt"
    I0415 14:19:16.407071       1 update.go:601] Writing file "/etc/sysctl.d/forward.conf"
    I0415 14:19:16.408463       1 update.go:601] Writing file "/etc/kubernetes/kubelet-plugins/volume/exec/.dummy"
    I0415 14:19:16.409409       1 update.go:601] Writing file "/etc/containers/registries.conf"
    I0415 14:19:16.411022       1 update.go:601] Writing file "/etc/containers/storage.conf"
    I0415 14:19:16.412588       1 update.go:601] Writing file "/etc/crio/crio.conf"
    I0415 14:19:16.414724       1 update.go:601] Writing file "/etc/kubernetes/kubelet.conf"
    I0415 14:19:16.416132       1 update.go:601] Writing file "/etc/machine-config-daemon/node-annotations.json"
    I0415 14:19:16.417727       1 update.go:601] Writing file "/etc/pivot/image-pullspec"
    I0415 14:19:16.419228       1 update.go:601] Writing file "/etc/kubernetes/kubeconfig"
    I0415 14:19:16.420967       1 update.go:538] Writing systemd unit "kubelet.service"
    I0415 14:19:16.422581       1 update.go:573] Enabling systemd unit "kubelet.service"
    I0415 14:19:16.422697       1 update.go:500] Enabled kubelet.service
    I0415 14:19:16.422707       1 update.go:538] Writing systemd unit "mcd-write-pivot-reboot.service"
    I0415 14:19:16.424116       1 update.go:573] Enabling systemd unit "mcd-write-pivot-reboot.service"
    I0415 14:19:16.424168       1 update.go:500] Enabled mcd-write-pivot-reboot.service
    I0415 14:19:16.424450       1 update.go:720] machine-config-daemon initiating reboot: runOnceFromIgnition complete
    I0415 14:19:16.427705       1 update.go:766] MCD is not rebooting in onceFrom with --skip-reboot
    I0415 14:19:16.427724       1 start.go:194] Shutting down MachineConfigDaemon
```

**Pull request merged**
