### PR TITLE
OCPBUGS-4605: [on-prem] Have keepalived check for haproxy status for API VIP

### PR DESCRIPTION
**Pull request by mandre**
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3339 and https://github.com/openshift/machine-config-operator/pull/3416 to release-4.11.

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Seems like a fine cherry-pick, is there some way we can verify functionality?

**Comment by mandre** [comment]
@cybertron we'd like to backport the keepalived healthcheck change to 4.10. Could you PTAL?

**Pull request closed without merging**
