### PR TITLE
OCPBUGS-15575: Dockerfile: pin to nmstate-2.2.9

### PR DESCRIPTION
**Pull request by yuqi-zhang**
nmstate build was updated in https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=71688

further work in https://github.com/openshift/machine-config-operator/pull/3720

4.14 version of https://github.com/openshift/machine-config-operator/pull/3764

### CODE REVIEW

**Comment by djoshy** [comment]
/lgtm 
Thanks, Jerry!

... And now we wait (:

**Comment by yuqi-zhang** [comment]
This shouldn't require pre-merge testing, since this shouldn't cause any behaviour change.

We can verify this via successful CI/nightly builds

**Comment by yuqi-zhang** [comment]
/override ci/prow/e2e-hypershift

This doesn't affect Hypershift directly.

**Comment by sinnykumari** [comment]
wait, looks like this PR got merged with okd-images test failing. This test used to be a required one, need to look what has changed

**Comment by cgwalters** [comment]
I think that was likely just due to a flake/failure in registry.access.redhat.com that hopefully got fixed.

**Comment by sinnykumari** [comment]
yeah, it was a flake. I was more wondering about test becoming optional

**Pull request merged**
