### PR TITLE
set cpu request and remove limits on pods

### PR DESCRIPTION
**Pull request by sjenning**
@smarterclayton 

UPDATE: include all pods and operators in this repo

### CODE REVIEW

**Comment by ashcrow** [comment]
"Generic build failure"

:confused:

**Comment by smarterclayton** [comment]
Seth is going to doc and send out an email.  Actually, we might want to create a CVO doc for this or something (someplace we can answer the question and point people to) - in docs/devel in CVO repo

**Comment by smarterclayton** [comment]
this is likely one of the major reasons e2e dies

**Comment by ashcrow** [comment]
```
connect: connection refused
```

/retest

**Comment by sjenning** [comment]
this should also fix these alert
alerts

**Pull request merged**
