### PR TITLE
OCPBUGS-15583: Revert "Revert "fix nodeStatusUpdateFrequency""

### PR DESCRIPTION
**Pull request by cdoern**
**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by cdoern** [comment]
/payload periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by cdoern** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade 10

**Comment by yuqi-zhang** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade 10

although I am not sure if this is expected to pass... it is 4.13->4.14 and this is 4.15 (but hopefully the diff is small enough right now)

**Comment by cdoern** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-gcp-ovn-rt-upgrade 10

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

Given that this has passed payload testing I think we're good to go

**Pull request merged**
