### PR TITLE
Bug 1826211: drop python usage for node-ip functionality

### PR DESCRIPTION
**Pull request by celebdor**
Recently the non_virtual_ip and nodeip-finder functionality was
implemented in golang on the baremetal-runtimecfg repository. This
commit changes the baremetal and the openstack platforms to use the
golang implementation via podman, so we do not block rhcos dropping
platform-python.

If baremetal IPI clusters, it means it works. This obsoletes https://github.com/openshift/machine-config-operator/pull/1564 but needs https://github.com/openshift/baremetal-runtimecfg/pull/57 to merge first

### CODE REVIEW

**Comment by celebdor** [comment]
verified to work on both masters and workers.

**Comment by celebdor** [comment]
https://github.com/openshift/baremetal-runtimecfg/pull/57 merged

**Comment by cybertron** [comment]
/lgtm

Just fixed an incorrect reference in the OpenStack templates.

**Comment by celebdor** [comment]
/retitle Bug 1826211: drop python usage for node-ip functionality

**Pull request merged**
