### PR TITLE
OCPBUGS-4039: NM resolve prepender: remove extra quotes in OKD flow

### PR DESCRIPTION
**Pull request by vrutkovs**
Fix bash script syntax to make OKD branch pass as correctly.

Bug was introduced in #3394

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
@cybertron or @jcaamano would either of you be able to take a look at this one?

**Comment by vrutkovs** [comment]
/cc @cgwalters @sinnykumari 
for approval

**Comment by sinnykumari** [comment]
@vrutkovs okd-e2e-vsphere is still failing, is that look unrelated from this PR?

**Comment by vrutkovs** [comment]
Right, okd-vsphere previously was failing on bootstrap - now it proceeds further (still digging on what's wrong there)

**Pull request merged**
