### PR TITLE
bug 1872802: revert of Bug 1868117: cleanup: remove legacy etcd bits

### PR DESCRIPTION
**Pull request by deads2k**
revert https://github.com/openshift/machine-config-operator/pull/1933 which appears to break upgrade 4.5 to 4.6

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
cc: @hexfusion

**Comment by cgwalters** [comment]
That's unfortunate :cry: 
/approve

Hm, I guess we don't have a job hooked up to repos for 4.5 upgrades yet.

**Comment by kikisdeliveryservice** [comment]
@deads2k do we have any data points showing that this broke upgrades?  can we get a bz with a summary laying this out?

**Comment by deads2k** [comment]
one better fix that isn't yet proven here: https://github.com/openshift/cluster-etcd-operator/pull/429

**Comment by deads2k** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1872802

**Comment by kikisdeliveryservice** [comment]
Asked in https://github.com/openshift/cluster-etcd-operator/pull/429 but are we trying that one in lieu of this PR? Or are we merging both?

**Comment by kikisdeliveryservice** [comment]
Looks like after merging the other PR upgrades were successful see: https://github.com/openshift/cluster-etcd-operator/pull/429#issuecomment-681163157

So I think we don't need this PR anymore? But I'll let @deads2k / @hexfusion give the official word.

**Comment by deads2k** [comment]
upgrades are green now

/close

**Pull request closed without merging**
