### PR TITLE
OCPBUGS-34959: ensure event handlers are registered after queue is configured

### PR DESCRIPTION
**Pull request by hexfusion**
This PR addresses a race with the ordering of event handlers and queue which can result in a panic.

tests:
clusterbot: 1
e2e-vsphere-ovn-techpreview: 1

### CODE REVIEW

**Comment by hexfusion** [comment]
Working on another approach

**Comment by deads2k** [comment]
perhaps this instead? https://github.com/openshift/machine-config-operator/pull/4391

**Comment by hexfusion** [comment]
credit to @deads2k for fix

**Comment by sergiordlr** [comment]
/hold
Until we can provide qe-approved label.

**Comment by sinnykumari** [comment]
Backport needed into 4.16 
/label  acknowledge-critical-fixes-only

**Comment by sergiordlr** [comment]
We haven't seen any panic in the MCO controller pod logs or in the MCO previous controller pod in:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4359/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview/1798380369465053184


In templates: 
private-templates/functionality-testing/aos-4_17/ipi-on-azure/versioned-installer-techpreview-ci
private-templates/functionality-testing/aos-4_17/ipi-on-aws/versioned-installer-customer_vpc-http_proxy-techpreview-ci
private-templates/functionality-testing/aos-4_17/ipi-on-vsphere/versioned-installer_techpreview

We have been able to manually enable featureset techpreview in template private-templates/functionality-testing/aos-4_17/ipi-on-aws/versioned-installer.

**Comment by hexfusion** [comment]
[failure](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4359/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview/1798412328698384384) unrelated to panic 

/test e2e-gcp-op-techpreview

**Comment by hexfusion** [comment]
seems the job is broken right now.

/test e2e-gcp-op-techpreview

**Comment by hexfusion** [comment]
flake

/test e2e-gcp-op-techpreview

**Comment by hexfusion** [comment]
> We haven't seen any panic in the MCO controller pod logs or in the MCO previous controller pod in: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4359/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview/1798380369465053184
> 
> Also using flexy-install templates: private-templates/functionality-testing/aos-4_17/ipi-on-azure/versioned-installer-techpreview-ci private-templates/functionality-testing/aos-4_17/ipi-on-aws/versioned-installer-customer_vpc-http_proxy-techpreview-ci private-templates/functionality-testing/aos-4_17/ipi-on-vsphere/versioned-installer_techpreview
> 
> We have been able to manually enable featureset techpreview in a cluster installed with template private-templates/functionality-testing/aos-4_17/ipi-on-aws/versioned-installer.
> 
> In https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4359/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview/1798616598567718912 we can see that the controller pod fails and is restarted reporting this logs: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4359/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview/1798616598567718912/artifacts/e2e-gcp-op-techpreview/gather-extra/artifacts/pods/openshift-machine-config-operator_machine-config-controller-77cc85c858-7rxhm_machine-config-controller_previous.log
> 
> ```
> E0606 08:09:39.026647       1 status.go:51] Could not find our MachineConfigNode for node. ci-op-165740vi-714a6-mwzcv-worker-a-pb8rq: machineconfignodes.machineconfiguration.openshift.io "ci-op-165740vi-714a6-mwzcv-worker-a-pb8rq" not found
> E0606 08:10:43.285059       1 leaderelection.go:332] error retrieving resource lock openshift-machine-config-operator/machine-config-controller: the server was unable to return a response in the time allotted, but may still be processing the request (get leases.coordination.k8s.io machine-config-controller)
> E0606 08:11:14.292873       1 leaderelection.go:332] error retrieving resource lock openshift-machine-config-operator/machine-config-controller: Get "https://172.30.0.1:443/apis/coordination.k8s.io/v1/namespaces/openshift-machine-config-operator/leases/machine-config-controller": dial tcp 172.30.0.1:443: connect: connection refused
> I0606 08:11:30.280914       1 leaderelection.go:285] failed to renew lease openshift-machine-config-operator/machine-config-controller: timed out waiting for the condition
> E0606 08:11:30.282523       1 leaderelection.go:308] Failed to release lock: Put "https://172.30.0.1:443/apis/coordination.k8s.io/v1/namespaces/openshift-machine-config-operator/leases/machine-config-controller": dial tcp 172.30.0.1:443: connect: connection refused
> I0606 08:11:30.282636       1 start.go:146] Stopped leading. Terminating.
> ```
> 
> We can see this other error in another execution: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4359/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview/1798646469121544192
> 
> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4359/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview/1798646469121544192/artifacts/e2e-gcp-op-techpreview/gather-extra/artifacts/pods/openshift-machine-config-operator_machine-config-controller-65774cb85d-ntjgl_machine-config-controller_previous.log
> 
> ```
> E0606 10:09:23.738222       1 reflector.go:147] github.com/openshift/client-go/machine/informers/externalversions/factory.go:125: Failed to watch *v1beta1.MachineSet: unknown (get machinesets.machine.openshift.io) - error from a previous attempt: http2: server sent GOAWAY and closed the connection; LastStreamID=47, ErrCode=NO_ERROR, debug=""
> E0606 10:09:23.749833       1 reflector.go:147] github.com/openshift/client-go/operator/informers/externalversions/factory.go:125: Failed to watch *v1alpha1.ImageContentSourcePolicy: unknown (get imagecontentsourcepolicies.operator.openshift.io)
> E0606 10:09:23.750107       1 reflector.go:147] k8s.io/client-go/informers/factory.go:159: Failed to watch *v1.Node: unknown (get nodes) - error from a previous attempt: http2: server sent GOAWAY and closed the connection; LastStreamID=47, ErrCode=NO_ERROR, debug=""
> E0606 10:09:23.750717       1 leaderelection.go:308] Failed to release lock: leases.coordination.k8s.io "machine-config-controller" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-controller" cannot update resource "leases" in API group "coordination.k8s.io" in the namespace "openshift-machine-config-operator"
> I0606 10:09:23.756022       1 start.go:146] Stopped leading. Terminating.
> E0606 10:09:23.750758       1 reflector.go:147] github.com/openshift/client-go/machineconfiguration/informers/externalversions/factory.go:125: Failed to watch *v1alpha1.PinnedImageSet: unknown (get pinnedimagesets.machineconfiguration.openshift.io) - error from a previous attempt: http2: server sent GOAWAY and closed the connection; LastStreamID=47, ErrCode=NO_ERROR, debug=""
> ```
> 
> @hexfusion @yuqi-zhang I don't see any panic in the installations that I have launched, but I have seen errors like the ones that I have pasted in this comment. Please, could you confirm that this error are not a problem before adding the qe-approved label? thank you!

I don't see how this change would introduce these errors directly we can take a further look as a followup. LGTM

**Comment by hexfusion** [comment]
[panic](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4359/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-techpreview/1798704994061389824) unrelated to this PR


/test e2e-gcp-op-techpreview

**Comment by sergiordlr** [comment]
The problems found in the controller's logs seem to be related to the lease. It doesn't seem to be related to the new pinned image functionality and we haven't found any panic after installing OCP with techpreview several times. We can add the qe-approved label.

/label qe-approved

**Comment by sinnykumari** [comment]
Removing hold since we have qe approval
/hold cancel

**Comment by hexfusion** [comment]
ci disruption

/retest-required

**Pull request merged**
