### PR TITLE
Bug 1942488: Use new --prefer-ipv6 flag to "runtimecfg node-ip" as appropriate

### PR DESCRIPTION
**Pull request by danwinship**
4.7 backport of #2478

### CODE REVIEW

**Comment by danwinship** [comment]
/hold
depends on https://github.com/openshift/baremetal-runtimecfg/pull/132

**Review by sinnykumari — APPROVED** [review]

**Comment by danwinship** [comment]
@celebdor or @cybertron can you `/lgtm`? (it's already got an approved)

**Comment by danwinship** [comment]
/hold
It has passed all of the required jobs. No need to keep spamming the broken jobs while waiting for `cherry-pick-approved`

**Comment by danwinship** [comment]
/hold cancel
(don't want this to accidentally miss cherry-pick)

**Pull request merged**
