### PR TITLE
skip test if not linux + hack/Makefile cleanups

### PR DESCRIPTION
**Pull request by runcom**
I'm occasionally developing from a mac, and found out that test is
failing cause it's assuming we're on linux and the kernel wrote the boot
id under /proc. It's not the case on osx so just skip the test if that
file isn't there.

The second commit accounts for an empty rev-parse --show-cdup on osx, and fixes that by testing the path to cd (which is not changing behavior on linux)

The other commits are doing a pass over a cleanup in hack and Makefile in order to start addressing #447 - specifically, we need to avoid stuff like #596 

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
This is also needed for https://github.com/openshift/release/pull/3332

so we can have a verify job which just calls `make verify` from this which is verifying we never have issues like #596 - in the future, we can add gofmt and other checks as well

**Comment by kikisdeliveryservice** [comment]
these failures have nothing to do with this PR. I'll check the forums to see if they are already reported.

ill retest later.

**Comment by kikisdeliveryservice** [comment]
a similar failure has been reported in BZ 1695278.  It seems to be happening on every run, so no point of mashing retest.

**Comment by kikisdeliveryservice** [comment]
openshift-bot is trolling me. :rofl:

**Pull request merged**
