### PR TITLE
pkg/operator: collect all needed resources

### PR DESCRIPTION
**Pull request by runcom**
collect everything needed, should be better than https://github.com/openshift/must-gather/pull/157

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
Niiice this is working now (on a test cluster):
```
...
[must-gather-mwthl] OUT cluster-scoped-resources/machineconfiguration.openshift.io/kubeletconfigs/
[must-gather-mwthl] OUT cluster-scoped-resources/machineconfiguration.openshift.io/kubeletconfigs/set-max-pods.yaml
...
```

**Comment by enxebre** [comment]
nice!
/lgtm
/hold
for anyone on mco to unhold

**Pull request merged**
