### PR TITLE
owners: Add mdbooth to approvers

### PR DESCRIPTION
**Pull request by pierreprinetti**
Add @mdbooth

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by Fedosin — APPROVED** [review]
/lgtm

**Review by ashcrow — APPROVED** [review]
https://github.com/mdbooth :+1:

**Comment by ashcrow** [comment]
This is adding a developer to the owners file ... passing e2e tests for code isn't really needed.

/override e2e-gcp-op

**Pull request merged**
