### PR TITLE
[release-4.6] Bug 1906298: update MCDDrainErr to reduce cardinality & fix nodename

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Cherry-pick of #2044
Replaces #2292

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
cmon buggie

/bugzilla refresh

**Review by sinnykumari — APPROVED** [review]
LGTM

**Review by darkmuggle — APPROVED** [review]
/lgtm

**Comment by kikisdeliveryservice** [comment]
these jobs are mostly red and run infrequently, trying again but this pr shouldn't be breaking them (it's just metrics)

/retest

**Pull request merged**
