### PR TITLE
Change the default crio.conf to use the values we want

### PR DESCRIPTION
**Pull request by cgwalters**
Rather than using `/etc/sysconfig/crio-network`, which was removed in
https://github.com/cri-o/cri-o/commit/cce25da96fb9e6c2d53744e49235b06b0a1c4537#diff-8f149e7773eb6fec135aa90b23aac30b

### CODE REVIEW

**Comment by cgwalters** [comment]
xref https://bugzilla.redhat.com/show_bug.cgi?id=1696774

**Comment by dcbw** [comment]
/lgtm

Certainly seems cleaner that setting crio-network, if we're already writing a crio.conf somewhere.

**Comment by kikisdeliveryservice** [comment]
sorry but what does the comment:
`Note this default is changed from base.` mean in this context?

**Comment by cgwalters** [comment]
> sorry but what does the comment: Note this default is changed from base. mean in this context?

From the RPM, which is itself a copy of upstream I think.

**Comment by kikisdeliveryservice** [comment]
@cgwalters could we put that in the comment then just so those of us not familiar will know?

**Comment by cgwalters** [comment]
> /lgtm cancel

OK I addressed those two things.

**Comment by kikisdeliveryservice** [comment]
thanks @cgwalters !!!!!!

/lgtm

**Comment by runcom** [comment]
How has this regressed though? Why wasn't there any gating which could have found this

**Comment by cgwalters** [comment]
(And now also changing the worker config)

**Pull request merged**
