### PR TITLE
Bug 1811140: Add containernetworking-plugin RPM's bin location to CRI-O config

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
**- What I did**

This is a back-port PR for https://github.com/openshift/machine-config-operator/pull/1630, goes hand-in-hand with https://github.com/openshift/cluster-network-operator/pull/602

Let me know in case someone requires more information.

**- How to verify it**

**- Description for the changelog**

/cc @danwinship

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
/retitle [release-4.4] Add containernetworking-plugin RPM's bin location to CRI-O config

**Comment by alexanderConstantinescu** [comment]
/retitle [release-4.4] Bug 1811140: Add containernetworking-plugin RPM's bin location to CRI-O config

**Comment by sdodson** [comment]
@alexanderConstantinescu lacks lgtm and approved

**Comment by danwinship** [comment]
oops, no one from MCO got cc-ed to review this because the `/cc` in the initial comment blocked auto-reviewer-assignment

/auto-cc
/lgtm

and for good measure
/assign @runcom 
since he approved the master PR

**Comment by umohnani8** [comment]
LGTM

**Comment by sdodson** [comment]
/retitle Bug 1811140: Add containernetworking-plugin RPM's bin location to CRI-O config

**Pull request merged**
