### PR TITLE
[release-4.9] Bug 2070490: configure-ovs: reload NM only when necessary

### PR DESCRIPTION
**Pull request by jcaamano**
Cherry pick of #3005 https://github.com/openshift/machine-config-operator/commit/dcb74d6cf7d13c7d4a4b2255b1ee1c70822c0734

### CODE REVIEW

**Comment by jcaamano** [comment]
e2e-metal-ipi-ovn-ipv6 seems busted with a different ovnk issue but the jobs gets past the changes on this PR that work as expected.
As far as backport risk assessment, this change avoids reloading NM when no configuration changes were made with configure-ovs. If that were to not work correctly, unnecessary reloads would be made causing longer boot delays or configuration would not be applied causing evident node networking issues at boot.

**Review by trozet — APPROVED** [review]
/lgtm

**Review by andreaskaris — APPROVED** [review]
/lgtm

The backport looks to be clean and the change makes sense.

**Pull request merged**
