### PR TITLE
OCPBUGS-42816: MachineConfigNode objects should not produce too many invalid apply requests

### PR DESCRIPTION
**Pull request by djoshy**
**- What I did**
Added a check so the MCO will always send in a non empty value for `newMCNode.Spec.ConfigVersion.Desired`. Also took this opportunity to update this file to use the daemon constants package.

**- How to verify it**
This bug only affects TechPreview clusters as MCN is not in the default featureset. With this fix, we should no longer see any errors in the daemon log about invalid MCN apply requests like the following:
```
E1006 10:59:31.339379   13305 upgrade_monitor.go:319] Error making MCN spec for Update Compatible: MachineConfigNode.machineconfiguration.openshift.io "ip-10-0-113-112.us-east-2.compute.internal" is invalid: spec.configVersion.desired: Invalid value: "": spec.configVersion.desired in body should match '^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$'
```

### CODE REVIEW

**Comment by sergiordlr** [comment]
Verified using IPI on AWS

Create a cluster using day1 techpreview config without the fix (flexy-install template private-templates/functionality-testing/aos-4_18/ipi-on-aws/versioned-installer-techpreview-ci):
```
$ nodelogs ip-10-0-25-150.us-east-2.compute.internal |grep monitor
E1114 14:30:17.264534    2366 upgrade_monitor.go:382] Error applying MCN Spec: MachineConfigNode.machineconfiguration.openshift.io "ip-10-0-25-150.us-east-2.compute.internal" is invalid: spec.configVersion.desired: Invalid value: "": spec.configVersion.desired in body should match '^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$'
E1114 14:30:17.264610    2366 upgrade_monitor.go:319] Error making MCN spec for Update Compatible: MachineConfigNode.machineconfiguration.openshift.io "ip-10-0-25-150.us-east-2.compute.internal" is invalid: spec.configVersion.desired: Invalid value: "": spec.configVersion.desired in body should match '^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$'
E1114 14:30:17.299006    2366 upgrade_monitor.go:382] Error applying MCN Spec: MachineConfigNode.machineconfiguration.openshift.io "ip-10-0-25-150.us-east-2.compute.internal" is invalid: spec.configVersion.desired: Invalid value: "": spec.configVersion.desired in body should match '^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$'
E1114 14:30:17.299028    2366 upgrade_monitor.go:319] Error making MCN spec for Update Compatible: MachineConfigNode.machineconfiguration.openshift.io "ip-10-0-25-150.us-east-2.compute.internal" is invalid: spec.configVersion.desired: Invalid value: "": spec.configVersion.desired in body should match '^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$'
E1114 14:30:17.635808    2366 upgrade_monitor.go:382] Error applying MCN Spec: MachineConfigNode.machineconfiguration.openshift.io "ip-10-0-25-150.us-east-2.compute.internal" is invalid: spec.configVersion.desired: Invalid value: "": spec.configVersion.desired in body should match '^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$'
E1114 14:30:17.635900    2366 upgrade_monitor.go:319] Error making MCN spec for Update Compatible: MachineConfigNode.machineconfiguration.openshift.io "ip-10-0-25-150.us-east-2.compute.internal" is invalid: spec.configVersion.desired: Invalid value: "": spec.configVersion.desired in body should match '^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$'
I1114 14:31:08.521997    2366 config_drift_monitor.go:246] Config Drift Monitor started
I1114 14:55:33.070773    2366 config_drift_monitor.go:255] Config Drift Monitor has shut down
I1114 14:55:49.373262    2366 config_drift_monitor.go:246] Config Drift Monitor started


```

Create a cluster using day1 techpreview config with the fix (flexy-install template private-templates/functionality-testing/aos-4_18/ipi-on-aws/versioned-installer-techpreview-ci):

```
$ nodelogs ip-10-0-14-175.us-east-2.compute.internal |grep monitor
I1114 09:56:03.382526    2485 config_drift_monitor.go:246] Config Drift Monitor started
I1114 10:20:10.901112    2485 config_drift_monitor.go:255] Config Drift Monitor has shut down
I1114 10:20:28.368052    2485 config_drift_monitor.go:246] Config Drift Monitor started

```

/label qe-approved

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

**Pull request merged**
