### PR TITLE
Nutanix platform

### PR DESCRIPTION
**Pull request by yannickstruyf3**
Adding the Nutanix platform to the MCO Operator.

### CODE REVIEW

**Review by kikisdeliveryservice — COMMENTED** [review]
2 questions:
1) does this require changes in https://github.com/openshift/machine-config-operator/tree/master/templates/common

2) if so, can you also add OWNERS for this so your team can be responsible for your templates/etc: https://github.com/openshift/machine-config-operator/blob/master/OWNERS_ALIASES

**Comment by sinnykumari** [comment]
You need to get https://github.com/openshift/api/pull/1059 merged first and then get the new openshift/api containing fixes vendored in MCO repo https://github.com/openshift/api/.

Putting hold until above has been done
/hold
Please remove hold once all the per-requesites has been done and is ready for review.

**Comment by yannickstruyf3** [comment]
@kikisdeliveryservice I added the approvers and also an update to the controllerconfig.crd.yaml

**Comment by thunderboltsid** [comment]
Rebased version of this PR can be found at https://github.com/openshift/machine-config-operator/pull/2942

**Pull request closed without merging**
