### PR TITLE
daemon: drop `systemctl stop kubelet` during node reboot

### PR DESCRIPTION
**Pull request by sinnykumari**
* With the upstream implementation of kubelet graceful shutdown feature, we don't explicitly stop the kubelet
 so that kubelet can gracefully shutdown pods when `GracefulNodeShutdown` feature gate is enabled. kubelet uses systemd inhibitor locks to delay node shutdown to terminate pods.
https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown
* On HA cluster MCO today performs explicit pod drain on node, so this feature is not much useful there. But quite useful on Non -HA clusters (like Single Node OpenShift) , where we skip pod drain. Such clusters can take advantage of `GracefulNodeShutdown` feature to terminate critical pods.

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Makes sense to me!

**Comment by mrunalp** [comment]
We can enable this after we rebase to 4.8 and enable the settings for node graceful shutdown.

**Comment by sinnykumari** [comment]
ok, I am putting hold on the PR until then.
@mrunalp please let us know when we have enabled graceful node shutdown feature in 4.8

/hold

**Comment by kikisdeliveryservice** [comment]
is nobody going to ask how @sinnykumari got the font in the title to be cool?

**Comment by rphillips** [comment]
+1 after the rebase lands

**Review by JAORMX — APPROVED** [review]

**Comment by kikisdeliveryservice** [comment]
@mrunalp @rphillips can we merge this now? do we want to backport?

**Comment by sinnykumari** [comment]
Not sure but I think node team is testing it in https://github.com/openshift/machine-config-operator/pull/2524 where tests are currently failing

**Comment by sinnykumari** [comment]
still valid until https://github.com/openshift/machine-config-operator/pull/2524 gets merged

**Comment by cgwalters** [comment]
Just to xref I think we want this *and* https://github.com/openshift/machine-config-operator/pull/3136

**Comment by yuqi-zhang** [comment]
Just to double check, is graceful shutdown now in OCP 4.12?

**Comment by sinnykumari** [comment]
Not yet, but I think plan is to have this feature available in 4.12. So, we will need this PR to adapt to this feature

**Comment by cgwalters** [comment]
> Just to xref I think we want this and https://github.com/openshift/machine-config-operator/pull/3136

I was wrong because I was confused by the difference between delay and blocking locks.  #3136 would be needed for us to honor *blocking* locks, which I think we also do want, but isn't a blocker (heh) for this.

/approve

I think we can just ship this without even having graceful shutdown enabled right now.

**Comment by sinnykumari** [comment]
Fixes [MCO-345](https://issues.redhat.com/browse/MCO-345)

**Comment by sinnykumari** [comment]
Removing hold since this patch can go in independently without waiting from graceful shutdown enabled.
/hold cancel

**Comment by sinnykumari** [comment]
@yuqi-zhang PTAL and LGTM if this looks alright to get merged

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

As I understand, this should be safe in our model anyways?

**Comment by sinnykumari** [comment]
Looks like ci issue.
/retest

**Pull request merged**
