### PR TITLE
debug: Send significant events to the apiserver for a node

### PR DESCRIPTION
**Pull request by smarterclayton**
These three events represent rough actions taken by the MCD that an
administrator should know about.

### CODE REVIEW

**Comment by smarterclayton** [comment]
@jlebon example as brought up in chat.  I need to double check that you have the right perms to send events though.

**Comment by abhinavdahiya** [comment]
@smarterclayton 
Will need to add handling to MCO for the new clusterroles and clusterrolebindings [here](https://github.com/openshift/machine-config-operator/blob/f915a1bfb2d98a2cdde2ea264008f7dfb58bf262/pkg/operator/sync.go#L155-L173) similar to [here](https://github.com/openshift/machine-config-operator/blob/f915a1bfb2d98a2cdde2ea264008f7dfb58bf262/pkg/operator/sync.go#L211-L227)

_sorry for explicit :innocent:_

**Comment by smarterclayton** [comment]
Ah, thanks.

On Nov 29, 2018, at 6:50 PM, Abhinav Dahiya <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton>
Will need to add handling to MCO for the new clusterroles and
clusterrolebindings here
<https://github.com/openshift/machine-config-operator/blob/f915a1bfb2d98a2cdde2ea264008f7dfb58bf262/pkg/operator/sync.go#L155-L173>
similar to here
<https://github.com/openshift/machine-config-operator/blob/f915a1bfb2d98a2cdde2ea264008f7dfb58bf262/pkg/operator/sync.go#L211-L227>

*sorry for explicit 😇*

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/machine-config-operator/pull/201#issuecomment-443037494>,
or mute the thread

**Comment by jlebon** [comment]
Ahh neat, wasn't aware of `oc get events`.

> I need to double check that you have the right perms to send events though.

Sounds good.

**Comment by cgwalters** [comment]
Looks like this overlaps with https://github.com/openshift/machine-config-operator/pull/202

**Comment by cgwalters** [comment]
Not an expert in this code but this PR looks good to me.  Seems like it's passing tests, just missing a slash-lgtm?

I'll rebase https://github.com/openshift/machine-config-operator/pull/202 on top of this one once this lands.

**Comment by smarterclayton** [comment]
@abhinavdahiya tag this too?

**Pull request merged**
