### PR TITLE
OCPBUGS-36810: When MCOS is deleted in building state configmap resources related to MOSC are not deleted.

### PR DESCRIPTION
**Pull request by dkhater-redhat**
**- What I did**
Fixed an issue where deleting a MachineOSConfig during its building state did not properly clean up related ConfigMap resources. This resulted in conflicts when reapplying the same MachineOSConfig, as existing ConfigMap resources prevented new builds from progressing.

**- How to verify it**
1. Apply a MachineOSConfig and verify that it starts building.
2. Delete the MachineOSConfig while it is still in the building state.
3. Reapply the same MachineOSConfig.
4. Verify that the build progresses successfully without conflicts, confirming that the previous ConfigMap resources were properly cleaned up.

**- Description for the changelog**
Fixed an issue where deleting a `MachineOSConfig` in the building state did not properly clean up associated `ConfigMap` resources, preventing conflicts when reapplying the same `MachineOSConfig`.

### CODE REVIEW

**Comment by umohnani8** [comment]
Changes LGTM

**Comment by sergiordlr** [comment]
@dkhater-redhat Hello! We have problems installing the images created for the PRs (all the PRs not only this one). Nevertheless, nightly builds are installing without problems. Could you please merge this PR? we will test it post-merge in the nightly build. Thanks!!

We don't add the qe-approved label since it will verified post-merge.

**Pull request merged**
