### PR TITLE
OCPBUGS-19427: Add source and mirror format regex validation

### PR DESCRIPTION
**Pull request by QiWang19**
**- What I did**
Add source and mirror format regex validation
**- How to verify it**
1. Apply an icsp CR with blacspaces in the source or mirror filed
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: repo-icsp
spec:
  repositoryDigestMirrors:
  - mirrors:
    - "example.io/cp4d-dp-xyz  "
    source: "  example.io/cp4d/dp/xyz"
```
2. MCO will not rollout this CR.
**- Description for the changelog**

Add source and mirror format regex validation.

### CODE REVIEW

**Comment by QiWang19** [comment]
@yuqi-zhang PTAL

**Review by yuqi-zhang — APPROVED** [review]
lgtm, leaving a

/hold

in case QE wants to pre-merge test. Feel free to drop if not needed

**Comment by QiWang19** [comment]
tested on the ci cluster
/hold cancel

**Review by mtrmac — COMMENTED** [review]
I’m sure these are stupid questions, at worst I will learn something:
- Why are these values accepted into the API writes in the first place, and not rejected at that point? We can’t change the validation patterns like https://github.com/openshift/api/blob/ef62af078a9387e739abd99ec1d80e9129bb5475/config/v1/types_image_digest_mirror_set.go#L108 any more? They somehow don’t apply? We did change them but that doesn’t help with CRs that already exists?
- What makes `" "` so special that it needs to be individually rejected, considering many other forbidden characters like `\`, and most of Unicode — and valid characters combined into an invalid syntax? It seems to me that if we should be validating the strings at this point at all, it would be more useful to validate using the _complete validation rules_, so that the code which follows this point can make some useful assumptions about the data. (And then we could also drop the `== ""` checks from this code, because that should also be rejected by the API validation rules of the field.)

**Comment by QiWang19** [comment]
@mtrmac 
- the openshift/api validation cannot apply to ICSP. can't update it's validation to ICSP CRD as tier1 api. 
- update to use the same complete validation pattern with the openshift/api.

**Comment by QiWang19** [comment]
@mtrmac PTAL

**Review by mtrmac — COMMENTED** [review]
/lgtm

Thanks for the explanation!

**Pull request merged**
