### PR TITLE
NO-ISSUE: Revert "disable mglru service"

### PR DESCRIPTION
**Pull request by sairameshv**
This reverts commit 5236644ad2c4868a90deb47745d7bf7fe322c2d2.

/cc @rphillips @harche

### CODE REVIEW

**Comment by kwilczynski** [comment]
Related to:

- https://github.com/openshift/machine-config-operator/pull/4466

**Comment by rphillips** [comment]
/hold cancel

The script removal was done here: https://github.com/openshift/machine-config-operator/pull/4466

**Pull request merged**
