### PR TITLE
[release-4.8] Bug 2062655: Improvements for configure-ovs script

### PR DESCRIPTION
**Pull request by jcaamano**
This is a cherry-pick of:
* 47957d7e: Improvements for configure-ovs script
* 7a5d2996: configure-ovs: cleanup leftovers from previous run
* 6528d2d: Configure-ovs: Ensure DHCP finishes for both address families
* af7b491: Use ip command to check for ipv4/v6 addresses

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@jcaamano could you take a look at the BZ issue here:
`expected dependent [Bugzilla bug 2060476](https://bugzilla.redhat.com/show_bug.cgi?id=2060476) to target a release in 4.9.0, 4.9.z, but it targets "4.8.z" instead`

**Comment by anuragthehatter** [comment]
Changes looks good to QE.Will verify once it lands in prod build
/label cherry-pick-approved

**Pull request merged**
