### PR TITLE
[release-4.10] OCPBUGS-3500: Add ephemeral storage to kubelet system reserved args

### PR DESCRIPTION
**Pull request by harche**
This is a manual pick of https://github.com/openshift/machine-config-operator/pull/3381

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
Seems like a clean cherrypick

/label backport-risk-assessed

**Comment by harche** [comment]
> Seems like a clean cherrypick
> 
> /label backport-risk-assessed

Thanks @yuqi-zhang

**Pull request merged**
