### PR TITLE
*: Support CoreOS configs in MCs

### PR DESCRIPTION
**Pull request by LorbusChris**
**- What I did**
Add support for parsing CoreOS configs from RawExtension in MC

This is one possible way to go about the issue discussed in #283 

**- How to verify it**
I'll add a test
**- Description for the changelog**
Support CoreOS configs in MCs

/hold

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
hi @LorbusChris is there any problem definition/background for this?

**Comment by LorbusChris** [comment]
@kikisdeliveryservice this is one way to solve https://github.com/openshift/machine-config-operator/issues/283
It has come up a few times. Just threw this up here to open up the discussion.

**Comment by cgwalters** [comment]
I like the idea but I think we should do this after https://github.com/coreos/fcct/pull/79

Also MCO team: I added a 4.7 label we can use for PRs like this - "things to look at/merge after we branch for 4.6".

**Review by cgwalters — CHANGES_REQUESTED** [review]
Moving off my review queue for now

**Comment by cgwalters** [comment]
So we could probably land this one pretty quickly if we agree to conditionalize it first on being on FCOS/OKD right?  There's low-to-zero risk for that and then we'd be able to tackle the "how does fcc work with RHCOS" as a separate phase or so.

**Comment by LorbusChris** [comment]
I've created an enhancement proposal for this: https://github.com/openshift/enhancements/pull/525

@cgwalters I'm not sure we need to conditionalize it for OKD - or are there any drawbacks to having it in OCP as a tech preview of sorts that is not used by any component by default, and not recommended to admin users yet?

**Comment by kikisdeliveryservice** [comment]
Agree on gating and also there's an open enhancement so it feels like that should be finished first..

/hold

**Comment by kikisdeliveryservice** [comment]
Also: is this okd-e2e test dead?

**Comment by LorbusChris** [comment]
@kikisdeliveryservice I don't think master and 4.6 okd tests will succeed just, yet as machine-os-content for 4.6+ still has some issues.
/retest

**Pull request closed without merging**
