### PR TITLE
mcd: Fix clusterrole.yaml

### LINKED ISSUE #66: MCD needs more perms to reboot the node
```
I0914 21:07:35.208898    6711 update.go:44] Update completed. Draining the node.
E0914 21:07:35.215929    6711 daemon.go:85] Marking degraded due to: pods is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot list pods at the cluster scope: no RBAC policy matched
```

### PR DESCRIPTION
**Pull request by ashcrow**
Resolves #66.

### CODE REVIEW

**Comment by jlebon** [comment]
Yeah, I had started down that path last week, but IIRC there's other permissions needed past that. Will try to unblock that path today, though we can start with this at least (and I'll reopen the issue as needed).

This looks good, though I think it needs a `./hack/update-generated-bindata.sh`.

**Comment by ashcrow** [comment]
@jlebon done.

**Comment by jlebon** [comment]
Follow up in #70.

**Pull request merged**
