### PR TITLE
Bug 1835233: Add support for configuring registries at install

### PR DESCRIPTION
**Pull request by umohnani8**
Fixes #1835233 (https://bugzilla.redhat.com/show_bug.cgi?id=1835233)
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

**- What I did**
Add support to bootstrap to configure the registries in the
cluster-wide Image CR. Ensure that the MCC can consume the
Image CR and generate /etc/containers/registries.conf correctly.

**- How to verify it**
1. Run `openshift-install create manifests`
2. Add the following Image CR yaml to the manifests directory created from step 1
```
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  creationTimestamp: null
  name: cluster
spec:
  registrySources:
    insecureRegistries:
    - blah.io
    - foo.io
```
3. Run `openshift-install create cluster`
4. Watch to ensure that the cluster was successfully installed and check the `/etc/containers/registries.conf` file on all the nodes to see that it has the configuration from the Image CR in step 2.

**- Description for the changelog**

Add day 1 support for registries configured in the cluster-wide Image CR

### CODE REVIEW

**Comment by umohnani8** [comment]
@runcom @kikisdeliveryservice PTAL

**Comment by cgwalters** [comment]
/approve
Ah, another source of the dreaded "machineconfig not found".  Offhand LGTM!

**Comment by umohnani8** [comment]
@runcom @kikisdeliveryservice this is ready, PTAL.
I know aws-scaleup is flaky, is ovn-step-registry flaky as well?

**Comment by runcom** [comment]
> I know aws-scaleup is flaky, is ovn-step-registry flaky as well?

sometimes yeah :(
Pending one offline sanity check question

/approve

**Comment by runcom** [comment]
holding to add a missing check that we have in the controller but not in bootstrap

/hold

**Comment by kikisdeliveryservice** [comment]
unit test seems like a legit failure: `error parsing reference of desired image from cluster version config` related to this PR
see: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1866/pull-ci-openshift-machine-config-operator-master-unit/1285618754994049024#1:build-log.txt%3A71

**Comment by umohnani8** [comment]
@runcom @kikisdeliveryservice this should be ready now, PTAL

**Comment by kikisdeliveryservice** [comment]
Q:  is there/will there be an e2e in installer verifying?

Otherwise L GTM

Deferring to @runcom for the final approval

/assign @runcom

**Comment by kikisdeliveryservice** [comment]
In the meantime

/retest

**Comment by umohnani8** [comment]
There is no e2e in installer, do we really need one there? The release-image value was already being used in other parts of bootkube.sh, I just added a new flag to be able to pass the value down to the MCO.

**Comment by sjenning** [comment]
@runcom can you do a final review and lgtm?

**Pull request merged**
