### PR TITLE
Bug 1896226: Remove recycler pod templates

### PR DESCRIPTION
**Pull request by bertinatto**
**- What I did**

Removed the recycler pod templates.

**- How to verify it**

The template files should no longer be created in these locations (master nodes):

```
/etc/kubernetes/recycler-pod.yaml
/etc/kubernetes/manifests/recycler-pod.yaml
```

**- Description for the changelog**

The template is no longer necessary in MCO because now it's embedded in
KCM operator: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/488

This PR should be merged after https://github.com/openshift/cluster-kube-controller-manager-operator/pull/488.

/assign @sjenning

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
until openshift/cluster-kube-controller-manager-operator#488 is merged.

**Comment by kikisdeliveryservice** [comment]
Is this ready @bertinatto ?

**Comment by bertinatto** [comment]
> Is this ready @bertinatto ?

Yes, but we need to wait for https://github.com/openshift/cluster-kube-controller-manager-operator/pull/490 so that we don't break the 4.7 => 4.6 downgrade.

**Comment by sjenning** [comment]
looks like a pretty rare flake on aws-serial
/retest

**Comment by bertinatto** [comment]
``` level=error msg=Error: Error creating IAM Role ci-op-mxqs04fs-5e954-ff8lh-bootstrap-role: LimitExceeded: Cannot exceed quota for RolesPerAccount: 1000 ```

/test e2e-aws-serial

**Comment by kikisdeliveryservice** [comment]
> > Is this ready @bertinatto ?
> 
> Yes, but we need to wait for [openshift/cluster-kube-controller-manager-operator#490](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/490) so that we don't break the 4.7 => 4.6 downgrade.

That PR is still open so throwing a hold on this to prevent accidental merge.

/hold

**Comment by bertinatto** [comment]
> > > Is this ready @bertinatto ?
> > 
> > 
> > Yes, but we need to wait for [openshift/cluster-kube-controller-manager-operator#490](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/490) so that we don't break the 4.7 => 4.6 downgrade.
> 
> That PR is still open so throwing a hold on this to prevent accidental merge.
> 
> /hold

So if we merge this PR before https://github.com/openshift/aws-ebs-csi-driver-operator/pull/110 we will break 4.7 => 4.6 dowgrades.

However, if I understand correctly, 4.7 => 4.6 downgrades are already broken since https://github.com/openshift/machine-config-operator/pull/2248 has been merged. As a result, we won't be supporting 4.7 => 4.6 downgrades and it's OK with going ahead with this PR, is that correct @sjenning?

**Pull request merged**
