### PR TITLE
Bump github.com/openshift/api for NodeSwap feature

### PR DESCRIPTION
**Pull request by ehashman**
**- What I did** Bumped openshift/api to `v0.0.0-20211203223044-9b3afd95c93a` to pull in https://github.com/openshift/api/pull/1061

**- How to verify it** Update versions in go.mod and run `go mod tidy` and `go mod vendor`

**- Description for the changelog** Bumped openshift/api to `v0.0.0-20211203223044-9b3afd95c93a`, adding support for the tech preview `NodeSwap` feature gate

/cc @rphillips 

enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/kubelet/node-swap.md#enable-nodeswap-feature-gate

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
Bump itself looks good to me. NodeSwap is only used via the featuregate right?

/assign rphillips

**Comment by sinnykumari** [comment]
With PR https://github.com/openshift/machine-config-operator/pull/2884/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R28 , required openshift/api change should already be available in MCO.
Closing this PR as this is no longer needed. Feel free to reopen if you think this PR is still needed.
/close

**Comment by ehashman** [comment]
@sinnykumari sure did: https://github.com/openshift/machine-config-operator/pull/2884/files#diff-3e7e0757e1678ddc9ff3d1a3cd38b12d0eb46eb400727782bd9e145b4f049344

thanks!

**Pull request closed without merging**
