### PR TITLE
Controlplane upgrades prep

### PR DESCRIPTION
**Pull request by cgwalters**
Prep work for  https://github.com/openshift/machine-config-operator/pull/1946 - basically stubbing out infrastructure.  See patches for details.

### CODE REVIEW

**Comment by ashcrow** [comment]
e2e-gcp-op failure is an infra flake (hitting limits)

**Comment by cgwalters** [comment]
The baseline cluster tests aren't really covering any of the new code here; the upgrade and `e2e-gcp-op` tests are most useful.

Also man...we really need to solve the problem of having controller pod logs go away when we upgrade and they get rescheduled.

**Comment by cgwalters** [comment]
OK cool, seeing the expected logs in e2e-gcp-op; this one should be good to go!
[e2e-gcp-upgrade](https://prow.ci.openshift.org/?job=*e2e-gcp-upgrade*) is quite red across the board which...a lot of that will hopefully what will be fixed by https://github.com/openshift/machine-config-operator/pull/1946 !  We'll see.

Dunno about metal-ipi.

**Comment by runcom** [comment]
/approve

@openshift/openshift-team-mco-maintainers ptal

**Comment by kikisdeliveryservice** [comment]
Metal-ipi job is dead. Let's try these 2 again.

/test e2e-gcp-op
/test e2e-aws-scaleup-rhel7

**Comment by kikisdeliveryservice** [comment]
Gah I meant

/test e2e-gcp-upgrade

**Comment by cgwalters** [comment]
Ooh hey, I had a logic error there causing us to try to update all controlplane nodes at once...hooray for CI tests.

**Comment by cgwalters** [comment]
OK e2e-gcp-upgrade is unbroken.

Hmm interesting, some of Prometheus test failures in e2e-gcp-op seem to be unique.

**Comment by cgwalters** [comment]
This one should be good to go, can I get a lgtm?

**Comment by cgwalters** [comment]
Can't affect rhel7 nodes really
/override e2e-aws-scaleup-rhel7

**Comment by cgwalters** [comment]
This is prep for fixing the upgrade problems, and I'm confident now we're not breaking anything new here.
/override ci/prow/e2e-gcp-upgrade

**Comment by ericavonb** [comment]
Catching up on all the issues behind this PR. I don't like adding new etcd-specific logic to the MCO. It feels like this moves us backwards from separating out etcd concerns into its own operator. Can we do this in a more component-agnostic way?

Something like, a node label or annotation that specifies upgrade priority classes maybe?

**Comment by ericavonb** [comment]
Similar requirement came up here: https://github.com/openshift/machine-config-operator/issues/662#issuecomment-510057616

**Comment by cgwalters** [comment]
> Catching up on all the issues behind this PR. I don't like adding new etcd-specific logic to the MCO. It feels like this moves us backwards from separating out etcd concerns into its own operator. Can we do this in a more component-agnostic way?

Let's debate in https://github.com/openshift/machine-config-operator/issues/1897 ?

**Pull request merged**
