### PR TITLE
image-references: Update maipo oscontainer

### PR DESCRIPTION
**Pull request by cgwalters**
This isn't the long term path, but let's do this until
we have that implemented.

### CODE REVIEW

**Comment by ashcrow** [comment]
```
aws_route_table_association.route_net.1: timeout while waiting for state to become 'success'
```

/test e2e-aws

**Comment by jlebon** [comment]
Can we add the corresponding OS version as a comment there?

**Comment by cgwalters** [comment]
For reference I was confused about how things work; the images referenced here are basically never really used...we should probably replace them with dummy values now.

The source of truth (AIUI) is the imagestreams maintained at api.ci which feed into the release controller, which uses them to update the release payload's `machine-os-content` and `oc adm release new` will use that digested pull spec and replace the value here.

https://github.com/openshift/origin/pull/21998 was trying to do this a different way but for now we're going to do some manual tagging.

**Pull request merged**
