### PR TITLE
WIP: With node crd

### PR DESCRIPTION
**Pull request by harche**
**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@harche what is the background for this pr?

/hold

**Comment by harche** [comment]
> @harche what is the background for this pr?
> 
> /hold

https://issues.redhat.com/browse/OCPNODE-638 

But we are far from a final implementation. This PR was created so that we can use cluster-bot for our testing, and hence `WIP` in the subject.

**Comment by kikisdeliveryservice** [comment]
> > @harche what is the background for this pr?
> > /hold
> 
> https://issues.redhat.com/browse/OCPNODE-638
> 
> But we are far from a final implementation. This PR was created so that we can use cluster-bot for our testing, and hence `WIP` in the subject.

As I mentioned to @rphillips there was no enhancement or discussion about adding a new controller to the MCO. That is an extremely disruptive change that would require serious consideration. I'd encourage you to look for a simpler path that doesn't require such a huge change. Is this actually necessary?

**Comment by harche** [comment]
@kikisdeliveryservice thanks for your inputs. 

Recently we had proposed to add [Node API](https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/mco-cgroupsv2-support.md#api-extensions) which will be used for node specific cluster configuration. To begin with it will be used for enabling [cgroups v2](https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/mco-cgroupsv2-support.md#control-group-v2-enablement-on-new-clusters) on the host as well as supporting [WorkerLatencyProfiles](https://github.com/openshift/enhancements/blob/master/enhancements/worker-latency-profile/worker-latency-profile.md#workerlatencyprofile). When it comes to `WorkerLatencyProfile` apart from MCO, Kube Controller Manager Operator and Kube API Server Operator [will use this Node API](https://github.com/openshift/enhancements/blob/master/enhancements/worker-latency-profile/worker-latency-profile.md#operational-aspects-of-api-extensions). In the near future, we will expand this Node API to have more node specific features such as enabling `crun` runtime on the hosts. 

I am not sure, if we can replace the Node API with Infra object. However, I agree that we should submit an enhancement proposal for adding a new controller. In fact, we now even have a [jira story](https://issues.redhat.com/browse/OCPNODE-864) to track that effort.

**Comment by harche** [comment]
@kikisdeliveryservice I had a chat with @rphillips around how infra object is handled via controller config. I will spend some more time in understanding how this can be used with what we want to achieve with Node CR.

**Pull request closed without merging**
