### PR TITLE
Bug 1789565: [release-4.2] Fix osImageURL upgrade race

### PR DESCRIPTION
**Pull request by runcom**
same as #1357 but for 4.2 to test it in CI (4.2->4.2)

### CODE REVIEW

**Comment by crawford** [comment]
Why isn't https://github.com/openshift/machine-config-operator/pull/1359/commits/031fee633ed7a92cd5b4dc9093e809334d3b6ec9 needed as well?

**Comment by runcom** [comment]
> Why isn't [031fee6](https://github.com/openshift/machine-config-operator/commit/031fee633ed7a92cd5b4dc9093e809334d3b6ec9) needed as well?

That has been removed as it can cause a race with the old MCO if we create the osimageurl CM before starting the new MCO. That case is similar to what happened during the 4.1->4.2 etcd bug.
It should be the MCO understanding and waiting on the correct osimageurl to show up, not the other way around.

**Comment by runcom** [comment]
@kikisdeliveryservice @yuqi-zhang @sinnykumari @ericavonb ptal

**Comment by wking** [comment]
[VERIFIED in 4.3][1]:

/bugzilla refresh

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1786993#c41

**Pull request merged**
