### PR TITLE
Dedupe on-prem templates

### PR DESCRIPTION
**Pull request by bcrochet**
There are a number of duplicated files across the on-prem platforms.
This patch begins the process of de-duplicating them. This is going
to be a bigger task than the bootstrap manifests, as not all of the
files are duplicated, and some have differences that would not lend
to being deduped. But this at least starts small, and proves the
concept.

**- What I did**

**- How to verify it**

**- Description for the changelog**

Dedupe templates for on-prem platforms

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Only skimmed this I think the lines deleted count looks awesome!

**Comment by ravidbro** [comment]
I put /hold to stop the bot from testing every hour until the conflict will be resolved

**Pull request merged**
