### PR TITLE
Revert disabling authorized_keys.d  Pull 2087  

### PR DESCRIPTION
**Pull request by fortinj66**
revert  https://github.com/openshift/machine-config-operator/pull/2087
            until https://github.com/openshift/machine-config-operator/issues/2385 is fixed

The authorized_keys file is not being created on cluster install and with authorized_keys.d disabled ssh into the
 cluster nodes is not possible without manual intervention.  Once that issue is fixed authorized_keys.d can be disabled.
    
 The entry has to be commented out so that the original value does not get overwritten.

### CODE REVIEW

**Review by kikisdeliveryservice — CHANGES_REQUESTED** [review]
can you clean up the commit, there should only be one.

**Comment by fortinj66** [comment]
Yep...  I'm not sure why I got two...  sigh

**Comment by fortinj66** [comment]
extra commit included...  closing for https://github.com/openshift/machine-config-operator/pull/2388

**Comment by fortinj66** [comment]
closing for https://github.com/openshift/machine-config-operator/pull/2388

**Pull request closed without merging**
