### PR TITLE
Update vSphere templates and manifests

### PR DESCRIPTION
**Pull request by jcpowermac**
The templates and manifests used in baremetal
have been updated for various bugfixes.  Updating
for both those changes and vSphere IPI/UPI
scenarios.

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Could you run a `make update`

**Comment by jcpowermac** [comment]
> Could you run a `make update`

Completely slipped my mind, thanks, updated

**Comment by kikisdeliveryservice** [comment]
e2e-vsphere tests are broken, so this PR shouldnt be blocked by that:
https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-vsphere

**Comment by yuqi-zhang** [comment]
Just wanted to see if we can catch an early failure of some sort, if any happen
/approve

**Comment by jcpowermac** [comment]
I used a custom release image to test this both in vSphere UPI and IPI if it makes you feel any better - multiple times to confirm I didn't miss anything and correspondingly break something

**Comment by kikisdeliveryservice** [comment]
> I used a custom release image to test this both in vSphere UPI and IPI if it makes you feel any better - multiple times to confirm I didn't miss anything and correspondingly break something
thanks @jcpowermac 
/lgtm

**Comment by kikisdeliveryservice** [comment]
Well, turns out I already opened a BZ for the failing test last month: 
https://bugzilla.redhat.com/show_bug.cgi?id=1813026

Supposedly it is now fixed, so let's see. If not I'll reopen the BZ:
/test e2e-vsphere

**Pull request merged**
