### PR TITLE
[baremetal] Add ipv6 support to static DHCP configuration

### PR DESCRIPTION
**Pull request by cybertron**
This is essentially an ipv6 version of #2188.

Co-authored-by: Antoni Segura Puimedon <antoni@redhat.com>

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by celebdor** [comment]
/lgtm

I just tried it locally and verified it to work. Some snippets:
```
[asegurap@r640-u01 dev-scripts]$ ssh core@fd2e:6f44:5dd8:c956::14                                                                                              
Red Hat Enterprise Linux CoreOS 47.83.202011301442-0             
  Part of OpenShift 4.7, RHCOS is a Kubernetes native operating system
  managed by the Machine Config Operator (`clusteroperator/machine-config`).
                                                                   
WARNING: Direct SSH access to machines is not recommended; instead,
make configuration changes via `machineconfig` objects:
  https://docs.openshift.com/container-platform/4.7/architecture/architecture-rhcos.html

---
Last login: Wed Dec  2 16:52:56 2020 from fd2e:6f44:5dd8:c956::1
[core@master-0 ~]$ nmcli --get-value ipv6.method c show ovs-if-br-ex                                                                                           
manual
[core@master-0 ~]$ nmcli c show ovs-if-br-ex | grep ipv6                                                                                             ipv6.method:                            manual
ipv6.dns:                               fe80::5054:ff:fe5b:122f,fd2e:6f44:5dd8:c956::1
ipv6.dns-search:                        ostest.test.metalkube.org
ipv6.dns-options:                       --
ipv6.dns-priority:                      0
ipv6.addresses:                         fd2e:6f44:5dd8:c956::14/128
ipv6.gateway:                           fe80::5054:ff:fe5b:122f
ipv6.routes:                            { ip = fd2e:6f44:5dd8:c956::/120, mt = 800 }; { ip = ff00::/8, mt = 256 }; { ip = fe80::/64, mt = 800 }; { ip = fe80::1e17:3a19:50ef:6499/128, mt = 0 }; { ip = fd2e:6f44:5dd8:c956::14/128, mt = 800 }; { ip = fd2e:6f44:5dd8:c956::14/128, mt = 0 }
ipv6.route-metric:                      -1
ipv6.route-table:                       0 (unspec)
ipv6.routing-rules:                     --
ipv6.ignore-auto-routes:                no
ipv6.ignore-auto-dns:                   no
ipv6.never-default:                     no
ipv6.may-fail:                          yes
ipv6.ip6-privacy:                       -1 (unknown)
ipv6.addr-gen-mode:                     stable-privacy
ipv6.ra-timeout:                        0 (default)
ipv6.dhcp-duid:                         --
ipv6.dhcp-iaid:                         --
ipv6.dhcp-timeout:                      0 (default)
ipv6.dhcp-send-hostname:                yes
ipv6.dhcp-hostname:                     --
ipv6.dhcp-hostname-flags:               0x0 (none)
ipv6.token:                             --
[core@master-0 ~]$ 
```

**Comment by celebdor** [comment]
image

As seen in the image. I killed dnsmasq (that was providing DHCP), rebooted and sshed to the machine again successfully
master-0 is `Ready` as well.

```[asegurap@r640-u01 dev-scripts]$ oc get nodes
NAME                                 STATUS   ROLES    AGE   VERSION
master-0.ostest.test.metalkube.org   Ready    master   68m   v1.19.2+ad738ba
master-1.ostest.test.metalkube.org   Ready    master   73m   v1.19.2+ad738ba
master-2.ostest.test.metalkube.org   Ready    master   73m   v1.19.2+ad738ba
worker-0.ostest.test.metalkube.org   Ready    worker   26m   v1.19.2+ad738ba
worker-1.ostest.test.metalkube.org   Ready    worker   39m   v1.19.2+ad738ba
[asegurap@r640-u01 dev-scripts]$

**Comment by sinnykumari** [comment]
lgtm
based on celebdor testing, seems to be working fine
/approve

**Comment by kikisdeliveryservice** [comment]
is prow acting up bc i see: `Pending — Not mergeable. Needs approved, lgtm labels.` <-- but this does have those labels?

**Comment by kikisdeliveryservice** [comment]
HOORAY! :fireworks:

**Pull request merged**
