### PR TITLE
Bug 2035199: add support for IPv6 and multiple routes to the same destination when setting MTU on routes during MTU migration

### PR DESCRIPTION
**Pull request by jcaamano**
Add support for IPv6, with a focus on (1) dynamically learned IPv6 routes and (2) scenarios with multiple routes to the same destination. For each route destination through a relevant device (e.g. br-ex or a physical interface), we take all routes to that destination (thus including different devs and metrics), so as to add equivalent higher-priority routes where:

- route MTU is set to new MTU if route MTU > new MTU or if there's no route MTU, only for handled devices;
- proto is set to static, which will take priority over dynamic routes;
- metric is set to the highest priority possible value while keeping the existing ordering between routes to the same destination;
- we use "ip replace" instead of "ip change", so that we effectively add a new route unless one with the same metric already exists, in which case we just override it.
- handle multipath routes

The script is idempotent.

Handling routes MTU with a NM dispatcher script has proven to be difficult because the route table changes as devices come up, so setting it up as a systemd service instead. 

Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>
Signed-off-by: Riccardo Ravaioli rravaiol@redhat.com

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by jcaamano** [comment]
`e2e-agnostic-upgrade` fails 90% of the time but has nothign to do with this PR :/

**Review by kikisdeliveryservice — APPROVED** [review]

**Pull request merged**
