### PR TITLE
Use library-go resourcemerge helper functions

### PR DESCRIPTION
**Pull request by mkenigs**
This is a commit I found lying around that I thought was blocked on creating an MCO CRD, but it isn't. It should be functionally equivalent except for the changes to MergeMap and MergeOwnerRefs. Is that difference okay?

Replaces custom versions of helper functions with the library-go
versions of EnsureObjectMeta, SetStringIfSet, BoolPtr, MergeMap, and
MergeOwnerRefs
Examining each change:
EnsureObjectMeta calls the same functions (SetStringIfSet, MergeMap,
and MergeOwnerRefs)
SetStringIfSet and BoolPtr are identical
MergeMap and MergeOwnerRefs remove keys that have "-" as a suffix in the
"required" map

### CODE REVIEW

**Comment by cgwalters** [comment]
Looks sane to me; this should be covered by our CI as far as I know.
/approve

Hmm, though why did just the CI test build fall over?

```
 Building github.com/openshift/machine-config-operator/cmd/machine-config-controller (machine-config-daemon-4.6.0-202006240615.p0-1374-g57efbe9c-dirty, 57efbe9c691607412e61817f88bd0122a0971264) for linux/amd64
# github.com/openshift/machine-config-operator/lib/resourcemerge
lib/resourcemerge/apps.go:11:2: undefined: EnsureObjectMeta
lib/resourcemerge/apps.go:28:2: undefined: EnsureObjectMeta 
```

**Comment by mkenigs** [comment]
Fixed, I'd forgotten to change code that will just get dropped once we use library-go for Deployments and Daemonsets

**Comment by mkenigs** [comment]
Can't remember when code freeze is, but does this look okay?

**Comment by jkyros** [comment]
This looks sane to me also.

I did check the logs/event volume and this doesn't seem to have any negative side-effects in that realm. 

/test e2e-aws

**Comment by cgwalters** [comment]
We'll almost certainly want this to help ensure we correctly handle things like changing the daemonset arguments, etc.
/lgtm

**Pull request merged**
