### PR TITLE
Add support for Azure platform

### PR DESCRIPTION
**Pull request by awesomenix**
**- What I did**

Add support for Azure platform

**- How to verify it**

installer will add support for azure platform soon.

**- Description for the changelog**
Add support for Azure platform

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
does this have an exception?  is there an existing installer pr (if so please link it)

/hold

**Comment by kikisdeliveryservice** [comment]
afaict, this would be in 4.2

**Comment by awesomenix** [comment]
@kikisdeliveryservice https://github.com/openshift/installer/pull/1534

**Comment by awesomenix** [comment]
@kikisdeliveryservice @enxebre can this be merged please, all other operators have support for azure platform except for this one, are there additional gates for this operator?

**Comment by enxebre** [comment]
this is part of an effort for upcoming Azure support
https://github.com/openshift/installer/pull/1534/files
https://github.com/openshift/cluster-api-provider-azure
One of the repo owners should validate this PR doesn't suppose any risk for 4.1, otherwise
/lgtm

**Comment by kikisdeliveryservice** [comment]
RHCOS isn't slated to support Azure until 4.2 and given how important the MCO is for 4.1 I'd much rather hold any new feature until 4.2 as planned. 
Happy to review later.

**Comment by kikisdeliveryservice** [comment]
RHCOS isn't slated to support Azure in this release and given how important the MCO,  I'd much rather hold any new feature until a future release as planned. 
Happy to review later.

**Comment by runcom** [comment]
This has a (almsot) 0.000% chance of breaking anything here as these if(s) are gonna be gated anyway.

/approve

**Comment by ashcrow** [comment]
> This has a (almsot) 0.000% chance of breaking anything here as these if(s) are gonna be gated anyway.

That's likely the case, but in terms of process, was the change approved to be merged into the installer?

**Comment by crawford** [comment]
Azure-related PRs are approved to be merged as long as they impose very little risk on the project. I agree with @runcom that this is extremely unlikely to break existing functionality, so this can be merged. Sorry for the surprise. I forgot we had to make any changes to the MCO.

**Pull request merged**
