### PR TITLE
pkg/controller: start informers before populating store in tests

### LINKED ISSUE #417: TestKubeletConfigCreate flake?
This test fails from time to time, let's track it down
```
--- FAIL: TestKubeletConfigCreate (0.12s)
    --- PASS: TestKubeletConfigCreate/aws (0.10s)
    --- FAIL: TestKubeletConfigCreate/none (0.01s)
    	kubelet_config_controller_test.go:207: Expected
    			testing.CreateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"create", Resource:schema.GroupVersionResource{Group:"", Version:"", Resource:"machineconfigs"}, Subresource:""}, Name:"", Object:(*v1.MachineConfig)(0xc4202f3180)}
    		got
    			testing.UpdateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"update", Resource:schema.GroupVersionResource{Group:"machineconfiguration.openshift.io", Version:"v1", Resource:"kubeletconfigs"}, Subresource:"status"}, Object:(*v1.KubeletConfig)(0xc4202f0780)}
    	kubelet_config_controller_test.go:176: 2 additional expected actions:[{ActionImpl:{Namespace: Verb:patch Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:kubeletconfigs} Subresource:} Name:smaller-max-pods Patch:[123 34 109 101 116 97 100 97 116 97 34 58 123 34 102 105 110 97 108 105 122 101 114 115 34 58 91 34 57 57 45 109 97 115 116 101 114 45 104 53 53 50 109 45 115 109 97 108 108 101 114 45 109 97 120 45 112 111 100 115 45 107 117 98 101 108 101 116 34 93 125 125]} {ActionImpl:{Namespace: Verb:update Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:kubeletconfigs} Subresource:status} Object:0xc420133900}]
```

```
--- FAIL: TestKubeletConfigUpdates (0.17s)
    --- PASS: TestKubeletConfigUpdates/aws (0.07s)
    --- PASS: TestKubeletConfigUpdates/none (0.05s)
    --- FAIL: TestKubeletConfigUpdates/unrecognized (0.05s)
    	kubelet_config_controller_test.go:213: Expected
    			testing.GetActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"get", Resource:schema.GroupVersionResource{Group:"", Version:"", Resource:"machineconfigs"}, Subresource:""}, Name:"99-master-p9l4d-kubelet"}
    		got
    			testing.UpdateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"update", Resource:schema.GroupVersionResource{Group:"machineconfiguration.openshift.io", Version:"v1", Resource:"kubeletconfigs"}, Subresource:"status"}, Object:(*v1.KubeletConfig)(0xc4203b1b80)}
    	kubelet_config_controller_test.go:76: 3 additional expected actions:[{ActionImpl:{Namespace: Verb:create Resource:{Group: Version: Resource:machineconfigs} Subresource:} Name: Object:0xc42003cf00} {ActionImpl:{Namespace: Verb:patch Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:kubeletconfigs} Subresource:} Name:smaller-max-pods Patch:[123 34 109 101 116 97 100 97 116 97 34 58 123 34 102 105 110 97 108 105 122 101 114 115 34 58 91 34 57 57 45 109 97 115 116 101 114 45 104 53 53 50 109 45 115 109 97 108 108 101 114 45 109 97 120 45 112 111 100 115 45 107 117 98 101 108 101 116 34 93 125 125]} {ActionImpl:{Namespace: Verb:update Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:kubeletconfigs} Subresource:status} Object:0xc4203b0f00}]
```

### LINKED ISSUE #444: Flake TestShouldMakeProgress
The test in $TITLE is racy, I've seen it failing now in #439 - here's the job https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/439/pull-ci-openshift-machine-config-operator-master-unit/1155

The test flake is easily reproducible with:
```
GOCACHE=off go test -race -v ./cmd/... ./pkg/... ./lib/...
```

Here's the failing output:

```
=== RUN   TestShouldMakeProgress
--- FAIL: TestShouldMakeProgress (0.01s)
    node_controller_test.go:171: Action update machineconfigpools has wrong object
        Diff:
         (*v1.MachineConfigPool){TypeMeta:(v1.TypeMeta){Kind:(string) APIVersion:(string)machineconfiguration.openshift.io/v1} ObjectMeta:(v1.ObjectMeta){Name:(string)test-cluster-master GenerateName:(string) Namespace:(string) SelfLink:(string) UID:(types.UID) ResourceVersion:(string) Generation:(int64)0 CreationTimestamp:(v1.Time){Time:(time.Time){wall:(uint64)0 ext:(int64)0 loc:(*time.Location)<nil>}} DeletionTimestamp:(*v1.Time)<nil> DeletionGracePeriodSeconds:(*int64)<nil> Labels:(map[string]string)<nil> Annotations:(map[string]string)<nil> OwnerReferences:([]v1.OwnerReference)<nil> Initializers:(*v1.Initializers)<nil> Finalizers:([]string)<nil> ClusterName:(string)} Spec:(v1.MachineConfigPoolSpec){MachineConfigSelector:(*v1.LabelSelector)<nil> MachineSelector:(*v1.LabelSelector){MatchLabels:(map[string]string)map[node-role:master] MatchExpressions:([]v1.LabelSelectorRequirement)<nil>} Paused:(bool)false MaxUnavailable:(*intstr.IntOrString){Type:(intstr.Type)0 IntVal:(int32)1 StrVal:(string)}} Status:(v1.MachineConfigPoolStatus){ObservedGeneration:(int64)0 Configuration:(v1.MachineConfigPoolStatusConfiguration){ObjectReference:(v1.ObjectReference){Kind:(string) Namespace:(string) Name:(string)v1 UID:(types.UID) APIVersion:(string) ResourceVersion:(string) FieldPath:(string)} Source:([]v1.ObjectReference)<nil>} MachineCount:(int32)2 UpdatedMachineCount:(int32)1 ReadyMachineCount:(int32)1 UnavailableMachineCount:(int32)
        
        A: 0 Conditions:([]v1.MachineConfigPoolCondition)[{Type:(v1.MachineConfigPoolConditionType)Updated Status:(v1.ConditionStatus)False LastTransitionTime:(v1.Time){Time:(time.Time){wall:(uint64)0 ext:(int64)0 loc:(*time.Location)<nil>}} Reason:(string) Message:(string)} {Type:(v1.MachineConfigPoolConditionType)Updating Status:(v1.ConditionStatus)True LastTransitionTime:(v1.Time){Time:(time.Time){wall:(uint64)0 ext:(int64)0 loc:(*time.Location)<nil>}} Reason:(string)All nodes are updating to v1 Message:(string)} {Type:(v1.MachineConfigPoolConditionType)Degraded Status:(v1.ConditionStatus)False LastTransitionTime:(v1.Time){Time:(time.Time){wall:(uint64)0 ext:(int64)0 loc:(*time.Location)<nil>}} Reason:(string) Message:(string)}]}}
        
        B: 1 Conditions:([]v1.MachineConfigPoolCondition)[{Type:(v1.MachineConfigPoolConditionType)Updated Status:(v1.ConditionStatus)False LastTransitionTime:(v1.Time){Time:(time.Time){wall:(uint64)0 ext:(int64)0 loc:(*time.Location)<nil>}} Reason:(string) Message:(string)} {Type:(v1.MachineConfigPoolConditionType)Updating Status:(v1.ConditionStatus)True LastTransitionTime:(v1.Time){Time:(time.Time){wall:(uint64)0 ext:(int64)0 loc:(*time.Location)<nil>}} Reason:(string)All nodes are updating to v1 Message:(string)} {Type:(v1.MachineConfigPoolConditionType)Degraded Status:(v1.ConditionStatus)False LastTransitionTime:(v1.Time){Time:(time.Time){wall:(uint64)0 ext:(int64)0 loc:(*time.Location)<nil>}} Reason:(string) Message:(string)}]}}
        ```

### LINKED ISSUE #449: TestContainerRuntimeConfigCreate flake
Basically the same flake as #417 but for the containerruntime controller:
Notice that #417 is closed but we've spotted it again, so we'll reopen it.

```
--- FAIL: TestContainerRuntimeConfigCreate (0.25s)
    --- FAIL: TestContainerRuntimeConfigCreate/aws (0.03s)
    	container_runtime_config_controller_test.go:207: Expected
    			testing.GetActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"get", Resource:schema.GroupVersionResource{Group:"", Version:"", Resource:"machineconfigs"}, Subresource:""}, Name:"99-master-426vz-containerruntime"}
    		got
    			testing.UpdateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"update", Resource:schema.GroupVersionResource{Group:"machineconfiguration.openshift.io", Version:"v1", Resource:"containerruntimeconfigs"}, Subresource:"status"}, Object:(*v1.ContainerRuntimeConfig)(0xc420135540)}
    	container_runtime_config_controller_test.go:176: 5 additional expected actions:[{ActionImpl:{Namespace: Verb:update Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:containerruntimeconfigs} Subresource:status} Object:0xc420134000} {ActionImpl:{Namespace: Verb:update Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:containerruntimeconfigs} Subresource:status} Object:0xc420134000} {ActionImpl:{Namespace: Verb:create Resource:{Group: Version: Resource:machineconfigs} Subresource:} Name: Object:0xc4200d2500} {ActionImpl:{Namespace: Verb:patch Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:containerruntimeconfigs} Subresource:} Name:set-log-level Patch:[123 34 109 101 116 97 100 97 116 97 34 58 123 34 102 105 110 97 108 105 122 101 114 115 34 58 91 34 57 57 45 109 97 115 116 101 114 45 115 120 50 118 114 45 99 111 110 116 97 105 110 101 114 114 117 110 116 105 109 101 34 93 125 125]} {ActionImpl:{Namespace: Verb:update Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:containerruntimeconfigs} Subresource:status} Object:0xc420134000}]
```

Jobs:

- https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/401/pull-ci-openshift-machine-config-operator-master-unit/1211

### LINKED ISSUE #451: TestKubeletConfigUpdates flake
Similar to #417 and #444, seen in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/450/pull-ci-openshift-machine-config-operator-master-unit/1222

```
--- FAIL: TestKubeletConfigUpdates (0.17s)
    --- PASS: TestKubeletConfigUpdates/aws (0.09s)
    --- FAIL: TestKubeletConfigUpdates/none (0.02s)
    	kubelet_config_controller_test.go:213: Expected
    			testing.UpdateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"update", Resource:schema.GroupVersionResource{Group:"", Version:"", Resource:"machineconfigs"}, Subresource:""}, Object:(*v1.MachineConfig)(0xc4203b2a00)}
    		got
    			testing.UpdateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"update", Resource:schema.GroupVersionResource{Group:"machineconfiguration.openshift.io", Version:"v1", Resource:"kubeletconfigs"}, Subresource:"status"}, Object:(*v1.KubeletConfig)(0xc420132500)}
    	kubelet_config_controller_test.go:76: 2 additional expected actions:[{ActionImpl:{Namespace: Verb:patch Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:kubeletconfigs} Subresource:} Name:smaller-max-pods Patch:[123 34 109 101 116 97 100 97 116 97 34 58 123 34 102 105 110 97 108 105 122 101 114 115 34 58 91 34 57 57 45 109 97 115 116 101 114 45 109 119 119 116 103 45 107 117 98 101 108 101 116 34 93 125 125]} {ActionImpl:{Namespace: Verb:update Resource:{Group:machineconfiguration.openshift.io Version:v1 Resource:kubeletconfigs} Subresource:status} Object:0xc4203aef00}]
```

/cc @sjenning @rphillips

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

The indexer in the informer uses a store which manages object using a read-write lock, the flakes come from the fact that if we don't sync up the store before adding objects, the listing of objects can race against an add (verified this by adding a bunch of debug logs during investigation and I could spot that `lister.List` can return empty even if we added objects to the indexer before starting the informers themselves).

Fixes #417 
Fixes #444 
Fixes #451 
Fixes #449 

Cannot reproduce anymore with this patch (running in a loop since 3 hours now), I'm able to consistently reproduce by running `go test -race` w/o this patch.

**- How to verify it**

```
true && while [ $? -eq 0 ]; do GOCACHE=off go test -race -v ./cmd/... ./pkg/... ./lib/...; done
```

w/o this patch the command above fails as soon as the flake makes the test error out. With the patch, the above continues perpetually.

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
CI glitch...

```
could not wait for build: the build machine-config-server failed after 6m6s with reason PullBuilderImageFailed: Failed pulling builder image.

Pulling image docker-registry.default.svc:5000/ci-op-v6y05...8fe8db228e015b2bd5ec62da99e0505f8fd6dbc7ce842e2153680dc ...

Pulling image registry.svc.ci.openshift.org/openshift/release:golang-1.10 ...
error: build error: failed to pull image: Get https://regi...t canceled (Client.Timeout exceeded while awaiting headers)
```

/retest

**Comment by runcom** [comment]
still glitch https://github.com/openshift/machine-config-operator/pull/457#issuecomment-465112310

**Comment by runcom** [comment]
CI errors apart (not unit), this is fixing the flakes as my tests never failed in more than 5 hours

**Comment by runcom** [comment]
the glitch is a CI issue

**Comment by runcom** [comment]
aws limit

/retest

**Comment by cgwalters** [comment]
LGTM, giving for another final review/merge:

/assign kikisdeliveryservice

**Comment by rphillips** [comment]
lgtm (deferring to @kikisdeliveryservice for review). Nice find

**Comment by kikisdeliveryservice** [comment]
HAProxy and other known flakes. 

/test e2e-aws

**Comment by abhinavdahiya** [comment]
known [flake](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/457/pull-ci-openshift-machine-config-operator-master-e2e-aws/2056#openshift-tests-the-bootstrap-user-should-successfully-login-with-password-decoded-from-kubeadmin-secret-suiteopenshiftconformanceparallel). 
```console
fail [github.com/openshift/origin/test/extended/bootstrap_user/bootstrap_user_login.go:52]: Expected error:
    <*util.ExitError | 0xc422561740>: {
        Cmd: "oc login --config=/tmp/configfile916071508 --namespace=e2e-test-bootstrap-login-cpctm -u kubeadmin -p 5LpcuRoMeuNntNkAusTRa269NuAbQoU9ptn4aloHbp4",
        StdErr: "Error from server (InternalError): Internal error occurred: unexpected response: 400",
        ExitError: {
            ProcessState: {
                pid: 11753,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 268025},
                    Stime: {Sec: 0, Usec: 66749},
                    Maxrss: 94440,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 15028,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 1198,
                    Nivcsw: 27,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
```

https://github.com/openshift/origin/pull/22088 is moving it to flake

**Comment by kikisdeliveryservice** [comment]
Thanks for the update on that test, @abhinavdahiya !

**Comment by runcom** [comment]
CI errors tracked in slack

/retest

**Pull request merged**
