### PR TITLE
OCPBUGS-18902: Internal Registry Secrets merge causing excessive API calls

### PR DESCRIPTION
**Pull request by djoshy**
**- What I did**
Added listers to hopefully reduce the amount of calls caused by #3806 

**- How to verify it**
internal registry secrets merge should work as before, but we should see a good amount of reduction in API calls by this code path

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
general logic lgtm!

**Comment by sinnykumari** [comment]
/lgtm
Feel free to remove hold once we have qe approval label

**Comment by sergiordlr** [comment]
Thank you @browsell for helping us to verify the number of api calls and cpu usage.

Since everything is ok, we add the qe-approved-label

/label qe-approved

**Comment by sinnykumari** [comment]
Looks like we need to rebase the change

**Comment by djoshy** [comment]
/unhold

Rebased, needs re-lgtm (:

**Pull request merged**
