### PR TITLE
Bug 1825417: Make getting the suffix of an MC more robust

### PR DESCRIPTION
**Pull request by umohnani8**
Fixes #1825417 (https://bugzilla.redhat.com/show_bug.cgi?id=1825417)

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

**- What I did**
Instead of relying on the order in which the ctrcfg
objects are added to the list, let's go through the
list and find the maximum suffix value used. We can
then add 1 to the max suffix value to be used for the
MC when creating the new ctrcfg object.

**- How to verify it**
Create multiple ctrcfg CRs and a new MC with a different suffix will be created for each one.

**- Description for the changelog**

### CODE REVIEW

**Review by mtrmac — COMMENTED** [review]
(Warning: based only on the diff, without fully understanding the operators.)

- Presumably `getManagedKubeletConfigKey` needs to be updated as well.
- This is Nth case of such duplication causing risk of not fixing the same bug everywhere. Wouldn’t it be well worth it to deduplicate the logic, by now? 
- It would be nice to have tests — perhaps split the `client.` API accesses from the underlying logic, and write unit tests for the logic.

**Comment by umohnani8** [comment]
There are 2 separate bugs so opened separate PRs, the kubelet config fix is in https://github.com/openshift/machine-config-operator/pull/2459

**Review by yuqi-zhang — APPROVED** [review]
The code itself seems fine to me. Just curious, I recall trying to reproduce this bug with you, what exactly was the reproduction condition?

**Comment by umohnani8** [comment]
@yuqi-zhang I wasn't able to always reproduce the issue, but when I did I noticed that the new ctrcfg was being added to the beginning of the items list instead of being appended to it. That was causing issues when were relying on the order to be newest at the end of the items list. So fixed it up to just look through the list and find the max suffix instead of checking the most recent ctrcfg that was created.

**Pull request merged**
