### PR TITLE
[release-4.5] Bug 1845636: etcd-quorum-guard: update containers section in deployment.yaml

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Made the following changes as settings were not getting
picked up:
- move and correct initialDelaySeconds and periodSeconds
- reorder container sub-elements to nest image under name
- add failureThreshold and timeoutSeconds

Closes: BZ 1845636

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
one mistake

/hold

**Comment by kikisdeliveryservice** [comment]
ok should be good

/hold cancel

**Comment by ashcrow** [comment]
Backport of https://github.com/openshift/machine-config-operator/pull/1818

**Pull request merged**
