### PR TITLE
templates: [on-prem] NM prepender: ensure /etc/systemd/resolved.conf.d dir exists

### PR DESCRIPTION
**Pull request by LorbusChris**
Fixes: https://github.com/openshift/okd/issues/690
See also: #2778 

**- How to verify it**
OKD e2e

**- Description for the changelog**
templates: NM prepender: ensure /etc/systemd/resolved.conf.d dir exists

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by cybertron** [comment]
/lgtm
/retest-required

OCP doesn't use this code path so it shouldn't affect any of our platforms. Change makes sense though.

**Review by kikisdeliveryservice — APPROVED** [review]
Given the above reviews and ci results, approving.

**Pull request merged**
