### PR TITLE
hack: add fish-aliases.sh

### PR DESCRIPTION
**Pull request by mkenigs**
Added some aliases helpful for working with MCD pods when hacking on the
MCO

Not sure if these are too personal or if someone else has better ones, but at least @cheesesashimi wanted to see these

### CODE REVIEW

**Comment by cgwalters** [comment]
Not strongly opposed but...it feels like this type of thing might be better as part of a tool shared across at least ocp core devs.  Hm, there's https://github.com/openshift/openshift-tools which is at least tangentially related.

**Comment by cheesesashimi** [comment]
Good to know that repo exists! I have a few things that might belong there.

**Comment by mkenigs** [comment]
> Not strongly opposed but...it feels like this type of thing might be better as part of a tool shared across at least ocp core devs. Hm, there's https://github.com/openshift/openshift-tools which is at least tangentially related.

Yeah that might be better. openshift-tools does seem kind of tangential though unless I didn't dig far enough. Would this go under scripts? Would another repo be helpful? I know both of you @cgwalters and @cheesesashimi have wrappers for openshift-install, which also seems like something that should be shared

**Comment by cgwalters** [comment]
> I know both of you @cgwalters and @cheesesashimi have wrappers for openshift-install, which also seems like something that should be shared

My wrapper for openshift-install got sophisticated enough that it outgrew being a shell script: https://github.com/cgwalters/xokdinst

**Comment by cheesesashimi** [comment]
I haven't used my `openshift-install` wrapper in quite some time. Now, the only "wrapper" (and I use that term loosely!) I have for it is a cron job that retrieves the latest installer for the release channel I'm interested in (e.g., `4.11.0-0.nightly`) and installs a cluster from that.

**Comment by mkenigs** [comment]
So is `openshift-tools` a good home for this? Didn't quite seem like a good fit. Also @cheesesashimi do you have better aliases? Might just close this if so

**Pull request closed without merging**
