### PR TITLE
Bug 1933772: Revert rework of signal handling

### PR DESCRIPTION
**Pull request by darkmuggle**
We need to revert the following commits due to Bugzilla 1933772
https://github.com/openshift/machine-config-operator/commit/dd7154131a868ec950e87cdfc74d1b89b3919792
https://github.com/openshift/machine-config-operator/commit/6d92a7bb54f5264f2863fdb6859ea1d4d1bfa9c6

### CODE REVIEW

**Comment by sinnykumari** [comment]
@mike-nguyen I think you need to verify if this revert causes bug https://bugzilla.redhat.com/show_bug.cgi?id=1927041 to appear back and then we can mark the bug as failed QA and would require another fix.

/lgtm

**Comment by sinnykumari** [comment]
Putting hold until @mike-nguyen get a chance to review.
/hold

**Comment by yuqi-zhang** [comment]
This is becoming higher priority so I think we should push through the revert ASAP.

/hold cancel
/approve
/lgtm

**Comment by yuqi-zhang** [comment]
The MCO is fine for the failing test, the test itself just has a very low pass rate due to other issues. Will leave the bot to retest

**Pull request merged**
