### PR TITLE
[release-4.9] Bug 2058511: Prepend to search domains instead of replacing

### PR DESCRIPTION
**Pull request by creydr**
Backport of:

* #2823
* #2835
* #2908

### CODE REVIEW

**Comment by mandre** [comment]
Thanks! We still need to reference a 4.9 bz in the PR title to make the bot happy:

/retitle [release-4.9] Bug 2058511: Prepend to search domains instead of replacing

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by cybertron** [comment]
What have I done?! O.O

:-)

**Pull request merged**
