### PR TITLE
Bug 1827143: daemon: consider addition of an RT kernel package as update

### PR DESCRIPTION
**Pull request by sinnykumari**
Install additional RT kernel package if any shipped
as part of update in machine-os-content

Also some code cleanup to simplify RT kernel update logic

### CODE REVIEW

**Comment by sinnykumari** [comment]
Not tested yet
/hold

**Comment by sinnykumari** [comment]
Looks good, relevant log from one of the m-c-d pod during 4.4 to 4.5 upgrade

```
...
I0428 14:15:20.064524  114005 update.go:1346] Updating rt-kernel packages on host: ["uninstall" "kernel-rt-core-4.18.0-147.8.1.rt24.101.el8_1.x86_64" "kernel-rt-modules-4.18.0-147.8.1.rt24.101.el8_1.x86_64" "kernel-rt-modules-extra-4.18.0-147.8.1.rt24.101.el8_1.x86_64" "--install" "/var/lib/containers/storage/overlay/6e1baae6f2e878f032034a02d488dfbe5ab467292c606156907c2b79cf9268e7/merged/kernel-rt-core-4.18.0-147.8.1.rt24.101.el8_1.x86_64.rpm" "--install" "/var/lib/containers/storage/overlay/6e1baae6f2e878f032034a02d488dfbe5ab467292c606156907c2b79cf9268e7/merged/kernel-rt-kvm-4.18.0-147.8.1.rt24.101.el8_1.x86_64.rpm" "--install" "/var/lib/containers/storage/overlay/6e1baae6f2e878f032034a02d488dfbe5ab467292c606156907c2b79cf9268e7/merged/kernel-rt-modules-4.18.0-147.8.1.rt24.101.el8_1.x86_64.rpm" "--install" "/var/lib/containers/storage/overlay/6e1baae6f2e878f032034a02d488dfbe5ab467292c606156907c2b79cf9268e7/merged/kernel-rt-modules-extra-4.18.0-147.8.1.rt24.101.el8_1.x86_64.rpm"]


...
I0428 14:22:26.917565    2185 rpm-ostree.go:368] Running captured: rpm-ostree status
I0428 14:22:27.140608    2185 daemon.go:814] State: idle
AutomaticUpdates: disabled
Deployments:
* pivot://registry.svc.ci.openshift.org/ci-ln-4b5gsm2/stable@sha256:c19d5e4c7db297cc357b770ae11dea25f41b24b0ba3ef637da4ce5de31d219e9
              CustomOrigin: Managed by machine-config-operator
                   Version: 45.81.202004241728-0 (2020-04-24T17:34:15Z)
       RemovedBasePackages: kernel-core kernel-modules kernel kernel-modules-extra 4.18.0-147.8.1.el8_1
             LocalPackages: kernel-rt-kvm-4.18.0-147.8.1.rt24.101.el8_1.x86_64
                            kernel-rt-core-4.18.0-147.8.1.rt24.101.el8_1.x86_64
                            kernel-rt-modules-4.18.0-147.8.1.rt24.101.el8_1.x86_64
                            kernel-rt-modules-extra-4.18.0-147.8.1.rt24.101.el8_1.x86_64

  pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8cea2679f40cd5e5bb95b7f511d444ea7ad74800bcc366d0129eb682459cdffd
              CustomOrigin: Managed by machine-config-operator
                   Version: 44.81.202004260825-0 (2020-04-26T08:30:26Z)
       RemovedBasePackages: kernel-core kernel-modules kernel kernel-modules-extra 4.18.0-147.8.1.el8_1
             LocalPackages: kernel-rt-core-4.18.0-147.8.1.rt24.101.el8_1.x86_64
                            kernel-rt-modules-4.18.0-147.8.1.rt24.101.el8_1.x86_64
                            kernel-rt-modules-extra-4.18.0-147.8.1.rt24.101.el8_1.x86_64
...
```

/hold cancel

**Comment by cgwalters** [comment]
LGTM, thanks for doing this!  The code is definitely better now that we're just reading the parsed rpm-ostree JSON state instead of calling out to the subprocess again.

One thing that might make sense as part of https://github.com/coreos/fedora-coreos-tracker/issues/401
is to have a simple file that's something like:
```
extensions.yaml:
kernel-rt:
  - kernel-rt
  - kernel-rt-kvm
  - kernel-rt-modules
usbguard: {}
```

or something so that we have an abstraction between "feature name" and "list of RPMs making up feature" - kind of like metapackages I guess.

**Comment by runcom** [comment]
> usbguard: {}

do we really want this 😭 I proposed another way of tackling what I think are security options using something like "securityLevels" or profiles. You just set that in an MC and the MCO knows what to install (much like we do with `kernelType`as it's not `kernelRT: true`). We would have `securityLevel: 1` for instance and the MCO installs usbguard for instance - not sure how practical that would be but let's see

**Comment by cgwalters** [comment]
Definitely worth discussing a higher level interface!

**Pull request merged**
