### PR TITLE
cleanup: remove setup-etcd-environment

### PR DESCRIPTION
**Pull request by hexfusion**
This PR will be part of an exercise to clean up all remaining etcd pieces from MCO.

phase 1

- remove setup-etcd-environment command
- remove required flags for etcd-image and kube-client-agent-image

Next, we will remove these flags from the installer. Once they are removed the rest of the remaining etcd templates and logic can be removed.

Once quorum-guard is moved we can remove we can also remove `--etcd-ca` and `--etcd-metric-ca` flags.

### CODE REVIEW

**Comment by hexfusion** [comment]
504 timeout 
/test images

**Comment by hexfusion** [comment]
packet failed

/test e2e-metal-ipi

**Comment by kikisdeliveryservice** [comment]
e2e-metal doesn't look reliable - we can retest but don't have to block on it.

https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-metal-ipi?buildId=1283840497890103296

**Comment by hexfusion** [comment]
> I0716 20:49:34.215017    2799 daemon.go:1115] In desired config rendered-master-b8e511bb502c880a277c90564ef17cf0
MCD is happy doesnt seem related

/test e2e-gcp-upgrade

**Pull request merged**
