### PR TITLE
MCO-1065: MCO-1171: API bump for ManagedBootImages and NodeDisruptionPolicy GA

### PR DESCRIPTION
**Pull request by djoshy**
**- What I did**
This PR currently vendors my API fork, which has the promoted feature gates. This will be updated to use the actual API repo prior to merge. This is currently done for testing purposes. 

**- How to verify it**
- Both of these features will be active in default cluster installs. Refer to #4281, #4267, #4472 for detailed testing instructions.
- All e2es should pass.

API side PR: https://github.com/openshift/api/pull/1975

### CODE REVIEW

**Comment by sergiordlr** [comment]
It has been tested using IPI on GCP

We have executed the following test cases with and without techpreview


Executed test cases with and without techpreview

```
"[sig-mco] MCO Bootimages Author:sregidor-NonHyperShiftHOST-NonPreRelease-Medium-74238-BootImages not updated by default [Disruptive] [Serial]"
"[sig-mco] MCO Bootimages Author:sregidor-NonHyperShiftHOST-NonPreRelease-Medium-74239-ManagedBootImages on GCP. Restore Partial MachineSet images [Disruptive] [Serial]"
"[sig-mco] MCO Bootimages Author:sregidor-NonHyperShiftHOST-NonPreRelease-Medium-74240-ManagedBootImages on GCP. Restore All MachineSet images [Disruptive] [Serial]"
"[sig-mco] MCO Bootimages Author:sregidor-NonHyperShiftHOST-NonPreRelease-Medium-74751-ManagedBootImages on GCP. Fix errors [Disruptive] [Serial]"
"[sig-mco] MCO Bootimages Author:sregidor-NonHyperShiftHOST-NonPreRelease-Medium-74764-ManagedBootImages on GCP. Delete machineset when error [Disruptive] [Serial]"


"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-High-73368-NodeDisruptionPolicy files with action None [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-High-73375-NodeDisruptionPolicy files with action Restart [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-High-73378-NodeDisruptionPolicy files with action Reload [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-High-73385-NodeDisruptionPolicy files with action DaemonReload [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-High-73414-NodeDisruptionPolicy units with action None [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-High-73417-NodeDisruptionPolicy sshkey with action None [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-High-73489-NodeDisruptionPolicy MachineConfigurations is only effective with name cluster"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-Longduration-High-73374-NodeDisruptionPolicy files with action Reboot [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-Longduration-High-73388-NodeDisruptionPolicy files with action Drain [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-Longduration-High-73389-NodeDisruptionPolicy files with multiple actions [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-Longduration-High-73411-NodeDisruptionPolicy units with multiple actions [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-Longduration-High-73413-NodeDisruptionPolicy units with action Reboot [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-Longduration-High-73415-NodeDisruptionPolicy sshkey with multiple actions [Disruptive] [Serial]"
"[sig-mco] MCO NodeDisruptionPolicy Author:rioliu-NonPreRelease-Longduration-High-73418-NodeDisruptionPolicy sshkey with action Reboot [Disruptive] [Serial]"
OCP-75110 - [MCO][MCO-1123] Propagate a NodeDisruptionPolicy failure condition via degrading the daemon
OCP-75109 - [MCO][MCO-1125] NodeDisruptionPolicy files allow paths to be defined for non-disruptive updates
```

We upgraded a cluster from 4.16 -> 4.17+fix. The upgrade was executed without problems.

```
    history:
    - acceptedRisks: |-
        Target release version="" image="registry.build05.ci.openshift.org/ci-ln-qy9q022/release:latest" cannot be verified, but continuing anyway because the update was forced: release images that are not accessed via digest cannot be verified
        Precondition "ClusterVersionRecommendedUpdate" failed because of "UnknownUpdate": RetrievedUpdates=False (VersionNotFound), so the recommended status of updating from 4.16.0-0.nightly-2024-08-01-012721 to 4.17.0-0.ci.test-2024-07-30-153004-ci-ln-qy9q022-latest is unknown.
      completionTime: "2024-08-01T09:16:52Z"
      image: registry.build05.ci.openshift.org/ci-ln-qy9q022/release:latest
      startedTime: "2024-08-01T08:18:38Z"
      state: Completed
      verified: false
      version: 4.17.0-0.ci.test-2024-07-30-153004-ci-ln-qy9q022-latest
    - completionTime: "2024-08-01T06:43:35Z"
      image: registry.ci.openshift.org/ocp/release@sha256:fdc05e4b117f0503f7810af51971fdefc574d416f994953fecbab36b2db7706d
      startedTime: "2024-08-01T06:20:10Z"
      state: Completed
      verified: false
      version: 4.16.0-0.nightly-2024-08-01-012721

```

/label qe-approved

**Comment by djoshy** [comment]
/hold
to prevent accidental merge

**Comment by yuqi-zhang** [comment]
/lgtm

We'll follow up with a fix to the API pin to not break payloads

**Comment by deads2k** [comment]
has to be merged with https://github.com/openshift/api/pull/1975

**Pull request merged**
