### PR TITLE
OWNERS: add cgwalters as approver

### PR DESCRIPTION
**Pull request by sinnykumari**

### CODE REVIEW

**Comment by sinnykumari** [comment]
damm, okd-e2e-aws got missed. Maybe follow-up PR tomorrow

**Comment by kikisdeliveryservice** [comment]
> damm, okd-e2e-aws got missed. Maybe follow-up PR tomorrow

already working on it @sinnykumari  ;)

**Comment by cgwalters** [comment]
Looking forward to working with this team again more in the new year!  A lot of great people *and* a firehose of pull requests :smile:

**Pull request merged**
