### PR TITLE
Bug 1913582: fix IsLikeTraditionalRhel7() to account for minor versions

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Bug Summary: 
The VERSION_ID was 7.5 but our check IsLikeTraditionalRhel7() did not account for minor versions (only for "7" not for 7.x) and so returned false. This resulted in dn.loggerSupportsJournal being set to true which is the relevant value when selecting which logger to use. So instead of using storePendingStateLegacyLogger() (for cases where journald isn't avail) we used normal logger resulting in the --journald flag erroneously being used for a rhel7 node.

Also added a unit test for this func to keep it working going forward.  Pre-fix unit new test failed and returned false for 7.5, now it correctly returns true.

### CODE REVIEW

**Comment by ashcrow** [comment]
Thank you for working on this!

**Comment by darkmuggle** [comment]
Change looks good so far.

**Review by darkmuggle — APPROVED** [review]
/lgtm
/approve
@kikisdeliveryservice thank you kindly for the quick fix

**Comment by kikisdeliveryservice** [comment]
okd job is red so skipping

e2e-aws isn't looking very good today either..

/skip

**Review by ashcrow — APPROVED** [review]

**Comment by kikisdeliveryservice** [comment]
No backport required, this VersionID check was introduced in 4.7 via https://github.com/openshift/machine-config-operator/pull/2242

**Comment by kikisdeliveryservice** [comment]
no point of retesting rn

/hold

**Pull request merged**
