### PR TITLE
[release-4.1] Bug 1718436: DR: backport fixes

### PR DESCRIPTION
**Pull request by hexfusion**
This PR backports all fixes to DR between 5/20 - 6/5 as outlined below

Branch | Date | Message | Commit | Author
-- | -- | -- | -- | --
Master (#804) | 6/5/19 | DR: use param to populate etcd name for etcd-member-recover | b8994e06e52e9245ef83c084b414a4b680706eee | hexfusion
Master (#793) | 5/24/19 | DR: add validate_environment to openshift-recovery-tools | 4e0e2d102ed7d0fe2e9e113f3c4eb2a03d029c84 | hexfusion
Master (#788) | 5/22/19 | Reload systemd services on disk before starting kubelet | 92879196f0078110b5d218f59cb3c770aae87856 | vrutkovs
Master (#779) | 5/20/19 | Store stopped manifests in ASSET_DIR | 8554f3abdb94ccdb20de5043d819cc6972164365 | vrutkovs
Master (#779)| 5/20/19 | DR start_static_pods: reread a list of static pods when starting them | dd3be74e8a3662baba9b57fea9dc6ca62c3eec23 | vrutkovs
Master (#780)| 5/20/19 | templates/master/00-master: resolve unpopulated var when ETCD_CONNSTR… … | 9fb47329fb9be0c826b7938e12bf67b2a4a7a2dd | hexfusion

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1718436

### CODE REVIEW

**Comment by brenton** [comment]
Do we have bugzillas for any of these fixes?  Now that we're GA we'll need bugs opened in order to make changes to the released product.

**Comment by kikisdeliveryservice** [comment]
@brenton I think a BZ is forthcoming to get these fixes backported

**Comment by hexfusion** [comment]
BZ : https://bugzilla.redhat.com/show_bug.cgi?id=1718436

**Comment by kikisdeliveryservice** [comment]
(added a colon in the name to get the bugzilla tags active. looks like the BZ should be for 4.1.0 in order to backport.)

**Comment by kikisdeliveryservice** [comment]
but @vrutkovs you'll have to send an email out to get this officially backported

**Pull request merged**
