### PR TITLE
Bug 1949818: test/e2e: add e2e test for Single Node OpenShift

### PR DESCRIPTION
**Pull request by sinnykumari**
Also, refactor existing e2e test so that common functionalities
can be shared between both SNO and regular cluster

### CODE REVIEW

**Comment by sinnykumari** [comment]
Require https://github.com/openshift/release/pull/17357

**Comment by sinnykumari** [comment]
Rebased and fixed merge conflict

**Comment by yuqi-zhang** [comment]
Did a first pass and the general code lgtm. Quick question, when you say:

> Require openshift/release#17357

Does't 17357 require this to merge first such that it can run `make test-e2e-single-node`? Or am I misunderstanding the comment and that's what you meant?

**Comment by sinnykumari** [comment]
> Did a first pass and the general code lgtm. Quick question, when you say:
> 
> > Require [openshift/release#17357](https://github.com/openshift/release/pull/17357)
> 
> Does't 17357 require this to merge first such that it can run `make test-e2e-single-node`? Or am I misunderstanding the comment and that's what you meant?

No, https://github.com/openshift/release/pull/17357 needs to merge first so that `e2e-gcp-op-single-node` job gets created and we can start a job on this PR with something like `/test e2e-gcp-op-single-node`

**Comment by sinnykumari** [comment]
There is a known issue that on Single Node OpenShift, load is too high for any pod to be deployed when RT kernel profile is being used. As a result, MCO operation gets impacted and are very slow causing our further ci tests to fail like rollback of RT kernel. This is because when we are perform rollback operation, RHCOS node is booted into RT kernel. Corresponding bug: https://bugzilla.redhat.com/show_bug.cgi?id=1939133 . 

I have moved RealTime kernel test as last test and removed rollback. We can add rollback test once bug#1939133 has been fixed or we have resources in ci to run SNO that is optimized for RT kernel.

**Comment by sinnykumari** [comment]
Hmm, from the [log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2507/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op-single-node/1382658948632416256) e2e-gcp-op-single-node succeeded:
```
 INFO[2021-04-15T12:42:23Z] Running step e2e-gcp-op-single-node-test.    
INFO[2021-04-15T14:03:44Z] Step e2e-gcp-op-single-node-test succeeded after 1h21m20.061125104s.
```
But, gathering must-gather logs failed. Looks like having RT kernel installed on node is making node cry for resources. I am going to completely remove TestKernelType test until https://bugzilla.redhat.com/show_bug.cgi?id=1939133 is resolved.

**Comment by sinnykumari** [comment]
Finally, e2e-gcp-op-single-node is green :tada: 
@yuqi-zhang @kikisdeliveryservice should be good to go now.

**Comment by yuqi-zhang** [comment]
/lgtm

Looks great! Thanks for working on this!

**Pull request merged**
