### PR TITLE
OCPCLOUD-2010: Re-vendor api and library-go for external platform support

### PR DESCRIPTION
**Pull request by adriengentil**
Revendor openshift/api and openshift/library-go in order to support the
external platform type when feature set `TechPreviewNoUpgrade` is 
enabled.

library-go PR: https://github.com/openshift/library-go/pull/1496
API PR: https://github.com/openshift/api/pull/1434

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
lgtm, just waiting on the upstream PRs so we can revendor

**Comment by adriengentil** [comment]
TestFeatureGateDrift test fails with:
```
 kubelet_config_features_test.go:45: template FeatureGates do not match openshift/api FeatureGates: (tmpl=[map[AlibabaPlatform:true OpenShiftPodSecurityAdmission:true RetroactiveDefaultStorageClass:false]], api=[&map[AlibabaPlatform:true CloudDualStackNodeIPs:true OpenShiftPodSecurityAdmission:true RetroactiveDefaultStorageClass:false]]
```

> looks like the template output needs to be adjusted for the change in feature gates perhaps?
where is this template? :eyes:

**Comment by adriengentil** [comment]
ok I think it's this one https://github.com/openshift/machine-config-operator/blob/master/templates/master/01-master-kubelet/_base/files/kubelet.yaml

**Comment by elmiko** [comment]
the e2e failures look related to csi driver issues, i don't think it is being caused by this pr.

/lgtm

**Comment by adriengentil** [comment]
/assign sinnykumari
As @elmiko said, the jobs look to be failing for unrelated reasons (reaching some kind of limits in AWS for the hypershift one)

**Comment by jkyros** [comment]
Awesome, hypershift passed
/approve

**Pull request merged**
