### PR TITLE
[mcbs] Fast forward to master

### PR DESCRIPTION
**Pull request by cgwalters**
We're going to iterate on this branch, so the first step is to update it to match git master.

### CODE REVIEW

**Review by kikisdeliveryservice — APPROVED** [review]
Wowzers.

**Comment by mkenigs** [comment]
Should we rename this branch to layering?

**Review by sinnykumari — APPROVED** [review]

**Comment by sinnykumari** [comment]
> 



> Should we rename this branch to layering?

Not sure if it worth that effort considering it is a test branch. Also, renaming branch would mean making corresponding config changes into openshift/release repo too and getting approval from corresponding team.

**Comment by kikisdeliveryservice** [comment]
Agree branch name is fine as is.

**Pull request merged**
