### PR TITLE
DO NOT MERGE, testing master-4.1 CI

### PR DESCRIPTION
**Pull request by runcom**
DO NOT MERGE, just testing the CI kicks for master-4.1

### CODE REVIEW

**Comment by runcom** [comment]
Looks like CI works just fine for this branch

**Comment by kikisdeliveryservice** [comment]
I had changed a PR to use the master-4.1 branch and can confirm CI ran against it correctly as well!

**Comment by kikisdeliveryservice** [comment]
just to be safe, since this is confirmed. 
/hold

**Comment by runcom** [comment]
Yup, let's close this now :+1:

**Pull request closed without merging**
