### PR TITLE
daemon/update: retry pivot 5 times on failed rc

### PR DESCRIPTION
**Pull request by jlebon**
In the spirit of retrying all the things that could fail transiently,
just wrap the `/bin/pivot` call in a retry loop.

Closes: #276

### CODE REVIEW

**Comment by jlebon** [comment]
Now tested!

**Comment by cgwalters** [comment]
Kind of wonder whether we should move to scheduling a pod on the node instead; that way we go through all the same pull/retry/auth machinery as the rest of the containers.  But this is fine for now.

**Pull request merged**
