### PR TITLE
OCPBUGS-22364: Bump openshift/API to mark MCO cert observability fields optional in CRD

### PR DESCRIPTION
**Pull request by jkyros**
This bumps the MCO API to bring in the cert obvservability field changes from https://github.com/openshift/api/pull/1637 

( It looks like controllerConfig picked up some network-related CRD changes in the platform spec also) 

All I did: 
- `$ go get -u github.com/openshift/api`
- `$ make go-deps`
- `$ hack/crds-sync.sh`

### CODE REVIEW

**Comment by jkyros** [comment]
Had to account for verify being pickier about `%w` usage and the ContainerRuntimeConfig API changes from https://github.com/openshift/api/pull/1656 which this also drags in.

**Comment by jkyros** [comment]
yuck, unit passed locally, is that a flake?
/test unit

**Comment by QiWang19** [comment]
The ci/prow/unit failure `pkg/controller/container-runtime-config` resource.Quantity can be fixed by the commit https://github.com/openshift/machine-config-operator/pull/4044/commits/a8cd848305663d6c7d97928cb982b32fcb226e98
right now I am not sure about the failures of the pkg/controller/kubelet-config

**Comment by jkyros** [comment]
Oh, heyyyy @QiWang19 it looks like you are doing the same thing I am doing....and you have more tests. Excellent timing :smile: 

Yeah, I had hacked in some quick `nil` checks + fixes to accommodate the ControllerRuntime changes, but your commit is definitely more detailed and probably better. 

The flake I was referencing was weirdly seemingly not related to any of this. I got a weird unit run that failed with : 

```
1121 22:45:59.020479   22201 render_controller.go:564] No BaseOSContainerImage set
    render_controller_test.go:151: Action update machineconfigpools has wrong object
        Diff:
           &v1.MachineConfigPool{
          	TypeMeta:   {APIVersion: "machineconfiguration.openshift.io/v1"},
          	ObjectMeta: {Name: "test-cluster-master", UID: "wc9zt", Labels: {"machineconfiguration.openshift.io/mco-built-in": "", "pools.operator.machineconfiguration.openshift.io/test-cluster-master": ""}},
          	Spec: v1.MachineConfigPoolSpec{
          		... // 2 identical fields
          		Paused:         false,
          		MaxUnavailable: nil,
          		Configuration: v1.MachineConfigPoolStatusConfiguration{
          			ObjectReference: {Name: "rendered-test-cluster-master-a39f193e46d2048532b91e0ddc0faceb"},
          			Source: []v1.ObjectReference{
          				{
          					Kind:       "MachineConfig",
          					Namespace:  "",
        - 					Name:       "00-test-cluster-master",
        + 					Name:       "05-extra-master",
          					UID:        "",
          					APIVersion: "machineconfiguration.openshift.io/v1",
          					... // 2 identical fields
          				},
          				{
          					Kind:       "MachineConfig",
          					Namespace:  "",
        - 					Name:       "05-extra-master",
        + 					Name:       "00-test-cluster-master",
          					UID:        "",
          					APIVersion: "machineconfiguration.openshift.io/v1",
          					... // 2 identical fields
          				},
          			},
          		},
          	},
          	Status: {Configuration: {ObjectReference: {Name: "rendered-test-cluster-master-a39f193e46d2048532b91e0ddc0faceb"}}, Conditions: {{Type: "RenderDegraded", Status: "False", LastTransitionTime: {Time: s"1970-01-01 00:00:00 +0000 UTC"}}}},
          }
```
Which felt very non-deterministic. And it never happened again, and seemed unrelated to everything.

**Comment by QiWang19** [comment]
@jkyros Do you plan to merge this as part of 4.15? if so #4044 can wait after this one

**Comment by jkyros** [comment]
@QiWang19 Yes, I do intend to merge this as part of 4.15, I'll try to get this finished up tomorrow or Wed.

**Comment by jkyros** [comment]
Actually...it looks like Charlie is going to bump API as part of https://github.com/openshift/machine-config-operator/pull/4012 so that might obviate this. I'll close this if #4012 merges

**Comment by jkyros** [comment]
#4012 merged which bumps the API and contains these changes, closing this.

**Pull request closed without merging**
