### PR TITLE
OCPBUGS-28545: Delete state files on reboot only

### PR DESCRIPTION
**Pull request by MarSik**
This is a semi-automated cherry-pick of https://github.com/openshift/machine-config-operator/pull/4124

This replaces https://github.com/openshift/machine-config-operator/pull/4151 that has a merge conflict.

### CODE REVIEW

**Comment by MarSik** [comment]
/relabel [release-4.15] OCPBUGS-28545: Delete state files on reboot only

**Review by yuqi-zhang — APPROVED** [review]
/label backport-risk-assessed
/lgtm

**Pull request merged**
