### PR TITLE
Bug 1828112: remove quotes around kubelet_node_ip to account for rhel7

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Using approach from https://github.com/openshift/machine-config-operator/pull/1439 by removing quotes around kubelet_node_ip for rhel7.

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1828112

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
testing
/hold

**Comment by kikisdeliveryservice** [comment]
@mtnbikenc PTAL - is this the necessary fix?

**Comment by mtnbikenc** [comment]
@kikisdeliveryservice That's basically what I was expecting.  I just wanted to make sure there were no other aspects of the change to consider.

**Comment by kikisdeliveryservice** [comment]
wowzers something seems to have gone terribly wrong on this test.. (unrelated to pr)
/test e2e-aws

**Comment by kikisdeliveryservice** [comment]
both rhel7&metal-ipi jobs are failing solidly (unrelated to this) - those are known issues.  

the ovirt test did pass so will remove hold and allow this to merge.

/skip

**Pull request merged**
