### PR TITLE
Update instructions to disable CVO.

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
`oc delete daemonset...` returns an error, the correct instruction is now `oc delete deploy...`

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@cgwalters I would think so, tho I'm not sure. But I'm ok with waiting until the job failures get resolved too. :)

**Comment by kikisdeliveryservice** [comment]
cc: @abhinavdahiya

**Comment by jlebon** [comment]
#194

**Comment by ashcrow** [comment]
/test e2e-aws

Continued flakes.

**Pull request merged**
