### PR TITLE
Dependencies: update to kubernetes-1.17.1

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Openshift 4.4 will be targeting 1.17. Since we will need api
updates for https://github.com/openshift/machine-config-operator/pull/1377,
might as well update all kube items while we're at it.

Note that we used to use openshift/kubernetes/* repos, but they
haven't been updated for awhile. Targeting upstream directly instead.

Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
This is a superset of https://github.com/openshift/machine-config-operator/pull/1377, not quite sure if I got this right though cc @runcom

**Comment by kikisdeliveryservice** [comment]
> Note that we used to use openshift/kubernetes/* repos, but they
> haven't been updated for awhile. Targeting upstream directly instead.

They seem to be updated frequently: https://github.com/openshift/origin/commits/master/vendor/k8s.io

**Comment by kikisdeliveryservice** [comment]
Let me poke around a little to figure out how this works.

**Comment by kikisdeliveryservice** [comment]
So I think if you want to use openshift's kube you use it from origin, which has already been bumped to 1.17.1 see: https://github.com/openshift/origin/commits/master as opposed to openshift/kubernetes

**Comment by runcom** [comment]
Found what's happening (thanks @deads2k a lot as well) - it appears we weren't fetching the correct object in units since the early days but that bug was shadowed somehow. Bumping to a new kube has to have fixed that bug and we're left with our unit failure, applying this patch fixes the units:

```diff
commit a2c81984c7600c333810e8bc78bd4ae6559a2c12
Author: Antonio Murdaca <runcom@linux.com>
Date:   Thu Jan 23 14:53:28 2020 +0100

    pkg/operator: fix DeepCopy and unit test
    
    Signed-off-by: Antonio Murdaca <runcom@linux.com>

diff --git a/pkg/operator/status.go b/pkg/operator/status.go
index 1972c74e..35bdf2f5 100644
--- a/pkg/operator/status.go
+++ b/pkg/operator/status.go
@@ -217,7 +217,8 @@ func (optr *Operator) fetchClusterOperator() (*configv1.ClusterOperator, error)
        if err != nil {
                return nil, err
        }
-       return co, nil
+       coCopy := co.DeepCopy()
+       return coCopy, nil
 }
 
 func (optr *Operator) initializeClusterOperator() (*configv1.ClusterOperator, error) {
diff --git a/pkg/operator/status_test.go b/pkg/operator/status_test.go
index 89198116..fbaf643e 100644
--- a/pkg/operator/status_test.go
+++ b/pkg/operator/status_test.go
@@ -536,6 +536,7 @@ func TestOperatorSyncStatus(t *testing.T) {
                cov1helpers.SetStatusCondition(&co.Status.Conditions, configv1.ClusterOperatorStatusCondition{Type: configv1.OperatorDegraded, Status: configv1.ConditionFalse})
                cov1helpers.SetStatusCondition(&co.Status.Conditions, configv1.ClusterOperatorStatusCondition{Type: configv1.OperatorUpgradeable, Status: configv1.ConditionUnknown})
                co.Status.Versions = append(co.Status.Versions, configv1.OperandVersion{Name: "operator", Version: "test-version"})
+               optr.name = coName
 
                for j, sync := range testCase.syncs {
                        optr.inClusterBringup = sync.inClusterBringUp
```

**Comment by runcom** [comment]
ok, I was able to push directly here - let's see

**Comment by runcom** [comment]
alrighty, units passed

**Comment by yuqi-zhang** [comment]
/retest

Thanks for the fix!

**Comment by yuqi-zhang** [comment]
/retest ci/prow/e2e-aws
throttling

**Comment by kikisdeliveryservice** [comment]
oh aws... :(

/test e2e-aws

**Comment by runcom** [comment]
/lgtm 

Also

**Pull request merged**
