### PR TITLE
[release-4.10] Bug 2072621: Fix bootstrap-unit test failure caused by #3008

### PR DESCRIPTION
**Pull request by QiWang19**
https://coreos.slack.com/archives/C02CZNQHGN8/p1650653177443869 pointed out the ci failed
with wrong arguments of containerruntimeconfig.New.containerruntimeconfig.New was updated
with PR #3008, this is a follow up PR of it.
Signed-off-by: Qi Wang <qiwan@redhat.com>

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@QiWang19 there are some failures in here still:  
--- FAIL: TestE2EBootstrap (54.74s)
    --- PASS: TestE2EBootstrap/With_no_additional_manifests (9.11s)
    --- FAIL: TestE2EBootstrap/With_a_featuregate_manifest (6.62s)
    --- FAIL: TestE2EBootstrap/With_a_featuregate_manifest_and_master_kubelet_config_manifest (12.64s)
    --- FAIL: TestE2EBootstrap/With_a_worker_kubelet_config_manifest (12.57s)
    --- FAIL: TestE2EBootstrap/With_a_container_runtime_config (6.57s)

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

**Comment by kikisdeliveryservice** [comment]
As this is fixing the actual 4.10-bootstrap-unit job we don' tneed to rerun any other tests

/override ci/prow/e2e-agnostic-upgrade

**Comment by kikisdeliveryservice** [comment]
@sunilcio would you be able to approve this for merging?

**Comment by kikisdeliveryservice** [comment]
Weird tide didn't pick up @yuqi-zhang 's approval ?

` Not mergeable. Needs approved, backport-risk-assessed labels. `

let me try

/approve

**Comment by sanchezl** [comment]
/assign @sunilcio 

_Needs cherry-pick-approved label._

**Pull request merged**
