### PR TITLE
FF master-4.3 branch

### PR DESCRIPTION
**Pull request by runcom**
As per email from Clayton, bringing changes via a PR is the current flow.

cc @sgreene570

### CODE REVIEW

**Comment by cgwalters** [comment]
Will this really fast forward though?  Won't it generate a merge commit from the PR, or does prow have special support for this somehow?

That's not bad really, we already have a ton of merge commits - just noting that in the end we're going to have merges both ways when we merge back to master.

**Comment by cgwalters** [comment]
/assign sgreene570
Anyways, I'll believe you this is syncing master :smile: , giving to sgreene for lgtm.

**Comment by runcom** [comment]
> Will this really fast forward though? Won't it generate a merge commit from the PR, or does prow have special support for this somehow?
> 
> That's not bad really, we already have a ton of merge commits - just noting that in the end we're going to have merges both ways when we merge back to master.

yeah, thought about that as well - maybe I'll follow up with Clayton/Steve to understand that

**Comment by runcom** [comment]
> Anyways, I'll believe you this is syncing master

I believe Clayton :smile:

**Pull request merged**
