### PR TITLE
server/api_test: Adjust expected error message for Go 1.18

### PR DESCRIPTION
**Pull request by cgwalters**
Right now Fedora doesn't ship Go 1.17, only Go 1.18beta.  That
version emits a different error message for incompatible TLS
versions.  Adjust our unit test to handle both.

(Also, a motivation for me is to cross-check the new CI configuration
 after https://github.com/openshift/release/pull/27015 )

### CODE REVIEW

**Comment by cgwalters** [comment]
Yep, https://github.com/openshift/release/pull/27015 seemed to have the intended effect!  Now we're only launching 3 clusters¹ instead of 10.

¹ (for this PR that only affects the unit test and can't ever break anything in-cluster, but that's an aside)

**Review by kikisdeliveryservice — APPROVED** [review]
/lgtm

**Comment by kikisdeliveryservice** [comment]
hmm:
``` === CONT  TestRunShared/MCD_Config_Drift
    helpers.go:262: Setup complete (took 2m58.552950553s)
Job for rpm-ostreed.service failed.
See "systemctl status rpm-ostreed.service" and "journalctl -xe" for details.
error: exit status: 1
command terminated with exit code 1
    utils.go:356: 
        	Error Trace:	utils.go:356
        	            				helpers.go:37
        	            				helpers.go:27
        	            				mcd_config_drift.go:170
        	            				shared.go:45
        	Error:      	Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc00000e6d8), Stderr:[]uint8(nil)}
        	Test:       	TestRunShared/MCD_Config_Drift
        	Messages:   	failed to exec cmd [chroot /rootfs /usr/bin/rpm-ostree kargs] on node ci-op-l9f2cpj3-1354f-gps7k-worker-a-m7x5l: ● rpm-ostreed.service - rpm-ostree System Management Daemon 
```

**Comment by cgwalters** [comment]
Hmm.  Thanks for highlighting that!  It's not related to this PR, but I think it is a bug in rpm-ostree.  Investigating.

**Comment by cgwalters** [comment]
OK, this cannot break the e2e tests, it only affects the unit tests.  Retesting our e2es is just a waste of money.
/override ci/prow/e2e-gcp-op

**Pull request merged**
