### PR TITLE
tests/e2e: Refactor and reduce test run time 

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Refactor mco e2e tests and reduce time of the e2e tests by ~50% by removing duplicative tests & using custom pools. Current runtime based on this PR is ~55m for the mco e2e tests to run down from ~100min.

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
`Pod pending timeout. ` <-- seem to be some weird e2e issues in play ignoring for now.

**Comment by kikisdeliveryservice** [comment]
Got this fixed locally will repush tomorrow.

**Comment by kikisdeliveryservice** [comment]
Last succesful run was approx ~62 min..
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1884/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1280570834427056128/artifacts/e2e-gcp-op/container-logs/test.log

**Comment by kikisdeliveryservice** [comment]
So I decided to shoot the moon even tho I got the e2e down to ~62 min and use custom pools for kargs.. That's when it all went south. I think there's an issue rolling back - I opened #1912 to test (also deleted all the other e2e so hopefully it runs a lot faster over there too):

Ok seeing same error in this ci run that I saw in my local cluster: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1884/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1280664102313660416/artifacts/e2e-gcp-op/machineconfigpools.json

**Comment by kikisdeliveryservice** [comment]
Ok will update our test karg arguments as there seems to be a bug in rpmostree : https://github.com/openshift/machine-config-operator/pull/1912#issuecomment-655365262

**Comment by kikisdeliveryservice** [comment]
Last successful test run was 55m.

**Comment by kikisdeliveryservice** [comment]
Ok that was an awful rebase. :rofl:

**Comment by runcom** [comment]
Test started last Wednesday at 10:20 AM passed after 2h27m45s.
Test started last Thursday at 10:53 PM passed after 2h28m50s.
Test started today at 2:44 AM passed after 1h48m46s

I'd say... 😌 

/approve

**Comment by kikisdeliveryservice** [comment]
@runcom this is ready whenever you are :smile_cat:

**Comment by cgwalters** [comment]
Didn't deep dive but LGTM overall!

In the future one thing we can consider is using temporary machinesets too (gets into https://github.com/openshift/machine-config-operator/issues/1720 ) - we can parallelize the tests arbitrarily by having a MCP+machineset per test scenario (at the cost of more $ of course).

**Comment by kikisdeliveryservice** [comment]
this is a test refactor in e2e-gcp-op, there's not reason to keep retesting on the known broken e2e-aws and waste resources since this doesn't touch at that all and it's retesting a billion times at this point

/override e2e-aws

**Pull request merged**
