### PR TITLE
Bug 1879409: docs: Update for Ignition spec 2/3 dual support

### PR DESCRIPTION
**Pull request by travier**
**- What I did**

Additional documentation updates for Ignition spec 2/3 dual support.

### CODE REVIEW

**Comment by travier** [comment]
This is a docs only change so I don't think the CI is relevant here.

**Comment by travier** [comment]
Rebased. This will also require backporting to 4.6 & 4.7.

**Comment by cgwalters** [comment]
/approve
/lgtm

> Rebased. This will also require backporting to 4.6 & 4.7.

Currently while there are `release-4.6` git branches they're just automatically fast forwarded to match `master`.

This technically requires a BZ to merge unfortunately.

**Review by cgwalters — APPROVED** [review]

**Pull request merged**
