### PR TITLE
Bump timeout for e2e-aws-op

### PR DESCRIPTION
**Pull request by cgwalters**
We seem to be taking longer here.

### CODE REVIEW

**Comment by runcom** [comment]
I'm fine with this if we're just timing out on the latest test added (quorum guard afaict)

**Comment by hexfusion** [comment]
/lgtm

Thanks @cgwalters @runcom !

**Comment by cgwalters** [comment]
```
              "degradedMachineCount": 0,
                "machineCount": 3,
                "observedGeneration": 1,
                "readyMachineCount": 2,
                "unavailableMachineCount": 1,
                "updatedMachineCount": 2
            }
```

**Comment by runcom** [comment]
@cgwalters that just looks like the worker pool is still rolling and reconciling to me

**Comment by kikisdeliveryservice** [comment]
120 seems awfully high? i assume we just trying it to see if it's truly a timeout issue?

**Comment by cgwalters** [comment]
>  i assume we just trying it to see if it's truly a timeout issue?

Right.  
/hold
Since we probably don't want to merge as is.
Also I suspect 2 hours may also be the timeout for Prow jobs in general?  Need to investigate that.

**Comment by cgwalters** [comment]
I find myself getting confused by `getUnavailableMachines`...it feels like it's supposed to be `getMachinesToUpdate` but shouldn't it be checking for nodes which *are* ready?

```
diff --git a/pkg/controller/node/status.go b/pkg/controller/node/status.go
index 75c16477..dfdd2ee1 100644
--- a/pkg/controller/node/status.go
+++ b/pkg/controller/node/status.go
@@ -192,10 +192,12 @@ func getUnavailableMachines(currentConfig string, nodes []*corev1.Node) []*corev
 			continue
 		}
 
-		nodeNotReady := !isNodeReady(node)
+		if !isNodeReady(node) {
+			continue
+		}
 		if dconfig == currentConfig && (dconfig != cconfig || nodeNotReady) {
 			unavail = append(unavail, node)
-			glog.V(2).Infof("Node %s unavailable: different configs (desired: %s, current %s) or node not ready %v", node.Name, dconfig, cconfig, nodeNotReady)
+			glog.V(2).Infof("Node %s unavailable: different configs (desired: %s, current %s)", node.Name, dconfig, cconfig)
 		}
 	}
 	return unavail
```

**Comment by cgwalters** [comment]
Paste from @sjenning 
```
default                                      72s         Warning   MCDBootstrapSyncFailure       node/master-1                                          pending config rendered-master-1eb4fcd28e9f85ea9ac914d1789ad529 bootID a86994cc-fd33-47d4-a3e6-76da3c3d6fa2 matches current! Failed to reboot?
default                                      47s         Warning   MCDBootstrapSyncFailure       node/master-0                                          pending config rendered-master-8e7d5408d19158180e4cd0b6750b434c bootID d1a6236c-df42-412d-bac6-49155ea4ea82 matches current! Failed to reboot?
openshift-machine-config-operator            14s         Warning   FailedScheduling              pod/etcd-quorum-guard-745f7c4d8f-9wstp                 0/6 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) were unschedulable, 3 node(s) didn't match node selector.

$ oc get nodes
NAME       STATUS                     ROLES    AGE   VERSION
master-0   Ready,SchedulingDisabled   master   20h   v1.13.4+e8d1fd69b
master-1   Ready,SchedulingDisabled   master   20h   v1.13.4+e8d1fd69b
master-2   Ready                      master   20h   v1.13.4+e8d1fd69b
worker-0   Ready                      worker   20h   v1.13.4+1f90f9755
worker-1   Ready                      worker   20h   v1.13.4+1f90f9755
worker-2   Ready                      worker   20h   v1.13.4+1f90f9755
```

**Comment by kikisdeliveryservice** [comment]
Noticing in the logs that one of the daemons has no logs!

**Comment by runcom** [comment]
> I find myself getting confused by `getUnavailableMachines`...it feels like it's supposed to be `getMachinesToUpdate` but shouldn't it be checking for nodes which _are_ ready?

@cgwalters your patch is reporting unavailable=0 when nodes aren't ready tho, which is what makes progress if _everything_ is available.

**Comment by cgwalters** [comment]
Closing in favor of https://github.com/openshift/machine-config-operator/pull/697

**Pull request closed without merging**
