### PR TITLE
OCPBUGS-10924: Switch default SA to machine-config-operator

### PR DESCRIPTION
**Pull request by cdoern**
create the new account, tombstone the old one, and update all references.

All tests should work the same as proof that this change does not impact functionality.

### CODE REVIEW

**Comment by sergiordlr** [comment]
1. Using IPI on AWS. The operator pod is not using the "default" service account

```
$ oc get pods -l k8s-app=machine-config-operator -o yaml -n openshift-machine-config-operator |grep serviceAcc
    serviceAccount: machine-config-operator
    serviceAccountName: machine-config-operator
        - serviceAccountToken:

```

Only custom-account-openshift-machine-config-operator  clusterrolebinding is created  (we don't create default-account-openshift-machine-config-operator)

```
$ oc get clusterrolebinding |grep machine-config-operator
custom-account-openshift-machine-config-operator                            ClusterRole/cluster-admin                                                               38m
```

The following test cases were executed and passed:

"[sig-mco] MCO Author:sregidor-NonPreRelease-High-45239-KubeletConfig has a limit of 10 per cluster [Disruptive] [Serial]"
"[sig-mco] MCO Author:sregidor-NonPreRelease-Medium-57009-Kubeletconfig custom tlsSecurityProfile [Disruptive] [Serial]"
"[sig-mco] MCO Author:mhanss-Longduration-NonPreRelease-Critical-42369-add container runtime config [Disruptive] [Serial]"
"[sig-mco] MCO scale Author:sregidor-NonHyperShiftHOST-NonPreRelease-LongDuration-High-63894-Scaleup using 4.1 cloud image[Disruptive] [Serial]"
"[sig-mco] MCO Author:sregidor-NonHyperShiftHOST-NonPreRelease-Critical-62084-Certificate rotation in paused pools[Disruptive] [Serial]"
"[sig-mco] MCO Author:sregidor-NonPreRelease-Medium-52373-Modify proxy configuration in paused pools [Disruptive] [Serial]"
"[sig-mco] MCO Author:sregidor-NonHyperShiftHOST-NonPreRelease-Critical-62084-Certificate rotation in paused pools[Disruptive] [Serial]"
"[sig-mco] MCO Author:sregidor-Longduration-NonPreRelease-High-47009-Config Drift. New Service Unit. [Serial]"
"[sig-mco] MCO Layering Author:sregidor-ConnectedOnly-VMonly-Longduration-NonPreRelease-Critical-54085-Update osImage changing /etc /usr and rpm [Disruptive] [Serial]"




2. Upgrade using IPI on IBM:

Before upgrade the default SA is used by machine-config-operator pod:
```
$ oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.nightly-2023-06-20-224158   True        False         15m     Cluster version is 4.13.0-0.nightly-2023-06-20-224158

$ oc get pods -l k8s-app=machine-config-operator -o yaml -n openshift-machine-config-operator |grep serviceAcc
    serviceAccount: default
    serviceAccountName: default
        - serviceAccountToken:
```

The upgrade is executed without problems
```
$ oc get clusterversion -o yaml
....
    history:
    - acceptedRisks: |-
        Target release version="" image="registry.build01.ci.openshift.org/ci-ln-4hs2vmb/release:latest" cannot be verified, but continuing anyway because the update was forced: release images that are not accessed via digest cannot be verified
        Forced through blocking failures: Multiple precondition checks failed:
        * Precondition "EtcdRecentBackup" failed because of "ControllerStarted": RecentBackup: The etcd backup controller is starting, and will decide if recent backups are available or if a backup is required
        * Precondition "ClusterVersionRecommendedUpdate" failed because of "UnknownUpdate": RetrievedUpdates=False (VersionNotFound), so the recommended status of updating from 4.13.0-0.nightly-2023-06-20-224158 to 4.14.0-0.ci.test-2023-06-26-074430-ci-ln-4hs2vmb-latest is unknown.
      completionTime: "2023-06-26T09:52:36Z"
      image: registry.build01.ci.openshift.org/ci-ln-4hs2vmb/release:latest
      startedTime: "2023-06-26T08:37:24Z"
      state: Completed
      verified: false
      version: 4.14.0-0.ci.test-2023-06-26-074430-ci-ln-4hs2vmb-latest
    - completionTime: "2023-06-26T08:21:44Z"
      image: registry.ci.openshift.org/ocp/release@sha256:127ebebfe1b39b05186781d1a926cab8f06d0599febc30697aa7a34c1e7ccc36
      startedTime: "2023-06-26T07:58:57Z"
      state: Completed
      verified: false
      version: 4.13.0-0.nightly-2023-06-20-224158
```

After upgrade:

The clusterrolebinding for the default account is removed, and a new one is created for the custom account. The operator pod is not using the default SA:

```
$ oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.14.0-0.ci.test-2023-06-26-074430-ci-ln-4hs2vmb-latest   True        False         14m     Cluster version is 4.14.0-0.ci.test-2023-06-26-074430-ci-ln-4hs2vmb-latest

$ oc get clusterrolebinding custom-account-openshift-machine-config-operator default-account-openshift-machine-config-operator
NAME                                               ROLE                        AGE
custom-account-openshift-machine-config-operator   ClusterRole/cluster-admin   44m
Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "default-account-openshift-machine-config-operator" not found

$ oc get pods -l k8s-app=machine-config-operator -o yaml -n openshift-machine-config-operator |grep serviceAcc
    serviceAccount: machine-config-operator
    serviceAccountName: machine-config-operator
        - serviceAccountToken:
```


After the upgrade we could execute "[sig-mco] MCO Author:sregidor-Longduration-NonPreRelease-High-47045-Config Drift. Compressed files. [Serial]" test case, and the test case passed.


We can add the qe-approved label

/label qe-approved

**Comment by djoshy** [comment]
Strange, it applied approved but not lgtm :thinking:

**Comment by sinnykumari** [comment]
perhaps some issue with bot

**Pull request merged**
