### PR TITLE
OCPBUGS-5696: remove goutils from dependency tree

### PR DESCRIPTION
**Pull request by cheesesashimi**
**- What I did**

Analyzed the MCO to understand where goutils was being introduced as a dependency. I discovered that it was introduced via the sprig template helper library. We only make use of two functions within that library (which do not depend on goutils). This enabled me to do the following:
- Copy those funcs we use into our codebase.
- Consolidate the use of those funcs into a single place. Further consolidation is possible, but outside the scope of this PR.
- Wrote smoke test to validate that all templated manifests can be rendered and then decoded into the appropriate structs.
- Removed sprig, goutils, and its dependent libraries from our vendor folder and go.mod / go.sum files.

Note to reviewer: I put the dependency removal in a commit by itself for easier review.

**- How to verify it**

Run the unit test suite

**- Description for the changelog**
Remove goutils from our dependency tree

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Did a first pass and everything makes sense, thanks for the quick fix!

As a side note, this did annoyingly create 5 bugs:
https://issues.redhat.com/browse/OCPBUGS-5696
https://issues.redhat.com/browse/OCPBUGS-5694
https://issues.redhat.com/browse/OCPBUGS-5692
https://issues.redhat.com/browse/OCPBUGS-5690
https://issues.redhat.com/browse/OCPBUGS-5688

in 4.12->4.8 order, but no 4.13, so it seems that e.g. an option would be:
1. create a 4.13 bug (or clone the 4.12 one)
2. backport each release manually and reference the relevant bug

or
1. close the current bugs and have /cherry-pick create the necessary magic

up to you which works better

**Comment by cheesesashimi** [comment]
Lets try the cherrypick magic as a first-pass. If we end up having a lot of difficulty, I'll do them manually.

**Comment by yuqi-zhang** [comment]
/retest required

I wonder if this works

**Comment by yuqi-zhang** [comment]
oh whoops that should have been 1 command

but I do see the new required jobs, so I think we're good. I think this shouldn't require any pre-merge testing either right? Just removing some deps so CI coverage should be enough

**Comment by cheesesashimi** [comment]
Yeah, I think this is all we need.

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

I don't think this needs pre-merge testing, since it doesn't change any behaviour really, just removes some dependencies and adds testing. Will let the regular bug verification process do the trick instead.

**Pull request merged**
