### PR TITLE
Bug 1957972: Remove remnants of mdns functionality

### PR DESCRIPTION
**Pull request by cybertron**
mDNS was removed in #2465, but a couple of the related templates were
missed. This just cleans those up too.

Note that there are also references to mdns in the MCO code, but I'm going
to leave the removal of those until 4.9 so we don't risk breaking anything on
upgrade.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
I see all the related CI jobs have passed.
/lgtm

On a side note, we should also merge https://github.com/openshift/installer/pull/4821

**Comment by mandre** [comment]
Per the bot suggestion, assigning Kirsten for approval.
/assign @kikisdeliveryservice

**Review by kikisdeliveryservice — APPROVED** [review]
Makes sense to me.

**Pull request merged**
