### PR TITLE
Bug 1949827: Add KUBELET_NODEIP_HINT to nodeip-configuration

### PR DESCRIPTION
**Pull request by cybertron**
When we added the nodeip-configuration service for None platform
deployments, we broke some existing users who were relying on the
(largely undefined) previous behavior Kubelet used to select its
node ip. While it is possible to work around this by overriding the
node ip selection logic, that's very cumbersome and not an acceptable
user experience.

This change adds a KUBELET_NODEIP_HINT env variable that can be used
to override the default behavior of runtimecfg when selecting a node
ip. When the variable is unset, the old behavior of selecting an
address on the interface of the default route will take effect. When
the variable is set, its value will be passed to runtimecfg like a
VIP for the IPI platforms. This will cause runtimecfg to prefer an
address in the same subnet as the one provided in
KUBELET_NODEIP_HINT. If no such address is found, it will fall back
to the default route logic as before.

KUBELET_NODEIP_HINT can be set using a systemd environment file.
The file must be named /etc/default/nodeip-configuration
with contents such as (replacing the IP as appropriate):

KUBELET_NODEIP_HINT=192.0.2.1

This file should be created using a machine-config manifest that is
passed to the installer so it will take effect on initial deployment.
The node ip cannot be changed after the node registers initially so
this cannot be done as a day 2 operation.

Note that the IP specified in the hint does not necessarily need to
exist in the environment, it just needs to be in the correct subnet.
No traffic will be sent to this address.

**- What I did**

**- How to verify it**

**- Description for the changelog**

Added a mechanism for deployers to override the default node ip selection logic in None platform deployments.

### CODE REVIEW

**Comment by cybertron** [comment]
/cc @danwinship 

This is essentially what you suggested as a workaround on the bz. I went with a more generic env var name in case some of these deployments did not want the nodes listening on the same subnet as the api server (although...is that even valid?). I also used the built-in override mechanism in systemd to specify the value which kept the changes to the service file minimal.

I semi-successfully tested this in an IPI deployment by hacking up the nodeip-configuration for IPI to do the same thing. It seemed to work, although I couldn't complete deployment that way because my bootstrap node wasn't connected to the additional network I specified so there was no connectivity with the nodes. They did select the correct address to bind to though.

**Comment by danwinship** [comment]
> in case some of these deployments did not want the nodes listening on the same subnet as the api server (although...is that even valid?)

I think so, though it would be weird...

> I also used the built-in override mechanism in systemd to specify the value which kept the changes to the service file minimal.

I used `EnvironmentFile` in my example because it's a lot easier for the user that way. The MachineConfig just needs to say:

    source: data:,KUBELET_NODEIP_HINT=192.0.2.1

rather than:

    source: data:base64,W1NlcnZpY2VdCkVudmlyb25tZW50PSJLVUJFTEVUX05PREVJUF9ISU5UPTE5Mi4wLjIuMSIK

**Comment by danwinship** [comment]
/lgtm
anyway

**Comment by cybertron** [comment]
> > I also used the built-in override mechanism in systemd to specify the value which kept the changes to the service file minimal.
> 
> I used `EnvironmentFile` in my example because it's a lot easier for the user that way. The MachineConfig just needs to say:
> 
> ```
> source: data:,KUBELET_NODEIP_HINT=192.0.2.1
> ```
> 
> rather than:
> 
> ```
> source: data:base64,W1NlcnZpY2VdCkVudmlyb25tZW50PSJLVUJFTEVUX05PREVJUF9ISU5UPTE5Mi4wLjIuMSIK
> ```

Hmm, yeah. I guess that must have been a holdover from when I tried to implement this only in baremetal-runtimecfg (which didn't work because podman doesn't pass env vars through by default, so service changes were needed anyway). Let me try switching this to EnvironmentFile since there's no reason to do it this way now.

**Comment by cybertron** [comment]
Okay, I switched to EnvironmentFile. I had to add a default one that sets the variable to empty or the service fails when you don't create the file. Otherwise this is pretty much the same as before.

**Comment by kikisdeliveryservice** [comment]
@cybertron can you make sure to get the ocp docs updated to include this (if it doesn't already)?

**Review by kikisdeliveryservice — COMMENTED** [review]
For such a small change would you mind squashing the commits into one - esp since some of them aren't relevant to final implementation?

**Comment by cybertron** [comment]
Squashed the changes and I'll talk to the docs folks about where to put this.

**Comment by kikisdeliveryservice** [comment]
Q: is this tested anywhere periodics,etc..? 

This seems sane to me, @cgwalters you reviewed the initial [nodeip-configuration](https://github.com/openshift/machine-config-operator/pull/2121) PR - care to take a :eyes: ?

**Comment by cybertron** [comment]
> Q: is this tested anywhere periodics,etc..?

I'm pretty sure it's not. It's a tricky thing to test - in my local testing of this patch I had to tweak the metal IPI service to behave the same as UPI because I'm not set up for UPI. Even then, I couldn't do full deployments because the bootstrap node isn't on the extra networks so I can verify that the nodes come up using the correct IP but they can't connect back to the bootstrap on that interface.

**Comment by danwinship** [comment]
> > Q: is this tested anywhere periodics,etc..?
> 
> I'm pretty sure it's not.

Yeah... this only applies to UPI, and dev-scripts only does IPI, so we can't test this on bare metal in CI. We might be able to test it on vsphere or openstack? I don't know much about our CI setups there...

OTOH, it's pretty clear just from looking at the patch that it shouldn't _break_ anything, so we could just let it merge and then let the customers who are begging for this try it out. (See also, `bugzilla/severity-urgent`.)

**Comment by kikisdeliveryservice** [comment]
> Q: is this tested anywhere periodics,etc..?
> 
> This seems sane to me, @cgwalters you reviewed the initial [nodeip-configuration](https://github.com/openshift/machine-config-operator/pull/2121) PR - care to take a eyes ?

/assign @cgwalters

**Comment by cgwalters** [comment]
Hmm, obviously this ship has sailed but now that I'm looking at this it feels like what we really want is to offer something that more directly configures kubelet, instead of adding a new config file.

So AIUI, people will be injecting a single "hint IP" via MachineConfig that would apply to an entire pool (e.g. "worker") correct?

(We have the kubeletconfig CRD...seems like this could be part of that?)

But anyways
/approve

**Comment by cybertron** [comment]
> Hmm, obviously this ship has sailed but now that I'm looking at this it feels like what we really want is to offer something that more directly configures kubelet, instead of adding a new config file.

This is intended to be a backportable temporary solution while we work on better support for multiple networks. In the future we do want to come up with a better mechanism, but in the meantime this will help with a significant pain point for some customers.

> 
> So AIUI, people will be injecting a single "hint IP" via MachineConfig that would apply to an entire pool (e.g. "worker") correct?

Right.

> 
> (We have the kubeletconfig CRD...seems like this could be part of that?)

Maybe, but since node ip is machine-specific we can't just set it in kubeletconfig. I suppose we could use it as a more formal interface to the hint though.

@danwinship Can you lgtm again?

**Comment by cgwalters** [comment]
> Maybe, but since node ip is machine-specific we can't just set it in kubeletconfig.

Wait, that clashes with the statement that it applies to a pool.  This relates to https://github.com/openshift/machine-config-operator/issues/1720 - are people going to be editing the pointer configuration for this?

**Comment by cgwalters** [comment]
I'll
/lgtm
again since the only change was squashing; we can do any further fixes as followups.

**Comment by cybertron** [comment]
> > Maybe, but since node ip is machine-specific we can't just set it in kubeletconfig.
> 
> Wait, that clashes with the statement that it applies to a pool. This relates to #1720 - are people going to be editing the pointer configuration for this?

The hint applies to the pool, but the actual kubelet node ip is determined by runtimecfg on a per-node basis. IIUC, using kubeletconfig would cut runtimecfg out of the loop since those settings go directly into kubelet.conf.

**Pull request merged**
