### PR TITLE
OWNERS: Rework to move everyone to toplevel, add runcom

### PR DESCRIPTION
**Pull request by cgwalters**
We're reorganizing the teams to have part of the RHCOS team own
this operator too.

### CODE REVIEW

**Comment by runcom** [comment]
is this file still needed though in `pkg/daemon`? https://github.com/openshift/machine-config-operator/blob/master/pkg/daemon/OWNERS

**Comment by cgwalters** [comment]
> is this file still needed though in pkg/daemon? https://github.com/openshift/machine-config-operator/blob/master/pkg/daemon/OWNERS

Good call; thanks.  I removed all of the "sub-OWNERS" ↑

**Pull request merged**
