### PR TITLE
Bug 2017564: Prepend to search domains instead of replacing

### PR DESCRIPTION
**Pull request by cybertron**
Previously the resolv-prepender script overwrote the search domains
with a specific set of domains, notably including the cluster domain
so cluster addresses will resolve. However, this is not desirable as
it may miss some configured search domains if they don't happen to
come in via DHCP (for example, search domains configured on an
interface via nmcli/nmstate).

This change modifies the prepender logic to also prepend the cluster
domain to the search domain list rather than overwrite it completely.
This means that we don't have to manage the full list of search
domains like we did before. We just add on to the default ones
NetworkManager writes, which should result in less confusing DNS
behavior from the script.

One caveat is that I don't know if the same method can be used for
the resolved case and I don't have any way to test that locally, so
I've left the logic there alone for now. If this turns out to be a
problem for OKD as well then someone will have to work with us to
get that behavior changed too.

**- What I did**

**- How to verify it**

**- Description for the changelog**
The resolv-prepender script no longer overwrites the search domain list. Instead, it prepends the cluster domain so cluster addresses will resolve as expected, but any custom DNS settings will also be respected.

### CODE REVIEW

**Comment by cybertron** [comment]
/hold

I need to test this locally to make sure I didn't miss any changes when I templated the new commands.

**Comment by cybertron** [comment]
/hold cancel

Results from my local test run:
```# Generated by KNI resolv prepender NM dispatcher script
search ostest.test.metalkube.org
nameserver 192.168.111.23
nameserver 192.168.111.1
```

And with a custom search domain and server added:
```# Generated by KNI resolv prepender NM dispatcher script
search ostest.test.metalkube.org nemebean.com
nameserver 192.168.111.23
nameserver 11.1.1.1
nameserver 192.168.111.1
```

Everything seems to be working as intended.

**Comment by kikisdeliveryservice** [comment]
@rvanderp3 e2e-vsphere is pretty red but e2e-vsphere-upgrade is passing

https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-vsphere

should we be waiting for a green run on that?

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by kikisdeliveryservice — APPROVED** [review]
Looks like the vsphere job has now indeed passed :)

**Pull request merged**
