### PR TITLE
BUG 1747124: cmd/setup-etcd-environment: add support for s390, s390x arch

### PR DESCRIPTION
**Pull request by hexfusion**
etcd has no limitations to the architecture that the binary is compiled with (assuming it can compile). But it does require the environment variable `ETCD_UNSUPPORTED_ARCH` to be populated with the arch at runtime if that architecture is not supported upstream[1]. This PR adds support for OpenShift etcd to run s390 and s390x binaries required for IBM Z.

[1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/supported-platform.md

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1747124

Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
> /cc @crawford @yselkowitz

/approve

do we need Alex to sign this off or I can merge?

**Comment by hexfusion** [comment]
> > /cc @crawford @yselkowitz
> 
> /approve
> 
> do we need Alex to sign this off or I can merge?

@runcom lets merge and see if it works for them. The ping to Alex was for observability, thanks!

**Comment by yselkowitz** [comment]
Please note that this fixes only the runtime issue, but does not fix the build of the ose-etcd container.

**Comment by hexfusion** [comment]
> Please note that this fixes only the runtime issue, but does not fix the build of the ose-etcd container.

Build should be covered as soon as https://github.com/openshift/etcd/pull/17 merges.

**Comment by kikisdeliveryservice** [comment]
this scaleup test isn't required and has been failing consistently since adding to the repo.

https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-aws-scaleup-rhel7

**Comment by runcom** [comment]
> this scaleup test isn't required and has been failing consistently since adding to the repo.
> 
> https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-aws-scaleup-rhel7

let's skip it here, the job isn't required

**Pull request merged**
