### PR TITLE
OCPBUGS-2248: [alicloud] provider ID not being set for kubelet

### PR DESCRIPTION
**Pull request by rvanderp3**
starting a PR to reproduce and test changes related to https://issues.redhat.com/browse/OCPBUGS-3311

### CODE REVIEW

**Comment by rvanderp3** [comment]
would like to test this with with e2e-alibaba but need an approval on https://github.com/openshift/release/pull/34644

**Comment by rvanderp3** [comment]
installation succeeded.  test failures in e2e-alibabacloud do not appear to be related to this PR.

**Review by yuqi-zhang — APPROVED** [review]
makes sense to me

/hold 

so Ryan can take a final look from the node side

**Pull request merged**
