### PR TITLE
HACKING.md: add paragraph to turn verbose on

### PR DESCRIPTION
**Pull request by runcom**
Add a paragraph about turning debugging on using `oc patch` for any
given component.

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by jlebon** [comment]
Doesn't this only work if you disable the MCO though? Otherwise it'll reapply e.g. the daemonset definition and overwrite the patch.

**Comment by runcom** [comment]
I should add a note about that, yeah

**Pull request merged**
