### PR TITLE
featuregates: Add default featuregates and comparison check

### PR DESCRIPTION
**Pull request by rphillips**
**- What I did**
Add check to skip machineconfig changes if featuregates are the same

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1699353
Fixes: https://github.com/openshift/cluster-config-operator/pull/39

**- How to verify it**

**- Description for the changelog**

/cc @sjenning @deads2k

### CODE REVIEW

**Comment by rphillips** [comment]
/hold cancel

Added unit test to confirm openshift/api FeatureGates match MCC templates.

**Comment by rphillips** [comment]
OperatorFailing was removed from openshift/api... Figuring out the patch. https://github.com/openshift/api/commit/a9fb3b1629b23b3198c3d94017fc63430afcf6cc

**Comment by runcom** [comment]
> OperatorFailing was removed from openshift/api... Figuring out the patch. [openshift/api@a9fb3b1](https://github.com/openshift/api/commit/a9fb3b1629b23b3198c3d94017fc63430afcf6cc)

we do have this open for that
https://github.com/openshift/machine-config-operator/issues/641

**Comment by rphillips** [comment]
Thanks for the reference!

This PR will depend on #641 getting resolved to make sure all the featuregates are in sync.

**Comment by deads2k** [comment]
/hold

https://github.com/openshift/cluster-kube-apiserver-operator/pull/423 need to test green .  I'm willing to try https://github.com/openshift/origin/pull/22611 but https://github.com/openshift/api/pull/292 is the backup plan

**Comment by rphillips** [comment]
@runcom @deads2k can you give this PR a final review?

**Comment by deads2k** [comment]
if they are the same, why is there a diff when they are serialized?  Do you just need a stable ordering in the serialization?

**Comment by rphillips** [comment]
@deads2k We need to check if they are the same, which the original code did not do.

**Comment by deads2k** [comment]
I'm ok with this, but without having a stable serialization, I worry that you'll end up chasing this kind of problem around.  I'll leave it with @runcom, but I see this as a risk.

**Comment by runcom** [comment]
> @deads2k We need to check if they are the same, which the original code did not do.

is the risk of not having this PR that we re-compute this at every sync? hearing from @deads2k (since I'm not familiar with this code/feature) I would move this to 4.2 if it's just to skip a sync.

**Comment by rphillips** [comment]
@runcom the main issue is that the default FeatureGate CR cannot be created. The FeatureGate controller within the MCC sees the new CR and attempts to apply the new MachineConfig. The new machineconfig causes a reboot cycle across the nodes. This is problematic on the install (bootstrapping) stage of the cluster.

This PR will see the new FeatureGate CR and notice it should not create a new MachineConfig; skipping the reboot cycle. I'm open to suggestions for another way to skip the MachineConfig creation, but noticing the FeatureGates are equal seems like the most prudent path forward (especially on initial bootstrap).

**Comment by runcom** [comment]
> I'm ok with this, but without having a stable serialization, I worry that you'll end up chasing this kind of problem around. I'll leave it with @runcom, but I see this as a risk.

@deads2k can you clarify on the risk? the risk could be that we're going to reboot once more right?

**Comment by rphillips** [comment]
```
level=error msg="\t* module.vpc.aws_route_table_association.private_routing[3]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.private_routing.3: timeout while waiting for state to become 'success' (timeout: 5m0s)"
```

/retest

**Comment by sjenning** [comment]
/lgtm
@deads2k https://github.com/openshift/cluster-kube-apiserver-operator/pull/423 is merged
/hold cancel
@runcom can you review/approve?

**Comment by deads2k** [comment]
> > I'm ok with this, but without having a stable serialization, I worry that you'll end up chasing this kind of problem around. I'll leave it with @runcom, but I see this as a risk.
> 
> @deads2k can you clarify on the risk? the risk could be that we're going to reboot once more right?

Without stable serialization in the MCO as a whole, any other change you're making and detecting can result in infinite looping or mismatched SHAs.  It's a generic problem, not a specific one.

I not worried about this pull in particular, only the pattern as a whole which this pull doesn't make any worse.

**Comment by runcom** [comment]
Thanks David

/lgtm

**Pull request merged**
