### PR TITLE
[wip] vsphere - excessive vip migration

### PR DESCRIPTION
**Pull request by jcpowermac**
trying to use nopreempt to resolve vip migration

### CODE REVIEW

**Comment by yboaron** [comment]
Because we use two track scripts to set Keepalived instance priority  I think we might see unexpected behavior when **nopreempt**  is set, for example an instance with 2 successful scripts won't preempt an instance with a single successful script .
So I'm not sure if nopreempt is a good idea with the current Keepalived track scripts config.

see [1]

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1870177

**Comment by mandre** [comment]
We were also experiencing high failover rate with keepalived on openstack platform and ended up solving it with https://github.com/openshift/machine-config-operator/pull/2077 and https://github.com/openshift/machine-config-operator/pull/2077.

**Comment by jcpowermac** [comment]
Thanks @mandre and @yboaron.

Just going to close this pr and deal with the issue in CI.

**Pull request closed without merging**
