### PR TITLE
pkg/operator: wait for cache on mcp/cc/mcp

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

added cache sync for the other listers we are using in the operator

**- How to verify it**

CI

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
MCO has error:
```E0408 11:13:16.236440       1 reflector.go:134] github.com/openshift/machine-config-operator/pkg/generated/informers/externalversions/factory.go:101: Failed to list *v1.ControllerConfig: the server could not find the requested resource (get controllerconfigs.machineconfiguration.openshift.io)```

is that this pr? or?

**Comment by runcom** [comment]
I believe that's normal since the config operator fails:

```
items: [
{
apiVersion: "config.openshift.io/v1",
kind: "ClusterOperator",
metadata: {
creationTimestamp: "2019-04-08T10:51:13Z",
generation: 1,
name: "authentication",
resourceVersion: "12577",
selfLink: "/apis/config.openshift.io/v1/clusteroperators/authentication",
uid: "3a112048-59ec-11e9-989d-0a0aad7aab7e"
},
spec: { },
status: {
conditions: [
{
lastTransitionTime: "2019-04-08T10:51:13Z",
message: "Failing: error checking payload readiness: unable to check route health: failed to GET route: EOF",
reason: "Failing",
status: "True",
type: "Failing"
},
```
nothing is progressing afaict

**Comment by kikisdeliveryservice** [comment]
I think the 3 informer commits should be squashed here just to tighten up the commits a bit.

**Comment by runcom** [comment]
> I think the 3 informer commits should be squashed here just to tighten up the commits a bit.

They are 3 different units

- fix a bug
- refractor a loop
- refactor client usages

If I'll look at a single commit mixing those together in the future I would feel bad lol

**Comment by runcom** [comment]
BTW, I've removed the last commit since it's not in #610 🎉

**Comment by LorbusChris** [comment]
lgtm pending CI success!

**Comment by LorbusChris** [comment]
bootstrap complete timed out

/retest

**Comment by kikisdeliveryservice** [comment]
seeing in e2e-aws/artifacts/e2e-aws/bootstrap/openshift.service:
```Apr 09 13:36:25 ip-10-0-10-57 openshift.sh[1346]: error: unable to recognize "./99_openshift-machineconfig_master.yaml": no matches for kind "MachineConfig" in version "machineconfiguration.openshift.io/v1```

**Comment by runcom** [comment]
ok I've finally understood what's happening here! (basically MC,MCP,CC aren't even a thing by the time we try to sync informers cause we haven't installed the CRDs...). I'll rework this out a bit.

**Comment by runcom** [comment]
Should be fixed now

**Comment by runcom** [comment]
oh finally this turned green and the others are going to as well

**Comment by cgwalters** [comment]
Nice work on this, love the split-up commits!

**Comment by runcom** [comment]
> /lgtm

wut, it ignored @kikisdeliveryservice lgtm 🤔

**Comment by kikisdeliveryservice** [comment]
@runcom that's really weird!!!

**Pull request merged**
