### PR TITLE
add ipsec extension

### PR DESCRIPTION
**Pull request by yuvalk**
**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by cgwalters** [comment]
Let's note this requires https://github.com/openshift/os/pull/1308
/approve

**Comment by travier** [comment]
Let's link to https://issues.redhat.com/browse/OCPBU-633

**Comment by travier** [comment]
It takes some time for merged pull requests in openshift/os to land in a payload available in CI.
/retest

**Comment by cgwalters** [comment]
Tests are failing due to
> E0613 12:22:33.121894    5142 writer.go:200] Marking Degraded due to: error running rpm-ostree update --install kernel-devel --install kernel-headers --install krb5-workstation --install libkadm5 --install ipsec --install usbguard: error: Packages not found: ipsec

Because we needed https://github.com/openshift/os/pull/1308#issuecomment-1587565854

/retest

**Pull request merged**
