### PR TITLE
MCD: update hacking doc

### PR DESCRIPTION
**Pull request by yuqi-zhang**
The CVO is now a daemonset.

### CODE REVIEW

**Comment by ashcrow** [comment]
lovely. A doc only update is failing CI :laughing:

**Comment by ashcrow** [comment]
Ah looks like content for CI hasn't sync'd fully yet:

```
could not wait for build: the build machine-config-operator failed after 13s with reason PullBuilderImageFailed: Failed pulling builder image.
```

**Comment by sdemos** [comment]
well, let's give it another shot then!

/retest

**Comment by abhinavdahiya** [comment]
The daemonset is temporary. Waiting for `k8s 1.12` to be available for openshift. So you might have to switch it back pretty soon. :)

/lgtm

**Pull request merged**
