### PR TITLE
daemon: Explicitly stop kubelet.service first before rebooting

### PR DESCRIPTION
**Pull request by cgwalters**
This is resurrecting the other part of:
https://github.com/openshift/machine-config-operator/pull/237

Basically it's not advantageous to us to try to shut down everything
at once; we want to ensure kubelet can fully shut itself down
gracefully, and only after that initiate the reboot for the rest
of the machine.

This also sets the MCD up to be in full explicit control of
kubelet shutdown; e.g. if we wanted to configure timeout behavior
more, we could easily do that with this "2 phase" shutdown (though
it would involve some custom code and not a shell script one-liner).

### CODE REVIEW

**Comment by cgwalters** [comment]
The thing we want to add at some point on top of this that https://github.com/openshift/machine-config-operator/pull/237 was trying to do is ensure that kubelet's `SIGTERM` handling evicts daemonset pods too, and doesn't allow new ones to be scheduled.

**Comment by rphillips** [comment]
lgtm

**Comment by cgwalters** [comment]
@rphillips Were you intentionally omtting a `/` there, to defer to a second review?  (I'm fine if that's the case, just curious)

**Pull request merged**
