### PR TITLE
[release-4.6] Bug 1899622: backport bond options fixes

### PR DESCRIPTION
**Pull request by trozet**
Includes fixes for bond options, dhcp client id, and iface parsing.

### CODE REVIEW

**Comment by trozet** [comment]
@danwinship @celebdor

**Comment by markmc** [comment]
(patch manager) looks like a fix for an issue that is affecting some real-world users

**Comment by markmc** [comment]
@trozet @danwinship still needs approved label

**Review by yuqi-zhang — APPROVED** [review]

**Pull request merged**
