### PR TITLE
daemon/fsclient: Wraps file system operations

### PR DESCRIPTION
**Pull request by ashcrow**
Part of #101 

/cc @jlebon @sdemos @kikisdeliveryservice

### CODE REVIEW

**Comment by ashcrow** [comment]
/hold

Holding until after the current round of testing.

**Comment by ashcrow** [comment]
Updated:

- Cleaned up some confusing code
- Added mock
- Wired client into the daemon

**Comment by ashcrow** [comment]
@kikisdeliveryservice I think this will be the next need to be able to do testing of your PRs code path. Since `Daemon.update()` (and likely whatever ends up writing SSH keys) attempts to do operating system operations this mock would be able to intercept and return to cover different scenarios.

**Comment by kikisdeliveryservice** [comment]
@ashcrow sounds good, will take a look. thank you!

**Comment by ashcrow** [comment]
```
operator Instantiate the template e2e-aws into the operator namespace and wait for any pods to complete 50m54s
```

Totally unrelated.

**Comment by ashcrow** [comment]
/hold cancel

Originally I was going to write an example test with it but since it's so low level and requires other stubs in combination I'm dropping the hold.

**Pull request merged**
