### PR TITLE
Start openvswitch and ovsdb-server when network is ovn/ovs

### PR DESCRIPTION
**Pull request by runcom**
This was merged but caused CNO CI issues on upgrades so we reverted. Bringing this up for @mccv1r0 @squeed @dcbw for further testing before the green light on this.

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by trozet** [comment]
CNO patch is now merged

/retest

**Comment by squeed** [comment]
OVN and openshift-sdn came up fine! This looks good. The test failure is the annoying ovn deadlock; that should be fixed soon.
for what it's worth,
/lgtm

**Comment by runcom** [comment]
> OVN and openshift-sdn came up fine! This looks good. The test failure is the annoying ovn deadlock; that should be fixed soon.
> for what it's worth,
> /lgtm

given the confidence in this by the CNO team, I'm unholding this :) thanks everybody for the testing

/hold cancel

**Comment by squeed** [comment]
/test e2e-aws
(something seems wrong with the CI cluster)

**Pull request merged**
