### PR TITLE
daemon: Refuse to disable FIPS mode

### PR DESCRIPTION
**Pull request by cgwalters**
Our new thought around this is that really FIPS should be a "day 1"
operation, and we don't want to make it really easy to undo.
See also https://github.com/openshift/installer/pull/2594
 Anyone who wants to force this can change the MC flag, then
`oc debug node` and run the disable command by hand, then reboot.

Our MachineConfig merge semantics should make it hard for this
to happen unless the admin explicitly deletes the installer-generated MC,
but still.

Since we don't support it and don't want customers
to do it by accident, let's disable it and also stop wasting compute
hours testing it.

### CODE REVIEW

**Comment by ashcrow** [comment]
This makes sense to me. Should we refuse to let them change FIPS at all since Day 2 wouldn't be valid?

**Comment by runcom** [comment]
> This makes sense to me. Should we refuse to let them change FIPS at all since Day 2 wouldn't be valid?

yeah, I was actually thinking if day2 isn't valid at all we might want to go the route to completely drop this FIPS from MC and either you install with fips or not. That would be the safest option to me w/o providing any way to disable it through the MCO

**Comment by cgwalters** [comment]
> Should we refuse to let them change FIPS at all since Day 2 wouldn't be valid?

Possibly but we *currently* rely on this code since we haven't landed an initramfs replacement yet.

**Comment by ashcrow** [comment]
/override ci/prow/e2e-gcp-op

I've been told there are currently some issues being looked at for the above job. Skipping.

**Comment by cgwalters** [comment]
I just noticed this in the logs:
```
I1031 20:38:14.869340       1 node_controller.go:433] Pool worker: node ci-op--bgjrr-w-d-lpplg.c.openshift-gce-devel-ci.internal is now reporting unready: node ci-op--bgjrr-w-d-lpplg.c.openshift-gce-devel-ci.internal is reporting OutOfDisk
```

**Comment by kikisdeliveryservice** [comment]
in the failed run it took almost and hour to evict arouter pod:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1233/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/231/artifacts/e2e-gcp-op/pods/openshift-machine-config-operator_machine-config-daemon-xsg8p_machine-config-daemon.log

**Comment by kikisdeliveryservice** [comment]
@cgwalters i noticed in the fips e2e they were hitting OOD on 2 nodes in the failed runs as well.  sent you the link to chat convo

**Comment by crawford** [comment]
Are we concerned about transitions in the opposite direction? Going from non-FIPS compliant to (technically still not) FIPS compliant seems more dangerous.

**Comment by cgwalters** [comment]
@crawford  Yes but see
https://github.com/openshift/machine-config-operator/pull/1233#issuecomment-548526302
(We need this right now to test FIPS at all until we land the updated RHCOS)

**Comment by cgwalters** [comment]
@ashcrow You added a hold - can you explain why?

**Comment by ashcrow** [comment]
@cgwalters I added it as @kikisdeliveryservice wanted to review why the GCE job failed to ensure it was a flake.

**Comment by kikisdeliveryservice** [comment]
> @ashcrow You added a hold - can you explain why?

held bc we saw the failed FIPs test and wanted to investigate it (ie the stuff we've been looking at)


@cgwalters  If you are fine with merging it without it passing that job at all, I'm fine with removing hold. I dont know enough about FIPs to say so myself... just lmk

**Comment by cgwalters** [comment]
Hmm.  I think this PR is quite safe, and will actually help our issues with the e2e-gcp-op test suite since it'll shorten it a bit.

But, it can also probably wait until we've figured out that suite.

**Comment by kikisdeliveryservice** [comment]
It's late for me, but I've figured out that our test is failing precisely bc FIPS day2 is broken.  I have a PR here removing the test to unblock the PRs that have been stuck since Friday:
See #1244 

Can someone in the morning just double check and then merge this (and then approve my PR)?  We have features blocked so it would be great to get the test gone and things back to working.

**Comment by ashcrow** [comment]
Needs a quick rebase

**Comment by cgwalters** [comment]
OK rebased :surfing_man: and I also added some code to more cleanly handle the [pending RHCOS change](https://gitlab.cee.redhat.com/coreos/redhat-coreos/merge_requests/680/diffs) to drop `rhcos-tools`.

**Comment by ashcrow** [comment]
/override ci/prow/e2e-aws-scaleup-rhel7

My understanding is the above failing test is unrelated

**Comment by kikisdeliveryservice** [comment]
GCP errors

/test e2e-gcp-upgrade

**Pull request merged**
