### PR TITLE
[OCPNODE-1382] ctrcfg: update CRD to always allow crun

### PR DESCRIPTION
**Pull request by haircommander**
Where it was formally only allowed when a cluster was in TP, it is now being moved to GA, and so update the CRD

Signed-off-by: Peter Hunt <pehunt@redhat.com>

**- What I did**

**- How to verify it**

**- Description for the changelog**
Make `crun` runtimeDefault field in ContainerRuntimeConfig generally available

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
makes sense to me, essentially a revert of https://github.com/openshift/machine-config-operator/pull/3295/commits/66cdd1aca024438984b01c9927ac7de8ba9c5cd9

**Comment by haircommander** [comment]
@QiWang19 @rphillips PTAL

**Review by QiWang19 — COMMENTED** [review]
/lgtm

**Pull request merged**
