### PR TITLE
Bug 2034537: OWNERS: Update ShiftStack members

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by sinnykumari** [comment]
Out of curiosity, is Shiftstack and OpenStack refers to same team in OpenShift?

**Comment by pierreprinetti** [comment]
>Shiftstack and OpenStack refers to same team in OpenShift

Within the context of OpenShift, we are the OpenStack team indeed. However since we officially are in the OpenStack organisation, it's weird to refer to the team as "openstack" in that context... hence the juggling :sweat_smile:

**Comment by sinnykumari** [comment]
Interesting information, thanks for sharing :)

**Review by sinnykumari — APPROVED** [review]

**Comment by kikisdeliveryservice** [comment]
Since this is just an OWNER's file  update no need to retest

/override e2e-aws
/override e2e-gcp-op

**Pull request merged**
