### PR TITLE
MCD: fix another panic in onceFrom with Ignition

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

follow up to #483 cause there's still a panic in rhel scaleup job

**- How to verify it**

rhel scaleup job

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
cc @vrutkovs

**Comment by vrutkovs** [comment]
That fixes the scaleup here, thanks!

**Comment by jstuever** [comment]
/retest

Flaky.

**Pull request merged**
