### PR TITLE
OCPBUGS-18906: Remove dependency on k8s.io/kubernetes packages

### PR DESCRIPTION
**Pull request by djoshy**
**- What I did**
Created internal objects since we were not using any functionality of the package anyway. We were just using it as a vehicle to marshal and unmarshal.

**- How to verify it**
Secrets merging should work as before. 

**- Description for the changelog**
operator: removed k8s pkg dependancy

### CODE REVIEW

**Comment by cgwalters** [comment]
Nice; I wonder if there's actually some public equivalent of this in the github.com/containers namespace?  [Using a search](https://github.com/search?q=org%3Acontainers+%22Username+string%22&type=code) leads to the podman copy; another copy here looks like? https://github.com/containers/image/blob/255f36875ce5ca16bf941c18d4a2af2663daf952/pkg/docker/config/config.go#L26

May be worth trying to factor that out into a public type.

(But obviously, this is *way* better than vendoring kube, so please don't block on it, just a drive-by thought)

**Comment by sergiordlr** [comment]
Verified using IPI on GCP

All critical test cases passed
Those test cases were executed and passed:

"[sig-mco] MCO Layering Author:sregidor-ConnectedOnly-Longduration-NonPreRelease-Medium-54056-Update osImage using the internal registry to store the image [Disruptive] [Serial]"
"[sig-mco] MCO Author:sregidor-NonPreRelease-Longduration-Medium-57595-Use empty pull-secret[Disruptive] [Serial]"
"[sig-mco] MCO Author:mhanss-NonPreRelease-Longduration-High-42680-change pull secret in the openshift-config namespace [Serial]"

We can add the qe-approved label

/label qe-approved

**Pull request merged**
