### PR TITLE
Bug 1952358: vSphere platform none vmxnet3v4 fix

### PR DESCRIPTION
**Pull request by jcpowermac**
This adds `templates/common/none` directory
with the fix `platform: vsphere` for vmxnet3 v4.

### CODE REVIEW

**Comment by jcpowermac** [comment]
I am unsure who the owners should be. Probably not vsphere

**Comment by yuqi-zhang** [comment]
Two quick questions:

1. Aside from metal-on-vsphere, do we know if there are other use cases for `none`?
2. As an alternative, we could ship this as a base template, and gate on vsphere platform (I guess the script already does, because `vmxnet3` should only be used on vsphere right?). It *should* not affect other platforms and doesn't open the potential can of worms of a "none" platform. Would there be other downsides to this?

**Comment by jcpowermac** [comment]
> Two quick questions:
> 
> 1. Aside from metal-on-vsphere, do we know if there are other use cases for `none`?

Any cloud platform that we currently don't support directly and baremetal upi. There could be more and I am forgetting

> 2. As an alternative, we could ship this as a base template, and gate on vsphere platform (I guess the script already does, because `vmxnet3` should only be used on vsphere right?). It _should_ not affect other platforms and doesn't open the potential can of worms of a "none" platform. Would there be other downsides to this?

I think this is up to the MCO team. I just tried out adding the none template directory and it worked. I figured that we are limiting our potential for an issue. If mco feels more comfortable moving it to base I have no problem moving it.

**Pull request closed without merging**
