### PR TITLE
NO-JIRA: Fix patch comparison bug in test

### PR DESCRIPTION
**Pull request by QiWang19**
**- What I did**
Fix patch comparison bug in test `func checkAction`
**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by rphillips** [comment]
5 years old... Nice find.

/lgtm
/approve

**Comment by rphillips** [comment]
/retitle NO-JIRA: Fix patch comparison bug in test

**Review by yuqi-zhang — APPROVED** [review]
Looks much cleaner, thanks!

**Pull request merged**
