### PR TITLE
ovirt: Use the DNSVIP for workers

### PR DESCRIPTION
**Pull request by rgolangh**
oVirt worker will most of the time failed to join the cluster because they don't have a nameserver
set to resolve the api or api-int.
The problem is that a `/etc/dhclient/dhclient.conf` is written during the network manager pre-up hook, using the file https://github.com/openshift/machine-config-operator/commit/d3d4e5fd662bd54c04cd38374d3cc28ceb7c4dff#diff-35faebd7db8179e62b9eb7ca9604ce72
and because of a race, dhclient doesn't recognize the new config.

- What I did
This change will write `/etc/dhcp/dhclient.conf` using ignition, with the DNS VIP prepended 
as the first nameserver. The DNSVIP is interpolated by the server so it is written in its final form
in the ignition phase (just like the masters). This eliminates the race I'm seeing.

Related-to: https://github.com/openshift/machine-config-operator/issues/1312

- How to verify it

Run IPI installation of oVirt, 3 master (all of them use those static pods) and 2 workers which are added using cluster-api-provider-ovirt, and see them join and go into `Ready` state.

- Description for the changelog
Set the `DNSVIP` as the first nameserver for worker by writing `/etc/dhcp/dhclient.conf` using ignition.

### CODE REVIEW

**Comment by ericavonb** [comment]
💯 to removing templating where possible. I only did a quick look over and don't see anything jump out at me. Lemme go through it more thoughtfully to be sure of the underlying logic. lmk if you need this merged more urgently tho.

**Comment by rgolangh** [comment]
@ericavonb do note that the first commit here is taken from a PR #1298 
It is not depended on it but I wanted to see them both running and to verify the behaviour.

**Comment by yboaron** [comment]
@rgolangh  Any reason for including the static pods resources customizations to this PR? 
I would suggest splitting this PR

**Comment by rgolangh** [comment]
That was just to help me run them without failing on memory. In the end it
should be removed. (it has a separate PR)

**Comment by rgolangh** [comment]
@ericavonb I can't seem to get rid of the aws errors. Is that a known issue?

**Comment by ericavonb** [comment]
> @ericavonb I can't seem to get rid of the aws errors. Is that a known issue?

Looks like AWS has not doing well yesterday: https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-aws?buildId=

I'll look at this PR's failures to make sure they are failing for the same reason the others were.

**Comment by ericavonb** [comment]
Looks like e2e-aws passed 🎉 ! Leaving the lgmt to someone from the ovirt side.

/approve

**Comment by cuppett** [comment]
@ericavonb looks we are ready now. Can this be approved by somebody else on the team?

**Comment by rgolangh** [comment]
@yboaron @celebdor Can one of you lgtm this?

**Pull request merged**
