### PR TITLE
Bug 1829923: etcd-quorum-guard: update containers section in deployment.yaml

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Made the following changes as settings were not getting
picked up:
- move failure threshold/timeout to nest under readinessProbe
- move and correct initialDelaySeconds and periodSeconds
- reorder container sub-elements to nest image under name

### CODE REVIEW

**Comment by ironcladlou** [comment]
/retitle Bug 1829923: etcd-quorum-guard: move failure threshold/timeout to under readiness

**Comment by kikisdeliveryservice** [comment]
cc: @wking

**Comment by kikisdeliveryservice** [comment]
e2e-aws seems to have some issues..

```level=error msg="When applying changes to module.vpc.aws_vpc.new_vpc[0], provider" level=error msg="\"registry.terraform.io/-/aws\" produced an unexpected new value for was" level=error msg="present, but now absent."```

/test e2e-aws

**Comment by hexfusion** [comment]
LGTM in principle, let's confirm we see expected results.

**Comment by kikisdeliveryservice** [comment]
> LGTM in principle, let's confirm we see expected results.

cool after this is confirmed we can cherrypick to 4.5

**Comment by ironcladlou** [comment]
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-gcp-upgrade/1271147848536166400/artifacts/e2e-gcp-upgrade/pods.json

```
"failureThreshold": 3,
"initialDelaySeconds": 5,
"periodSeconds": 10,
"successThreshold": 1,
"timeoutSeconds": 1
```

Hmmm...

**Comment by kikisdeliveryservice** [comment]
i think the containers section is off  maybe?

**Comment by kikisdeliveryservice** [comment]
other platforms are doing it in this format:
https://github.com/openshift/machine-config-operator/blob/6452d0596763d3579bac906fd1e12341b3ad9188/manifests/vsphere/coredns.yaml#L51

**Comment by kikisdeliveryservice** [comment]
checking the e2e-aws job that just passed:
```
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-aws/1271179174106632192/artifacts/e2e-aws/gather-extra/deployments.json | zcat | jq -r '.items[] | select(.metadata.name | contains("quorum-guard")).spec.template.spec.containers[] | select(.name == "guard").readinessProbe.timeoutSeconds'
3
```

**Comment by kikisdeliveryservice** [comment]
also:

$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-aws/1271179174106632192/artifacts/e2e-aws/gather-extra/deployments.json | zcat | jq -r '.items[] | select(.metadata.name | contains("quorum-guard")).spec.template.spec.containers[] | select(.name == "guard").readinessProbe.periodSeconds'
5

**Comment by kikisdeliveryservice** [comment]
Cleaned up commits and repushed, if we get a successful run we can verify the way I did above to make sure the values are now correct.

**Comment by wking** [comment]
/lgtm
/hold

Pull the hold when the results look good :)

**Comment by kikisdeliveryservice** [comment]
reconfirming in this e2e-aws run:
Expect deployment values from PR ftr:
initialDelaySeconds: 5
periodSeconds: 5
failureThreshold: 3
timeoutSeconds: 3

e2e-aws deployments.json check:
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-aws/1271220314893717504/artifacts/e2e-aws/gather-extra/deployments.json | zcat | jq -r '.items[] | select(.metadata.name | contains("quorum-guard")).spec.template.spec.containers[] | select(.name == "guard").readinessProbe.failureThreshold'
3
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-aws/1271220314893717504/artifacts/e2e-aws/gather-extra/deployments.json | zcat | jq -r '.items[] | select(.metadata.name | contains("quorum-guard")).spec.template.spec.containers[] | select(.name == "guard").readinessProbe.initialDelaySeconds'
5
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-aws/1271220314893717504/artifacts/e2e-aws/gather-extra/deployments.json | zcat | jq -r '.items[] | select(.metadata.name | contains("quorum-guard")).spec.template.spec.containers[] | select(.name == "guard").readinessProbe.periodSeconds'
5
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-aws/1271220314893717504/artifacts/e2e-aws/gather-extra/deployments.json | zcat | jq -r '.items[] | select(.metadata.name | contains("quorum-guard")).spec.template.spec.containers[] | select(.name == "guard").readinessProbe.timeoutSeconds'
3

And also:
e2e-aws pods.json check:

$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-aws/1271220314893717504/artifacts/e2e-aws/gather-extra/pods.json | jq -r '.items[] | select(.metadata.name | contains("quorum-guard")).spec.containers[] | select(.name == "guard").readinessProbe | {initialDelaySeconds, periodSeconds, failureThreshold, timeoutSeconds} | tostring'
{"initialDelaySeconds":5,"periodSeconds":5,"failureThreshold":3,"timeoutSeconds":3}
{"initialDelaySeconds":5,"periodSeconds":5,"failureThreshold":3,"timeoutSeconds":3}
{"initialDelaySeconds":5,"periodSeconds":5,"failureThreshold":3,"timeoutSeconds":3}

**Comment by kikisdeliveryservice** [comment]
rhel7 and metal-ipi seem to have RBAC issues

/skip

**Comment by kikisdeliveryservice** [comment]
Since I've confirmed this 2x am lifting hold to merge

/hold cancel

**Comment by kikisdeliveryservice** [comment]
Backports for 4.4 & 4.5:
https://github.com/openshift/machine-config-operator/pull/1819
https://github.com/openshift/machine-config-operator/pull/1820

Also fixed the BZs to link correctly to the open PRs :smile: 

@ironcladlou @hexfusion PTAL at the above backports

**Comment by ironcladlou** [comment]
I don't see the right values in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-gcp-upgrade/1271220339220680704/artifacts/e2e-gcp-upgrade/pods.json

But I do see them in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1818/pull-ci-openshift-machine-config-operator-master-e2e-aws/1271220314893717504/artifacts/e2e-aws/gather-extra/pods.json

Which is somewhat concerning. I don't know how to explain the discrepancy yet.

I'm running an upgrade test against https://github.com/openshift/machine-config-operator/pull/1819 to exercise 4.4 -> 4.5 and see what happens.

**Comment by wking** [comment]
CVO code [looks][1] [like][2] it is [missing][3] some properties.  Not sure yet if that is intentional or not, but seems like a CVO bug to me.

[1]: https://github.com/openshift/cluster-version-operator/blob/2df3d56142fd8200bd8313a8bee7cd5757696b89/lib/resourcemerge/core.go#L126-L127
[2]: https://github.com/openshift/cluster-version-operator/blob/2df3d56142fd8200bd8313a8bee7cd5757696b89/lib/resourcemerge/core.go#L162
[3]: https://github.com/openshift/cluster-version-operator/blob/2df3d56142fd8200bd8313a8bee7cd5757696b89/lib/resourcemerge/core.go#L166

**Comment by ironcladlou** [comment]
@wking 
>CVO code looks like it is missing some properties. Not sure yet if that is intentional or not, but seems like a CVO bug to me.

Interesting... that could explain the upgrade results. Still waiting on my Y upgrade run to confirm the issue.

**Comment by ironcladlou** [comment]
Wanted to test a Y upgrade but cluster-bot didn't like that this PR was merged so I went with https://github.com/openshift/machine-config-operator/pull/1819:

```
test upgrade 4.4 openshift/machine-config-operator#1819
```

https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1272513653010075648/artifacts/launch/pods.json

```
 "failureThreshold": 3,
"periodSeconds": 10,
"successThreshold": 1,
"timeoutSeconds": 1
```

**Comment by ironcladlou** [comment]
https://github.com/openshift/cluster-version-operator/pull/383

**Pull request merged**
