### PR TITLE
Bump to the latest Ignition 2.7.0

### PR DESCRIPTION
**Pull request by cgwalters**
On general principle; that's what's in current RHCOS 4.7 and we
should support that version of configs.

### CODE REVIEW

**Comment by ashcrow** [comment]
cc @miabbott

**Review by ashcrow — APPROVED** [review]

**Comment by jlebon** [comment]
I think this is pretty safe because it's purely a vendor update and parsing-related imports are versioned to the spec, so this isn't on its own causing us to accept spec 3.2.0 configs, but it sets us up for that (and we'll need that for 4.7).

/lgtm

**Pull request merged**
