### PR TITLE
[release-4.7] Bug 1968759: Bump drain timeout to 1h 

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Manual backport of https://github.com/openshift/machine-config-operator/pull/2597

### CODE REVIEW

**Comment by sinnykumari** [comment]
Looks like you are still working on it, didn't noticed it while adding lgtm.
Removing lgtm label, will look again once ready
/lgtm cancel

**Comment by kikisdeliveryservice** [comment]
Probably should consider bumping 4.7 gcp-op run time to 90, we bumped it in 4.8 via in March: https://github.com/openshift/machine-config-operator/commit/36b6d53f3aada527dc43639870497e3f02bd8cab

And we're seeing similar timeouts in 4.7 (not just this PR) but many of the failures on this branch. If this doesn't pass by EOD I'll bump runtime to 90. We probably should've done 4.7 when we bumped 4.8 since both branches were similar at bump time.

**Comment by kikisdeliveryservice** [comment]
gcp-op passing, e2e-aws-serial flaky

@sinnykumari  can you re-lgtm so the bit can take over retesting?

/test e2e-aws-serial

**Comment by kikisdeliveryservice** [comment]
Vpc limit on aws-serial ugh.

**Pull request merged**
