### PR TITLE
Add vSphere IPI

### PR DESCRIPTION
**Pull request by jcpowermac**
Uses existing baremetal networking like openstack and ovirt.

- Added manifests and template for vSphere which identical
beyond names as ovirt (cp and sed).
- Updated bindata as required
- Update pkg/operator/bootstrap for vsphere

Requires: https://github.com/openshift/api/pull/541

### CODE REVIEW

**Comment by sdodson** [comment]
@jcpowermac Is this still WIP for any reason other than needing #1377 ?

**Comment by jcpowermac** [comment]
> @jcpowermac Is this still WIP for any reason other than needing #1377 ?

That is the only reason its WIP.  Need the change we made to the API.

**Comment by patrickdillon** [comment]
I have tested this with the base image from openshift/cluster-config-operator#111 and the machine-config-operator becomes available.

**Comment by jcpowermac** [comment]
Took off WIP
Should be ready once this PR merges:
https://github.com/openshift/machine-config-operator/pull/1393

**Comment by yuqi-zhang** [comment]
-- FAIL: TestGenerateMachineConfigs (0.44s)
    render_test.go:286: failed to generate machine configs: failed to create MachineConfig for role master: failed to execute template: template: ../../../templates/common/vsphere/files/vsphere-coredns-db.yaml:14:26: executing "../../../templates/common/vsphere/files/vsphere-coredns-db.yaml" at <.Infra.Status.PlatformStatus.VSphere.APIServerInternalIP>: can't evaluate field Status in type *v1.Infrastructure

**Comment by jcpowermac** [comment]
Updated:
`pkg/controller/template/test_data/controller_config_vsphere.yaml`

**Comment by iliws** [comment]
p

**Pull request merged**
