### PR TITLE
Bug 1898036: Copy files from NM overlay onto /etc/NetworkManager/system-connections

### PR DESCRIPTION
**Pull request by rcarrillocruz**
**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by celebdor** [comment]
The code looks good to me. I'm launching a baremetal ipi deployment with it to verify it

**Review by bcrochet — APPROVED** [review]
/lgtm

**Comment by celebdor** [comment]
/lgtm

```
[core@master-0 ~]$ uptime
 18:57:04 up 0 min,  1 user,  load average: 6.47, 1.66, 0.56
[core@master-0 ~]$ ls /etc/NetworkManager/system-connections-merged/
br-ex.nmconnection               ovs-if-br-ex.nmconnection  ovs-port-br-ex.nmconnection
default_connection.nmconnection  ovs-if-phys0.nmconnection  ovs-port-phys0.nmconnection
[core@master-0 ~]$ ls /run/nm-system-connections/
[core@master-0 ~]$ logout
Connection to fd2e:6f44:5dd8:c956::14 closed.
```

The snippet above shows how after reboot, the upperdir `/run/nm-system-connections/` is empty but the connections are in `/etc/NetworkManager/system-connections-merged`. It also makes it evident that it works since we are SSHed into it.

Finally, all the nodes are ready:
```
[asegurap@r640-u01 machine-config-operator]$ oc get nodes
NAME                                 STATUS   ROLES    AGE   VERSION
master-0.ostest.test.metalkube.org   Ready    master   64m   v1.19.2+ad738ba
master-1.ostest.test.metalkube.org   Ready    master   60m   v1.19.2+ad738ba
master-2.ostest.test.metalkube.org   Ready    master   59m   v1.19.2+ad738ba
worker-0.ostest.test.metalkube.org   Ready    worker   26m   v1.19.2+ad738ba
worker-1.ostest.test.metalkube.org   Ready    worker   22m   v1.19.2+ad738ba
[asegurap@r640-u01 machine-config-operator]$
```

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by kikisdeliveryservice** [comment]
@mandre is this e2e-openstack tests working?

**Review by kikisdeliveryservice — APPROVED** [review]

**Pull request merged**
