### PR TITLE
Bug 2058626: Revert "Bump(openshift/api): to get CSI changes"

### PR DESCRIPTION
**Pull request by jsafrane**
This reverts commit 817e3a6cff52c3b2b3563de6d28a4d2921303549 / PR https://github.com/openshift/machine-config-operator/pull/2949

It broke fsGroup in Prometheus Pods / PVs. See https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-azure/1496904660361940992 and https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2058626#c1

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
cc @bertinatto

**Review by yuqi-zhang — APPROVED** [review]

**Comment by wking** [comment]
[e2e-azure][1]:

```
INFO[2022-02-25T17:01:10Z] Running step e2e-azure-ipi-install-install.  
INFO[2022-02-25T17:37:10Z] Step e2e-azure-ipi-install-install succeeded after [36](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2968/pull-ci-openshift-machine-config-operator-master-e2e-azure/1497253671023415296#1:build-log.txt%3A36)m0s.
```

Which is enough for me to be satisfied.

/lgtm

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2968/pull-ci-openshift-machine-config-operator-master-e2e-azure/1497253671023415296#1:build-log.txt%3A34-35

**Comment by bertinatto** [comment]
/lgtm
Just to add more context, this revert is intended to unblock CI and give us more time to fix the real issue.
We'll revert this revert in a few days.

**Comment by wking** [comment]
[e2e-azure-upgrade][1] launched from `4.11.0-0.ci.test-2022-02-25-165548` which had the broken code this PR reverts, and install failed as expected for those broken releases.

[e2e-azure][2] failed, but just on `etcdHighNumberOfFailedGRPCRequests`, which is a noisy alert for Azure, so fix confirmed.

[e2e-agnostic-upgrade][3] ran on Azure, and failed the same way as e2e-azure-upgrade.  We probably need to `/override ci/prow/e2e-agnostic-upgrade`.

[e2e-gcp-op][4] is apparently required too, per the Tide message, and that's still running.  But since this is a clean revert of the most-recently-landed PR, I have no problem just `/override ...`ing everything that's keeping this from merging.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2968/pull-ci-openshift-machine-config-operator-master-e2e-azure-upgrade/1497253889223692288#1:build-log.txt%3A106
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2968/pull-ci-openshift-machine-config-operator-master-e2e-azure/1497253671023415296
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2968/pull-ci-openshift-machine-config-operator-master-e2e-agnostic-upgrade/1497250224706424832
[4]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2968/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1497250224970665984

**Comment by yuqi-zhang** [comment]
Given trevor's assessment, and looking at the various failures starting when https://github.com/openshift/machine-config-operator/pull/2949 merged, there's enough correlational evidence to believe that the e2e-agnostic upgrades are failing due to the install failing due to the previous PR. 

Overriding just that test (and it should be a safe operation anyways. There are no successful e2e-upgrades on azure so this can't make it worse)

/override ci/prow/e2e-agnostic-upgrade

**Comment by gnufied** [comment]
@yuqi-zhang @bertinatto @wking how do we ensure that nobody else bumps the api while we fix CSIDriver issue for real? Will adding a comment to `go.mod` help?

**Comment by yuqi-zhang** [comment]
>@yuqi-zhang @bertinatto @wking how do we ensure that nobody else bumps the api while we fix CSIDriver issue for real? Will adding a comment to go.mod help?

Depends on how long we foresee the fix taking. If its in the next few weeks, we can probably just be careful

**Pull request merged**
