### PR TITLE
OCPBUGS-5999: 4.12 - remove goutils from dependency tree

### PR DESCRIPTION
**Pull request by cheesesashimi**
**- What I did**

Analyzed the MCO to understand where goutils was being introduced as a dependency. I discovered that it was introduced via the sprig template helper library. We only make use of two functions within that library (which do not depend on goutils). This enabled me to do the following:
- Copy those funcs we use into our codebase.
- Consolidate the use of those funcs into a single place. Further consolidation is possible, but outside the scope of this PR.
- Wrote smoke test to validate that all templated manifests can be rendered and then decoded into the appropriate structs.
- Removed sprig, goutils, and its dependent libraries from our vendor folder and go.mod / go.sum files.

Note to reviewer: I put the dependency removal in a commit by itself for easier review. This is manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3480.

**- How to verify it**

Run the unit test suite

**- Description for the changelog**
Remove goutils from our dependency tree

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
lgtm, seems like a clean cherry-pick, I couldn't quite tell if there was a diff between this and the 4.13 PR, but if there was any, likely doesn't affect anything

**Comment by cheesesashimi** [comment]
> lgtm, seems like a clean cherry-pick, I couldn't quite tell if there was a diff between this and the 4.13 PR, but if there was any, likely doesn't affect anything

Most of the merge conflict for this branch was happening in the `go.sum` file. It was easier to cherry-pick the code changes then run `$ go mod tidy && go mod vendor` to fix things.

**Comment by sergiordlr** [comment]
Verified that there was no reference to goutils in the repository and run test case "[sig-mco] MCO Author:mhanss-Longduration-NonPreRelease-Critical-42438-add journald systemd config [Disruptive] [Serial]" as a sanity check.


We add the qe-approve label

/label qe-approved

**Comment by yuqi-zhang** [comment]
@sergiordlr since this is 4.12, can you see if you can apply the cherry-pick approved label?

**Comment by sergiordlr** [comment]
> @sergiordlr since this is 4.12, can you see if you can apply the cherry-pick approved label?

/label cherry-pick-approved

**Pull request merged**
