### PR TITLE
OCPBUGS-2197: OCPBUGS-2122: update: Inject proxy data for firstboot

### PR DESCRIPTION
**Pull request by cgwalters**
The least invasive fix for ensuring we get the proxy setup in the unit.

Closes: https://issues.redhat.com/browse/OCPBUGS-2197

### CODE REVIEW

**Comment by cgwalters** [comment]
Not tested manually, but this seems sufficiently obvious to just toss up directly and let CI cover the non-proxy paths.  If I correctly read the incantation from the cluster-bot spellbook (i.e. "test upgrade openshift/machine-config-operator#3370 [quay.io/openshift-release-dev/ocp-release:4.12.0-ec.4-x86_64](http://quay.io/openshift-release-dev/ocp-release:4.12.0-ec.4-x86_64) proxy"), then https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1580175797228933120 will test an upgrade with a proxy enabled from this.

**Comment by sinnykumari** [comment]
This should also fix https://issues.redhat.com/browse/OCPBUGS-2122 and https://issues.redhat.com/browse/OCPBUGS-2245 . Running proxy job that we have in payload to get ci coverage.
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-proxy

**Comment by cgwalters** [comment]
/hold
until we verify https://pr-payload-tests.ci.openshift.org/runs/ci/d36a5440-4a30-11ed-8a6d-c80c3c04d9f0-0 passed

**Comment by sinnykumari** [comment]
another attempt to also include OCPBUGS-2122 (after fixing target version)
/jira refresh

**Comment by stbenjam** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-proxy

**Comment by cgwalters** [comment]
Ah no, we actually need to inject the proxy environment into the container, not the systemd unit.

**Comment by stbenjam** [comment]
Logs are in the installer log-bundle, it shows this:

```
Oct 12 16:36:57 ip-10-0-57-66 machine-config-daemon[2132]: W1012 16:36:57.096500    2132 firstboot_complete_machineconfig.go:46] error: failed to update OS to registry.build01.ci.openshift.org/ci-op-km61h217/stable@sha256:67e996c9886db89d3b8b66fed715806ebd91a7d598564bc0d33b75be2d5f9d75 : error running rpm-ostree rebase --experimental ostree-unverified-registry:registry.build01.ci.openshift.org/ci-op-km61h217/stable@sha256:67e996c9886db89d3b8b66fed715806ebd91a7d598564bc0d33b75be2d5f9d75: error: remote error: pinging container registry registry.build01.ci.openshift.org: Get "https://registry.build01.ci.openshift.org/v2/": dial tcp 54.243.147.229:443: i/o timeout
```

Is that the right place? Looks like rpm-ostree rebase is run in pkg/daemon/update.go - is that getting the proxy settings?

**Comment by cgwalters** [comment]
> Is that the right place? Looks like rpm-ostree rebase is run in pkg/daemon/update.go - is that getting the proxy settings?

We actually now have *three* places this needs to be handled confusingly:

- old machine-os-content flow (all works)
- firstboot (and 4.11 upgrade hack) `machine-config-daemon-update-rpmostree-via-container.service` :new: 
- Default (happy path) `rpm-ostreed.service` :new: 

Both the latter two should be fixed now, let's see.

/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-proxy

**Comment by sinnykumari** [comment]
latest proxy job failed during m-c-d-firstboot:
```
Oct 12 18:45:27 ip-10-0-48-255 machine-config-daemon[2134]: W1012 18:45:27.469507    2134 firstboot_complete_machineconfig.go:46] error: failed to update OS to registry.build01.ci.openshift.org/ci-op-pf8311f2/stable@sha256:67e996c9886db89d3b8b66fed715806ebd91a7d598564bc0d33b75be2d5f9d75 : error running rpm-ostree rebase --experimental ostree-unverified-registry:registry.build01.ci.openshift.org/ci-op-pf8311f2/stable@sha256:67e996c9886db89d3b8b66fed715806ebd91a7d598564bc0d33b75be2d5f9d75: error: remote error: pinging container registry registry.build01.ci.openshift.org: Get "https://registry.build01.ci.openshift.org/v2/": dial tcp 54.243.147.229:443: i/o timeout
Oct 12 18:45:27 ip-10-0-48-255 machine-config-daemon[2134]: : exit status 1
```

**Comment by cgwalters** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-proxy
I don't know why this isn't working; been fighting trying to get a debug shell in a reproducer environment.  Added some debug information in the hope that will help.  But I think what may work better is to spawn a cluster in the proxy env, then do an upgrade from it.  Will look at that tomorrow.

**Comment by cgwalters** [comment]
OK, hopping into a 4.11 cluster's node that is set up with a proxy, and manually overriding rpm-ostree+ostree+skopeo, I can verify that injecting the `EnvironmentFile=/etc/mco/proxy.env` is indeed sufficient to let us pull containers via the skopeo proxy (as expected!).

**Comment by cgwalters** [comment]
Ohh...I think I see the problem, somehow we're not getting the new drop-in.  It may have to do with the fact that we have two separate drop-ins for rpm-ostreed?  Digging

**Comment by cgwalters** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-proxy

**Comment by MaysaMacedo** [comment]
Thanks for working on this! It also helps openstack installations with proxy. I tested it manually

**Comment by cgwalters** [comment]
Yep, looking at the payload job, we're now past the install phase! :tada:

Man...this not working on the first try because that obscure template inheritance issue just completely undermined my confidence, and I'm glad the problem was just something silly and not anything fundamental.

**Comment by cgwalters** [comment]
/hold cancel
since the install phase covers what we care about here

**Comment by sinnykumari** [comment]
yep, looking at [install log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/openshift-machine-config-operator-3370-nightly-4.12-e2e-aws-ovn-proxy/1580543119965818880/artifacts/e2e-aws-ovn-proxy/ipi-install-install/artifacts/.openshift_install.log),
```
time="2022-10-13T13:48:10Z" level=info msg="Install complete!"
time="2022-10-13T13:48:10Z" level=info msg="To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/tmp/installer/auth/kubeconfig'"
```

This was tricky, thanks for getting this fixed!
/lgtm

**Comment by cgwalters** [comment]
/override ci/prow/e2e-aws
Failed during deprovisioning, not related to this change, and we have previous passes with basically the same code.
/override ci/prow/e2e-agnostic-upgrade
Ditto on deprovisioner

**Pull request merged**
