### PR TITLE
[release-4.13] OCPBUGS-19414: The kubeconfig copied on to each node has 644 permissions

### PR DESCRIPTION
**Pull request by inesqyx**
This is a manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3808
/assign yuqi-zhang

### CODE REVIEW

**Comment by inesqyx** [comment]
@openshift-cherrypick-robot: [Jira Issue OCPBUGS-15367](https://issues.redhat.com/browse/OCPBUGS-15367) has been cloned as [Jira Issue OCPBUGS-19414](https://issues.redhat.com/browse/OCPBUGS-19414). Will retitle bug to link to clone.
/retitle [release-4.13] OCPBUGS-19414: SSHkeys fails to write on upgrade to 4.13.rc3

**Comment by inesqyx** [comment]
@openshift-cherrypick-robot: [Jira Issue OCPBUGS-15367](https://issues.redhat.com/browse/OCPBUGS-15367) has been cloned as [Jira Issue OCPBUGS-19414](https://issues.redhat.com/browse/OCPBUGS-19414). Will retitle bug to link to clone.
/retitle [release-4.13] OCPBUGS-19414: The kubeconfig copied on to each node has 644 permissions

**Comment by yuqi-zhang** [comment]
Hmm, what's going on here, the bot is reporting all tests failed but the tide status seems fine...

**Pull request merged**
