### PR TITLE
[release-4.16] OCPBUGS-37759: Guard MachineOSBuild & MachineOSConfig informers with feature gates

### PR DESCRIPTION
**Pull request by djoshy**
Manual cherry pick of #4497

### CODE REVIEW

**Comment by inesqyx** [comment]
/hold 
for qe to apply the /cherry-pick-approved label

**Comment by inesqyx** [comment]
/lgtm 
otherwise

**Review by yuqi-zhang — APPROVED** [review]
/label backport-risk-assessed

Safe backport

**Pull request merged**
