### PR TITLE
Bug 1706689: pkg: Catch up to the api change introduced in openshift/api#308 

### PR DESCRIPTION
**Pull request by abhinavdahiya**
Requires https://github.com/openshift/installer/pull/1718

/cc @runcom

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
since this requires openshift/installer#1718 to be merged first, for safety:

/hold

**Comment by abhinavdahiya** [comment]
/retest

https://github.com/openshift/installer/pull/1718 merged
/hold cancel

**Comment by runcom** [comment]
can you rebase to pick can you rebase to pick #719

**Comment by abhinavdahiya** [comment]
> can you rebase to pick can you rebase to pick #719

you don't need to rebase for that, i can delete the project in ci cluster if this run fails before running a retest to bring in updated MCO master.

**Comment by runcom** [comment]
this is good to go, but I'm holding just for the beta

/hold

**Comment by kikisdeliveryservice** [comment]
This should be in the merge pool, though it can take a while for it to go in.

**Pull request merged**
