### PR TITLE
OCPNODE-2438: bump API and update CRD manifests

### PR DESCRIPTION
**Pull request by QiWang19**
Bump API to get the ClusterImagePolicy doc update https://github.com/openshift/api/pull/1927
Run hack/crds-sync.sh to update the manifests

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by QiWang19** [comment]
@yuqi-zhang Could you review?

**Comment by yuqi-zhang** [comment]
I see another bump via @djoshy 's https://github.com/openshift/machine-config-operator/pull/4477 (which is 2 days behind yours).

Would you be ok with doing it as part of that PR instead? Would you need the bump to 07-17 or is 07-15 fine?

**Comment by QiWang19** [comment]
ClusterImagePolicy updates is not in https://github.com/openshift/machine-config-operator/pull/4477. I also need to bump to 7-17 to get https://github.com/openshift/api/pull/1964

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

**Pull request merged**
