### PR TITLE
Annotate manifests for single-node-developer cluster profile

### PR DESCRIPTION
**Pull request by guillaumerose**
This implements phase 1 of openshift/enhancements#482

### CODE REVIEW

**Comment by cgwalters** [comment]
This is going to conflict with https://github.com/openshift/machine-config-operator/pull/2221 but I guess whoever merges second will just win the conflict resolution game :wink:   Well to be fair to him since it was first I added lgtm.

I thought CodeReady wasn't using the MCO because it wasn't doing in-place updates?  In light of https://github.com/openshift/enhancements/pull/504 though perhaps that is changing?

**Comment by kikisdeliveryservice** [comment]
This was discussed in the team meeting and @runcom and @crawford are both aware said that we can merge this for 4.7 for CRC.

**Comment by kikisdeliveryservice** [comment]
ugh labelling isn't getting picked up... reported in 4-dev =(

**Comment by guillaumerose** [comment]
@cgwalters It runs once when we bootstrap the cluster and then we disable it. But the long term goal is to keep it activated (and handle reboot, etc.).

**Pull request merged**
