### PR TITLE
Bug 1797035: Get etcdctl binary from the etcd image and not from the upstream releases

### PR DESCRIPTION
**Pull request by Prashanth684**
A backport of PR #1422. Could not do an automatic cherry pick because of some differences.

### CODE REVIEW

**Comment by runcom** [comment]
cc @hexfusion

**Comment by Prashanth684** [comment]
@runcom cherry-pick-approved ? thanks!

**Comment by Prashanth684** [comment]
could this be cherry-pick approved please?

**Comment by sinnykumari** [comment]
I believe cherry-pick-approval gets done periodically by patch manager

**Pull request merged**
