### PR TITLE
clusterrole: add featuregates to allowed resources

### PR DESCRIPTION
**Pull request by rphillips**
**- What I did**
FeatureGates need to be added to the clusterrole to allow for reading and listing.

**- How to verify it**

**- Description for the changelog**
`NONE`

### CODE REVIEW

**Comment by sjenning** [comment]
LGTM
/assign @abhinavdahiya

**Comment by cgwalters** [comment]
Hum...how did this slip through e2e?  My libvirt cluster is failing due to not having this atm.

/lgtm

**Pull request merged**
