### PR TITLE
[Test][release-4.12]: Increase NM Wait Online Timeout

### PR DESCRIPTION
**Pull request by zeeke**
Manual backport of
- https://github.com/openshift/machine-config-operator/pull/3531

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
@zeeke did the automatic cherry-pick fail?

To make it easier, we can directly cherry-pick with the bot to create the associated jira issue as well

**Comment by zeeke** [comment]
> To make it easier, we can directly cherry-pick with the bot to create the associated jira issue as well

@yuqi-zhang yes, but I need the master PR to be merged. I need this PR to make a 4.12 build for testing purposes.

**Comment by yuqi-zhang** [comment]
Ah got it, thanks, marking as it testing

**Comment by zeeke** [comment]
Closing waiting the discussion on:
- https://github.com/openshift/machine-config-operator/pull/3531

**Pull request closed without merging**
