### PR TITLE
Bug 2033729: Remove runtime request timeout restriction and add azure config

### PR DESCRIPTION
**Pull request by rphillips**
* Removes the restriction of setting the runtimeRequestTimeout within the kubelet config.
* Adds an azure specific config to bump the runtimeRequestTimeout to 4m

### CODE REVIEW

**Comment by dgoodwin** [comment]
Thank you! lgtm but will let MCO folks tag.

**Review by sinnykumari — APPROVED** [review]
LGTM, this change mainly effect azure platform
/lgtm

**Comment by umohnani8** [comment]
Can this be backported to 4.8 as well? Only the change to remove the restriction around setting the runtime request timeout. We are seeing some issues with timeouts so would like to increase this to see if it helps mitigate the issue.

**Comment by oarribas** [comment]
While this was reverted by the PR #2890, the runtime request timeout restriction was finally removed by #3026.

**Pull request merged**
