### PR TITLE
OCPBUGS-224: Make sure there is a search domain in resolv.conf

### PR DESCRIPTION
**Pull request by cybertron**
In environments where no search domains are provided in the DNS
configuration, we were not correctly populating the search list with
the cluster domain because the sed did not match any lines. This
change adds a special case to ensure we always have a search list
in resolv.conf.

**- What I did**

**- How to verify it**

**- Description for the changelog**
Fixed a problem in environments where no search domain was included in the DNS configuration

### CODE REVIEW

**Comment by cybertron** [comment]
/hold

I messed up the conditional here. :-(

**Comment by cybertron** [comment]
/hold cancel

This version looks like it's working.
/test e2e-metal-ipi
/test e2e-vsphere

**Review by mandre — COMMENTED** [review]
I just tried this patch on an OpenStack cloud that does not provide default search domain. I got a successful install and all nodes had the base domain added to `resolv.conf`.

The e2e-openstack failure seems unrelated to me.

/retest

**Comment by yuqi-zhang** [comment]
Just to clarify, are you looking to backport this to 4.9? The bug seems to indicate that this was an issue starting in 4.9

**Comment by cybertron** [comment]
> Just to clarify, are you looking to backport this to 4.9? The bug seems to indicate that this was an issue starting in 4.9

Yes, it looks like this will need to be backported to 4.9.

/test e2e-openstack

**Review by yuqi-zhang — APPROVED** [review]
Script itself looks sane. Will leave to others to LGTM based on actual testing

**Comment by cybertron** [comment]
/test e2e-openstack

Not sure why retest didn't work, but I believe the openstack job is unblocked now.

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
