### PR TITLE
Bug 1763695: [release-4.2] pkg/daemon: drain before applying changes

### PR DESCRIPTION
**Pull request by runcom**
backport of #1200 

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
/approve
I am not sure why we didn't do this from the very start.  It seems a lot safer.
That said, I do think a longer term fix is https://github.com/openshift/machine-config-operator/issues/1190 - but that's harder (and actually would only apply to RHCOS, but we'd still want to drain classic RHEL first).

**Comment by cgwalters** [comment]
Hm, is there no master equivalent of this PR?

**Comment by cgwalters** [comment]
Also worth a least a summary of why we need this in the commit message - something like:

> Since the MCO owns writing kubelet static pod configurations, we need to drain *before* attempting to change them so that e.g. the etcd-quorum-guard's PDB has a chance to operate.  This would have also mitigated a bug in 4.1 to 4.2 upgrades - see https://github.com/openshift/machine-config-operator/pull/1177

**Comment by runcom** [comment]
needs further discussion and approval + master PR etc etc (now BZ is wrong)

**Comment by runcom** [comment]
/cherrypick release-4.1

4.1 BZ here: https://bugzilla.redhat.com/show_bug.cgi?id=1763696

**Comment by cgwalters** [comment]
Does this one need to have been explicitly created as a cherry-pick of the master PR?  Maybe it doesn't matter and we just need an architect to do the label dance.

**Comment by runcom** [comment]
Patch manager will add the label to pick this up, we're waiting on this to let it soak a bit in master

**Comment by eparis** [comment]
This will not be able to merge until BZ 1762536 has been VERIFIED by QE. And after that someone runs `/bugzilla refresh`

**Comment by kikisdeliveryservice** [comment]
@runcom your cherry pick to 4.1 failed..

**Pull request merged**
