### PR TITLE
OCPBUGS-17841: Ensure gcp-routes hack for internalLB hairpin traffic works for SGW

### PR DESCRIPTION
**Pull request by tssurya**
Same as https://github.com/openshift/machine-config-operator/pull/3904 but for GCP
this time @huiran0826 we should ensure we don't break SDN :D 
Also I don't plan to backport the GCP fix unless someone asks

### CODE REVIEW

**Comment by ricky-rav** [comment]
I still haven't reviewed the code, but to speed things up I've tested it already on SNO, which is where an upgrade from 4.13 to 4.14 was stuck due to a missing logical route on ovn_cluster_router.


Now after a 4.13->4.14 upgrade, the routes have been added to NBDB:
```
sh-5.1# ovn-nbctl lr-policy-list ovn_cluster_router 
Routing Policies
      1010 inport == "rtos-ci-ln-ldds4xk-72292-nwblz-master-0" && ip4.dst == 10.0.0.2         reroute                10.128.0.2
      1010 inport == "rtos-ci-ln-ldds4xk-72292-nwblz-master-0" && ip4.dst == 34.134.126.150         reroute                10.128.0.2
      1010 inport == "rtos-ci-ln-ldds4xk-72292-nwblz-master-0" && ip4.dst == 35.232.72.34         reroute                10.128.0.2
      1004 inport == "rtos-ci-ln-ldds4xk-72292-nwblz-master-0" && ip4.dst == 10.0.0.3 /* ci-ln-ldds4xk-72292-nwblz-master-0 */         reroute                10.128.0.2
       102 (ip4.src == $a4548040316634674295 || ip4.src == $a13607449821398607916) && ip4.dst == $a14918748166599097711           allow               pkt_mark=1008
       102 ip4.src == 10.128.0.0/14 && ip4.dst == 10.128.0.0/14           allow
       102 ip4.src == 10.128.0.0/14 && ip4.dst == 100.64.0.0/16           allow
```

I extracted the full logs from the journal and pasted them here: https://privatebin.corp.redhat.com/?955a4c750095ea6d#C7vNnSJP25QLhvBWvATRKfBwfWHLikGf2GZ1XJyAZzYd

The following excerpt shows the routes getting added:
```
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Processing route for NIC 0/42:01:0a:00:00:03 for 10.0.0.2
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Processing route for NIC 0/42:01:0a:00:00:03 for 34.134.126.150
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Processing route for NIC 0/42:01:0a:00:00:03 for 35.232.72.34
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Found ovnkube-controller pod... 2647b1e472603
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Found v4route vips:
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ci-ln-ldds4xk-72292-nwblz-master-0
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring rule for 10.0.0.2 for external clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring rule for 10.0.0.2 for internal clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring rule for 34.134.126.150 for external clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring rule for 34.134.126.150 for internal clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring rule for 35.232.72.34 for external clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring rule for 35.232.72.34 for internal clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Found ovnkube-controller pod... 2647b1e472603
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Found ovn-k8s-mp0 interface IP 10.128.0.2
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ci-ln-ldds4xk-72292-nwblz-master-0
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring route for 10.0.0.2 for internal clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: OVNK Routes on ovn-cluster-router at 1010 priority:
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Route does not exist; creating it...
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ovn-nbctl lr-policy-add ovn_cluster_router 1010 inport == rtos-ci-ln-ldds4xk-72292-nwblz-master-0 && ip4.dst == 10.0.0.2 reroute 10.128.0.2
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring route for 34.134.126.150 for internal clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: OVNK Routes on ovn-cluster-router at 1010 priority:
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Route does not exist; creating it...
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ovn-nbctl lr-policy-add ovn_cluster_router 1010 inport == rtos-ci-ln-ldds4xk-72292-nwblz-master-0 && ip4.dst == 34.134.126.150 reroute 10.128.0.2
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ensuring route for 35.232.72.34 for internal clients
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: OVNK Routes on ovn-cluster-router at 1010 priority:
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: Route does not exist; creating it...
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: ovn-nbctl lr-policy-add ovn_cluster_router 1010 inport == rtos-ci-ln-ldds4xk-72292-nwblz-master-0 && ip4.dst == 35.232.72.34 reroute 10.128.0.2
Oct 03 13:43:32 ci-ln-ldds4xk-72292-nwblz-master-0 bash[1154]: done applying vip rules
```

**Comment by ricky-rav** [comment]
In my message from yesterday I forgot to include the main part, that is that CNCC is finally able to communicate to the API server via the internal LB IP.
Without the fix from this PR, if we do an upgrade from 4.13 to 4.14, CNCC fails at initialization:
```
$ oc logs -n openshift-cloud-network-config-controller cloud-network-config-controller-d8bf64485-lccbj
2023-10-03T17:55:27.105321631+00:00 stderr F W1003 17:55:27.105131       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2023-10-03T17:55:57.113461428+00:00 stderr F F1003 17:55:57.113383       1 main.go:345] Error building controller runtime client: Get "https://api-int.ci-ln-cjbzqt2-72292.origin-ci-int-gce.dev.rhcloud.com:6443/api?timeout=32s": dial tcp 10.0.0.2:6443: i/o timeout
```

With this PR, CNCC successfully starts:
```
$ oc logs -n openshift-cloud-network-config-controller          cloud-network-config-controller-69d5775dc4-b6p9s
W1003 18:06:49.532640       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1003 18:06:49.574908       1 leaderelection.go:245] attempting to acquire leader lease openshift-cloud-network-config-controller/cloud-network-config-controller-lock...
I1003 18:09:12.366060       1 leaderelection.go:255] successfully acquired lease openshift-cloud-network-config-controller/cloud-network-config-controller-lock
I1003 18:09:12.366899       1 simple_featuregate_reader.go:171] Starting feature-gate-detector
I1003 18:09:12.369011       1 main.go:320] FeatureGates initialized: knownFeatureGates=[AdminNetworkPolicy AdmissionWebhookMatchConditions AlibabaPlatform AutomatedEtcdBackup AzureWorkloadIdentity BuildCSIVolumes CSIDriverSharedResource CloudDualStackNodeIPs DynamicResourceAllocation EventedPLEG ExternalCloudProvider ExternalCloudProviderAzure ExternalCloudProviderExternal ExternalCloudProviderGCP GCPLabelsTags GatewayAPI InsightsConfigAPI MachineAPIOperatorDisableMachineHealthCheckController MachineAPIProviderOpenStack MaxUnavailableStatefulSet NodeSwap OpenShiftPodSecurityAdmission PrivateHostedZoneAWS RetroactiveDefaultStorageClass RouteExternalCertificate SigstoreImageVerification VSphereStaticIPs ValidatingAdmissionPolicy]
I1003 18:09:12.369052       1 event.go:298] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-cloud-network-config-controller", Name:"cloud-network-config-controller", UID:"", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'FeatureGatesInitialized' FeatureGates updated to featuregates.Features{Enabled:[]v1.FeatureGateName{"AlibabaPlatform", "AzureWorkloadIdentity", "BuildCSIVolumes", "CloudDualStackNodeIPs", "ExternalCloudProviderAzure", "ExternalCloudProviderExternal", "PrivateHostedZoneAWS"}, Disabled:[]v1.FeatureGateName{"AdminNetworkPolicy", "AdmissionWebhookMatchConditions", "AutomatedEtcdBackup", "CSIDriverSharedResource", "DynamicResourceAllocation", "EventedPLEG", "ExternalCloudProvider", "ExternalCloudProviderGCP", "GCPLabelsTags", "GatewayAPI", "InsightsConfigAPI", "MachineAPIOperatorDisableMachineHealthCheckController", "MachineAPIProviderOpenStack", "MaxUnavailableStatefulSet", "NodeSwap", "OpenShiftPodSecurityAdmission", "RetroactiveDefaultStorageClass", "RouteExternalCertificate", "SigstoreImageVerification", "VSphereStaticIPs", "ValidatingAdmissionPolicy"}}
I1003 18:09:12.369800       1 controller.go:88] Starting node controller
I1003 18:09:12.369808       1 controller.go:88] Starting secret controller
I1003 18:09:12.369817       1 controller.go:91] Waiting for informer caches to sync for node workqueue
I1003 18:09:12.369818       1 controller.go:88] Starting cloud-private-ip-config controller
I1003 18:09:12.369822       1 controller.go:91] Waiting for informer caches to sync for secret workqueue
I1003 18:09:12.369829       1 controller.go:91] Waiting for informer caches to sync for cloud-private-ip-config workqueue
E1003 18:09:12.370428       1 event.go:280] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cloud-network-config-controller.178aab4bf45b8c75", GenerateName:"", Namespace:"openshift-cloud-network-config-controller", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-cloud-network-config-controller", Name:"cloud-network-config-controller", UID:"", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}, Reason:"FeatureGatesInitialized", Message:"FeatureGates updated to featuregates.Features{Enabled:[]v1.FeatureGateName{\"AlibabaPlatform\", \"AzureWorkloadIdentity\", \"BuildCSIVolumes\", \"CloudDualStackNodeIPs\", \"ExternalCloudProviderAzure\", \"ExternalCloudProviderExternal\", \"PrivateHostedZoneAWS\"}, Disabled:[]v1.FeatureGateName{\"AdminNetworkPolicy\", \"AdmissionWebhookMatchConditions\", \"AutomatedEtcdBackup\", \"CSIDriverSharedResource\", \"DynamicResourceAllocation\", \"EventedPLEG\", \"ExternalCloudProvider\", \"ExternalCloudProviderGCP\", \"GCPLabelsTags\", \"GatewayAPI\", \"InsightsConfigAPI\", \"MachineAPIOperatorDisableMachineHealthCheckController\", \"MachineAPIProviderOpenStack\", \"MaxUnavailableStatefulSet\", \"NodeSwap\", \"OpenShiftPodSecurityAdmission\", \"RetroactiveDefaultStorageClass\", \"RouteExternalCertificate\", \"SigstoreImageVerification\", \"VSphereStaticIPs\", \"ValidatingAdmissionPolicy\"}}", Source:v1.EventSource{Component:"cloud-network-config-controller-69d5775dc4-b6p9s", Host:""}, FirstTimestamp:time.Date(2023, time.October, 3, 18, 9, 12, 368950389, time.Local), LastTimestamp:time.Date(2023, time.October, 3, 18, 9, 12, 368950389, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:serviceaccount:openshift-cloud-network-config-controller:cloud-network-config-controller" cannot create resource "events" in API group "" in the namespace "openshift-cloud-network-config-controller"' (will not retry!)
I1003 18:09:12.372402       1 controller.go:182] Assigning key: ci-ln-cjbzqt2-72292-n9jrh-master-0 to node workqueue
I1003 18:09:12.470142       1 controller.go:96] Starting secret workers
I1003 18:09:12.470163       1 controller.go:96] Starting node workers
I1003 18:09:12.470201       1 controller.go:102] Started node workers
I1003 18:09:12.470170       1 controller.go:102] Started secret workers
I1003 18:09:12.470274       1 controller.go:96] Starting cloud-private-ip-config workers
I1003 18:09:12.470319       1 controller.go:102] Started cloud-private-ip-config workers
I1003 18:09:12.815005       1 node_controller.go:142] Setting annotation: 'cloud.network.openshift.io/egress-ipconfig: [{"interface":"nic0","ifaddr":{"ipv4":"10.0.0.0/17"},"capacity":{"ip":100}}]' on node: ci-ln-cjbzqt2-72292-n9jrh-master-0
I1003 18:09:12.825636       1 controller.go:160] Dropping key 'ci-ln-cjbzqt2-72292-n9jrh-master-0' from the node workqueue
I1003 18:10:32.532963       1 controller.go:182] Assigning key: ci-ln-cjbzqt2-72292-n9jrh-master-0 to node workqueue
I1003 18:10:32.733466       1 node_controller.go:142] Setting annotation: 'cloud.network.openshift.io/egress-ipconfig: [{"interface":"nic0","ifaddr":{"ipv4":"10.0.0.0/17"},"capacity":{"ip":100}}]' on node: ci-ln-cjbzqt2-72292-n9jrh-master-0
I1003 18:10:32.744315       1 controller.go:160] Dropping key 'ci-ln-cjbzqt2-72292-n9jrh-master-0' from the node workqueue
I1003 18:10:37.561652       1 controller.go:182] Assigning key: ci-ln-cjbzqt2-72292-n9jrh-master-0 to node workqueue
I1003 18:10:37.801321       1 node_controller.go:142] Setting annotation: 'cloud.network.openshift.io/egress-ipconfig: [{"interface":"nic0","ifaddr":{"ipv4":"10.0.0.0/17"},"capacity":{"ip":100}}]' on node: ci-ln-cjbzqt2-72292-n9jrh-master-0
I1003 18:10:37.812272       1 controller.go:160] Dropping key 'ci-ln-cjbzqt2-72292-n9jrh-master-0' from the node workqueue
```

**Comment by ricky-rav** [comment]
/lgtm
Thank you, Surya!

**Review by trozet — APPROVED** [review]
/lgtm

**Comment by huiran0826** [comment]
/label qe-approved
Tested PR on both sdn and ovn cluster, verification steps added in bug, loooks good.

**Review by sinnykumari — APPROVED** [review]
/test e2e-gcp-op

**Comment by tssurya** [comment]
/test e2e-gcp-op
--

**Pull request merged**
