### PR TITLE
Updated bin data

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**- What I did**
Fix bin data
**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
Thank you @ravisantoshgudimetla !!

/lgtm

**Comment by kikisdeliveryservice** [comment]
cc: @sgreene570 @cgwalters 

This passes verify so merging to get everything unstuck

**Comment by sgreene570** [comment]
Thanks!

**Comment by cgwalters** [comment]
How did this differ from https://github.com/openshift/machine-config-operator/pull/956 ?

**Comment by kikisdeliveryservice** [comment]
I did 956 _before_ i realized we changed go bind-data packages. :smile:

**Comment by kikisdeliveryservice** [comment]
@cgwalters we went from using `https://github.com/jteeuwen/go-bindata` to ` github.com/go-bindata/go-bindata`
which you have to install locally.

see: https://github.com/openshift/machine-config-operator/pull/929

**Pull request merged**
