### PR TITLE
Change to owners for baremetal component

### PR DESCRIPTION
**Pull request by bfournie**

### CODE REVIEW

**Review by sinnykumari — APPROVED** [review]
Someone from baremetal team can add lgtm :)

**Comment by kikisdeliveryservice** [comment]
Can baremetal folks confirm this change?

/assign @celebdor @cybertron @bcrochet

**Comment by cybertron** [comment]
/lgtm

Works for me. Brad is no longer working on baremetal networking and I trust Bob not to approve anything crazy. :-)

**Comment by kikisdeliveryservice** [comment]
Since this is an owner's file change we don't need to rerun tests

/override ci/prow/e2e-agnostic-upgrade
/override ci/prow/e2e-aws

**Comment by sinnykumari** [comment]
This needs either a bz or I think baremetal team can manually add valid-bz label (as this is just owner file change) to get merged/

**Pull request merged**
