### PR TITLE
bootstrap: Clarify that "root ca" is really "MCS CA"

### PR DESCRIPTION
**Pull request by cgwalters**
No code changes, just renaming the variable and adding a link to the official doc.

Part of https://issues.redhat.com/browse/MCO-642

### CODE REVIEW

**Comment by cgwalters** [comment]
I think this PR is very safe; the relevant code paths are covered by CI well, and in the end it's really just renaming a variable and adding comments.  So let's just add the labels necessary to land this.

**Comment by sinnykumari** [comment]
LGTM
We need someone from TRT to add valid-bz
/assign @dgoodwin

**Comment by sinnykumari** [comment]
Unrelated to this PR, looking for re-enabling e2e-gcp-op-single-node node on MCO PRs as we don't have any ci coverage for SNO. Using this PR to get some signal first
/test e2e-gcp-op-single-node

**Comment by dgoodwin** [comment]
If feature related, please submit via the feature merge queue form: https://docs.google.com/forms/d/e/1FAIpQLScZ586J1krk-mqDbiywta0PphAy4jZC-FMWarKHosw9ZDNgEg/viewform?usp=sf_link

If this is a bug fix, you just need a valid 4.14 bug.

**Comment by cgwalters** [comment]
@dgoodwin It's neither.  It's a small code cleanup that has 0.00001% change of regressing or breaking anything.

**Comment by cgwalters** [comment]
(Same situation with https://github.com/openshift/installer/pull/7232 )

**Comment by cgwalters** [comment]
Oh I see, e2e-hypershift is broken again for unrelated reasons :cry:

**Pull request merged**
