### PR TITLE
templates: increase kubelet loglevel for better troubleshooting

### PR DESCRIPTION
**Pull request by sjenning**
@mrunalp @derekwaynecarr

### CODE REVIEW

**Comment by sjenning** [comment]
/hold cancel
let actually merge this.  much of the helpful tracing in the kubelet is at loglevel 3.
@rphillips

**Comment by runcom** [comment]
we're increasing the timeout in #692 (cause we believe it's just us taking longer since we've added another test to the op suite).

/retest
/lgtm

**Comment by runcom** [comment]
please rebase to pick up the CI fix

**Pull request merged**
