### PR TITLE
OCPBUGS-30139: [release-4.15] Use NM's dns-change event for resolv.conf

### PR DESCRIPTION
**Pull request by mkowalski**
This is a manual cherry-pick for commits implementing OPNET-355. Initially discovered as bug RHEL-2184.

### CODE REVIEW

**Comment by cybertron** [comment]
/test e2e-metal-ipi
/test e2e-metal-ipi-ovn-ipv6

Test failures look unrelated. I would particularly like to see the ipv6 job pass since that tends to exercise some different code paths than the ipv4 jobs.

**Comment by cybertron** [comment]
Can we reference https://issues.redhat.com/browse/OCPBUGS-30139 in this PR since I closed the original backport in favor of this one? We'll need a bug to get this merged anyway.

**Comment by mkowalski** [comment]
There is a bug and escalation (https://issues.redhat.com/browse/OCPBUGS-36639 / https://issues.redhat.com/browse/RHOCPPRIO-318) opened for OCP 4.14 that will benefit from this PR merging.

**Comment by mkowalski** [comment]
/retitle OCPBUGS-36639: [release-4.15] Use NM's dns-change event for resolv.conf

**Comment by mkowalski** [comment]
/retitle OCPBUGS-30139: [release-4.15] Use NM's dns-change event for resolv.conf

**Pull request merged**
