### PR TITLE
Enable unicast keepalived for all on-prem platforms

### PR DESCRIPTION
**Pull request by cybertron**
Initially this was only enabled for baremetal in the interest of
limiting the impacts of any new bugs introduced by the change. We've
now been running with unicast on baremetal since 4.6 and should have
worked out the kinks. Additionally, other on-prem platforms (notably
vsphere) are running into similar problems to what prompted the
change on baremetal.

In the interest of simplifying the support matrix for on-prem
platforms, this enables unicast on all of them. For the moment that
entails only hard-coding the ENABLE_UNICAST env var and moving the
flip-mode file template from baremetal-specific to all of on-prem.
I'm leaving the render functions for the moment in the interest of
avoiding issues on upgrade if an old template gets rendered by a
newer MCO. They can be cleaned up in 4.12.

**- What I did**

**- How to verify it**

**- Description for the changelog**
Enable unicast keepalived for all on-prem platforms.

### CODE REVIEW

**Comment by cybertron** [comment]
fatal: unable to access 'https://github.com/openshift/machine-config-operator.git/': Could not resolve host: github.com

seems to be the reason all the jobs insta-failed. I am confused why make update made no changes here. Was there a change to how the manifests directory is handled?

**Comment by jcpowermac** [comment]
@cybertron what is the plan for upgrade? Is that an issue?

**Comment by cybertron** [comment]
> @cybertron what is the plan for upgrade? Is that an issue?

There is code for handling the transition to unicast on upgrade, but we discovered that it has a bug[0] as part of the discussion that led to this change. However, all that means is existing clusters stay multicast and new clusters get unicast. Since clusters that were installed multicast were obviously working in that mode, I don't see it as a blocker to switching new clusters (although we do want to fix it for consistency, of course).

We wanted to push ahead with this change first so we can get a lot of soak time on the change in the 4.11 cycle just in case there are any platform-specific issues that come up. If we can fix the mode change bug in 4.11 too then that's a bonus, but either way this will fix the vrid collision problem for new clusters.

0: https://bugzilla.redhat.com/show_bug.cgi?id=2053309

**Review by mandre — COMMENTED** [review]
LGTM as far as OpenStack is concerned.

**Pull request merged**
