### PR TITLE
vendor: update openshift/kubernetes-drain

### PR DESCRIPTION
**Pull request by runcom**
xref https://github.com/openshift/kubernetes-drain/pull/1

tl;dr; the drain function wasn't correctly waiting for all pods to be
gone before reporting success.

This needs to get in for 4.1 as well, tracking bug for 4.1 is https://bugzilla.redhat.com/show_bug.cgi?id=1729510 (I'll use that in the backport PR)

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
something is slowing _a_ node down with this patch, causing tests to time out - what's funny is that something is also wrong in logs collection, some nodes are missing logs in artifacts and files for logs are also lying (notice logs should start at 18:34 but they're starting at 19:29):

```
-- Logs begin at Fri 2019-07-12 18:34:21 UTC, end at Fri 2019-07-12 19:45:27 UTC. --
Jul 12 19:29:01 localhost kernel: Linux version 4.18.0-80.4.2.el8_0.x86_64 (mockbuild@x86-vm-08.build.eng.bos.redhat.com) (gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)) #1 SMP Fri Jun 14 13:20:24 UTC 2019
```

**Comment by runcom** [comment]
/hold

a node is definitely hitting something cause it's stuck at drain and we don't have logs, testing this out on some cluster to understand what's happening

**Comment by runcom** [comment]
ok, looks like an issue in evicting image-registry - it takes 600s slowing everything down, talking to devex to understand more

**Comment by cgwalters** [comment]
Since drain is a library now, we could probably try to tweak it so we log which pods aren't being evicted at the timeout?

**Comment by runcom** [comment]
> ok, looks like an issue in evicting image-registry - it takes 600s slowing everything down, talking to devex to understand more

https://bugzilla.redhat.com/show_bug.cgi?id=1729979

**Comment by runcom** [comment]
note to self, this needs yet another bump but we're currently still blocked on an image-regsitry PR (which in turn is blocked by another CI PR to fix a test)

**Comment by runcom** [comment]
/hold cancel

this should now pass the test as the linked bz above for image-registry has been merged

**Comment by cgwalters** [comment]
From one of the MCD logs:

```
2019-07-30T10:51:23.67504164Z I0730 10:51:23.675008    3613 update.go:148] Draining failed with: daemonsets.apps "tuned" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-cluster-node-tuning-operator": tuned-87vf6; daemonsets.apps "dns-default" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-dns": dns-default-s4l28; daemonsets.apps "node-ca" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-image-registry": node-ca-xscjq; daemonsets.apps "machine-config-daemon" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-machine-config-operator": machine-config-daemon-c2lxl; daemonsets.apps "node-exporter" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-monitoring": node-exporter-5wwss; daemonsets.apps "multus" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-multus": multus-z5vvr; daemonsets.apps "ovs" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-sdn": ovs-ppxvv; daemonsets.apps "sdn" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-sdn": sdn-9wcsf, retrying
2019-07-30T10:52:03.738201819Z I0730 10:52:03.738150    3613 update.go:93] daemonsets.apps "machine-config-daemon" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-machine-config-operator": machine-config-daemon-c2lxl; daemonsets.apps "node-exporter" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-monitoring": node-exporter-5wwss; daemonsets.apps "multus" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-multus": multus-z5vvr; daemonsets.apps "ovs" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-sdn": ovs-ppxvv; daemonsets.apps "sdn" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-sdn": sdn-9wcsf; daemonsets.apps "tuned" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-cluster-node-tuning-operator": tuned-87vf6; daemonsets.apps "dns-default" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-dns": dns-default-s4l28; daemonsets.apps "node-ca" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-daemon" cannot get resource "daemonsets" in API group "apps" in the namespace "openshift-image-registry": node-ca-xscjq
```

Odd...hm, wait this may relate to daemonsets moving out of extensions into the core?

**Comment by cgwalters** [comment]
IOW we probably want

```
diff --git a/manifests/machineconfigdaemon/clusterrole.yaml b/manifests/machineconfigdaemon/clusterrole.yaml
index 186feb82..f8a51999 100644
--- a/manifests/machineconfigdaemon/clusterrole.yaml
+++ b/manifests/machineconfigdaemon/clusterrole.yaml
@@ -10,6 +10,9 @@ rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["*"]
+- apiGroups: ["apps"]
+  resources: ["daemonsets"]
+  verbs: ["get"]
 - apiGroups: ["extensions"]
   resources: ["daemonsets"]
   verbs: ["get"]
```

(Although at this point the MCD is so highly privileged it's a bit questionable to try to limit the rolebindings, but eh)

**Comment by runcom** [comment]
updated, thanks @cgwalters !

**Pull request merged**
