### PR TITLE
[DNM] Bump `openshift/api`, Update `CgroupModeV2` with `CgroupModeDefault`

### PR DESCRIPTION
**Pull request by sairameshv**
**- What I did**
Bumped `openshift/api`
Updated the references of `CgroupModeV2` with `CgroupModeDefault` based on https://github.com/openshift/api/pull/1527 
**- How to verify it**

**- Description for the changelog**

Bumped `openshift/api`, Updated the references of `CgroupModeV2` to `CgroupModeDefault` based on https://github.com/openshift/api/pull/1527

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@sairameshv Can you point me in the AWS job to where I can see that this effect has taken place? Does this change end up in the generated machine config?

**Comment by sairameshv** [comment]
> @sairameshv Can you point me in the AWS job to where I can see that this effect has taken place? Does this change end up in the generated machine config?

This change doesn't generate any Machine Config.
This needs to be part of `kubelet_config_nodes.go` when we try to explicitly set the cgroupsMode to "v2" in the newly installed OCP clusters if the cgroupMode is found to be empty.
But, as of now, it is hardcoded to "v2" instead of this default.
Ref: https://github.com/openshift/machine-config-operator/pull/3789#discussion_r1264032117

**Comment by JoelSpeed** [comment]
Right, so actually, https://github.com/openshift/machine-config-operator/pull/3789 is the proof PR we need to show that this change isn't API change isn't breaking anything right?

Are the changes included there not mergeable with the old default value? Strikes me that you don't need to change to the v2 and back to default if you can include the API bump in that PR right?

**Comment by sairameshv** [comment]
> Right, so actually, #3789 is the proof PR we need to show that this change isn't API change isn't breaking anything right?
> 
> Are the changes included there not mergeable with the old default value? Strikes me that you don't need to change to the v2 and back to default if you can include the API bump in that PR right?

Yes @JoelSpeed, I agree that the API changes can be included as a bump in the above PR. But, considering the approaching release timeline, we agreed to have the MCO changes with the hardcoded "v2" value get in first and then focus on getting in the API PR, MCO bump PR.
cc: @haircommander

**Comment by haircommander** [comment]
@sairameshv can you update this?

**Comment by sairameshv** [comment]
> @sairameshv can you update this?

@haircommander , I see the code has been updated/re-factored recently and I don't find the need/usage of the variable `CGroupModeDefault`.

So, I think it makes sense to close this PR.

**Comment by haircommander** [comment]
would you mind opening a PR to remove it, then?

**Comment by sairameshv** [comment]
@haircommander , Sorry for the delay.
Here is the API PR that has the required change. Would you mind taking a look?
https://github.com/openshift/api/pull/1527 

Once the above API PR is merged, I would update the MCO code to refer `CGroupModeDefault` wherever applicable.

**Pull request closed without merging**
