### PR TITLE
templates/master/00-master: add 127.0.0.1 to etcd metric proxy SAN.

### PR DESCRIPTION
**Pull request by hexfusion**
etcd-quorum-guard needs the ability to pin to the host etcd instance to check health. Because we are now using the metric chain of trust we need to allow 127.0.0.1 in the SAN the same as etcd server currently does to simplify these TLS connections.

Assists #613

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@hexfusion I thought 613 was closed?

**Comment by hexfusion** [comment]
> @hexfusion I thought 613 was closed?

see that don't pay attention for 5 mins :).

**Comment by hexfusion** [comment]
@kikisdeliveryservice actually we still want quorum guard standalone to use metric certs so I would like to keep this open if possible.

**Comment by RobertKrawitz** [comment]
@hexfusion @kikisdeliveryservice this could also be used to allow the standalone etcd-quorum-guard to use the metrics cert.

**Comment by kikisdeliveryservice** [comment]
I think there are some wider spread aws issues right now, so retesting might not help.

**Comment by RobertKrawitz** [comment]
@hexfusion is there any guarantee that the proxy won't cache health status (which would defeat the whole purpose of the quorum guard)?

**Comment by hexfusion** [comment]
@RobertKrawitz the proxy has no caching mechanism it has a handler that makes an HTTP request. On the curl side we could pass `-H 'Cache-Control: no-cache'` as a general safety mechanism for this concern.

**Comment by hexfusion** [comment]
We are not going to use metric certs for this use-case anymore closing

**Pull request closed without merging**
