### PR TITLE
OCPBUGS-33694: daemon/update: disable systemd unit before overwriting

### PR DESCRIPTION
**Pull request by jlebon**
When overwriting a systemd unit with new content, we need to account for
the case where the new unit content has a different `[Install]` section.
If it does, then simply overwriting will leak the previous enablement
symlinks and become node state. That's OK most of the time, but this can
cause real issues as we've seen with the combination of #3967 which does
exactly that (changing `[Install]` sections) and #4213 which assumed
that those symlinks were cleaned up. More details on that cocktail in:

https://issues.redhat.com/browse/OCPBUGS-33694?focusedId=24917003#comment-24917003

Fix this by always checking if the unit is currently enabled, and if so,
running `systemctl disable` *before* overwriting its contents. The unit
will then be re-enabled (or not) based on the MachineConfig.

Fixes: https://issues.redhat.com/browse/OCPBUGS-33694

---

daemon/update: add workaround for OCPBUGS-33694

Due to the bug detailed in the previous commit, we now have nodes out
there that have stale enablement symlinks on-disk. It would be too risky
to try to catch them all and clean them up, but at least let's clean up
the ones that are known to be problematic.

---

**- What I did**

See commit messages above.

**- How to verify it**

To verify the bug fix (first commit):

- Boot to an OCP version that doesn't have https://github.com/openshift/machine-config-operator/pull/3967.
- Upgrade to an OCP version that has the bug fix (and implicitly also has https://github.com/openshift/machine-config-operator/pull/3967).
- Verify that there are no stale enablement symlinks.

To verify the workaround (second commit):

- Boot to an OCP version that doesn't have https://github.com/openshift/machine-config-operator/pull/3967.
- Upgrade to an OCP version that does have https://github.com/openshift/machine-config-operator/pull/3967.
- Upgrade to an OCP version that has the workaround.
- Verify that the stale enablement symlinks are removed.

**- Description for the changelog**

Stop leaking enablement symlinks when writing systemd units.

### CODE REVIEW

**Comment by jlebon** [comment]
Keeping as draft for now since this is not yet tested. @jbtrystram will go through the testing procedures.

**Review by travier — APPROVED** [review]
Code LGTM

**Comment by jbtrystram** [comment]
I did some more testing, with this PR: 
1 - launched a cluster with this change
2 - created the following machine config: 
```yaml
# Generated by Butane; do not edit
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-hello
spec:
  config:
    ignition:
      version: 3.4.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=A hello world unit!
            After=network-online.target
            Requires=network-online.target
            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=/usr/bin/echo "Hello, World!"
            [Install]
            WantedBy=default.target
          enabled: true
          name: hello.service
```
3 - apply the machine config and wait for deployment
4 - in a debug pod, confirm that symlink `/etc/systemd/system/default.target.wants/hello.service` exist.
5 - update the prevous machine config with: 
```
...
            [Install]
            WantedBy=multi-users.target
...
```
6 - apply the machine config and wait for deployment
7 -  in a debug pod, confirm that symlink `/etc/systemd/system/default.target.wants/hello.service` don't exist.
8 -  in debug pod, confirm that symlink `/etc/systemd/system/multi-users.target.wants/hello.service` exist.

**Comment by jlebon** [comment]
Thanks so much @jbtrystram for testing!

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

Great catch, we should probably spend some time auditing the paths we do have, as there is possible more that may cause issues.

I don't think this will need pre-merge QE testing given the extensive context and testing already done, so will leave that to the backport process.

Thanks for the patch @jlebon !

**Pull request merged**
