### PR TITLE
MCO-595: Remove MCO's pending config workflow

### PR DESCRIPTION
**Pull request by djoshy**
**- What I did**
Removed all references/checks for the journal pending config writes. In some cases, I replaced them with `desiredConfig` checks and in other cases removed them entirely. 

**- How to verify it**
Upgrades tests should work without any *new* complaints (: 

**- Description for the changelog**
daemon: removed pending config checks

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
> That said, IIRC the idea with "pending config" is to be a "transient state" between "current" and "desired". I don't see how we can entirely remove that...it seems to me that we at least need a single bit of state that says "we're trying to transition to the desired config"?

So, we do have that already today, done in two ways:
1. a currentconfig file we write to disk, indicating the transient state
2. a journal entry (which this is trying to remove)

And when we revisited the workflow, the two did essentially the exact same thing, so there was a duplication of effort, which was fine when things went well, but if anything errored, the journal entry made it exponentially harder to fix if it was e.g. referring to a non-existent hash, even a forcefile did not remove it.

So we wanted to do either or: 1. have the journal or 2. have the file indicate the transient state. We think 2 is easier to manage and less prone to errors + helps remove the MCO's dependency on journal

Hopefully that makes sense, we will try to make sure that what I just described above isn't broken (no regressions due to the removal of this)

**Comment by sinnykumari** [comment]
Putting hold for qe pre-merge testing
/hold

**Review by sinnykumari — COMMENTED** [review]
Overall LGTM.
/approve
I am little concerned that this change hitting some corner case regression. But I do agree with Jerry's rationale. 
As Jerry has more content of this issue, will be good to get your review as well.

**Comment by sergiordlr** [comment]
Verified using IPI on AWS.

We run a whole regression but the hypershift test cases.

All cases passed. We add the qe-approved label

/label qe-approved

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

Thanks for chasing this down David!

**Pull request merged**
