### PR TITLE
Revise KubeVirt platform for hypershift usage

### PR DESCRIPTION
**Pull request by davidvossel**
Originally the KubeVirt platform was being developed as an ipi installed platform. It was being treated very similar to other on-prem provides. This KubeVirt ipi effort has been abandoned.

In its place, we are working on a[ KubeVirt Hypershift platform](https://hypershift-docs.netlify.app/how-to/kubevirt/create-kubevirt-cluster/), which has different requirements than the IPI installation. To account for this, we need to strip out all the left over IPI configuration bits. We do however want to keep the KubeVirt platform as a separate infrastructure platform because we will begin leveraging this platform in unique ways in the future.

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@davidvossel is there someone from your team who can also review this?

**Comment by cgwalters** [comment]
> we how are working on a KubeVirt Hypershift platform

Seems like this could use a hyperlink.

But anyways
/approve

**Comment by davidvossel** [comment]
>Seems like this could use a hyperlink.

I added a link to the kubevirt hypershift documentation in the PR description. That's about the best thing we have that's publicly accessible.

**Comment by kikisdeliveryservice** [comment]
@davidvossel please assign a kubevirt/hypershift approver for the final lgtm

**Comment by davidvossel** [comment]
> @davidvossel please assign a kubevirt/hypershift approver for the final lgtm

@nirarg would you be able to do the final lgtm here?

What I've done is revert the majority of the logic in #2098 while leaving the `KubevirtPlatformType` api value. Functionally, the `KubeVirt` platform should now behave like the `None` platform. This `KubeVirt` platform type gives us the ability to detect that the infrastructure is running on top of KubeVirt which can help with decision making for other operators (like cso someday having the ability to intelligently lay down the kubevirt csi driver)

**Pull request merged**
