### PR TITLE
bump openshift api and update FeatureGates

### PR DESCRIPTION
**Pull request by jcpowermac**
To get this to work I had to run:
```
go mod edit -replace github.com/openshift/api=github.com/openshift/api@0e2ff1e
make go-deps
```

Dependancy for PR: https://github.com/openshift/machine-config-operator/pull/1373

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
/retest

I'm thinking of bumping everything together in https://github.com/openshift/machine-config-operator/pull/1393 but I'm not sure if that's entirely correct. If that doesn't work we can merge this first.

The AWS error seems infra related so lets try again

**Comment by yuqi-zhang** [comment]
/retest

There are some weird test failures I'm working out for the other PR, so until then let's see if we can get this past CI, and we can merge this while I work on fixing kubelet tests.

**Comment by jcpowermac** [comment]
@ericavonb or @kikisdeliveryservice can you PTAL.

**Comment by runcom** [comment]
/hold

we might be able to land https://github.com/openshift/machine-config-operator/pull/1393 today which supersedes this :)

**Comment by jcpowermac** [comment]
/close
https://github.com/openshift/machine-config-operator/pull/1393
hopefully will merge shortly :)

**Pull request closed without merging**
