### PR TITLE
Bug 1713039: etcd quorum guard test does not correctly make nodes unschedulable

### PR DESCRIPTION
**Pull request by RobertKrawitz**
**- What I did**

Merged part of #764 and all of #789 

**- How to verify it**
Run e2e test

**- Description for the changelog**
etcd quorum guard test does not correctly make nodes unschedulable

### CODE REVIEW

**Comment by RobertKrawitz** [comment]
/assign @runcom @cgwalters 
@smarterclayton please check that I'm using the correct image.

**Comment by kikisdeliveryservice** [comment]
As per Steve's email does the title of this PR need the word "Bug:" in it?

**Comment by RobertKrawitz** [comment]
@kikisdeliveryservice @runcom @cgwalters @jlebon could someone look at this so we can get it into the 4.1 zstream?

**Comment by runcom** [comment]
> @smarterclayton please check that I'm using the correct image.

can someone else check on this as well? it looks right to me, but since this is going to 4.1, I won't break it

**Comment by kikisdeliveryservice** [comment]
is this ready or do we still need another :eyes:  @runcom @RobertKrawitz

**Comment by kikisdeliveryservice** [comment]
@smarterclayton can you PTAL?

**Comment by kikisdeliveryservice** [comment]
A request to have cherry-pick-approved is in progress.

**Comment by smarterclayton** [comment]
/approve

For 4.1.z

**Pull request merged**
