### PR TITLE
[release-4.1] Bug 1708602: pkg/daemon: workaround old util-linux logger in rhel7.6

### PR DESCRIPTION
**Pull request by runcom**
Cherry-pick of commits from #734 - that PR has been missed from the branching somehow but we need that to verify the linked BZ.

@imcleod ptal

### CODE REVIEW

**Comment by runcom** [comment]
scaleup can be overridden pls

**Comment by runcom** [comment]
needs lgtm as well to go in

**Comment by smarterclayton** [comment]
This needed to be approved by a release architect.  Please make sure you get that approval before merging.

**Comment by smarterclayton** [comment]
(this is approved, just reminding folks to double ask on every PR so we can get used to the process)

**Comment by runcom** [comment]
My bad, sorry about this.

**Comment by smarterclayton** [comment]
No worries

**Pull request merged**
