### PR TITLE
containerruntimeconfig: watch Image CR for registries

### PR DESCRIPTION
**Pull request by umohnani8**
Add support to watch the Image CR for registry changes
by the user. Populate /etc/containers/registries.conf
with these changes.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@mrunalp @runcom PTAL

**Comment by umohnani8** [comment]
This is ready to merge once tests are green. I didn't add a unit test for this because I am seeing some issues with the testing framework, which I am working to fix. Tested this on a cluster and changes are made to all nodes when the image config is added, edited/updated, and deleted. At the same time works for the container runtime config.
@mrunalp @runcom PTAL

**Comment by runcom** [comment]
code looks good to me
@cgwalters @kikisdeliveryservice @LorbusChris ptal as well

/approve

**Comment by mrunalp** [comment]
LGTM

**Comment by runcom** [comment]
all green here as well

**Pull request merged**
