### PR TITLE
templates: drop files related to registry

### PR DESCRIPTION
**Pull request by abhinavdahiya**
`cluster-image-registry-operator` now owns setting these up for access to internal registry.
https://github.com/openshift/cluster-image-registry-operator/blob/master/deploy/08-ca-daemonset.yaml#L26-L46

This fixes MCD and the `cluster-image-registry-operator` stepping on each other. And MCD currently reboot on syncing any
change which causes disruption on masters recurringly.

Should help dropping ownership of `/etc/hosts` and `/etc/docker.d/certs/...` from daemon
https://github.com/openshift/machine-config-operator/issues/224#issuecomment-445443040

### CODE REVIEW

**Comment by wking** [comment]
/lgtm

Offloading registry certs to the registry operator and `/etc/hosts` to the DNS operator makes sense to me.  And if this greens CI, I'm fine landing it without waiting for everyone else to wake up ;).  We can always revert in the morning if it doesn't hold up to sunlight :bat: :wink:

**Comment by wking** [comment]
Hrm, [router didn't come up][1]:

```
timeout waiting for openshift-ingress/deploy/router-default to be available
2018/12/08 09:37:40 Container test in pod e2e-aws failed, exit code 1, reason Error
```

Maybe there's a chicken/egg with one of these files?

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/225/pull-ci-openshift-machine-config-operator-master-e2e-aws/611/build-log.txt

**Comment by wking** [comment]
So one potential issue with being able to unilaterally merge this would be that, as described in openshift/cluster-dns-operator#63, the DNS operator is currently just appending to `/etc/hosts`.  It will need to start *managing* the file.  Does the content we're removing here differ from what RHCOS ships?

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/cluster-storage-operator/pull/5

Need this ^^

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=fatal msg="Error executing openshift-install: waiting for bootstrap-complete: timed out waiting for the condition"
```

[1]: https://deck-ci.svc.ci.openshift.org/log?job=pull-ci-openshift-machine-config-operator-master-e2e-aws&id=620

**Comment by smarterclayton** [comment]
Why is that oc error being printed?

**Comment by smarterclayton** [comment]
Ah, you aren’t getting a new release image when other tags change (outside of this project).  Might be time to change that.

**Comment by abhinavdahiya** [comment]
> Ah, you aren’t getting a new release image when other tags change (outside of this project). Might be time to change that.

Yeah, in one of my PRs in this repo i vaguely remember something like that happening.. *i don't remember which* :innocent: but I don't remember when...

**Pull request merged**
