### PR TITLE
OKD-174: Dockerfile: OKD: Reenable extensions image on SCOS

### PR DESCRIPTION
**Pull request by LorbusChris**
**- What I did**

Dockerfile: OKD: Reenable extensions image on SCOS

**- How to verify it**

SCOS payload can be built with this change

**- Description for the changelog**

/cc @sherine-k @travier

### CODE REVIEW

**Review by sherine-k — APPROVED** [review]
/lgtm

**Comment by LorbusChris** [comment]
Rebased

**Pull request merged**
