### PR TITLE
[release-4.10] Bug 2060954: Explicitly set keyfile as the default plugin

### PR DESCRIPTION
**Pull request by jcaamano**
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>
(cherry picked from commit 342f20bf2e6efe43e2735d426aae2d49674df3fb)

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
As a note this is a backport of https://github.com/openshift/machine-config-operator/pull/2984 so can't merge until that one does and is verified.

**Comment by wking** [comment]
I dropped the dependency on bug 2061654:

/bugzilla refresh

**Pull request merged**
