### PR TITLE
[release-4.8] Bug 2021073: [ipi onprem] cherry pick Keepalived default ingress scripts fixes

### PR DESCRIPTION
**Pull request by yboaron**
Manual cherry-pick:
 - https://github.com/openshift/machine-config-operator/pull/2637
 - https://github.com/openshift/machine-config-operator/pull/2798

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
@yboaron how are you feeling about this ovirt test? 

/test e2e-ovirt

**Comment by yboaron** [comment]
All on-prem platforms gates are fine, 
@kikisdeliveryservice , I think we can merge this backport PR

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by sinnykumari — APPROVED** [review]

**Comment by yboaron** [comment]
@cybertron Can you set the backport-risk-assessed label?

**Pull request merged**
