### PR TITLE
NO-ISSUE: Update the design doc dual support icsp and idms

### PR DESCRIPTION
**Pull request by QiWang19**
**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

**Comment by QiWang19** [comment]
@yuqi-zhang I rebased this aginst the master. Could you retag?

**Comment by djoshy** [comment]
Not sure why the override keeps getting removed :/ 

/override ci/prow/e2e-gcp-op-single-node

**Comment by djoshy** [comment]
I'm going to override hypershift as the failures seem unrelated and this is only a doc change after all

/override ci/prow/e2e-hypershift

**Pull request merged**
