### PR TITLE
Bug 1853298: [openstack/vsphere] Move dispatcher script to common

### PR DESCRIPTION
**Pull request by mandre**
This alignes OpenStack and vSphere platforms with with the BM one after
#1763 and #1765.

### CODE REVIEW

**Comment by mandre** [comment]
This PR is based on https://github.com/openshift/machine-config-operator/pull/1666, so we should really only be looking at the second commit here.

**Comment by kikisdeliveryservice** [comment]
for vsphere review also:
/assign @jcpowermac

**Comment by jcpowermac** [comment]
I can still review but please also assign...
/assign @patrickdillon

**Comment by kikisdeliveryservice** [comment]
> I can still review but please also assign...
> /assign @patrickdillon

thanks for letting me know @jcpowermac ! :+1:

**Comment by mandre** [comment]
/test e2e-openstack
/test e2e-vsphere

Rebased to remove the extra commit that has now merged to master.

**Comment by mandre** [comment]
This indeed fixes OpenStack CI, let's merge it.
@patrickdillon is there a known issue with vsphere CI?

**Comment by mandre** [comment]
/test e2e-vsphere

Seems like the vsphere job is broken since 2020-06-15, it likely has other issues. Any objection in merging this patch? This will at least unblock the OpenStack CI, and hopefully bring vsphere closer to green.

**Comment by runcom** [comment]
cc @patrickdillon ptal at vsphere as it seems to be red'ish since mid-June

/approve
/lgtm

**Comment by patrickdillon** [comment]
> cc @patrickdillon ptal at vsphere as it seems to be red'ish since mid-June

SPLAT team is actively handling vsphere CI, including building a new cluster dedicated to vsphere.

**Pull request merged**
