### PR TITLE
OCPNODE-2336: Drop ClusterImagePolicy validation on scope conflicts with release-image repo

### PR DESCRIPTION
**Pull request by QiWang19**
…ith release-image repo

Remove the restriction on setting policy for release payload repository to not block the implementation for https://github.com/openshift/enhancements/pull/1633

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by QiWang19** [comment]
@mtrmac PTAL

**Review by mtrmac — COMMENTED** [review]
Locally code LGTM; IIRC there should also be some change of the API documentation?

**Review by saschagrunert — APPROVED** [review]
/lgtm

API docs are tracked in https://issues.redhat.com/browse/OCPNODE-2358

**Comment by wking** [comment]
Avoid eliding the pull title, because this gets included in release-controller diffs and such:

/retitle OCPNODE-2336: Drop ClusterImagePolicy validation on scope conflicts with release-image repo

**Review by yuqi-zhang — APPROVED** [review]

**Pull request merged**
