### PR TITLE
Bug 1762019: use systemctl reboot instead of reboot

### PR DESCRIPTION
**Pull request by rphillips**
**- What I did**

ref: https://bugzilla.redhat.com/show_bug.cgi?id=1762019#c10

There are a number of master and worker logs that show `drain complete` from the MCD, but do not reboot.

MCD performs the following operations when starting:

  0. runs in `privileged: true` security context
  1. Mounts hostPath `/` to `/rootfs`
  2. Inside the container: chroot /rootfs

Running a similar test by using podman:

```sh
# podman run --privileged -ti -v /:/rootfs fedora /bin/bash -c 'chroot /rootfs'
# reboot ; echo $?
Failed to connect to bus: No data available
0
```

The `reboot` command it symlinked to systemctl; however, there appears to be a bug with the $0 handling with systemctl versus just running `systemctl reboot`.

Running the same test with `systemctl reboot` will reboot the machine every single time without errors.

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
Talked to Mrunal as well, all cool

/approve
/lgtm

**Comment by ashcrow** [comment]
```
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should report less than two alerts in firing or pending state [Suite:openshift/conformance/parallel/minimal]
```
Unrelated

**Pull request merged**
