### PR TITLE
Revert "MCO-565: MCO-568: MCO-659: MCO-660 On-cluster build opt-in function, building machine-os-builder stub, RBAC and service acct inclusions"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts openshift/machine-config-operator#3763

Testing at this phase but I suspect this has perma failed single-node: https://issues.redhat.com/browse/TRT-1170

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node

**Comment by cheesesashimi** [comment]
Taking a look, here's what's happening:

- The way this code currently works is we create the `machine-os-builder` deployment, but set it to 0 replicas until someone applies a specific label to a MachineConfigPool. At which point, we scale up the number of replicas to 1. If someone removes that label, we scale the number of replicas back down. Right now, the `machine-os-builder` pod starts but effectively no-ops.
- The e2e test is unhappy because it assumes there should be a minimum of one replica for each deployment it encounters.

We'll revisit this behavior and consider feature-gating this. In the meantime, I'll approve this revert PR to get everything unblocked.

**Comment by dgoodwin** [comment]
Thanks for jumping in @cheesesashimi !

**Comment by dgoodwin** [comment]
Jira filed for re-introducing: https://issues.redhat.com/browse/OCPBUGS-17100

**Pull request merged**
