### PR TITLE
Bug 1881137: vSphere: don't failover api vip if lb is responding

### PR DESCRIPTION
**Pull request by jcpowermac**
Ports #1893 to the vSphere platform.

vSphere CI is experiencing the issues described in the above
PR.

### CODE REVIEW

**Comment by jcpowermac** [comment]
/test e2e-vsphere

I tested manually and doesn't experience the same issue.

**Comment by yuqi-zhang** [comment]
The PR you linked https://github.com/openshift/machine-config-operator/pull/1892 is a closed debug PR. Were you trying to link something else?

/approve tentatively, let's see if we can get CI to pass

**Comment by jcpowermac** [comment]
> The PR you linked #1892 is a closed debug PR. Were you trying to link something else?
> 
> /approve tentatively, let's see if we can get CI to pass

Yeah it was supposed to be: https://github.com/openshift/machine-config-operator/pull/1893

**Comment by jcpowermac** [comment]
The test failures in vsphere are not related to this PR.
@jhixson74 @abhinavdahiya ptal

/test e2e-vsphere

**Comment by jcpowermac** [comment]
Manually tested as well. No install issues.

**Review by cgwalters — APPROVED** [review]
/lgtm

This is another thing we should start generating rather than templating so the code is shared.

**Pull request merged**
