### PR TITLE
Bug 1723928: Add script to generate bootstrap recovery kubeconfig

### PR DESCRIPTION
**Pull request by rphillips**
Pick for 4.1 of https://github.com/openshift/machine-config-operator/pull/792

DR Kubelet recovery script

### CODE REVIEW

**Comment by rphillips** [comment]
force pushed to regenerated the templates for 4.1

**Comment by hexfusion** [comment]
At this point, we probably need this to be blessed by @smarterclayton if it is going to make 4.1

**Comment by rphillips** [comment]
This can be in 4.1.z if that is easier.

**Comment by derekwaynecarr** [comment]
please link to an appropriate bz targeting 4.1.z and we can include this afterwards.

**Comment by rphillips** [comment]
@runcom could you review this for 4.1.z. Thanks!

**Comment by runcom** [comment]
This lgtm and has Sam lgtm but it needs probably eparis label for cherry-pick

/approve

**Comment by rphillips** [comment]
@eparis could you approve this pick for 4.1?

**Comment by eparis** [comment]
This has missed for 4.1.4 and will be re-reviewed next week for 4.1.5.

However, I do not see a BZ against 4.2 which shows that a human has run QE testing against the PR in master, nor do I see a unit/integration/e2e tests which gives confidence in an automated way. I believe you need to clone 1723928 to a new bug, set that to target release 4.2 and work with QE to validate that your work in master functions correctly before re-evaluation next monday.

**Comment by rphillips** [comment]
@eparis the QA tests were done via: https://bugzilla.redhat.com/show_bug.cgi?id=1711910

**Comment by jwforres** [comment]
@rphillips looks like this was not an exact pick from https://github.com/openshift/machine-config-operator/pull/792/files
It looks like the additional files here are just test data for testing the script, is that correct?

**Comment by crawford** [comment]
The test_data is required because 4.1.z doesn't include https://github.com/openshift/machine-config-operator/pull/749, which removes the need for test_data.

**Comment by crawford** [comment]
From [the logs](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/794/pull-ci-openshift-machine-config-operator-release-4.1-e2e-aws/58/artifacts/e2e-aws/pods/openshift-marketplace_redhat-operators-7749cfcd87-6hzwb_redhat-operators.log):

```
time="2019-07-08T21:29:20Z" level=info msg="loading CRDs" port=50051 type=appregistry
time="2019-07-08T21:29:20Z" level=info msg="loading Bundles" port=50051 type=appregistry
time="2019-07-08T21:29:20Z" level=info msg="loading Packages" port=50051 type=appregistry
time="2019-07-08T21:29:20Z" level=fatal msg="error loading manifest from remote registry - amqstreams.v1.2.0 specifies replacement that couldn't be found" port=50051 type=appregistry
```

This appears to be a remote issue. @kevinrizza is looking into this further. In the meantime...

/retest

**Pull request merged**
