### PR TITLE
WIP: daemon: Watch for 20 minute increments forever

### PR DESCRIPTION
**Pull request by ashcrow**
See #68

### CODE REVIEW

**Comment by jlebon** [comment]
Hmm, so it seems like there are a bunch of issues open about this upstream. The most relevant one is https://github.com/kubernetes/kubernetes/issues/31345. Would a better approach here be to check the specific error and if it's `ErrWatchClosed` just rerun it?

**Comment by ashcrow** [comment]
@jlebon interesting. Taking a look now.

**Comment by ashcrow** [comment]
@jlebon I'm going to open up an alternate PR using that pattern shortly.

**Comment by jlebon** [comment]
Closing in favour of https://github.com/openshift/machine-config-operator/pull/76.
/close

**Pull request closed without merging**
