### PR TITLE
add kubelet environment variable for extra node lables

### PR DESCRIPTION
**Pull request by yuvalk**
this can be used in conjunction with ignition that include something like:
```
$ cat /etc/systemd/system/kubelet.service.d/20-extralabels.conf
[Service]
Environment="FIRST_BOOT_ONLY_KUBELET_NODE_EXTRA_LABELS=node.kubernetes.io/role=rwn"
```
Which will allow to instantiate nodes directly into the desired MCP

Signed-off-by: Yuval Kashtan <yuvalkashtan@gmail.com>

**- What I did**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
So this would ensure that the node always has the correct label available and doesn't reboot back after getting the worker label here?

@yuvalk does this cover upi usecase? 

Can you walk me through the user flow using this change?

**Comment by kikisdeliveryservice** [comment]
Adding a hold for further discussion/testing. Thanks for the PR

/hold

**Comment by crawford** [comment]
This is what was suggested in https://bugzilla.redhat.com/show_bug.cgi?id=1850295, but that was closed. I assume this will be rejected for a similar reason, unfortunately.

**Comment by kikisdeliveryservice** [comment]
update: seems that there might be a viable alternative path that they're going to explore targetting the ingress&friends scheduling issues directly. will leave this open for now.

**Comment by slintes** [comment]
> This is what was suggested in https://bugzilla.redhat.com/show_bug.cgi?id=1850295, but that was closed. I assume this will be rejected for a similar reason, unfortunately.

If I understand correctly, the only argument in the end was preventing confusion about why you can set e.g. a custom role on registration, but not modify it? Not a strong argument IMHO, considering this would solve a big problem.

> update: seems that there might be a viable alternative path that they're going to explore targetting the ingress&friends scheduling issues directly. will leave this open for now.

To my best knowledge workload scheduling is only one part of the problem. Unneeded reboots and reprovisioning (from custom role which was installed using ignition, to worker role because of missing role label, and back to custom role after labels were set by "something") is the other part.

**Comment by yuvalk** [comment]
pushed a small fix to rename the environment variable in a more friendly name that denote the fact that it can be used only once.

**Comment by yuvalk** [comment]
> To my best knowledge workload scheduling is only one part of the problem. Unneeded reboots and reprovisioning (from custom role which was installed using ignition, to worker role because of missing role label, and back to custom role after labels were set by "something") is the other part.
Yep, we'd want to minimize reboots to shorten deployment time

also, I think this is very useful in more dynamic clusters, to prevent undesirable workload from reaching that node in the first place. consider the case of highly dynamic cluster. when the node is made schedulable on the 'general' worker pull it will start receiving workloads, just to evict it shortly afterwards..

**Comment by darkmuggle** [comment]
In light of https://bugzilla.redhat.com/show_bug.cgi?id=1850295#c11, we would need the Node team to ack this PR. I'm not entirely sure that this is the _correct_ path.

**Comment by kikisdeliveryservice** [comment]
> In light of https://bugzilla.redhat.com/show_bug.cgi?id=1850295#c11, we would need the Node team to ack this PR. I'm not entirely sure that this is the _correct_ path.

AFAIK, we are not going forward with this.

**Comment by yuvalk** [comment]
/close
We have a path to achieve the same without changing MCO
https://github.com/yuvalk/ocp-node-labels

**Pull request closed without merging**
