### PR TITLE
Bug 1709907: pkg/daemon: drop spammy logSystem

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

removed a really high spammy logSystem call

**- How to verify it**

check daemon logs in jobs

**- Description for the changelog**

### CODE REVIEW

**Comment by cgwalters** [comment]
Hm, a lot of these snuck in:

```
$ rg logSystem
pkg/daemon/daemon.go
351:	dn.logSystem("controller syncing started")
484:	dn.logSystem("Starting to manage node: %s", dn.name)
692:		dn.logSystem("using pending config same as desired")
762:		dn.logSystem("error loading pending config %v", err)
860:		dn.logSystem("Using current config on disk %s", currentOnDisk.GetName())
875:		dn.logSystem("Validating against pending config %s", state.pendingConfig.GetName())
879:		dn.logSystem("Validating against current config %s", state.currentConfig.GetName())
1046:	dn.logSystem("completed update for config %s", desiredConfigName)
```

Some of these are clearly duplicates and/or unnecessary.  For example:
```
		glog.Infof("Using current config on disk %s", currentOnDisk.GetName())
		dn.logSystem("Using current config on disk %s", currentOnDisk.GetName())
```
is redundant since `logSystem` also writes to `glog`.

**Comment by kikisdeliveryservice** [comment]
+1 on removing the others that @cgwalters pointed out as well.

**Comment by cgwalters** [comment]
OK wow the log is spammy, let's get this in and revisit the others next.
/lgtm

**Comment by runcom** [comment]
Where's the lgtm label

**Comment by kikisdeliveryservice** [comment]
> Where's the lgtm label

sometimes you have to yell.. :laughing:

**Pull request merged**
