### PR TITLE
Fix CRIO PidsLimit json tag

### PR DESCRIPTION
**Pull request by bvwells**
Fix CRIO PidsLimit json tag

### CODE REVIEW

**Comment by umohnani8** [comment]
/ok-to-test
LGTM
Thanks for catching that @bvwells!

**Comment by bvwells** [comment]
@umohnani8 no problems, thanks for the review!

**Review by cgwalters — APPROVED** [review]
/approve
Let's queue this for 4.7.

**Review by cgwalters — APPROVED** [review]
/lgtm

**Pull request merged**
