### PR TITLE
HACKING.md: Tweak development instructions

### PR DESCRIPTION
**Pull request by cgwalters**
- The exact versions we tested with were quite old, no reason
   to have those now.
 - Use `oc scale --replicas=0` for the CVO so it's easy to turn
   back on
 - Add note about `oc project` for shorthand
 - Use `1.` to let the Markdown renderer take care of incrementing
   integers for us

### CODE REVIEW

**Comment by jlebon** [comment]
> Use 1. to let the Markdown renderer take care of incrementing
integers for us

Oh neat, didn't realize it did that.

/lgtm

**Comment by kikisdeliveryservice** [comment]
@cgwalters how do we turn it back on? with `oc scale`? Could we maybe add that too?

**Comment by cgwalters** [comment]
> @cgwalters how do we turn it back on? with oc scale? Could we maybe add that too?

Yep, done.

**Comment by kikisdeliveryservice** [comment]
This is great @cgwalters !

**Comment by ashcrow** [comment]
/test e2e-aws

Flake. I doubt this documentation affects HAProxy :laughing:

**Pull request merged**
