### PR TITLE
HACKING.md: Remove kube commands

### PR DESCRIPTION
**Pull request by ashcrow**
See https://github.com/openshift/machine-config-operator/pull/144#issuecomment-433172099

### CODE REVIEW

**Comment by sdemos** [comment]
if these instructions were tested with a different version of the installer and/or rhcos we should fix the references at the top of the document.

**Comment by abhinavdahiya** [comment]
/approve

@sdemos `/lgtm`

**Comment by kikisdeliveryservice** [comment]
I wasn't so bold as to take them out last night =) Thanks @ashcrow !
/lgtm

**Comment by abhinavdahiya** [comment]
> I wasn't so bold as to take them out last night =)

#boldlygo

**Pull request merged**
