### PR TITLE
Add Christoph as a baremetal owner

### PR DESCRIPTION
**Pull request by cybertron**
He's been working on metal IPI for a while now so he should be in the
list. I also removed Yossi from the reviewer list since he recently
moved to a different team. I'm leaving him as an approver for now
since we might still want to pull him in on patches. We just don't
want to pester him with automatic review requests.

### CODE REVIEW

**Review by kikisdeliveryservice — APPROVED** [review]
@creydr can you lgtm this?

:)

**Review by creydr — APPROVED** [review]

**Comment by kikisdeliveryservice** [comment]
@cybertron can this wait until after freeze?

**Comment by cybertron** [comment]
Yeah, that should be fine. The hassle of opening a bz to merge this would likely be more than the hassle of not having Christoph in the list for another week. :-)

**Pull request merged**
