### PR TITLE
WIP: add os_version to node labels

### PR DESCRIPTION
**Pull request by rphillips**
**- What I did**

**- How to verify it**

**- Description for the changelog**
```
Add version_id to labels
```

### CODE REVIEW

**Comment by cgwalters** [comment]
I thought last time this came up we determined it wouldn't actually work because the labels from kubelet are only applied when the node is first created, so when we do an in-place update the label will become a lie?

Personally, while I see the rationale here I think it's going to be a better pattern to encourage daemonsets and other privileged containers to instead:

- ship multiple copies of binaries they intend to run on the host, built via e.g. multi-stage build
- Dynamically inspect the host and copy the right binary
- Profit

This is how we changed the SDN to work I think.

**Comment by rphillips** [comment]
I wasn't clear on the context. @sdodson asked me in slack .

**Comment by rphillips** [comment]
I remember the conversation and agree. This is problematic.

**Comment by cgwalters** [comment]
Had to dig it up but https://github.com/openshift/machine-config-operator/pull/514
which then eventually led to https://github.com/openshift/machine-config-operator/pull/584#issuecomment-485819654

History goes in cycles :smile:

**Pull request closed without merging**
