### PR TITLE
Bug 1772155: install: add proper terminationMessagePolicy for etcd quorum guard pods

### PR DESCRIPTION
**Pull request by alaypatel07**
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1772155

**- Description for the changelog**
add proper terminationMessagePolicy for etcd quorum guard pods

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
Don't we need a BZ to merge this?

**Comment by alaypatel07** [comment]
@kikisdeliveryservice yes we need BZ to get it in but I was not sure if we want it backported or if we want it for when master opens for merging without a BZ

**Comment by alaypatel07** [comment]
this looks like a flake
```
error: unable to extract layer sha256:46406a972439312c63f4f88c6d4aebc4757e5a8ce9a160bbe404cdda9ce29a7c from registry.svc.ci.openshift.org/ci-op-jjv4rhxx/stable@sha256:baafcfb4dbf81cd1d2a3f9575535f2f994041307bb49dc825e4b1d2fd9a6470a: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by kikisdeliveryservice** [comment]
aws seems to be having issues? reported error

```
"Error: Error adding role ci-op-jjv4rhxx-c4a31-fxwkz-bootstrap-role to IAM instance profile ci-op-jjv4rhxx-c4a31-fxwkz-bootstrap-profile: Error adding IAM Role ci-op-jjv4rhxx-c4a31-fxwkz-bootstrap-role to Instance Profile ci-op-jjv4rhxx-c4a31-fxwkz-bootstrap-profile: timeout while waiting for state to become 'success' (timeout: 30s)"
```

/test e2e-aws

**Comment by alaypatel07** [comment]
failures do not look like they are coming from the change in the PR
/test e2e-aws

**Pull request merged**
