### PR TITLE
*: remove Dockerfile.machine-config-daemon.upstream

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

not really used anymore now that we only have 1 image

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
Wasn't sure if anyone else was using this for some other purpose?

@cgwalters can you verify it's ok to remove?

**Comment by runcom** [comment]
> Wasn't sure if anyone else was using this for some other purpose?
> 
> @cgwalters can you verify it's ok to remove?

yeah, it's not referenced by anything in the current code and the reason why we added it (no entitlements on UBI) seems to be solved since it's working today

**Comment by kikisdeliveryservice** [comment]
> yeah, it's not referenced by anything in the current code and the reason why we added it (no entitlements on UBI) seems to be solved since it's working today

Ahh I think I was confused. In that case:

/lgtm

**Comment by kikisdeliveryservice** [comment]
almost there!

/retest

**Comment by kikisdeliveryservice** [comment]
gah timing out..

/retest

**Pull request merged**
