### PR TITLE
docs: Directories and links aren't supported

### PR DESCRIPTION
**Pull request by cgwalters**
Reported by QE.  Now separately we seemed not to fail trying to
do this for some reason; will investigate that.

### CODE REVIEW

**Comment by cgwalters** [comment]
/hold

more to this

**Comment by schituku** [comment]
https://github.com/openshift/machine-config-operator/blob/master/docs/MachineConfigDaemon.md#supported-vs-unsupported-ignition-config-changes
      Directories, files, links and systemd units are supported ignition config changes as per the doc

**Comment by jlebon** [comment]
Related: #328

**Comment by cgwalters** [comment]
Yep, I updated this to mark links as unsupported too.  IOW just files and systemd units are supported.

**Comment by kikisdeliveryservice** [comment]
good catch @cgwalters 

/lgtm

**Comment by kikisdeliveryservice** [comment]
is this good to go? still has a hold on it.

**Comment by schituku** [comment]
It looks like the doc based on which I reported this issue is now updated to have the directories and links not supported. Does that mean that this PR will be closed and will not make it? @cgwalters @jlebon 
https://github.com/openshift/machine-config-operator/blob/master/docs/MachineConfigDaemon.md#supported-vs-unsupported-ignition-config-changes

**Comment by cgwalters** [comment]
I don't quite understand, which doc are you talking about?  Do you see something wrong with the code/docs in this repo?

**Comment by schituku** [comment]
I'm referencing the table in [1] which lists the supported vs unsupported. Last week it used to say
Links YES
Directories YES
    Now it says NO.

[1] https://github.com/openshift/machine-config-operator/blob/master/docs/MachineConfigDaemon.md#supported-vs-unsupported-ignition-config-changes

**Comment by kikisdeliveryservice** [comment]
@schituku we have updated the table to accurately reflect what is supported. The current chart is the canonical status of our ignition support. Please use that table and its contents going forward.

**Pull request merged**
