### PR TITLE
templates/baremetal: add some tolerations

### PR DESCRIPTION
**Pull request by derekhiggins**
These seem pretty standard for Critical services.

Fixes: #1162

Yet to be verified

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
fyi: reported the aws lb errors. ci seems to be having some issues.

**Comment by runcom** [comment]
cc @celebdor

**Comment by kikisdeliveryservice** [comment]
@celebdor @derekhiggins this PR still needs a LGTM

**Comment by derekhiggins** [comment]
> @celebdor @derekhiggins this PR still needs a LGTM

Sorry, I had the environment set up to test this on in a while, if others are happy with it then I'm happy to merge, failing that I'll try and get this setup again soon to test it.

**Comment by kikisdeliveryservice** [comment]
@celebdor @derekhiggins any LGTMs coming soon on this?

**Comment by derekhiggins** [comment]
Tested, and didn't work because the "node.kubernetes.io/not-ready" toleration got added without a "key", not sure why. But looking at this closer maybe it should be dealt with differently by skipping this test for the "openshift-kni-infra" namespace, the same as was done for the openstack namespace(https://github.com/openshift/origin/pull/23833)?

**Comment by runcom** [comment]
> Tested, and didn't work because the "node.kubernetes.io/not-ready" toleration got added without a "key", not sure why. But looking at this closer maybe it should be dealt with differently by skipping this test for the "openshift-kni-infra" namespace, the same as was done for the openstack namespace([openshift/origin#23833](https://github.com/openshift/origin/pull/23833))?

/hold

**Comment by kikisdeliveryservice** [comment]
This hasn't seen anything pushed since January.  Closing but please feel free to reopen if you'd like to continue work on this.

**Pull request closed without merging**
