### PR TITLE
MCO-640: Move all log functions to klog 

### PR DESCRIPTION
**Pull request by inesqyx**
**- What I did**
1. Replace imports for the glog libraries with klog 
2. Replace glog functions with klog functions 

**- How to verify it**
Checked the log for MCC, MCD, MCO and MCS against logs generated before replacement --> Functionality remained.

### CODE REVIEW

**Review by sinnykumari — COMMENTED** [review]
Minor changes mentioned belwo otherwise, LGTM.

- Since we are completely getting away with direct use of glog, I am wondering we should remove glog as a dep in our go.mod https://github.com/openshift/machine-config-operator/blob/master/go.mod#L24 ?
- Will be good to squash all commits into a single commit with commit message including why we are making this change.

**Comment by inesqyx** [comment]
> Minor changes mentioned below otherwise, LGTM.
> 
> * Since we are completely getting away with direct use of glog, I am wondering we should remove glog as a dep in our go.mod https://github.com/openshift/machine-config-operator/blob/master/go.mod#L24 ? I will look into that and run go mad vendor to resync everything with vendor as well. Thanks for the check, Sinny!
> * Will be good to squash all commits into a single commit with commit message including why we are making this change. Will do :)

**Comment by sinnykumari** [comment]
> I will look into that and run go mod vendor to resync everything with vendor as well. Thanks for the check, Sinny!

you can directly run `make go-deps`  too

**Comment by inesqyx** [comment]
> > I will look into that and run go mod vendor to resync everything with vendor as well. Thanks for the check, Sinny!
> 
> you can directly run `make go-deps` too

By retrying, the glog library got added automatically when run go mod vendor OR make go-deps

**Comment by sinnykumari** [comment]
Nice work! thanks Ines for working on this :)
/lgtm
/approve

**Pull request merged**
