### PR TITLE
Config Drift Monitor should alert on unexpected SSH key changes

### PR DESCRIPTION
**Pull request by cheesesashimi**
**- What I did**

The Config Drift Monitor should listen for mutations to the SSH key files. Additionally, in the case of RHCOS 8 -> RHCOS 9, it should alert if an SSH key was written to the old path.

**- How to verify it**

1. Run the Config Drift Monitor unit test suite.
2. Launch a cluster and mutate the SSH key file (`/home/core/.ssh/authorized_keys` for RHCOS 8, `/home/core/.ssh/authorized_keys.d/ignition` for RHCOS 9). The node should drift.
3. Put an SSH key in the incorrect place.

**- Description for the changelog**
Config Drift Monitor watches for mutations to SSH key files

### CODE REVIEW

**Comment by sinnykumari** [comment]
@cheesesashimi Looks like this will also solve, https://issues.redhat.com/browse/MCO-435. Does that sounds correct?

**Comment by cheesesashimi** [comment]
> @cheesesashimi Looks like this will also solve, https://issues.redhat.com/browse/MCO-435. Does that sounds correct?

Yes, this should fix that one as well.

**Comment by cheesesashimi** [comment]
I plan to pare this PR down in both scope and complexity by breaking up the refactoring into separate PRs so that this can be focused solely on what's needed to make Config Drift Monitor aware of SSH keys.

**Pull request closed without merging**
