### PR TITLE
vendor: update github.com/openshift/api

### PR DESCRIPTION
**Pull request by tomassedovic**
This brings in changes from openshift/api#374 which add PlatformStatus for BareMetal and OpenStack.

### CODE REVIEW

**Comment by tomassedovic** [comment]
I ran this command: `dep ensure -update github.com/openshift/api`. It printed out this warning:

```
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  github.com/blang/semver

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.
```

And it removed `github.com/blang/semver` from `Gopkg.lock`. I'm not sure whether that's a problem or not so I'm just highlighting it here. Everything builds fine for me locally.

**Comment by runcom** [comment]
> And it removed `github.com/blang/semver` from `Gopkg.lock`. I'm not sure whether that's a problem or not so I'm just highlighting it here. Everything builds fine for me locally.

probably side effect of https://github.com/openshift/machine-config-operator/pull/977 which is fine

**Comment by kikisdeliveryservice** [comment]
@runcom is correct, our only semver usage was removed in 977 yesterday

**Comment by tomassedovic** [comment]
@runcom in an accompanying vendor patch in the installer, @vrutkovs said the `prow/e2e-aws-upgrade` job will keep failing until https://github.com/openshift/release/pull/4279 is merged and that we can `/skip` it for now:

https://github.com/openshift/installer/pull/2015#issuecomment-512357025

Are you okay with skipping it here too and reviewing as is?

**Comment by runcom** [comment]
> @runcom in an accompanying vendor patch in the installer, @vrutkovs said the `prow/e2e-aws-upgrade` job will keep failing until [openshift/release#4279](https://github.com/openshift/release/pull/4279) is merged and that we can `/skip` it for now:
> 
> [openshift/installer#2015 (comment)](https://github.com/openshift/installer/pull/2015#issuecomment-512357025)

there's no mention of e2e-aws-upgrade in the PRs you referenced - those are about the scaleup test which isn't in the matrix at all.
Also, we can't just skip e2e-aws-upgrade - and we don't even have power if we wanted to

**Comment by tomassedovic** [comment]
Reading comprehension fail, I'm so sorry!

**Comment by tomassedovic** [comment]
@runcom All tests pass, sorry for the confusion yesterday. Is there anything else you'd like to see?

**Pull request merged**
