### PR TITLE
OCPBUGS-32027: Decrease logs of keepalived

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by zhaozhanqi** [comment]
@mkowalski sounds like the changes is not valid. logs still show

```
# oc get pod keepalived-master-0 -n openshift-kni-infra -o yaml | grep console
            /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --vrrp --log-console &
          /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --vrrp --log-console &
```
the logs still be shown

```
time="2024-03-13T09:45:12Z" level=info msg="Searching for Node IP of worker-0. Using '192.168.111.20/24' as machine network. Filtering out VIPs '[192.168.111.5 192.168.111.4]'."
time="2024-03-13T09:45:12Z" level=info msg="For node worker-0 selected peer address 192.168.111.23 using NodeInternalIP"
time="2024-03-13T09:45:12Z" level=info msg="Searching for Node IP of worker-1. Using '192.168.111.20/24' as machine network. Filtering out VIPs '[192.168.111.5 192.168.111.4]'."
time="2024-03-13T09:45:12Z" level=info msg="For node worker-1 selected peer address 192.168.111.24 using NodeInternalIP"
time="2024-03-13T09:45:12Z" level=info msg="Searching for Node IP of worker-2. Using '192.168.111.20/24' as machine network. Filtering out VIPs '[192.168.111.5 192.168.111.4]'."
time="2024-03-13T09:45:12Z" level=info msg="For node worker-2 selected peer address 192.168.111.25 using NodeInternalIP"
time="2024-03-13T09:45:12Z" level=info msg="Searching for Node IP of master-0. Using '192.168.111.20/24' as machine network. Filtering out VIPs '[192.168.111.5 192.168.111.4]'."
time="2024-03-13T09:45:12Z" level=info msg="For node master-0 selected peer address 192.168.111.20 using NodeInternalIP"
time="2024-03-13T09:45:12Z" level=info msg="Searching for Node IP of master-1. Using '192.168.111.20/24' as machine network. Filtering out VIPs '[192.168.111.5 192.168.111.4]'."
time="2024-03-13T09:45:12Z" level=info msg="For node master-1 selected peer address 192.168.111.21 using NodeInternalIP"
time="2024-03-13T09:45:12Z" level=info msg="Searching for Node IP of master-2. Using '192.168.111.20/24' as machine network. Filtering out VIPs '[192.168.111.5 192.168.111.4]'."
time="2024-03-13T09:45:12Z" level=info msg="For node master-2 selected peer address 192.168.111.22 using NodeInternalIP"
```

**Comment by mkowalski** [comment]
This PR is about different log lines, sorry it is messy but I wanted to split PRs per component. The lines you pasted now are coming from runtimecfg and will be removed by https://github.com/openshift/baremetal-runtimecfg/pull/301

**Comment by mkowalski** [comment]
/cc @cybertron 

This will certainly decrease keepalived logs, but at the same time makes us blind(er) whenever we need to debug VIPs. I have really mixed feelings whether we should merge it or not

**Comment by cybertron** [comment]
What log messages do we lose from this? If, for example, it's just the one about dumping the current state in response to the liveness probe I'm fine with that. The liveness probe will tell us if that stops happening anyway. If we're losing messages that relate to healthcheck scripts and vip moves then I'm not so sure.

**Comment by cybertron** [comment]
Okay, I checked this locally and I don't think I want to make this change. AFAICT all it does is remove the gratuitous ARP messages, which are useful to tell which node has the VIP at a glance. It doesn't remove all of the unnecessary liveness probe messages that comprise most of the log volume either so I don't think it will accomplish much.

**Comment by zhaozhanqi** [comment]
@mkowalski @cybertron with this fix, I can see the following logs as the bug do not wanted.

```
Fri Apr 12 02:43:19 2024: Printing VRRP data for process(34) on signal
Fri Apr 12 02:43:29 2024: Printing parent data for process(33) on signal
Fri Apr 12 02:43:29 2024: Printing VRRP data for process(34) on signal
Fri Apr 12 02:43:39 2024: Printing parent data for process(33) on signal
Fri Apr 12 02:43:39 2024: Printing VRRP data for process(34) on signal
Fri Apr 12 02:43:49 2024: Printing parent data for process(33) on signal
Fri Apr 12 02:43:49 2024: Printing VRRP data for process(34) on signal
Fri Apr 12 02:43:59 2024: Printing parent data for process(33) on signal
Fri Apr 12 02:43:59 2024: Printing VRRP data for process(34) on signal
Fri Apr 12 02:44:09 2024: Printing parent data for process(33) on signal
Fri Apr 12 02:44:09 2024: Printing VRRP data for process(34) on signal
Fri Apr 12 02:44:19 2024: Printing parent data for process(33) on signal
Fri Apr 12 02:44:19 2024: Printing VRRP data for process(34) on signal
Fri Apr 12 02:44:29 2024: Printing parent data for process(33) on signal
Fri Apr 12 02:44:29 2024: Printing VRRP data for process(34) on signal
```

```
$ oc rsh -n openshift-vsphere-infra keepalived-ci-ln-t1hl01b-c1627-dkp2w-worker-0-dvtsg
Defaulted container "keepalived" out of: keepalived, keepalived-monitor, render-config-keepalived (init)
sh-4.4# ^C
sh-4.4# ps -ef | grep keep
root           1       0  0 01:58 ?        00:00:00 /bin/bash -c #/bin/bash sigterm_handler() {   if pid=$(pgrep -o keepalived); then     kill -s SIGTERM "$pid"   fi }  reload_keepalived() {   if pid=$(pgrep -o keepalived); then       kill -s SIGHUP "$pid"   else       /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --vrrp --log-console &   fi }  msg_handler() {   while read -r line; do     echo "The client sent: $line" >&2     # currently only 'reload' msg is supported     if [ "$line" = reload ]; then         reload_keepalived     fi   done }  remove_vip() {   address=$1   interface=$(ip -o a | awk "/\s${address}\// {print \$2}")   cidr=$(ip -o a | awk "/\s${address}\// {print \$4}")   if [ -n "$interface" ]; then       ip a del $cidr dev $interface   fi }  set -ex # Ensure that we don't have stale VIPs configured # See https://bugzilla.redhat.com/show_bug.cgi?id=1931505 remove_vip "10.38.252.2" remove_vip "10.38.252.3" declare -r keepalived_sock="/var/run/keepalived/keepalived.sock" export -f msg_handler export -f reload_keepalived export -f sigterm_handler  # in remote worker case sleep forever if [ -f "/run/nodeip-configuration/remote-worker" ]; then    sleep infinity    exit 0 fi  trap sigterm_handler SIGTERM if [ -s "/etc/keepalived/keepalived.conf" ]; then     /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --vrrp --log-console & fi  rm -f "$keepalived_sock" socat UNIX-LISTEN:${keepalived_sock},fork system:'bash -c msg_handler' 
root          21       1  0 01:58 ?        00:00:00 socat UNIX-LISTEN:/var/run/keepalived/keepalived.sock,fork system:bash -c msg_handler
root          22      21  0 01:58 ?        00:00:00 socat UNIX-LISTEN:/var/run/keepalived/keepalived.sock,fork system:bash -c msg_handler
root          23      22  0 01:58 ?        00:00:00 socat UNIX-LISTEN:/var/run/keepalived/keepalived.sock,fork system:bash -c msg_handler
root          39      24  0 01:59 ?        00:00:00 /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --vrrp --log-console
root          40      39  0 01:59 ?        00:00:01 /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --vrrp --log-console
root       18876   18471  0 02:49 pts/0    00:00:00 grep keep

```

**Comment by mkowalski** [comment]
> Okay, I checked this locally and I don't think I want to make this change. AFAICT all it does is remove the gratuitous ARP messages, which are useful to tell which node has the VIP at a glance. It doesn't remove all of the unnecessary liveness probe messages that comprise most of the log volume either so I don't think it will accomplish much.

Yeah, I agree completely. This change is not something we should ever do in the current form. If at all, it should be behind a config, but in the best case it should not land at all (in any flavour)

/hold

**Comment by mkowalski** [comment]
/close

Won't do in the current form

**Pull request closed without merging**
