### PR TITLE
OCPBUGS-39199: clusteroperator/machine-config blips Degraded=True during upgrade test

### PR DESCRIPTION
**Pull request by djoshy**
**- What I did**
Add a short retry for the operator image version check before degrading.

**- How to verify it**
This is hard to manually verify, but we should no longer see failures of the sort listed in the bug. Existing e2es should pass and this retry should not have a discernible performance impact.

### CODE REVIEW

**Comment by sergiordlr** [comment]
/label qe-approved

We will post-merge verify this issue by querying the CI.

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

**Pull request merged**
