### PR TITLE
machineconfig.crd.yaml: add passwd schema

### PR DESCRIPTION
**Pull request by ericavonb**
Better CRD validation via OpenAPIV3 schema. Taken from https://github.com/coreos/ignition/blob/spec2x/schema/ignition.json

### CODE REVIEW

**Comment by ericavonb** [comment]
/assign @kikisdeliveryservice 
@kikisdeliveryservice these look like the right set of supported fields?

**Comment by kikisdeliveryservice** [comment]
@ericavonb Correct.  The only part of passwd we support is users and only the user core and only property is SSH keys.

**Comment by ericavonb** [comment]
@kikisdeliveryservice I have a feeling this is going to get caught up in whatever 🔥 CI tests are going through today. Can you look over and give a lgtm if it looks give minus CI tests passing?

**Comment by kikisdeliveryservice** [comment]
Will test with a cluster this afternoon to double check.

**Comment by kikisdeliveryservice** [comment]
@ericavonb do you have a sample mc that i can start with (so i can go faster) + expected output

**Comment by ericavonb** [comment]
Bad- `oc apply...` should fail (from https://access.redhat.com/solutions/4073041):
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 00-master-ssh-02
spec:
  config:
    passwd:
      users:
      - name: core
        sshAuthorizedKeys: |
          <<ssh-public rsa key goes here>>
```

Good- `oc apply...` should succeed: 
```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 50-master-ssh-02
spec:
  config:
    passwd:
      users:
      - name: core
        sshAuthorizedKeys:
          - |
            <<ssh-public rsa key goes here>>
```

**Comment by kikisdeliveryservice** [comment]
Looks good! Output from my bogus config:

```$ oc create -f evb-config.yaml 
The MachineConfig "sssh-test" is invalid: spec.config.passwd.users.sshAuthorizedKeys: Invalid value: "string": spec.config.passwd.users.sshAuthorizedKeys in body must be of type array: "string"``

/lgtm

**Comment by kikisdeliveryservice** [comment]
gah aws not again..

/retest

**Pull request merged**
