### PR TITLE
OCPBUGS-37534: Revert "MCD-pull: run after network-online.target in Azure"

### PR DESCRIPTION
**Pull request by yuqi-zhang**
This reverts commit c7d6ec2799237dc3678f2507b6f5e511589890b4.

This fix was only partial for Azure (only fixed scaleup but not install) so the fix will still have to be augmented on the ARO side.

On top of that, this introduces a cycling order for older versions on Azure, which breaks 4.9->4.13 upgrades for Azure and some 4.12->4.13 ARO clusters. At this point it's probably best to revert this and have ARO implement a fix via changing dnsmasq instead.

### CODE REVIEW

**Comment by djoshy** [comment]
/override e2e-hypershift 

overriding hypershift as failure seems unrelated and this shouldn't affect hypershift

**Comment by sergiordlr** [comment]
Verified using IPI on Azure

- It could be installed and new worker nodes could be created using machinesets
- Successful upgrade 4.16 -> 4.7+fix

/label qe-approved

**Comment by djoshy** [comment]
/unhold

I guess branch happened, but not sure why the bot wants "4.18." instead of 4.18.0. Also jira doesn't have 4.18 anything in the target field right now

**Comment by sdodson** [comment]
Jumping this one to the front of the line as we need to get backports on this moving.

**Pull request merged**
