### PR TITLE
[release-4.8] Bug 1995809: crio: complete crio default config

### PR DESCRIPTION
**Pull request by wking**
Backporting #2723 to 4.8.

### CODE REVIEW

**Comment by deads2k** [comment]
(patch manager)

blocker bug

**Review by kikisdeliveryservice — APPROVED** [review]

**Comment by wking** [comment]
Still not quite verified, but [we're][1] [optimistic][2], and can keep rolling forward.  I've twiddled the labels to get this landed, to make next week's QE verification easier.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1995810#c2
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1995810#c3

**Pull request merged**
