### PR TITLE
OCPBUGS-3756: daemon: Stop setting I/O scheduler to bfq

### PR DESCRIPTION
**Pull request by sinnykumari**
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3415 as some conflict were showing up

### CODE REVIEW

**Comment by mor120** [comment]
Verification: https://main-jenkins-csb-cnvqe.apps.ocp-c1.prod.psi.redhat.com/job/cnv-tests-runner-containerized/451/consoleFull

**Comment by sinnykumari** [comment]
weird, looks like bot went crazy(regression?) and assigned this bug for cherry-pick label to all QE who are included for MCO repo

**Comment by rioliu-rh** [comment]
label cherry-pick-approved

**Pull request merged**
