### PR TITLE
MCO-1248: port {azure,gcp}-routes.sh from iptables to nftables

### PR DESCRIPTION
**Pull request by danwinship**
iptables is going away in RHEL10; this PR ports {azure,gcp}-routes.sh from iptables to nftables.

What's different:
- The old azure script created separate iptables and ip6tables rules, but the nftables version just uses the `inet` family so we can put both sets of rules together (and we don't need to check if IPv6 is enabled or not; the IPv6 rule will just never match anything if IPv6 is disabled.)
- The old version used an iptables rule per VIP, the new version uses a single nftables rule that does a set match against all the VIPs at once.
- The old version did "figure out which rules don't belong, then remove then, then add new rules", while the new version does "atomically overwrite the old rules with the new rules".

Other than that (and the commit that removes an unnecessary ACCEPT rule), there are no changes in functionality; I had previously started an attempt to refactor them first (#3619, #3673, #3674, #3675) but wasn't having much luck with that, and we need to get rid of iptables, so...

### CODE REVIEW

**Comment by danwinship** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 5

**Comment by danwinship** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 6
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 6

**Comment by danwinship** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 6

**Comment by danwinship** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 6

**Comment by danwinship** [comment]
ok, gcp payload passed in the [first run](https://pr-payload-tests.ci.openshift.org/runs/ci/91e1b5e0-4c5e-11ef-9aa0-de06f78ca57b-0), azure payload passed in the [second run](https://pr-payload-tests.ci.openshift.org/runs/ci/7163e640-4e74-11ef-85b3-ebdf6b3ccdbe-0) (after failing all 6 times in the original run because of a [bug](https://github.com/openshift/machine-config-operator/compare/2969be62ee116fa3465fe356c85abf542f4eb9c6..69898919b7dd122e75467ce41148773c2e0e8dcb#diff-c42a692db1163fe89e65e2ae58e2ac644544084f7793ecaca6721c889991f2c2L93-R96), showing that the payload test does actually depend on this script working)

**Comment by jcaamano** [comment]
@danwinship LGTM

one question about commit [Remove unnecessary {azure,gcp}-routes rules](https://github.com/openshift/machine-config-operator/pull/4494/commits/a4969bbd8833fa798ff002271239398cbd1c4659)

You are assuming there those rules you removed are a workaround for potentially existing DROP rules of a third party firewall. Perhaps this is a correct assumption but what if its a workaround for a DROP table policy or DROP rules of our own, like for example the drop rules we have in place for GCP at `If a connection for a VIP comes in while we have no rewrite rule for that VIP...`

**Comment by danwinship** [comment]
> what if its a workaround for a DROP table policy

You can't _just_ change the default table policy and not do anything else though; that would break all sorts of traffic. So you'd need to add a bunch of ACCEPT rules, and then that's just another way of saying "third-party firewall".

> or DROP rules of our own

(There is only the single pair of DROP rules in gcp-routes, and there are no DROP rules in azure-routes.)

> like for example the drop rules we have in place for GCP at `If a connection for a VIP comes in while we have no rewrite rule for that VIP...`

Hm... the DROP rule is in the FORWARD chain, but the ACCEPT rule is in the INPUT chain, so they can't ever match the same packet; either the kernel is delivering the packet to a local interface (in which case the ACCEPT rule can match but the DROP rule can't) or it's forwarding it off-host (in which case the DROP rule can match but the ACCEPT rule can't).

In fact, looking more closely at the (gcp) ACCEPT rule, I don't think it can ever match _anything_, even in the "overly aggressive firewall" case; it's on the INPUT chain (meaning it is only checked against packets which are being delivered to a local interface), but it checks `! --dst-type LOCAL` (meaning it will only match a packet whose (post-DNAT) destination address is not an IP on any local interface).

Oddly, the azure-routes ACCEPT rule is instead installed on both OUTPUT and FORWARD, but _not_ INPUT. So in that case the `! --dst-type LOCAL` is just unnecessary rather than contradictory. But anyway, we don't have any DROP rules on azure, so it's unnecessary anyway.

**Comment by jcaamano** [comment]
ok, I have the odd feeling we might be missing something, but if we don't know what, it is as if we weren't.

**Comment by djoshy** [comment]
/approve

I'll admit this is not my domain so I'll defer to @jcaamano. The payloads look good too. Holding in case this requires QE testing, but feel free to unhold if not required.

/unhold

**Comment by danwinship** [comment]
/hold cancel

The failure mode for this is that a very small percentage of apiserver connections would fail during upgrades, which we have checks for in the upgrade jobs, but which is hard to notice in human testing (since the failed connections would get retried so everything still _works_, just a little bit more slowly than it should have). So I think the payload jobs validate this better than QE could.

**Comment by danwinship** [comment]
/hold cancel
/retest-required
infra flakes

**Pull request merged**
