### PR TITLE
templates/master/00-master: update recovery template to work with setup-etcd-environment

### PR DESCRIPTION
**Pull request by hexfusion**
This PR fixes DR scripts that were broken by recent changes to `setup-etcd-environment`.

### CODE REVIEW

**Comment by hexfusion** [comment]
/hold

I am kind of confused since this is against master the Bug should probably be removed and added to PR against 4.3.

/joke

**Comment by hexfusion** [comment]
>level=error msg="Cluster operator cloud-credential Degraded is True with CredentialsFailing: 1 of 4 credentials requests are failing to sync."
level=info msg="Cluster operator cloud-credential Progressing is True with Reconciling: 3 of 4 credentials requests provisioned, 1 reporting errors."
level=info msg="Cluster operator image-registry Available is False with DeploymentNotFound: The deployment does not exist"
level=info msg="Cluster operator image-registry Progressing is True with Error: Unable to apply resources: unable to sync storage configuration: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request id: EF705343AB608775, host id: wMAF6szgvBt9BGjmrLHMnwvk4bN8mz+47u8dlLHt5zNJuqiWELCroaLLPud38KecBqH7OSzh30Q="

/test e2e-aws

**Comment by kikisdeliveryservice** [comment]
@hexfusion we'd have to merge into master first then backport to 4.x

**Comment by runcom** [comment]
fixed BZs references, I think

**Pull request merged**
