### PR TITLE
[release-4.11] OCPBUGS-21016: vendor: unpin deps and update library-go, container and kube deps

### PR DESCRIPTION
**Pull request by sinnykumari**
Due to pinning, vendored packages has been outdated and were still on kube 1.23. Since, 4.11 release uses kube 1.24, delta has been quite. It needed to update container libs, commit https://github.com/openshift/machine-config-operator/commit/d5ddbfd547ea5cee8652a43ee4a6e66650f3fa17.

### CODE REVIEW

**Comment by djoshy** [comment]
I think I maybe missing context, but quick question:
Based on the [remediation](https://docs.google.com/document/d/1F99glzhX2i2Ppe5Qq3M-Po_jSSUiVssqFyWRhVm1X3o/edit?usp=sharing) doc, I thought 4.11 needed a specific replace clause. Is that no longer the case?

And minor nit - looks like the commit message for the first commit has some boilerplate text that snuck in

**Comment by sinnykumari** [comment]
> I think I maybe missing context, but quick question: Based on the [remediation](https://docs.google.com/document/d/1F99glzhX2i2Ppe5Qq3M-Po_jSSUiVssqFyWRhVm1X3o/edit?usp=sharing) doc, I thought 4.11 needed a specific replace clause. Is that no longer the case?

Existing replace that we removed in this PR was about pinned older version of k8s.io libs which was pointing to 1.23. Removing them is needed so that we use kube 1.24 based libs in 4.11 which OCP 4.11 uses.

You are right, doc says to use replace and suggest to use openshift/kube* instead of using upstream k8s.io/ .  However, I am not sure if this is a recommendation or a requirement. MCO pulls in lot of k8s.io deps direct/indirect and I need to understand if we need to do replace for all direct and indirect dependencies. We can keep this PR on hold until this is clear.

@dgrisonnet I saw your related  4.11 https://github.com/openshift/kubernetes-apiserver/pull/47 ,  any thoughts on this?

> And minor nit - looks like the commit message for the first commit has some boilerplate text that snuck in

Good catch, fixed.

**Comment by dgrisonnet** [comment]
> You are right, doc says to use replace and suggest to use openshift/kube* instead of using upstream k8s.io/ . However, I am not sure if this is a recommendation or a requirement.

Sorry if it wasn't clear in the mitigation doc, but using the downstream forks for the upstream deps is only required when http/2 is still enabled, so in your case it is fine to do without

**Comment by sinnykumari** [comment]
ci test failure seems unrelated.
skipping optional tests and running retest
/skip
/retest

**Comment by sinnykumari** [comment]
> Sorry if it wasn't clear in the mitigation doc, but using the downstream forks for the upstream deps is only required when http/2 is still enabled, so in your case it is fine to do without

Thanks for confirming!

**Comment by sinnykumari** [comment]
Test were failing due to  missing RBAC for API coordination.k8s.io
[MCC log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/4019/pull-ci-openshift-machine-config-operator-release-4.11-e2e-gcp-op/1723081952417812480/artifacts/e2e-gcp-op/gather-extra/artifacts/pods/openshift-machine-config-operator_machine-config-controller-85dd6c67c6-l2f25_machine-config-controller.log):
```
E1110 21:27:11.459280       1 leaderelection.go:330] error retrieving resource lock openshift-machine-config-operator/machine-config-controller: leases.coordination.k8s.io "machine-config-controller" is forbidden: User "system:serviceaccount:openshift-machine-config-operator:machine-config-controller" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "openshift-machine-config-operator"
```
Cherry-picked commit https://github.com/openshift/machine-config-operator/pull/3270/commits/c9ceacfcfb00677ce31d08933308a88558cd52d4

**Comment by sinnykumari** [comment]
ci tests are looking good, should be good to get merged

**Comment by djoshy** [comment]
/lgtm 

Thanks for picking these up, Sinny!

**Pull request merged**
