### PR TITLE
Test Revert "Block RHCOS gcp-routes service on both masters and workers"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts openshift/machine-config-operator#3619

Just seeing if this is our culprit for https://issues.redhat.com/browse/OCPBUGS-11655

Turns out it is, in the 5 jobs run below you can see virtually no ingress disruption as opposed to the 20-50s we're getting every single run otherwise. 

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of (job/X or job/X, test/Y tuple) to confirm the fix has corrected the problem:

`/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade 5` 

And verify the ingress disruption looks good. This is best done by expanding job-run-summary, viewing each job that made it past install, opening the first spyglass panel, searching for 'disrupt', you should see minimal disruption of no more than a few seconds, rather than 20-50s. 

cc @danwinship @yuqi-zhang

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade 5

**Comment by jkyros** [comment]
makes sense
/approve

**Pull request merged**
