### PR TITLE
baremetal: Drop custom kubelet configuration.

### PR DESCRIPTION
**Pull request by russellb**
The purpose of this change was to make masters able to run workloads
by default.  This is needed to complete a successful deployment of a
3-node bare metal install.  This particular approach was only short
term, while better interfaces were developed to control this behavior.
    
The scheduler configuration resource now includes a
"mastersSchedulable" boolean, enabled here:
    
https://github.com/openshift/machine-config-operator/pull/937
    
This installer PR made it the default behavior if no workers were
defined at install time:
    
https://github.com/openshift/installer/pull/2004
    
With these changes in place, the custom kubelet config for the
baremetal platform is no longer necessary.

### CODE REVIEW

**Comment by russellb** [comment]
/hold

As discussed in the description, this needs to wait for one of the two mentioned installer PRs to merge first.

**Comment by russellb** [comment]
The installer change went in, but the scheduler setting is not working as expected, bug filed here: https://github.com/openshift/machine-config-operator/issues/1024

**Comment by russellb** [comment]
The prerequisites for this merged a while ago, so this should be ready to go in.

/cc stbenjam
/cc hardys

**Comment by eparis** [comment]
I believe we went a different direction and don't need this anymoe.

**Comment by stbenjam** [comment]
master still has the baremetal kubelet override: https://github.com/openshift/machine-config-operator/blob/master/templates/master/01-master-kubelet/baremetal/units/kubelet.yaml

@russellb We should be able to drop this now, right?

**Comment by russellb** [comment]
@stbenjam Yes, and that's what this PR did.  It dropped it.

@eparis why did you close this?  Can you provide a bit more detail about what "different direction" you're talking about?

**Comment by hardys** [comment]
@russellb Hey this looks like it resolves https://bugzilla.redhat.com/show_bug.cgi?id=1828250 - would you mind rebasing when you get a moment and we can re-test/review?

**Comment by russellb** [comment]
This PR is replaced by #1817

**Comment by kikisdeliveryservice** [comment]
> This PR is replaced by #1817

@russellb can you please close this PR then?

**Comment by russellb** [comment]
> > This PR is replaced by #1817
> 
> @russellb can you please close this PR then?

Yeah I meant to do that before when I left this comment.  sorry about that

**Pull request closed without merging**
