### PR TITLE
Switch to https://github.com/coreos/rpmostree-client-go

### PR DESCRIPTION
**Pull request by cgwalters**
We have a lot of ad-hoc code in the MCO interacting with rpm-ostree.
There's about 50% of it that uses this "NodeUpdaterClient" abstraction
which I guess in theory could have tried to also support e.g.
traditional dnf/apt systems or whatever, but never did - and
its API has grown things that make no sense on those systems (e.g.
"staged deployment" etc.)

The other half of the code ignores that abstraction (sensibly) and
just runs `rpm-ostree` via the CLI directly, crafting command
line arguments.

We now have https://github.com/coreos/rpmostree-client-go
which is intending to be "official" Go bindings which for now
just wrap the CLI, but do so in a more consistent way and offering
a cleaner API.

---

### CODE REVIEW

**Comment by cgwalters** [comment]
If we go this route (and I think we should) a next step would be to just remove the `NodeUpdaterClient` abstraction; the mock unit tests we have basically aren't useful.

**Comment by jkyros** [comment]
- The realist in me says leave it how it is since it's currently less overhead for the MCO, and we'd likely be dependent on you to merge changes to this wrapper (not that you aren't responsive, you are very responsive, but you know what I mean) 
- The purist in me says yes, we should do this, so that rpm-ostree can expose things to us in the way they're meant to be used, and potentially other parties could benefit from using this wrapper 
> If we go this route (and I think we should) a next step would be to just remove the NodeUpdaterClient abstraction; the mock unit tests we have basically aren't useful.

Yes, I think we can probably work through what to do with the "node updater client" as we work through layering?

**Comment by cgwalters** [comment]
> and we'd likely be dependent on you to merge changes to this wrapper

We'll definitely move this into github.com/coreos/rpmostree-client-go - and anyone on the coreos team hence could review and merge PRs.  (Not to mention, happy to give review/commit access to you too :smile: )

**Comment by cgwalters** [comment]
Depends on https://github.com/openshift/machine-config-operator/pull/3325

**Comment by cgwalters** [comment]
OK now that https://github.com/openshift/machine-config-operator/pull/3317 merged, I've rebased :surfer: this

**Comment by cgwalters** [comment]
I've invited @jkyros from this team as a collaborator on https://github.com/coreos/rpmostree-client-go (and am happy to add others) to ensure the MCO team can always get timely and quick fixes into that repo.

(But that said again, nothing at all stops the MCO or anyone else from continuing to just run `/usr/bin/rpm-ostree` too)

**Comment by cheesesashimi** [comment]
Just wanted to add that I like this change and am happy to see rpm-ostree get its own proper client!

**Comment by cgwalters** [comment]
Friendly ping, seems like everyone's in favor, can someone drop a lgtm?

**Comment by sinnykumari** [comment]
Don't see any concern with this move. Also happy that rpm-ostree will be having its own client lib which multiple project can directly use (including MCO)

Minor update in commit message and PR header
should be github.com/coreos/rpmostree-client-go/ instead of  https://github.com/cgwalters/rpmostree-client-go/

**Comment by cgwalters** [comment]
Ah yep, updated the commit and PR title.

**Pull request merged**
