### PR TITLE
[release-4.12] OCPBUGS-21723: keepalived/ingress: change healthcheck script 

### PR DESCRIPTION
**Pull request by mandre**
This is a manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3687 and https://github.com/openshift/machine-config-operator/pull/3908.

### CODE REVIEW

**Comment by mandre** [comment]
@cybertron, PTAL.

/assign @cybertron

**Comment by cybertron** [comment]
/assign @yuqi-zhang 
@sergiordlr can you give cherry-pick-approved?

**Review by yuqi-zhang — APPROVED** [review]

**Comment by cybertron** [comment]
@rbbratta @anuragthehatter Could one of you give this cherry-pick-approved?

**Pull request merged**
