### PR TITLE
*: remove etcd quorum guard

### PR DESCRIPTION
**Pull request by hexfusion**
We are migrating `quorum-guard` to the `openshift-etcd` namespace. The reason it originally lived here was that we did not have an operator to take reference to the cli image it uses.

depends on https://github.com/openshift/cluster-etcd-operator/pull/142

### CODE REVIEW

**Comment by hexfusion** [comment]
/hold 

for https://github.com/openshift/cluster-etcd-operator/pull/142

**Comment by abhinavdahiya** [comment]
hmm.. cvo doesn't clean up / prune removed deployments (or any other object) from release images, i think mco / ceo will have to take ownership of that.

**Comment by hexfusion** [comment]
> hmm.. cvo doesn't clean up / prune removed deployments (or any other object) from release images, i think mco / ceo will have to take ownership of that.

yeah good point to manage this we have a controller "guardbudget" that will handle this teardown this on CEO end.

**Comment by cgwalters** [comment]
etcd has left the building

**Comment by runcom** [comment]
> depends on [openshift/cluster-etcd-operator#142](https://github.com/openshift/cluster-etcd-operator/pull/142)

this PR has been closed :thinking: does this still depend on something?

**Comment by hexfusion** [comment]
we are not going to go this route in 4.4

**Pull request closed without merging**
