### PR TITLE
Revert "OCPBUGS 33803: machine-os-puller SA refreshes every hour, causing machine config regeneration"

### PR DESCRIPTION
**Pull request by djoshy**
Let's see if reverting this is fine as https://github.com/openshift/openshift-controller-manager/pull/306 has landed

### CODE REVIEW

**Comment by sinnykumari** [comment]
Made some minor edit to subject to unlink bug so that backport PR https://github.com/openshift/machine-config-operator/pull/4374 can be merged once OCPBUGS-33803 moves to verified state
/jira refresh

**Comment by djoshy** [comment]
Closing this as the [temporary fix was necessary](https://github.com/openshift/machine-config-operator/pull/4374) for 4.16 as well. The longer term fix can be found here: https://github.com/openshift/machine-config-operator/pull/4372

**Pull request closed without merging**
