### PR TITLE
Use env instead /usr/bin/bash

### PR DESCRIPTION
**Pull request by mkenigs**
I need this to run the script on NixOS

### CODE REVIEW

**Comment by cgwalters** [comment]
Previous Nix user over here https://github.com/openshift/installer/commit/e6712fa11a935c1f8c87f6ce904b99e171f07bc7

**Comment by mkenigs** [comment]
Haha sure sign of a Nix user :joy:

**Review by yuqi-zhang — APPROVED** [review]
/lgtm

**Comment by sinnykumari** [comment]
skip optional test to prevent reruns
/skip

**Pull request merged**
