### PR TITLE
Bug 1697657: vendor: bump openshift/api and needed k8s deps

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

**- What I did**

Bump openshift/api as per https://bugzilla.redhat.com/show_bug.cgi?id=1697657 and other k8s deps as needed by the openshift/api bump

**- How to verify it**

CI

**- Description for the changelog**

### CODE REVIEW

**Comment by rphillips** [comment]
To fix the unit tests we need to bump client-go as well.

Depends on: https://github.com/openshift/client-go/pull/100

**Comment by runcom** [comment]
> To fix the unit tests we need to bump client-go as well.
> 
> Depends on: [openshift/client-go#100](https://github.com/openshift/client-go/pull/100)

@rphillips so I should wait on that to merge?

**Comment by rphillips** [comment]
@runcom yes, and we will need to regenerate the deps update on this PR after the client-go patch merges in.

**Comment by runcom** [comment]
> To fix the unit tests we need to bump client-go as well.

actually, I don't think this is the case. The only units failing are related to the fact that the container_runtime controller reports the REAL error on failure, where the kubelet_config just silently ignores it see https://github.com/openshift/machine-config-operator/pull/603

In there, we talked about it, and right now, if something goes wrong the controller isn't throwing an error cause UpdateStatus succedes (again, the container runtime controller does the right thing by returning the actual error)

**Comment by rphillips** [comment]
I'm seeing this error in the build log:

```
# github.com/openshift/machine-config-operator/vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go:99:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_featuregate.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go:110:48: too many arguments in call to testing.NewRootPatchSubresourceAction
	have (schema.GroupVersionResource, string, types.PatchType, []byte, []string...)
	want (schema.GroupVersionResource, string, []byte, ...string)
```

**Comment by runcom** [comment]
> I'm seeing this error in the build log:

yeah, but that doesn't relate to https://github.com/openshift/client-go/pull/100 - I mean that PR is probably still required but bumping client-go locally just worked for me and then there's the unit error I mentioned above related to kubelet_config. I'm creating an issue to be more precise.

**Comment by rphillips** [comment]
Looks like we are dependent on a new k8s.io/client-go with this [patch](https://github.com/kubernetes/client-go/commit/f0c6576981f26757c12f4757060d2a036951b67c#diff-ae2b1fca515949e5d54fb22b8ed95575) to bring in MergePatchType support.

**Comment by runcom** [comment]
> Looks like we are dependent on a new k8s.io/client-go with this [patch](https://github.com/kubernetes/client-go/commit/f0c6576981f26757c12f4757060d2a036951b67c#diff-ae2b1fca515949e5d54fb22b8ed95575) to bring in MergePatchType support.

oh nice, that would be perfect and fixes the units that are failing with container_runtime units.

Any eta on when that's gonna land in openshift/client-go?

**Comment by abhinavdahiya** [comment]
looking at the diff in Gopkg.lock which is updating each package, but the commit message being `bump openshift/api`

you probably want to run `dep ensure -update github.com/openshift/api github.com/openshift/client-go` compared to `dep ensure -update`

**Comment by rphillips** [comment]
@abhinavdahiya thanks for the tip, because I was trying a bunch of things with dep and failing.

```diff
diff --git a/Gopkg.toml b/Gopkg.toml
index ae550eab..d8cdd0e5 100644
--- a/Gopkg.toml
+++ b/Gopkg.toml
@@ -105,7 +105,7 @@ required = [
 
 [[constraint]]
   name = "k8s.io/api"
-  branch = "release-1.13"
+  branch = "release-1.14"
 
 [[constraint]]
   name = "k8s.io/apiextensions-apiserver"
@@ -113,7 +113,7 @@ required = [
 
 [[constraint]]
   name = "k8s.io/client-go"
-  version = "10.0.0"
+  version = "v11.0.0"
 
 [[constraint]]
   name = "k8s.io/code-generator"
```

[Note: v11.0.0 is not a typo, upstream added a 'v' in front of the version]

Then
```
dep ensure -v -update github.com/openshift/api github.com/openshift/client-go k8s.io/client-go
```

After doing these steps I got a successful `make test`.

**Comment by runcom** [comment]
alright, I just `-update`on openshift/api and openshift/client-go and the kube deps that we need to correctly generate the code for 1.13 (not really going to use 1.14 code).

For the failing units, I'm trying to find a nice hack while we move to 1.14 as the patch to backport just for that is huge and won't be backported afaict.

**Comment by runcom** [comment]
ok, last commit adds a workaround till we upgrade to 1.14 (not soon likely) @rphillips ptal I'll add something similar for kubelet controller once #617 merges and I rebase this

**Comment by runcom** [comment]
Ok, this should be good to go now :tada:

**Comment by kikisdeliveryservice** [comment]
aws HAProxy woes

/test e2e-aws

**Comment by runcom** [comment]
rebased, needs another LGTM pls

**Comment by runcom** [comment]
ok this is failing on a known issue (see Slack)

**Comment by runcom** [comment]
@eparis since we're bumping openshift/api and kube to 1.13, do we have to bump the golang images to 1.11?

**Comment by eparis** [comment]
no, you do not need to bump golang. it sohuld be fine.

**Comment by runcom** [comment]
> no, you do not need to bump golang. it sohuld be fine.

alrighty, but I'll just leave it written here that we're bumping all our kube* deps to 1.13.4 then to bump openshift/api 😄

**Comment by runcom** [comment]
> New changes are detected. LGTM label has been removed.

I've rebased this and added a commit which aligns our kube deps to 1.13.x which is the one we support in 4.1

@kikisdeliveryservice @cgwalters @LorbusChris ptal again pls

**Comment by runcom** [comment]
And finally green again

**Pull request merged**
