### PR TITLE
OCPBUGS-6997: Fix 4.12 art images

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Manual partial-cherry-pick of Sinny's 4.13 fix at https://github.com/openshift/machine-config-operator/pull/3514

Supercedes https://github.com/openshift/machine-config-operator/pull/3359

### CODE REVIEW

**Comment by jkyros** [comment]
I don't think this PR broke anything, I just think the timings line up sometimes now to where this test needs a retry block:  
``` 
=== RUN   TestClusterOperatorStatusExtension
    mco_test.go:124: 
        	Error Trace:	/go/src/github.com/openshift/machine-config-operator/test/e2e/mco_test.go:124
        	Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Operation cannot be fulfilled on clusteroperators.config.openshift.io \"machine-config\": the object has been modified; please apply your changes to the latest version and try again", Reason:"Conflict", Details:(*v1.StatusDetails)(0xc00080e5a0), Code:409}}
        	Test:       	TestClusterOperatorStatusExtension
--- FAIL: TestClusterOperatorStatusExtension (0.08s)
FAIL
FAIL	github.com/openshift/machine-config-operator/test/e2e	5428.759s
FAIL
```

"John, didn't you see this before and weren't you going to write this up?"
I plead the 5th. :smile: 

/test e2e-gcp-op

**Comment by yuqi-zhang** [comment]
Hmm, that's a new one to me. Looking at search.ci this fails approximately 20% of the time, which is not the end of the world, but would be nice to throw in I suppose

Are you already tracking that somewhere?

**Comment by sinnykumari** [comment]
Thanks Jerry for the PR!  It was long pending, bot should hopefully get some peace now :D
/lgtm
/label backport-risk-assessed

**Comment by rioliu-rh** [comment]
@yuqi-zhang @sinnykumari I suppose if CI jobs are all pass, we can consider this bug is fixed.

**Comment by yuqi-zhang** [comment]
@rioliu-rh yes, I think so, the main commit was directly cherry-picked from master, and the other commit was a formatting fix, and doesn't affect functionality

**Pull request merged**
