### PR TITLE
  recycler pod: drop serviceAccountName

### PR DESCRIPTION
**Pull request by haircommander**
**- What I did**

this static pod fails on creation because static pods can't have an attached service account.
This would normally not be that problematic (the mirror pod creation fails in the API server, but continues in kubelet),
however, Multus queries the API-server for pod status, and fails if it can't be found.
This, this pod is never actually created.

**- How to verify it**
```
kubelet_service.log:Nov 10 03:07:32.757094 ip-10-0-143-173 hyperkube[1522]: E1110 03:07:32.757070    1522 kubelet.go:1583] Failed creating a mirror pod for "recyler-pod-ip-10-0-143-173.ec2.internal_openshift-infra(c4a6d0bdd7ae69ac5efa10a12ad33bc0)": pods "recyler-pod-ip-10-0-143-173.ec2.internal" is forbidden: a mirror pod may not reference service accounts
...
crio_service.log:Nov 10 03:07:32.798133 ip-10-0-143-173 crio[1487]: time="2020-11-10 03:07:32.798004563Z" level=error msg="Error adding network: Multus: [openshift-infra/recyler-pod-ip-10-0-143-173.ec2.internal]: error getting pod: pods \"recyler-pod-ip-10-0-143-173.ec2.internal\" not found" file="ocicni/ocicni.go:771"
```
does not appear

**- Description for the changelog**

### CODE REVIEW

**Comment by haircommander** [comment]
@bertinatto PTAL

**Comment by haircommander** [comment]
(I happened upon this by poking through the logs of https://github.com/openshift/machine-config-operator/pull/2210 trying to figure out why it failed, my understanding is incomplete but hopefully near-correct)

**Review by kikisdeliveryservice — APPROVED** [review]
This seems sane to me but I defer to @bertinatto to LGTM as they originally added this template.

**Comment by bertinatto** [comment]
/lgtm

This makes sense to me. This template is a copy of the one used in 3.x, so I'm not sure why we haven't seen this before.

**Comment by kikisdeliveryservice** [comment]
lots of retesting will remove hold when they start to pass..

/hold

**Comment by sjenning** [comment]
I don't believe we need this.

This pod was not intended to be a static pod in the first place.  See https://github.com/openshift/machine-config-operator/pull/2238

@haircommander if you agree, can you close this?

**Comment by sjenning** [comment]
@haircommander I also pulled in the typo fix for `recyler`

**Comment by haircommander** [comment]
agreed that this can be closed!

**Pull request closed without merging**
