### PR TITLE
OCPBUGS-6622:  controller: don't render new MC until base MCs update

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3506

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
/label backport-risk-assessed

Already tested on 4.11

**Comment by sergiordlr** [comment]
In order to verify this PR we will only execute an **upgrade  4.10 -> 4.11+PR after creating a kubeletconfig resource and a containerruntimeconfig resource**.

The error is the result of a race condition when a problem in kubelet happens, it is not easy to reproduce unless using hacked payloads. It was done in the original PR, in this cherry-pick we will only do the verification by upgrading and making sure that nothing is broken.


A kubeletconfig and a containerruntimeconfig were present in the cluster:
```
$ oc get mc
NAME                                                    GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
....
99-worker-generated-containerruntime                    04906c53952d63c73318207f4d1d3ec5b98a47d6   3.2.0             79m
.....
99-worker-generated-kubelet                             04906c53952d63c73318207f4d1d3ec5b98a47d6   3.2.0             79m
....
```


The upgrade was executed from 4.10 -> 4.11+PR

```
$ oc get clusterversion -o yaml
....
    history:
    - completionTime: "2023-01-26T12:15:03Z"
      image: registry.build05.ci.openshift.org/ci-ln-zbd5b8k/release:latest
      startedTime: "2023-01-26T11:12:49Z"
      state: Completed
      verified: false
      version: 4.11.0-0.ci.test-2023-01-26-110134-ci-ln-zbd5b8k-latest
    - completionTime: "2023-01-26T10:49:47Z"
      image: registry.ci.openshift.org/ocp/release@sha256:49c974316cccab5cf84778677f4c2f2250caf461888e7a2d1631b122413de0d5
      startedTime: "2023-01-26T10:30:56Z"
      state: Completed
      verified: false
      version: 4.10.0-0.nightly-2023-01-26-013515

```

No problem happened in the upgrade:

```
$ oc get mcp,clusterversion
NAME                                                         CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
machineconfigpool.machineconfiguration.openshift.io/master   rendered-master-5f840f92908c1de84fdf9b999e415239   True      False      False      3              3                   3                     0                      106m
machineconfigpool.machineconfiguration.openshift.io/worker   rendered-worker-beb74b789cec6e6cf7e0e022144a91d5   True      False      False      3              3                   3                     0                      106m

NAME                                         VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
clusterversion.config.openshift.io/version   4.11.0-0.ci.test-2023-01-26-110134-ci-ln-zbd5b8k-latest   True        False         5m9s    Cluster version is 4.11.0-0.ci.test-2023-01-26-110134-ci-ln-zbd5b8k-latest
```

We run unittests too, all test cases passed. The new test case too

$ make test-unit
....
=== RUN   TestVersionSkew
--- PASS: TestVersionSkew (0.00s)
**=== RUN   TestGenerateRenderedConfigOnLatestControllerVersionOnly
--- PASS: TestGenerateRenderedConfigOnLatestControllerVersionOnly (0.00s)**
=== RUN   TestDoNothing


We add qe-approved label

/label qe-approved

**Comment by yuqi-zhang** [comment]
/cherry-pick release-4.10

Let's get this back to 4.10 as well

**Pull request merged**
