### PR TITLE
Update vendored Ignition to v2.13

### PR DESCRIPTION
**Pull request by cgwalters**
Splitting this out of https://github.com/openshift/machine-config-operator/pull/2976 which seems to have unveiled even more bugs.

---

daemon/update_test: Fix Ignition RAID specification

Newer ignition versions validate this more.

---

Update vendored Ignition to v2.13

Prep for updating the fcct -> butane vendoring.

### CODE REVIEW

**Comment by cgwalters** [comment]
OK, this one should be good to go.

**Comment by cgwalters** [comment]
I looked a bit at e2e-aws-upgrade-single-node, I don't see how those disruption tests could ever pass.  AFAICS we're the only repo running it.

**Comment by cgwalters** [comment]
/test e2e-agnostic-upgrade
I think it would be good to have the upgrade test pass, looks like that one was potentially an Azure resourcing issue?

**Comment by cgwalters** [comment]
/test e2e-gcp-op-single-node
This one has had recent passes (is specific to us).  The test timed out, in a quick look it seems the mc-operator was waiting in the standard 2m timeout for leader election.  Hmm, this looks quite slow - and it also actually seems pretty silly for us to do leader election in SNO...

```
I0309 19:22:08.952199       1 leaderelection.go:248] attempting to acquire leader lease openshift-machine-config-operator/machine-config-controller...
I0309 19:27:26.885125       1 leaderelection.go:258] successfully acquired lease openshift-machine-config-operator/machine-config-controller
```

**Review by kikisdeliveryservice — APPROVED** [review]
/lgtm

**Pull request merged**
