### PR TITLE
build: Symlink rather than copy Dockerfiles for operator

### PR DESCRIPTION
**Pull request by cgwalters**
This way we avoid duplication.

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
These files will be deleted in a couple of days so I dont think it's necessary to do this.

**Comment by runcom** [comment]
> These files will be deleted in a couple of days so I dont think it's necessary to do this.

Colin actually mentioned he's broken on the make deploy scripts so unless we can fix this _today_ I think this might be a good shortcut

**Comment by kikisdeliveryservice** [comment]
> > These files will be deleted in a couple of days so I dont think it's necessary to do this.
> 
> Colin actually mentioned he's broken on the make deploy scripts so unless we can fix this _today_ I think this might be a good stopgap

Can we just make this change in the other PR then?  Or conversely this needs to merge before his other PR bc of the linking.

**Comment by cgwalters** [comment]
> Or conversely this needs to merge before his other PR bc of the linking.

I wanted to test them independently in CI; the other one depends on this, but this can go in quite safely I think.

**Comment by kikisdeliveryservice** [comment]
This is now hitting BZ1728888 :(

**Pull request merged**
